>DL;HLA:HLA00601
HLA:HLA00601 DQA1*01:01:01 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA01409
HLA:HLA01409 DQA1*01:01:02 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAGGGGC CATTGTGA* 
>DL;HLA:HLA00602
HLA:HLA00602 DQA1*01:02:01:01 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGTGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA06598
HLA:HLA06598 DQA1*01:02:01:02 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGTGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA06594
HLA:HLA06594 DQA1*01:02:01:03 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGTGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA06599
HLA:HLA06599 DQA1*01:02:01:04 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGTGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA00603
HLA:HLA00603 DQA1*01:02:02 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGTGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA02338
HLA:HLA02338 DQA1*01:02:03 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGTGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA02432
HLA:HLA02432 DQA1*01:02:04 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACTGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGTGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA00604
HLA:HLA00604 DQA1*01:03:01:01 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGAGA AGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCACGCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGTGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CCTTGTGA* 
>DL;HLA:HLA06601
HLA:HLA06601 DQA1*01:03:01:02 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGAGA AGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCACGCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGTGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CCTTGTGA* 
>DL;HLA:HLA00605
HLA:HLA00605 DQA1*01:04:01:01 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCAT GATGAGCCCT
 TGTGGAGGTG AAGGCATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGCACCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA06597
HLA:HLA06597 DQA1*01:04:01:02 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCAT GATGAGCCCT
 TGTGGAGGTG AAGGCATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGCACCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA01376
HLA:HLA01376 DQA1*01:04:02 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCAT GATGAGCCCT
 TGTGGAGGTG AAGGCATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGCACCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA00606
HLA:HLA00606 DQA1*01:05:01 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCAT GATGAGCCCC
 TGTGGAGGTG AAGGCATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA11066
HLA:HLA11066 DQA1*01:05:02 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCAT GATGAGCCCT
 TGTGGAGGTG AAGGCATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA01003
HLA:HLA01003 DQA1*01:06 249 bases
 CTGACCACGT TGCCTCTTGT GGTGTAAACT TGTACCAGTT TTACGGTCCC TCTGGCCAGT
 ACACCCATGA ATTTGATGGA GATGAGCAGT TCTACGTGGA CCTGGAGAGG AAGGAGGCTG
 CCTGGCGGTG GCCTGAGTTC AGCAAATTTG GAGGTTTTGA CCCGCAGGGT GCACTGAGAA
 ACATGGCTGT GGCAAAACAC AACTTGAACA TCATGATTAA ACGCTACAAC TCTACCGCTG
 CTACCAATG*     
>DL;HLA:HLA01905
HLA:HLA01905 DQA1*01:07 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCAT GATGAGCCCT
 TGTGGAGGTG AAGGCATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAATGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGCACCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA07277
HLA:HLA07277 DQA1*01:08 531 bases
 CTGACCACGT TGCCTCTTGT GGTGTAAACT TGTACCAGTT TTACGGTCCC TCTGGCCAGT
 ACACCCATGA ATTTGATGGA GATGAGCAGT TCTACGTGGA CCTGGAGAGG AAGGAGACTG
 CCTGGCGGTG GCCTGAGTTC AGCAAATTTG GAGGTTTTGA CCCGCAGGGT GCACTGAGAA
 ACATGGCTGT GGCAAAACAC AACTTGAACA TCATGATTAA ACGCTACAAC TCTACCGCTG
 CTACCAATGA GGTTCCTGAG GTCACAGTGT TTTCCAAGTC TCCCGTGACA CTGGGTCAGC
 CCAACACCCT CATTTGTCTT GTGGACAACA TCTTTCCTCC TGTGGTCAAC ATCACATGGC
 TGAGCAATGG GCAGTCAGTC ACAGAAGCTG TTTCTGAGAC CAGCTTCCTC TCCAAGAGTG
 ATCATTCCTT CTTCAAGATC AGTTACCTCA CCTTCCTCCC TTCTGCTGAT GAGATTTATG
 ACTGCAAGGT GGAGCACTGG GGCCTGGACC AGCCTCTTCT GAAACACTGG G*
>DL;HLA:HLA07278
HLA:HLA07278 DQA1*01:09 531 bases
 CTGACCACGT TGCCTCTTGT GGTGTAAACT TGTACCAGTT TTACGGTCCC TCTGGCCAGT
 ACACCCATGA ATTTGATGGA GATGAGCAGT TCTACGTGGA CCTGGAGAGG AAGGAGACTG
 CCTGGCGGTG GCCTGAGTTC AGCAAATTTG GAGGTTTTGA CCCGCAGGGT GCACTGAGAA
 ACATGGCTGT GGCAAAACAC AACTTGAACA TCATGATTAA ACGCTACAAC TCTACCGCTG
 CTACCAATGA GGTTCCTGAG GTCACAGTGT TTTCCAAGTC TCCCGTGACA CTGGATCAGC
 CCAACACCCT CATTTGTCTT GTGGACAACA TCTTTCCTCC TGTGGTCAAC ATCACATGGC
 TGAGCAATGG GCAGTCAGTC ACAGAAGGTG TTTCTGAGAC CAGCTTCCTC TCCAAGAGTG
 ATCATTCCTT CTTCAAGATC AGTTACCTCA CCTTCCTCCC TTCTGCTGAT GAGATTTATG
 ACTGCAAGGT GGAGCACTGG GGCCTGGACC AGCCTCTTCT GAAACACTGG G*
>DL;HLA:HLA08431
HLA:HLA08431 DQA1*01:10 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTTCACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGAGA AGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCAC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCACGCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGTGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CCTTGTGA* 
>DL;HLA:HLA08433
HLA:HLA08433 DQA1*01:11 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCTC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT GTGGTGTAAA CTTGTACCAG
 TTTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGAGA GGAAGGAGAC TGCCTGGCGG TGGCCTGAGT TCAGCAAATT TGGAGGTTTT
 GACCCGCAGG GTGCACTGAG AAACATGGCT GTGGCAAAAC ACAACTTGAA CATCATGATT
 AAACGCTACA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATTTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACATG GCTGAGCAAT GGGCAGTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CCAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCTAGCC CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGTGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CATTGTGA* 
>DL;HLA:HLA09875
HLA:HLA09875 DQA1*01:12 531 bases
 CTGACCACGT TGCCTCTTGT GGTGTAAACT TGTACCAGTT TTACGGTCCC TCTGGCCAGT
 ACACCCATGA ATTTGATGGA GATGAGGAGT TCTACGTGGA CCTGGAGAGG AAGGAGACTG
 CCTGGCGGTG GCCTGAGTTC AGCAAATTTG GAGGTTTTGA CCCGCAGGGT GCACTGAGAA
 ACATGGCTGT GGCAAAACAC AACTTGAACA TCATGATTAA ACGCTACAAC TCTACCGCTG
 CTACCAATGA GGTTCCTGAG GTCACAGTGT TTTCCAAGTC TCCCGTGACA CTGGGTCAGC
 CCAACACCCT CATTTGTCTT GTGGACAACA TCTTTCCTCC TGTGGTCAAC ATCACATGGC
 TGAGCAATGG GCAGTCAGTC ACAGAAGGTG TTTCTGAGAC CAGCTTCCTC TCCAAGAGTG
 ATCATTCCTT CTTCAAGATC AGTTACCTCA CCTTCCTCCC TTCTGCTGAT GAGATTTATG
 ACTGCAAGGT GCAGCACTGG GGCCTGGACC AGCCTCTTCT GAAACACTGG G*
>DL;HLA:HLA00607
HLA:HLA00607 DQA1*02:01 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCGT GATGAGCCCT
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTTGCCTCTT ACGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTTCACCCAT GAATTTGATG GAGACGAGGA GTTCTATGTG
 GACCTGGAGA GGAAGGAGAC TGTCTGGAAG TTGCCTCTGT TCCACAGACT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTG CTAAAACATA ACTTGAACAT CCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCAGCC CAACACCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACCTGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT
 TCTGCTGATG AGATTTATGA CTGCAAGGTG GAGCACTGGG GCCTGGATGA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCACCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGT
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GGACCGTCTT GATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA00608
HLA:HLA00608 DQA1*03:01:01 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCGT GATGAGCCCT
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCTT ACGGTGTAAA CTTGTACCAG
 TCTTATGGTC CCTCTGGGCA GTACAGCCAT GAATTTGATG GAGACGAGGA GTTCTATGTG
 GACCTGGAGA GGAAGGAGAC TGTCTGGCAG TTGCCTCTGT TCCGCAGATT TAGAAGATTT
 GACCCGCAAT TTGCACTGAC AAACATCGCT GTGCTAAAAC ATAACTTGAA CATCGTGATT
 AAACGCTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA TGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAACA CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGGACCGT CTTGATCATC
 CGAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CCTTGTGA* 
>DL;HLA:HLA00610
HLA:HLA00610 DQA1*03:02 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCGT GACGAGCCCT
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCTT ACGGTGTAAA CTTGTACCAG
 TCTTATGGTC CCTCTGGGCA GTACAGCCAT GAATTTGATG GAGACGAGGA GTTCTATGTG
 GACCTGGAGA GGAAGGAGAC TGTCTGGCAG TTGCCTCTGT TCCGCAGATT TAGAAGATTT
 GACCCGCAAT TTGCACTGAC AAACATCGCT GTGCTAAAAC ATAACTTGAA CATCGTGATT
 AAACGCTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGATG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA TGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAACA CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGGACCGT CTTGATCATC
 CGAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CCTTGTGA* 
>DL;HLA:HLA00611
HLA:HLA00611 DQA1*03:03:01 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCGT GATGAGCCCT
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCTT ACGGTGTAAA CTTGTACCAG
 TCTTATGGTC CCTCTGGGCA GTACAGCCAT GAATTTGATG GAGACGAGGA GTTCTATGTG
 GACCTGGAGA GGAAGGAGAC TGTCTGGCAG TTGCCTCTGT TCCGCAGATT TAGAAGATTT
 GACCCGCAAT TTGCACTGAC AAACATCGCT GTGCTAAAAC ATAACTTGAA CATCGTGATT
 AAACGCTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGATG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA TGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAACA CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGGACCGT CTTGATCATC
 CGAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CCTTGTGA* 
>DL;HLA:HLA07419
HLA:HLA07419 DQA1*03:03:02 768 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTCGCCC TGACCACCGT GATGAGCCCT
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCTT ACGGTGTAAA CTTGTACCAG
 TCTTATGGTC CCTCTGGGCA GTACAGCCAT GAATTTGATG GAGACGAGGA GTTCTATGTG
 GACCTGGAGA GGAAGGAGAC TGTCTGGCAG TTGCCTCTGT TCCGCAGATT TAGAAGATTT
 GACCCGCAAT TTGCACTGAC AAACATCGCT GTGCTAAAAC ATAACTTGAA CATCGTGATT
 AAACGCTCCA ACTCTACCGC TGCTACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TCTCCCGTGA CACTGGGTCA GCCCAACACC CTTATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGATG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA TGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAACA CCTATGTCAG AGCTCACAGA GACTGTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGGGACCGT CTTGATCATC
 CGAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC CCTTGTGA* 
>DL;HLA:HLA00612
HLA:HLA00612 DQA1*04:01:01 765 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTG ACAAAACACA ACTTGAACAT CCTGATTAAA
 CGCTCCAACT CTACTGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACGC TGGGTCAGCC CAACACCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT
 TCTGCTGATG AGATTTATGA CTGCAAGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGAT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA01694
HLA:HLA01694 DQA1*04:01:02:01 765 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTG ACAAAACACA ACTTGAACAT CCTGATTAAA
 CGCTCCAACT CTACTGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCTGTGACGC TGGGTCAGCC CAACACCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT
 TCTGCTGATG AGATTTATGA CTGCAAGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGAT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA09342
HLA:HLA09342 DQA1*04:01:02:02 765 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTG ACAAAACACA ACTTGAACAT CCTGATTAAA
 CGCTCCAACT CTACTGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCTGTGACGC TGGGTCAGCC CAACACCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT
 TCTGCTGATG AGATTTATGA CTGCAAGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGAT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA01697
HLA:HLA01697 DQA1*04:02 765 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTG ACAAAACACA ACTTGAACAT CCTGATTAAA
 CGCTCCAACT CTACTGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACGC TGGGTCAGCC CAACACCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGATC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT
 TCTGCTGATG AGATTTATGA CTGCAAGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGAT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA01774
HLA:HLA01774 DQA1*04:03N 246 bases
 CTGACCATGT TGCCTCTTAT GGTGTAAACT TGTACCAGTC TTACGGTCCC TCTGGCCAGT
 ACACCCATGA ATTTGATGGA GACGAGCAGT TCTACGTGGA CCTGGGGAGG AAGGAGACTG
 TCTGGTGTTT GCCTGTTCTC AGATAATTTA GATTTGACCC GCAATTTGCA CTGACAAACA
 TCGCTGTGAC AAAACACAAC TTGAACATCC TGATTAAACG CTCCAACTCT ACTGCTGCTA
 CCAATG*     
>DL;HLA:HLA01874
HLA:HLA01874 DQA1*04:04 528 bases
 CTGACCATGT TGCCTCTTAT GGTGTAAACT TGTACCAGTC TTACGGTCCC TCTGGCCAGT
 ACACCCATGA ATTTGATGGA GACGAGCAGT TCTACGTGGA CCTGGGGAGG AAGGAGACTG
 TCTGGTGTTT GCCTGTTCTC AGACAATTTA GATTTGACCC GCAATTTGCA CTGACAAACA
 TCGCTGTGAC AAAACACAAC TTGAACATCC TGATTAAACG CTCCAACTCT ACTGCTGCTA
 CCAATGAGGT TCCTGAGGTC ACAGTGTTTT CCAAGTCTCC CGTGACGCTG GGTCAGCCCA
 ACACCCTCAT CTGTCTTGTG GACAACATCT TTCCTCCTGT GGTCAACATC ACATGGCTGA
 GCAATGGGCA CTCAGTCACA GAAGGTGTTT CTGAGACCAG CTTCCTCTCC AAGAGTGATC
 ATTCCTTCTT CAAGATCAGT CACCTCACCT TCCTCCCTTC TGCTGATGAG ATTTATGACT
 GCAAGGTGGA GCACTGGGGC CTGGACGAGC CTCTTCTGAA ACACTGGG* 
>DL;HLA:HLA00613
HLA:HLA00613 DQA1*05:01:01:01 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTCGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTC CTAAAACATA ACTTGAACAG TCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCAGCC CAACATCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CCTCCTCCCT
 TCTGCTGAGG AGAGTTATGA CTGCAAGGTG GAGCACTGGG GCCTGGACAA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGAT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA06618
HLA:HLA06618 DQA1*05:01:01:02 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTCGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTC CTAAAACATA ACTTGAACAG TCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCAGCC CAACATCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CCTCCTCCCT
 TCTGCTGAGG AGAGTTATGA CTGCAAGGTG GAGCACTGGG GCCTGGACAA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGAT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA00614
HLA:HLA00614 DQA1*05:01:02 258 bases
 GAAGACATTG TGGCTGACCA CGTTGCCTCT TATGGTGTAA ACTTGTACCA GTCTTACGGT
 CCCTCTGGCC AGTACACCCA TGAATTTGAT GGAGATGAGC AGTTCTACGT GGACCTGGGG
 AGGAAGGAGA CTGTCTGGTG TTTGCCTGTT CTCAGACAAT TTAGATTTGA CCCGCAATTT
 GCACTGACAA ACATCGCTGT CCTAAAACAT AACTTGAACA GTCTGATTAA ACGCTCCAAC
 TCTACCGCTG CTACCAAT*    
>DL;HLA:HLA00616
HLA:HLA00616 DQA1*05:02 222 bases
 GGTGTAAACT TGTACCAGTC TTACGGTCCC TCTGGCCAGT ACACCCATGA ATTTGATGGA
 GATGAGCAGT TCTACGTGGA CCTGGGGAGG AAGGAGACTG TCTGGTGTTT GCCTGTTCTC
 AGACAATTTA GATTTGACCG GCAATTTGCA CTGACAAACA TCGCTGTCCT AAAACATAAC
 TTGAACAGTC TGATTAAACG CTCCAACTCT ACCGCTGCTA CC* 
>DL;HLA:HLA00617
HLA:HLA00617 DQA1*05:03 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTCGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTC CTAAAACATA ACTTGAACAG TCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCAGCC CAACATCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CCTCCTCCCT
 TCTTCTGAGG AGAGTTATGA CTGCAAGGTG GAGCACTGGG GCCTGGACAA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGAT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA00618
HLA:HLA00618 DQA1*05:04 246 bases
 CTGACCACGT CGCCTCTTAT GGTGTAAACT TGTACCAGTC TTACGGTCTC TCTGGCCAGT
 ACACCCATGA ATTTGATGGA GATGAGCAGT TCTACGTGGA CCTGGGGAGG AAGGAGACTG
 TCTGGTGTTT GCCTGTTCTC AGACAATTTA GATTTGACCC GCAATTTGCA CTGACAAACA
 TCGCTGTCCT AAAACATAAC TTGAACAGTC TGATTAAACG CTCCAACTCT ACCGCTGCTA
 CCAATG*     
>DL;HLA:HLA00619
HLA:HLA00619 DQA1*05:05:01:01 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG ACCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTCGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTC CTAAAACATA ACTTGAACAG TCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCAGCC CAACATCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CCTCCTCCCT
 TCTGCTGAGG AGAGTTATGA CTGCAAGGTG GAGCACTGGG GACTGGACAA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA06614
HLA:HLA06614 DQA1*05:05:01:02 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG ACCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTCGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTC CTAAAACATA ACTTGAACAG TCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCAGCC CAACATCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CCTCCTCCCT
 TCTGCTGAGG AGAGTTATGA CTGCAAGGTG GAGCACTGGG GACTGGACAA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA06609
HLA:HLA06609 DQA1*05:05:01:03 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG ACCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTCGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTC CTAAAACATA ACTTGAACAG TCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCAGCC CAACATCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CCTCCTCCCT
 TCTGCTGAGG AGAGTTATGA CTGCAAGGTG GAGCACTGGG GACTGGACAA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA02339
HLA:HLA02339 DQA1*05:06 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTCGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTC CTAAAACATA ACTTGAACAG TCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAG TGGGTCAGCC CAACATCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CCTCCTCCCT
 TCTTCTGAGG AGAGTTATGA CTGCAAGGTG GAGCACTGGG GCCTGGACAA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGAT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA02340
HLA:HLA02340 DQA1*05:07 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG GCCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTCGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTC CTAAAACATA ACTTGAACAG TCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCAGCC CAACATCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CCTCCTCCCT
 TCTTCTGAGG AGAGTTATGA CTGCAAGGTG GAGCACTGGG GCCTGGACAA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGAT TGTCTGTGGG CCTCGTGTGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA02341
HLA:HLA02341 DQA1*05:08 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG ACCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTCGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTC CTAAAACATA ACTTGAACAG TCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCAGCC CAACATCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 ATCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CCTCCTCCCT
 TCTGCTGAGG AGAGTTATGA CTGCAAGGTG GAGCACTGGG GACTGGACAA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA02433
HLA:HLA02433 DQA1*05:09 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG ACCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTA AAGACATTGT GGCTGACCAC GTCGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTC CTAAAACATA ACTTGAACAG TCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCAGCC CAACATCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CCTCCTCCCT
 TCTGCTGAGG AGAGTTATGA CTGCAAGGTG GAGCACTGGG GACTGGACAA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA04360
HLA:HLA04360 DQA1*05:10 528 bases
 CTGACCACGT CGCCTCTTAT GGTGTAAACT TGTACCAGTC TTACGGTCCC TCTGGCCAGT
 ACACCCATGA ATTTGATGGA GATGAGCAGT TCTACGTGGA CCTGGGGAGG AAGGAGACTG
 TCTGGTGTTT GCCTGTTCTC AGACAATTTA GATTTGACCC GCAATTTGCA CTGACAAACA
 TCGCTGTCCT AAAACATAAC TTGAACAGTC TGGTTAAACG CTCCAACTCT ACCGCTGCTA
 CCAATGAGGT TCCTGAGGTC ACAGTGTTTT CCAAGTCTCC CGTGACACTG GGTCAGCCCA
 ACATCCTCAT CTGTCTTGTG GACAACATCT TTCCTCCTGT GGTCAACATC ACATGGCTGA
 GCAATGGGCA CTCAGTCACA GAAGGTGTTT CTGAGACCAG CTTCCTCTCC AAGAGTGATC
 ATTCCTTCTT CAAGATCAGT TACCTCACCC TCCTCCCTTC TGCTGAGGAG AGTTATGACT
 GCAAGGTGGA GCACTGGGGA CTGGACAAGC CTCTTCTGAA ACACTGGG* 
>DL;HLA:HLA06617
HLA:HLA06617 DQA1*05:11 765 bases
 ATGATCCTAA ACAAAGCTCT GATGCTGGGG ACCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAC GTCGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTC CTAAAACATA ACTTGAACAG TCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACAC TGGGTCAGCC CAACATCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CCTCCTCCCT
 TCTGCTGAGG AGAGTTATGA CTGCAAGGTG GAGCACTGGG GACTGGACAA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGGGAC TGTGGTCTGC
 GCCCTGGGGT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA00620
HLA:HLA00620 DQA1*06:01:01 765 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTTGCCC TGACCACCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCTT ATGGTGTAAA CTTGTACCAG
 TCTTACGGTC CCTCTGGCCA GTTCACCCAT GAATTTGATG GAGACGAGCA GTTCTACGTG
 GACCTGGGGA GGAAGGAGAC TGTCTGGTGT TTGCCTGTTC TCAGACAATT TAGATTTGAC
 CCGCAATTTG CACTGACAAA CATCGCTGTG ACAAAACACA ACTTGAACAT CCTGATTAAA
 CGCTCCAACT CTACCGCTGC TACCAATGAG GTTCCTGAGG TCACAGTGTT TTCCAAGTCT
 CCCGTGACGC TGGGTCAGCC CAACACCCTC ATCTGTCTTG TGGACAACAT CTTTCCTCCT
 GTGGTCAACA TCACATGGCT GAGCAATGGG CACTCAGTCA CAGAAGGTGT TTCTGAGACC
 AGCTTCCTCT CCAAGAGTGA TCATTCCTTC TTCAAGATCA GTTACCTCAC CTTCCTCCCT
 TCTGCTGATG AGATTTATGA CTGCAAGGTG GAGCACTGGG GCCTGGACGA GCCTCTTCTG
 AAACACTGGG AGCCTGAGAT TCCAGCCCCT ATGTCAGAGC TCACAGAGAC TGTGGTCTGC
 GCCCTGGGAT TGTCTGTGGG CCTCGTGGGC ATTGTGGTGG GCACTGTCTT CATCATCCGA
 GGCCTGCGTT CAGTTGGTGC TTCCAGACAC CAAGGGCCCT TGTGA* 
>DL;HLA:HLA00621
HLA:HLA00621 DQA1*06:01:02 227 bases
 GGTGTAAACT TGTACCAGTC TTACGGTCCC TCTGGCCAGT TCACCCATGA ATTTGATGGA
 GACGAGCAGT TCTACGTGGA CCTGGGGAGG AAGGAGACTG TCTGGTGTTT GCCTGTTCTC
 AGACAATTTA GATTTGACCC GCAATTTGCA CTGACAAACA TCGCCGTGAC AAAACACAAC
 TTGAACATCC TGATTAAACG CTCCAACTCT ACCGCTGCTA CCAATGA* 
>DL;HLA:HLA01861
HLA:HLA01861 DQA1*06:02 528 bases
 CTGACCATGT TGCCTCTTAT GGTGTAAACT TGTACCAGTC TTACGGTCCC TCTGGCCAGT
 TCACCCATGA ATTTGATGGA GACGAGCAGT TCTACGTGGA CCTGGGGAGG AAGGAGACTG
 TCTGGTGTTT GCCTGTTCTC AGACAATTTA GATTTGACCC GCAATTTGCA CTGACAAACA
 TCGCTGTGAC AAAACACAAC TTGAACATCC TGATTAAACG CTCCAACTCT ACCGCTGCTA
 CCAATGAGGT TCCTGAGGTC ACAGTGTTTT CCAAGTCTCC CGTGACGCTG GGTCAGCCCA
 ACACCCTCAT CTGTCTTGTG GACAACATCT TTCCTCCTGT GGTCAACATC ACATGGCTGA
 GCAATGGGCA CTCAGTCACA GAAGGTGTTT CTGAGACCCG CTTCCTCTCC AAGAGTGATC
 ATTCCTTCTT CAAGATCAGT TACCTCACCT TCCTCCCTTC TGCTGATGAG ATTTATGACT
 GCAAGGTGGA GCACTGGGGC CTGGACGAGC CTCTTCTGAA ACACTGGG* 
