>P1;HLA:HLA00662
HLA:HLA00662 DRA*01:01:01:01 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL*    
>P1;HLA:HLA06469
HLA:HLA06469 DRA*01:01:01:02 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL*    
>P1;HLA:HLA06470
HLA:HLA06470 DRA*01:01:01:03 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL*    
>P1;HLA:HLA06468
HLA:HLA06468 DRA*01:01:02 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL*    
>P1;HLA:HLA00663
HLA:HLA00663 DRA*01:02:01 226 bases
 EHVIIQAEFY LNPDQSGEFM FDFDGDEIFH VDMAKKETVW RLEEFGRFAS FEAQGALANI
 AVDKANLEIM TKRSNYTPIT NVPPEVTVLT NSPVELREPN VLICFIDKFT PPVVNVTWLR
 NGKPVTTGVS ETVFLPREDH LFRKFHYLPF LPSTEDVYDC RVEHWGLDEP LLKHWEFDAP
 SPLPETTENV VCALGLTVGL VGIIIGTIFI IKGLRKSNAA ERRGPL* 
>P1;HLA:HLA01593
HLA:HLA01593 DRA*01:02:02 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL*    
>P1;HLA:HLA06454
HLA:HLA06454 DRA*01:02:03 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL*    
