>P1;HLA:HLA00485
HLA:HLA00485 DMA*01:01:01:01 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA06456
HLA:HLA06456 DMA*01:01:01:02 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA06457
HLA:HLA06457 DMA*01:01:01:03 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA06464
HLA:HLA06464 DMA*01:01:01:04 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34481
HLA:HLA34481 DMA*01:01:01:05 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34453
HLA:HLA34453 DMA*01:01:01:06 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34444
HLA:HLA34444 DMA*01:01:01:07 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34474
HLA:HLA34474 DMA*01:01:01:08 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34643
HLA:HLA34643 DMA*01:01:01:09 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34571
HLA:HLA34571 DMA*01:01:01:10 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34579
HLA:HLA34579 DMA*01:01:01:11 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34596
HLA:HLA34596 DMA*01:01:01:12 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34597
HLA:HLA34597 DMA*01:01:01:13 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34521
HLA:HLA34521 DMA*01:01:01:14 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34573
HLA:HLA34573 DMA*01:01:01:15 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34581
HLA:HLA34581 DMA*01:01:01:16 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34553
HLA:HLA34553 DMA*01:01:01:17 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34519
HLA:HLA34519 DMA*01:01:01:18 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34523
HLA:HLA34523 DMA*01:01:01:19 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34535
HLA:HLA34535 DMA*01:01:01:20 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34532
HLA:HLA34532 DMA*01:01:01:21 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34555
HLA:HLA34555 DMA*01:01:01:22 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34546
HLA:HLA34546 DMA*01:01:01:23 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34572
HLA:HLA34572 DMA*01:01:01:24 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34556
HLA:HLA34556 DMA*01:01:01:25 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34554
HLA:HLA34554 DMA*01:01:01:26 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34545
HLA:HLA34545 DMA*01:01:01:27 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34534
HLA:HLA34534 DMA*01:01:01:28 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34533
HLA:HLA34533 DMA*01:01:01:29 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34594
HLA:HLA34594 DMA*01:01:01:30 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34449
HLA:HLA34449 DMA*01:01:01:31 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34487
HLA:HLA34487 DMA*01:01:01:32 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34486
HLA:HLA34486 DMA*01:01:01:33 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34503
HLA:HLA34503 DMA*01:01:01:34 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34505
HLA:HLA34505 DMA*01:01:01:35 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34621
HLA:HLA34621 DMA*01:01:01:36 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34506
HLA:HLA34506 DMA*01:01:01:37 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34466
HLA:HLA34466 DMA*01:01:01:38 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34609
HLA:HLA34609 DMA*01:01:01:39 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34633
HLA:HLA34633 DMA*01:01:01:40 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA38912
HLA:HLA38912 DMA*01:01:01:41 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA41352
HLA:HLA41352 DMA*01:01:01:42 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42095
HLA:HLA42095 DMA*01:01:01:43 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42779
HLA:HLA42779 DMA*01:01:01:44 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42791
HLA:HLA42791 DMA*01:01:01:45 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42876
HLA:HLA42876 DMA*01:01:01:46 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42857
HLA:HLA42857 DMA*01:01:01:47 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42877
HLA:HLA42877 DMA*01:01:01:48 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42858
HLA:HLA42858 DMA*01:01:01:49 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42904
HLA:HLA42904 DMA*01:01:01:50 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42789
HLA:HLA42789 DMA*01:01:01:51 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42780
HLA:HLA42780 DMA*01:01:01:52 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42784
HLA:HLA42784 DMA*01:01:01:53 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42781
HLA:HLA42781 DMA*01:01:01:54 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42930
HLA:HLA42930 DMA*01:01:01:55 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA43508
HLA:HLA43508 DMA*01:01:01:56 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA43506
HLA:HLA43506 DMA*01:01:01:57 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA43522
HLA:HLA43522 DMA*01:01:01:58 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA43325
HLA:HLA43325 DMA*01:01:01:59 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA43327
HLA:HLA43327 DMA*01:01:01:60 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA43387
HLA:HLA43387 DMA*01:01:01:61 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34570
HLA:HLA34570 DMA*01:01:02 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42080
HLA:HLA42080 DMA*01:01:03 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA00486
HLA:HLA00486 DMA*01:02:01:01 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34459
HLA:HLA34459 DMA*01:02:01:02 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34586
HLA:HLA34586 DMA*01:02:01:03 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34584
HLA:HLA34584 DMA*01:02:01:04 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34595
HLA:HLA34595 DMA*01:02:01:05 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34598
HLA:HLA34598 DMA*01:02:01:06 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34469
HLA:HLA34469 DMA*01:02:01:07 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34622
HLA:HLA34622 DMA*01:02:01:08 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34448
HLA:HLA34448 DMA*01:02:01:09 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42905
HLA:HLA42905 DMA*01:02:01:10 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42787
HLA:HLA42787 DMA*01:02:01:11 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA43328
HLA:HLA43328 DMA*01:02:01:12 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA00487
HLA:HLA00487 DMA*01:03:01:01 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 ALSFQAFSYL NFTPEPSDIF SCIVTHEIDH YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34696
HLA:HLA34696 DMA*01:03:01:02 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 ALSFQAFSYL NFTPEPSDIF SCIVTHEIDH YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA42721
HLA:HLA42721 DMA*01:03:01:03 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 ALSFQAFSYL NFTPEPSDIF SCIVTHEIDH YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA00488
HLA:HLA00488 DMA*01:04 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSIPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDC YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34522
HLA:HLA34522 DMA*01:05 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTLVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34585
HLA:HLA34585 DMA*01:06 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCKWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34580
HLA:HLA34580 DMA*01:07 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPNVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34557
HLA:HLA34557 DMA*01:08 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FEPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
>P1;HLA:HLA34544
HLA:HLA34544 DMA*01:09 261 bases
 MGHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIMGIVL IIYFRKPCSG D   
>P1;HLA:HLA43330
HLA:HLA43330 DMA*01:10 261 bases
 MVHEQNQGAA LLQMLPLLWL LPHSWAVPEA PTPMWPDDLQ NHTFLHTVYC QDGSPSVGLS
 EAYDEDQLFF FDFSQNTRVP RLPEFADWAQ EQGDAPAILF DKEFCEWMIQ QIGPKLDGKI
 PVSRGFPIAE VFTLKPLEFG KPNTLVCFVS NLFPPMLTVN WQHHSVPVEG FGPTFVSAVD
 GLSFQAFSYL NFTPEPSDIF SCIVTHEIDR YTAIAYWVPR NALPSDLLEN VLCGVAFGLG
 VLGIIVGIVL IIYFRKPCSG D   
