>DL;HLA:HLA00485
HLA:HLA00485 DMA*01:01 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA*     
>DL;HLA:HLA00486
HLA:HLA00486 DMA*01:02 564 bases
 CTCCTACTCC AATGTGGCCA GATGACCTGC AAAACCACAC ATTCCTGCAC ACAGTGTACT
 GCCAGGATGG GAGTCCCAGT GTGGGACTCT CTGAGGCCTA CGACGAGGAC CAGCTTTTCT
 TCTTCGACTT TTCCCAGAAC ACTCGGGTGC CTCGCCTGCC CGAATTTGCT GACTGGGCTC
 AGGAACAGGG AGATGCTCCT GCCATTTTAT TTGACAAAGA GTTCTGCGAG TGGATGATCC
 AGCAAATAGG GCCAAAACTT GATGGGAAAA TCCCGGTGTC CAGAGGGTTT CCTATCGCTG
 AAGTGTTCAC GCTGAAGCCC CTGGAGTTTG GCAAGCCCAA CACTTTGGTC TGTTTTGTCA
 GTAATCTCTT CCCACCCATG CTGACAGTGA ACTGGCAGCA TCATTCCATC CCTGTGGAAG
 GATTTGGGCC TACTTTTGTC TCAGCTGTCG ATGGACTCAG CTTCCAGGCC TTTTCTTACT
 TAAACTTCAC ACCAGAACCT TCTGACATTT TCTCCTGCAT TGTGACTCAC GAAATTGACC
 GCTACACAGC AATTGCCTAT TGGG*   
>DL;HLA:HLA00487
HLA:HLA00487 DMA*01:03 279 bases
 GGGTTTCCTA TCGCTGAAGT GTTCACGCTG AAGCCCCTGG AGTTTGGCAA GCCCAACACT
 TTGGTCTGTT TTGTCAGTAA TCTCTTCCCA CCCATGCTGA CAGTGAACTG GCAGCATCAT
 TCCGTCCCTG TGGAAGGATT TGGGCCTACT TTTGTCTCAG CTGTCGATGC ACTCAGCTTC
 CAGGCCTTTT CTTACTTAAA CTTCACACCA GAACCTTCTG ACATTTTCTC CTGCATTGTG
 ACTCACGAAA TTGACCACTA CACAGCAATT GCCTATTGG*  
>DL;HLA:HLA00488
HLA:HLA00488 DMA*01:04 279 bases
 GGGTTTCCTA TCGCTGAAGT GTTCACGCTG AAGCCCCTGG AGTTTGGCAA GCCCAACACT
 TTGGTCTGTT TTGTCAGTAA TCTCTTCCCA CCCATGCTGA CAGTGAACTG GCAGCATCAT
 TCCATCCCTG TGGAAGGATT TGGGCCTACT TTTGTCTCAG CTGTCGATGG ACTCAGCTTC
 CAGGCCTTTT CTTACTTAAA CTTCACACCA GAACCTTCTG ACATTTTCTC CTGCATTGTG
 ACTCACGAAA TTGACTGCTA CACAGCAATT GCCTATTGG*  
