>DL;HLA:HLA00485
HLA:HLA00485 DMA*01:01:01:01 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA06456
HLA:HLA06456 DMA*01:01:01:02 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA06457
HLA:HLA06457 DMA*01:01:01:03 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA06464
HLA:HLA06464 DMA*01:01:01:04 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34481
HLA:HLA34481 DMA*01:01:01:05 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34453
HLA:HLA34453 DMA*01:01:01:06 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34444
HLA:HLA34444 DMA*01:01:01:07 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34474
HLA:HLA34474 DMA*01:01:01:08 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34643
HLA:HLA34643 DMA*01:01:01:09 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34571
HLA:HLA34571 DMA*01:01:01:10 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34579
HLA:HLA34579 DMA*01:01:01:11 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34596
HLA:HLA34596 DMA*01:01:01:12 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34597
HLA:HLA34597 DMA*01:01:01:13 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34521
HLA:HLA34521 DMA*01:01:01:14 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34573
HLA:HLA34573 DMA*01:01:01:15 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34581
HLA:HLA34581 DMA*01:01:01:16 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34553
HLA:HLA34553 DMA*01:01:01:17 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34519
HLA:HLA34519 DMA*01:01:01:18 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34523
HLA:HLA34523 DMA*01:01:01:19 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34535
HLA:HLA34535 DMA*01:01:01:20 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34532
HLA:HLA34532 DMA*01:01:01:21 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34555
HLA:HLA34555 DMA*01:01:01:22 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34546
HLA:HLA34546 DMA*01:01:01:23 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34572
HLA:HLA34572 DMA*01:01:01:24 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34556
HLA:HLA34556 DMA*01:01:01:25 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34554
HLA:HLA34554 DMA*01:01:01:26 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34545
HLA:HLA34545 DMA*01:01:01:27 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34534
HLA:HLA34534 DMA*01:01:01:28 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34533
HLA:HLA34533 DMA*01:01:01:29 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34594
HLA:HLA34594 DMA*01:01:01:30 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34449
HLA:HLA34449 DMA*01:01:01:31 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34487
HLA:HLA34487 DMA*01:01:01:32 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34486
HLA:HLA34486 DMA*01:01:01:33 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34503
HLA:HLA34503 DMA*01:01:01:34 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34505
HLA:HLA34505 DMA*01:01:01:35 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34621
HLA:HLA34621 DMA*01:01:01:36 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34506
HLA:HLA34506 DMA*01:01:01:37 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34466
HLA:HLA34466 DMA*01:01:01:38 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34609
HLA:HLA34609 DMA*01:01:01:39 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34633
HLA:HLA34633 DMA*01:01:01:40 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34570
HLA:HLA34570 DMA*01:01:02 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCATGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA00486
HLA:HLA00486 DMA*01:02:01:01 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCATCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34459
HLA:HLA34459 DMA*01:02:01:02 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCATCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34586
HLA:HLA34586 DMA*01:02:01:03 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCATCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34584
HLA:HLA34584 DMA*01:02:01:04 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCATCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34595
HLA:HLA34595 DMA*01:02:01:05 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCATCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34598
HLA:HLA34598 DMA*01:02:01:06 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCATCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34469
HLA:HLA34469 DMA*01:02:01:07 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCATCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34622
HLA:HLA34622 DMA*01:02:01:08 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCATCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34448
HLA:HLA34448 DMA*01:02:01:09 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCATCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA00487
HLA:HLA00487 DMA*01:03:01:01 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GCACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCAC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34696
HLA:HLA34696 DMA*01:03:01:02 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GCACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCAC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA00488
HLA:HLA00488 DMA*01:04 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCATCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACTGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34522
HLA:HLA34522 DMA*01:05 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTGGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34585
HLA:HLA34585 DMA*01:06 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCAAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34580
HLA:HLA34580 DMA*01:07 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAATGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34557
HLA:HLA34557 DMA*01:08 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGAGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCGTGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
>DL;HLA:HLA34544
HLA:HLA34544 DMA*01:09 786 bases
 ATGGGTCATG AACAGAACCA AGGAGCTGCG CTGCTACAGA TGTTACCACT TCTGTGGCTG
 CTACCCCACT CCTGGGCCGT CCCTGAAGCT CCTACTCCAA TGTGGCCAGA TGACCTGCAA
 AACCACACAT TCCTGCACAC AGTGTACTGC CAGGATGGGA GTCCCAGTGT GGGACTCTCT
 GAGGCCTACG ACGAGGACCA GCTTTTCTTC TTCGACTTTT CCCAGAACAC TCGGGTGCCT
 CGCCTGCCCG AATTTGCTGA CTGGGCTCAG GAACAGGGAG ATGCTCCTGC CATTTTATTT
 GACAAAGAGT TCTGCGAGTG GATGATCCAG CAAATAGGGC CAAAACTTGA TGGGAAAATC
 CCGGTGTCCA GAGGGTTTCC TATCGCTGAA GTGTTCACGC TGAAGCCCCT GGAGTTTGGC
 AAGCCCAACA CTTTGGTCTG TTTTGTCAGT AATCTCTTCC CACCCATGCT GACAGTGAAC
 TGGCAGCATC ATTCCGTCCC TGTGGAAGGA TTTGGGCCTA CTTTTGTCTC AGCTGTCGAT
 GGACTCAGCT TCCAGGCCTT TTCTTACTTA AACTTCACAC CAGAACCTTC TGACATTTTC
 TCCTGCATTG TGACTCACGA AATTGACCGC TACACAGCAA TTGCCTATTG GGTACCCCGG
 AACGCACTGC CCTCAGATCT GCTGGAGAAT GTGCTGTGTG GCGTGGCCTT TGGCCTGGGT
 GTGCTGGGCA TCATCATGGG CATTGTTCTC ATCATCTACT TCCGGAAGCC TTGCTCAGGT
 GACTGA     
