>P1;HLA:HLA00489
HLA:HLA00489 DMB*01:01:01:01 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA06461
HLA:HLA06461 DMB*01:01:01:02 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA06462
HLA:HLA06462 DMB*01:01:01:03 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA06466
HLA:HLA06466 DMB*01:01:01:04 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34468
HLA:HLA34468 DMB*01:01:01:05 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34632
HLA:HLA34632 DMB*01:01:01:06 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34645
HLA:HLA34645 DMB*01:01:01:07 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34624
HLA:HLA34624 DMB*01:01:01:08 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34620
HLA:HLA34620 DMB*01:01:01:09 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34611
HLA:HLA34611 DMB*01:01:01:10 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34488
HLA:HLA34488 DMB*01:01:01:11 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34485
HLA:HLA34485 DMB*01:01:01:12 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34447
HLA:HLA34447 DMB*01:01:01:13 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34450
HLA:HLA34450 DMB*01:01:01:14 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34464
HLA:HLA34464 DMB*01:01:01:15 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34608
HLA:HLA34608 DMB*01:01:01:16 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34483
HLA:HLA34483 DMB*01:01:01:17 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34471
HLA:HLA34471 DMB*01:01:01:18 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34465
HLA:HLA34465 DMB*01:01:01:19 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34646
HLA:HLA34646 DMB*01:01:01:20 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34615
HLA:HLA34615 DMB*01:01:01:21 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34642
HLA:HLA34642 DMB*01:01:01:22 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34457
HLA:HLA34457 DMB*01:01:01:23 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34616
HLA:HLA34616 DMB*01:01:01:24 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34614
HLA:HLA34614 DMB*01:01:01:25 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34477
HLA:HLA34477 DMB*01:01:01:26 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34455
HLA:HLA34455 DMB*01:01:01:27 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34493
HLA:HLA34493 DMB*01:01:01:28 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34511
HLA:HLA34511 DMB*01:01:01:29 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34496
HLA:HLA34496 DMB*01:01:01:30 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34456
HLA:HLA34456 DMB*01:01:01:31 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34627
HLA:HLA34627 DMB*01:01:01:32 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34641
HLA:HLA34641 DMB*01:01:01:33 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34528
HLA:HLA34528 DMB*01:01:01:34 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34562
HLA:HLA34562 DMB*01:01:01:35 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34550
HLA:HLA34550 DMB*01:01:01:36 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34565
HLA:HLA34565 DMB*01:01:01:37 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34514
HLA:HLA34514 DMB*01:01:01:38 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34527
HLA:HLA34527 DMB*01:01:01:39 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34538
HLA:HLA34538 DMB*01:01:01:40 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34564
HLA:HLA34564 DMB*01:01:01:41 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34589
HLA:HLA34589 DMB*01:01:01:42 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA37489
HLA:HLA37489 DMB*01:01:01:43 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA37624
HLA:HLA37624 DMB*01:01:01:44 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA37496
HLA:HLA37496 DMB*01:01:01:45 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA37531
HLA:HLA37531 DMB*01:01:01:46 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA37643
HLA:HLA37643 DMB*01:01:01:47 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA37641
HLA:HLA37641 DMB*01:01:01:48 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA37664
HLA:HLA37664 DMB*01:01:01:49 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA41492
HLA:HLA41492 DMB*01:01:01:50 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA41250
HLA:HLA41250 DMB*01:01:01:51 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA00490
HLA:HLA00490 DMB*01:02:01:01 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SEHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34660
HLA:HLA34660 DMB*01:02:01:02 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SEHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34683
HLA:HLA34683 DMB*01:02:01:03 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SEHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA37655
HLA:HLA37655 DMB*01:02:01:04 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SEHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA37630
HLA:HLA37630 DMB*01:02:01:05 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SEHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA00491
HLA:HLA00491 DMB*01:03:01:01 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA06459
HLA:HLA06459 DMB*01:03:01:02 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA06463
HLA:HLA06463 DMB*01:03:01:03 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA06465
HLA:HLA06465 DMB*01:03:01:04 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34467
HLA:HLA34467 DMB*01:03:01:05 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34631
HLA:HLA34631 DMB*01:03:01:06 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34472
HLA:HLA34472 DMB*01:03:01:07 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34502
HLA:HLA34502 DMB*01:03:01:08 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34640
HLA:HLA34640 DMB*01:03:01:09 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34604
HLA:HLA34604 DMB*01:03:01:10 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34478
HLA:HLA34478 DMB*01:03:01:11 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34479
HLA:HLA34479 DMB*01:03:01:12 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34540
HLA:HLA34540 DMB*01:03:01:13 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34529
HLA:HLA34529 DMB*01:03:01:14 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34590
HLA:HLA34590 DMB*01:03:01:15 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34576
HLA:HLA34576 DMB*01:03:01:16 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA37525
HLA:HLA37525 DMB*01:03:01:17 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA37520
HLA:HLA37520 DMB*01:03:01:18 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA41443
HLA:HLA41443 DMB*01:03:01:19 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34513
HLA:HLA34513 DMB*01:03:02 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA00492
HLA:HLA00492 DMB*01:04 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SVHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHTGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA00493
HLA:HLA00493 DMB*01:05 175 bases
 ESTCLLDDAG TPKDFTYCIS FNKDLLTCWD PEENKMAPCE FGVLNSLANV LSQHLNQKDT
 LMQRLRNGLQ NCATHTQPFW GSLTNRTRPP SVQVAKTTPF NTREPVMLAC YVWGFYPAEV
 TITWRKNGKL VMPHSSVHKT AQPNGDWTYQ TLSHLALTPS YGDTYTCVVE HIGAP
>P1;HLA:HLA01083
HLA:HLA01083 DMB*01:06 188 bases
 GFVAHVESTC LLDDAGTPKD FTYCIFFNKD LLTCWDPEEN KMAPCEFGVL NSLANVLSQH
 LNQKDTLMQR LRNGLQNCAT HTQPFWGSLT NRTRPPSVQV AKTTPFNTRE PVMLACYVWG
 FYPAEVTITW RKNGKLVMPH SSEHKTAQPN GDWTYQTLSH LALTPSYGDT YTCVVEHTGA
 PEPILRDW     
>P1;HLA:HLA02012
HLA:HLA02012 DMB*01:07:01:01 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESACL LDDAGTPKDF TYCISFNKVL LTCWDPEENK
 MAPCEFGVLN NLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34777
HLA:HLA34777 DMB*01:07:01:02 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESACL LDDAGTPKDF TYCISFNKVL LTCWDPEENK
 MAPCEFGVLN NLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34687
HLA:HLA34687 DMB*01:07:01:03 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESACL LDDAGTPKDF TYCISFNKVL LTCWDPEENK
 MAPCEFGVLN NLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34743
HLA:HLA34743 DMB*01:07:01:04 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESACL LDDAGTPKDF TYCISFNKVL LTCWDPEENK
 MAPCEFGVLN NLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34626
HLA:HLA34626 DMB*01:08 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCEFGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILQDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
>P1;HLA:HLA34539
HLA:HLA34539 DMB*01:09 263 bases
 MITFLPLLLG LSLGCTGAGG FVAHVESTCL LDDAGTPKDF TYCISFNKDL LTCWDPEENK
 MAPCESGVLN SLANVLSQHL NQKDTLMQRL RNGLQNCATH TQPFWGSLTN RTRPPSVQVA
 KTTPFNTREP VMLACYVWGF YPAEVTITWR KNGKLVMPHS SAHKTAQPNG DWTYQTLSHL
 ALTPSYGDTY TCVVEHIGAP EPILRDWTPG LSPMQTLKVS VSAVTLGLGL IIFSLGVISW
 RRAGHSSYTP LPGSNYSEGW HIS   
