>DL;HLA:HLA00489
HLA:HLA00489 DMB*01:01 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG*    
>DL;HLA:HLA00490
HLA:HLA00490 DMB*01:02 284 bases
 GGCCACCATC TGTGCAAGTA GCCAAAACCA CTCCTTTTAA CACGAGGGAG CCTGTGATGC
 TGGCCTGCTA TGTGTGGGGC TTCTATCCAG CAGAAGTGAC TATCACGTGG AGGAAGAACG
 GGAAGCTTGT CATGCCTCAC AGCAGTGAGC ACAAGACTGC CCAGCCCAAT GGAGACTGGA
 CATACCAGAC CCTCTCCCAT TTAGCCTTAA CCCCCTCTTA CGGGGACACT TACACCTGTG
 TGGTAGAGCA CATTGGGGCT CCTGAGCCCA TCCTTCGGGA CTGG* 
>DL;HLA:HLA00491
HLA:HLA00491 DMB*01:03 285 bases
 GGCCACCATC TGTGCAAGTA GCCAAAACCA CTCCTTTTAA CACGAGGGAG CCTGTGATGC
 TGGCCTGCTA TGTGTGGGGC TTCTATCCAG CAGAAGTGAC TATCACGTGG AGGAAGAACG
 GGAAGCTTGT CATGCCTCAC AGCAGTGCGC ACAAGACTGC CCAGCCCAAT GGAGACTGGA
 CATACCAGAC CCTCTCCCAT TTAGCCTTAA CCCCCTCTTA CGGGGACACT TACACCTGTG
 TGGTAGAGCA CACTGGGGCT CCTGAGCCCA TCCTTCGGGA CTGGA* 
>DL;HLA:HLA00492
HLA:HLA00492 DMB*01:04 242 bases
 CAAAACCACT CCTTTTAACA CGAGGGAGCC TGTGATGCTG GCCTGCTATG TGTGGGGCTT
 CTATCCAGCA GAAGTGACTA TCACGTGGAG GAAGAACGGG AAGCTTGTCA TGCCTCACAG
 CAGTGTGCAC AAGACTGCCC AGCCCAATGG AGACTGGACA TACCAGACCC TCTCCCATTT
 AGCCTTAACC CCCTCTTACG GGGACACTTA CACCTGTGTG GTAGAGCACA CTGGGGCTCC
 TG*     
>DL;HLA:HLA00493
HLA:HLA00493 DMB*01:05 527 bases
 GGAAAGCACC TGTCTGTTGG ATGATGCTGG GACTCCAAAG GATTTCACAT ACTGCATCTC
 CTTCAACAAG GATCTGCTGA CCTGCTGGGA TCCAGAGGAG AATAAGATGG CCCCTTGCGA
 ATTTGGGGTG CTGAATAGCT TGGCGAATGT CCTCTCACAG CACCTCAACC AAAAAGACAC
 CCTGATGCAG CGCTTGCGCA ATGGGCTTCA GAATTGTGCC ACACACACCC AGCCCTTCTG
 GGGATCACTG ACCAACAGGA CACGGCCACC ATCTGTGCAA GTAGCCAAAA CCACTCCTTT
 TAACACGAGG GAGCCTGTGA TGCTGGCCTG CTATGTGTGG GGCTTCTATC CAGCAGAAGT
 GACTATCACG TGGAGGAAGA ACGGGAAGCT TGTCATGCCT CACAGCAGTG TGCACAAGAC
 TGCCCAGCCC AATGGAGACT GGACATACCA GACCCTCTCC CATTTAGCCT TAACCCCCTC
 TTACGGGGAC ACTTACACCT GTGTGGTAGA GCACATTGGG GCTCCTG* 
>DL;HLA:HLA01083
HLA:HLA01083 DMB*01:06 567 bases
 GTGGCTTCGT GGCCCATGTG GAAAGCACCT GTCTGTTGGA TGATGCTGGG ACTCCAAAGG
 ATTTCACATA CTGCATCTTC TTCAACAAGG ATCTGCTGAC CTGCTGGGAT CCAGAGGAGA
 ATAAGATGGC CCCTTGCGAA TTTGGGGTGC TGAATAGCTT GGCGAATGTC CTCTCACAGC
 ACCTCAACCA AAAAGACACC CTGATGCAGC GCTTGCGCAA TGGGCTTCAG AATTGTGCCA
 CACACACCCA GCCCTTCTGG GGATCACTGA CCAACAGGAC ACGGCCACCA TCTGTGCAAG
 TAGCCAAAAC CACTCCTTTT AACACGAGGG AGCCTGTGAT GCTGGCCTGC TATGTGTGGG
 GCTTCTATCC AGCAGAAGTG ACTATCACGT GGAGGAAGAA CGGGAAGCTT GTCATGCCTC
 ACAGCAGTGA GCACAAGACT GCCCAGCCCA ATGGAGACTG GACATACCAG ACCCTCTCCC
 ATTTAGCCTT AACCCCCTCT TACGGGGACA CTTACACCTG TGTGGTAGAG CACACTGGGG
 CTCCTGAGCC CATCCTTCGG GACTGGA*   
>DL;HLA:HLA02012
HLA:HLA02012 DMB*01:07 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CGCCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGTTCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AACTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG*    
