>DL;HLA:HLA00489
HLA:HLA00489 DMB*01:01:01:01 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA06461
HLA:HLA06461 DMB*01:01:01:02 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA06462
HLA:HLA06462 DMB*01:01:01:03 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA06466
HLA:HLA06466 DMB*01:01:01:04 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34468
HLA:HLA34468 DMB*01:01:01:05 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34632
HLA:HLA34632 DMB*01:01:01:06 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34645
HLA:HLA34645 DMB*01:01:01:07 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34624
HLA:HLA34624 DMB*01:01:01:08 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34620
HLA:HLA34620 DMB*01:01:01:09 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34611
HLA:HLA34611 DMB*01:01:01:10 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34488
HLA:HLA34488 DMB*01:01:01:11 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34485
HLA:HLA34485 DMB*01:01:01:12 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34447
HLA:HLA34447 DMB*01:01:01:13 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34450
HLA:HLA34450 DMB*01:01:01:14 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34464
HLA:HLA34464 DMB*01:01:01:15 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34608
HLA:HLA34608 DMB*01:01:01:16 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34483
HLA:HLA34483 DMB*01:01:01:17 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34471
HLA:HLA34471 DMB*01:01:01:18 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34465
HLA:HLA34465 DMB*01:01:01:19 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34646
HLA:HLA34646 DMB*01:01:01:20 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34615
HLA:HLA34615 DMB*01:01:01:21 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34642
HLA:HLA34642 DMB*01:01:01:22 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34457
HLA:HLA34457 DMB*01:01:01:23 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34616
HLA:HLA34616 DMB*01:01:01:24 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34614
HLA:HLA34614 DMB*01:01:01:25 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34477
HLA:HLA34477 DMB*01:01:01:26 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34455
HLA:HLA34455 DMB*01:01:01:27 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34493
HLA:HLA34493 DMB*01:01:01:28 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34511
HLA:HLA34511 DMB*01:01:01:29 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34496
HLA:HLA34496 DMB*01:01:01:30 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34456
HLA:HLA34456 DMB*01:01:01:31 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34627
HLA:HLA34627 DMB*01:01:01:32 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34641
HLA:HLA34641 DMB*01:01:01:33 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34528
HLA:HLA34528 DMB*01:01:01:34 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34562
HLA:HLA34562 DMB*01:01:01:35 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34550
HLA:HLA34550 DMB*01:01:01:36 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34565
HLA:HLA34565 DMB*01:01:01:37 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34514
HLA:HLA34514 DMB*01:01:01:38 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34527
HLA:HLA34527 DMB*01:01:01:39 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34538
HLA:HLA34538 DMB*01:01:01:40 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34564
HLA:HLA34564 DMB*01:01:01:41 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34589
HLA:HLA34589 DMB*01:01:01:42 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA37489
HLA:HLA37489 DMB*01:01:01:43 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA37624
HLA:HLA37624 DMB*01:01:01:44 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA37496
HLA:HLA37496 DMB*01:01:01:45 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA37531
HLA:HLA37531 DMB*01:01:01:46 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA37643
HLA:HLA37643 DMB*01:01:01:47 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA37641
HLA:HLA37641 DMB*01:01:01:48 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA37664
HLA:HLA37664 DMB*01:01:01:49 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA41492
HLA:HLA41492 DMB*01:01:01:50 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA41250
HLA:HLA41250 DMB*01:01:01:51 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA00490
HLA:HLA00490 DMB*01:02:01:01 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGAGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34660
HLA:HLA34660 DMB*01:02:01:02 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGAGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34683
HLA:HLA34683 DMB*01:02:01:03 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGAGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA37655
HLA:HLA37655 DMB*01:02:01:04 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGAGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA37630
HLA:HLA37630 DMB*01:02:01:05 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGAGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA00491
HLA:HLA00491 DMB*01:03:01:01 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA06459
HLA:HLA06459 DMB*01:03:01:02 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA06463
HLA:HLA06463 DMB*01:03:01:03 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA06465
HLA:HLA06465 DMB*01:03:01:04 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34467
HLA:HLA34467 DMB*01:03:01:05 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34631
HLA:HLA34631 DMB*01:03:01:06 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34472
HLA:HLA34472 DMB*01:03:01:07 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34502
HLA:HLA34502 DMB*01:03:01:08 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34640
HLA:HLA34640 DMB*01:03:01:09 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34604
HLA:HLA34604 DMB*01:03:01:10 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34478
HLA:HLA34478 DMB*01:03:01:11 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34479
HLA:HLA34479 DMB*01:03:01:12 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34540
HLA:HLA34540 DMB*01:03:01:13 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34529
HLA:HLA34529 DMB*01:03:01:14 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34590
HLA:HLA34590 DMB*01:03:01:15 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34576
HLA:HLA34576 DMB*01:03:01:16 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA37525
HLA:HLA37525 DMB*01:03:01:17 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA37520
HLA:HLA37520 DMB*01:03:01:18 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA41443
HLA:HLA41443 DMB*01:03:01:19 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34513
HLA:HLA34513 DMB*01:03:02 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTAG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA00492
HLA:HLA00492 DMB*01:04 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGTGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAC TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA00493
HLA:HLA00493 DMB*01:05 527 bases
 GGAAAGCACC TGTCTGTTGG ATGATGCTGG GACTCCAAAG GATTTCACAT ACTGCATCTC
 CTTCAACAAG GATCTGCTGA CCTGCTGGGA TCCAGAGGAG AATAAGATGG CCCCTTGCGA
 ATTTGGGGTG CTGAATAGCT TGGCGAATGT CCTCTCACAG CACCTCAACC AAAAAGACAC
 CCTGATGCAG CGCTTGCGCA ATGGGCTTCA GAATTGTGCC ACACACACCC AGCCCTTCTG
 GGGATCACTG ACCAACAGGA CACGGCCACC ATCTGTGCAA GTAGCCAAAA CCACTCCTTT
 TAACACGAGG GAGCCTGTGA TGCTGGCCTG CTATGTGTGG GGCTTCTATC CAGCAGAAGT
 GACTATCACG TGGAGGAAGA ACGGGAAGCT TGTCATGCCT CACAGCAGTG TGCACAAGAC
 TGCCCAGCCC AATGGAGACT GGACATACCA GACCCTCTCC CATTTAGCCT TAACCCCCTC
 TTACGGGGAC ACTTACACCT GTGTGGTAGA GCACATTGGG GCTCCTG 
>DL;HLA:HLA01083
HLA:HLA01083 DMB*01:06 567 bases
 GTGGCTTCGT GGCCCATGTG GAAAGCACCT GTCTGTTGGA TGATGCTGGG ACTCCAAAGG
 ATTTCACATA CTGCATCTTC TTCAACAAGG ATCTGCTGAC CTGCTGGGAT CCAGAGGAGA
 ATAAGATGGC CCCTTGCGAA TTTGGGGTGC TGAATAGCTT GGCGAATGTC CTCTCACAGC
 ACCTCAACCA AAAAGACACC CTGATGCAGC GCTTGCGCAA TGGGCTTCAG AATTGTGCCA
 CACACACCCA GCCCTTCTGG GGATCACTGA CCAACAGGAC ACGGCCACCA TCTGTGCAAG
 TAGCCAAAAC CACTCCTTTT AACACGAGGG AGCCTGTGAT GCTGGCCTGC TATGTGTGGG
 GCTTCTATCC AGCAGAAGTG ACTATCACGT GGAGGAAGAA CGGGAAGCTT GTCATGCCTC
 ACAGCAGTGA GCACAAGACT GCCCAGCCCA ATGGAGACTG GACATACCAG ACCCTCTCCC
 ATTTAGCCTT AACCCCCTCT TACGGGGACA CTTACACCTG TGTGGTAGAG CACACTGGGG
 CTCCTGAGCC CATCCTTCGG GACTGGA   
>DL;HLA:HLA02012
HLA:HLA02012 DMB*01:07:01:01 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CGCCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGTTCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AACTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34777
HLA:HLA34777 DMB*01:07:01:02 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CGCCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGTTCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AACTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34687
HLA:HLA34687 DMB*01:07:01:03 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CGCCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGTTCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AACTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34743
HLA:HLA34743 DMB*01:07:01:04 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CGCCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGTTCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AACTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34626
HLA:HLA34626 DMB*01:08 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATTTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCAGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
>DL;HLA:HLA34539
HLA:HLA34539 DMB*01:09 792 bases
 ATGATCACAT TCCTGCCGCT GCTGCTGGGG CTCAGCCTGG GCTGCACAGG AGCAGGTGGC
 TTCGTGGCCC ATGTGGAAAG CACCTGTCTG TTGGATGATG CTGGGACTCC AAAGGATTTC
 ACATACTGCA TCTCCTTCAA CAAGGATCTG CTGACCTGCT GGGATCCAGA GGAGAATAAG
 ATGGCCCCTT GCGAATCTGG GGTGCTGAAT AGCTTGGCGA ATGTCCTCTC ACAGCACCTC
 AACCAAAAAG ACACCCTGAT GCAGCGCTTG CGCAATGGGC TTCAGAATTG TGCCACACAC
 ACCCAGCCCT TCTGGGGATC ACTGACCAAC AGGACACGGC CACCATCTGT GCAAGTAGCC
 AAAACCACTC CTTTTAACAC GAGGGAGCCT GTGATGCTGG CCTGCTATGT GTGGGGCTTC
 TATCCAGCAG AAGTGACTAT CACGTGGAGG AAGAACGGGA AGCTTGTCAT GCCTCACAGC
 AGTGCGCACA AGACTGCCCA GCCCAATGGA GACTGGACAT ACCAGACCCT CTCCCATTTA
 GCCTTAACCC CCTCTTACGG GGACACTTAC ACCTGTGTGG TAGAGCACAT TGGGGCTCCT
 GAGCCCATCC TTCGGGACTG GACACCTGGG CTGTCCCCCA TGCAGACCCT GAAGGTTTCT
 GTGTCTGCAG TGACTCTGGG CCTGGGCCTC ATCATCTTCT CTCTTGGTGT GATCAGCTGG
 CGGAGAGCTG GCCACTCTAG TTACACTCCT CTTCCTGGGT CCAATTATTC AGAAGGATGG
 CACATTTCCT AG    
