>P1;HLA:HLA00494
HLA:HLA00494 DOA*01:01:01:01 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35554
HLA:HLA35554 DOA*01:01:01:02 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35427
HLA:HLA35427 DOA*01:01:01:03 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35468
HLA:HLA35468 DOA*01:01:01:04 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35446
HLA:HLA35446 DOA*01:01:01:05 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35492
HLA:HLA35492 DOA*01:01:01:06 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35430
HLA:HLA35430 DOA*01:01:01:07 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA00495
HLA:HLA00495 DOA*01:01:02:01 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA00496
HLA:HLA00496 DOA*01:01:02:02 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA00995
HLA:HLA00995 DOA*01:01:02:03 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35127
HLA:HLA35127 DOA*01:01:02:04 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35339
HLA:HLA35339 DOA*01:01:02:05 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35613
HLA:HLA35613 DOA*01:01:02:06 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35552
HLA:HLA35552 DOA*01:01:02:07 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35489
HLA:HLA35489 DOA*01:01:02:08 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35517
HLA:HLA35517 DOA*01:01:02:09 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35488
HLA:HLA35488 DOA*01:01:02:10 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35500
HLA:HLA35500 DOA*01:01:02:11 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35516
HLA:HLA35516 DOA*01:01:02:12 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35525
HLA:HLA35525 DOA*01:01:02:13 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35537
HLA:HLA35537 DOA*01:01:02:14 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35437
HLA:HLA35437 DOA*01:01:02:15 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35428
HLA:HLA35428 DOA*01:01:02:16 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35472
HLA:HLA35472 DOA*01:01:02:17 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35456
HLA:HLA35456 DOA*01:01:02:18 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35445
HLA:HLA35445 DOA*01:01:02:19 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35453
HLA:HLA35453 DOA*01:01:02:20 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35490
HLA:HLA35490 DOA*01:01:02:21 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35544
HLA:HLA35544 DOA*01:01:02:22 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35502
HLA:HLA35502 DOA*01:01:02:23 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35487
HLA:HLA35487 DOA*01:01:02:24 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35509
HLA:HLA35509 DOA*01:01:02:25 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35518
HLA:HLA35518 DOA*01:01:02:26 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35503
HLA:HLA35503 DOA*01:01:02:27 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35486
HLA:HLA35486 DOA*01:01:02:28 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35558
HLA:HLA35558 DOA*01:01:02:29 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35454
HLA:HLA35454 DOA*01:01:02:30 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35435
HLA:HLA35435 DOA*01:01:02:31 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35480
HLA:HLA35480 DOA*01:01:02:32 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35459
HLA:HLA35459 DOA*01:01:02:33 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35551
HLA:HLA35551 DOA*01:01:02:34 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35529
HLA:HLA35529 DOA*01:01:02:35 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35512
HLA:HLA35512 DOA*01:01:02:36 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35498
HLA:HLA35498 DOA*01:01:02:37 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35514
HLA:HLA35514 DOA*01:01:02:38 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35582
HLA:HLA35582 DOA*01:01:02:39 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36174
HLA:HLA36174 DOA*01:01:02:40 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36148
HLA:HLA36148 DOA*01:01:02:41 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36116
HLA:HLA36116 DOA*01:01:02:42 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36171
HLA:HLA36171 DOA*01:01:02:43 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36226
HLA:HLA36226 DOA*01:01:02:44 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36099
HLA:HLA36099 DOA*01:01:02:45 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36225
HLA:HLA36225 DOA*01:01:02:46 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36033
HLA:HLA36033 DOA*01:01:02:47 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA00996
HLA:HLA00996 DOA*01:01:03:01 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36132
HLA:HLA36132 DOA*01:01:03:02 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36172
HLA:HLA36172 DOA*01:01:03:03 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36282
HLA:HLA36282 DOA*01:01:03:04 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36235
HLA:HLA36235 DOA*01:01:03:05 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA00997
HLA:HLA00997 DOA*01:01:04:01 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA00998
HLA:HLA00998 DOA*01:01:04:02 222 bases
 DHMGSYGPAF YQSYGASGQF THEFDEEQLF SVDLKKSEAV WRLPEFGDFA RFDPQGGLAG
 IAAIKAHLDI LVERSNRSRA INVPPRVTVL PKSRVELGQP NILICIVDNI FPPVINITWL
 RNGQTVTEGV AQTSFYSQPD HLFRKFHYLP FVPSAEDVYD CQVEHWGLDA PLLRHWELQV
 PIPPPDAMET LVCALGLAIG LVGFLVGTVL IIMGTYVSSV PR 
>P1;HLA:HLA35403
HLA:HLA35403 DOA*01:01:04:03 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35556
HLA:HLA35556 DOA*01:01:04:04 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35452
HLA:HLA35452 DOA*01:01:04:05 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35466
HLA:HLA35466 DOA*01:01:04:06 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35473
HLA:HLA35473 DOA*01:01:04:07 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35528
HLA:HLA35528 DOA*01:01:04:08 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35536
HLA:HLA35536 DOA*01:01:04:09 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA38899
HLA:HLA38899 DOA*01:01:04:10 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA00999
HLA:HLA00999 DOA*01:01:05 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA02145
HLA:HLA02145 DOA*01:01:06 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35545
HLA:HLA35545 DOA*01:01:07 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35524
HLA:HLA35524 DOA*01:01:08 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35440
HLA:HLA35440 DOA*01:01:09 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35557
HLA:HLA35557 DOA*01:01:10 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35429
HLA:HLA35429 DOA*01:01:11 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36209
HLA:HLA36209 DOA*01:01:12 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA02153
HLA:HLA02153 DOA*01:02:01:01 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNCSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36207
HLA:HLA36207 DOA*01:02:01:02 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNCSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA36153
HLA:HLA36153 DOA*01:02:01:03 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNCSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA02154
HLA:HLA02154 DOA*01:03 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDIVV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA02155
HLA:HLA02155 DOA*01:04N 62 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPPSTS LTAPRASSPM NLMRNSCSLW
 TX     
>P1;HLA:HLA35354
HLA:HLA35354 DOA*01:05 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTILII
 MGTYVSSVPR     
>P1;HLA:HLA35538
HLA:HLA35538 DOA*01:06 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV VFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35510
HLA:HLA35510 DOA*01:07 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLCN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35481
HLA:HLA35481 DOA*01:08 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNILP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35471
HLA:HLA35471 DOA*01:09 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFAHF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35482
HLA:HLA35482 DOA*01:10 250 bases
 MALRARLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35457
HLA:HLA35457 DOA*01:11 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN RQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35539
HLA:HLA35539 DOA*01:12 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKDDH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35499
HLA:HLA35499 DOA*01:13 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPNAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35511
HLA:HLA35511 DOA*01:14 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFRYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
>P1;HLA:HLA35608
HLA:HLA35608 DOA*01:15 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FCKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR     
