>DL;HLA:HLA00494
HLA:HLA00494 DOA*01:01:01 753 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCCGC CTTCTACCAG
 TCTTACGGCG CCTCGGGCCA GTTCACCCAT GAATTTGATG AGGAACAGCT GTTCTCTGTG
 GACCTGAAGA AAAGCGAGGC CGTGTGGCGT CTGCCTGAGT TTGGTGACTT TGCCCGCTTT
 GACCCGCAGG GTGGGCTGGC CGGCATCGCC GCAATCAAAG CCCATCTGGA CATCCTGGTG
 GAGCGCTCCA ACCGCAGCAG AGCCATCAAC GTGCCTCCAC GGGTGACCGT GCTCCCCAAG
 TCTCGGGTGG AGCTGGGCCA GCCCAACATC CTCATCTGCA TCGTGGACAA CATCTTCCCC
 CCTGTGATCA ATATCACCTG GCTACGCAAC GGCCAAACTG TCACTGAGGG AGTGGCCCAG
 ACCAGCTTCT ATTCCCAGCC TGACCATTTG TTCCGCAAGT TCCACTACCT GCCCTTCGTG
 CCCTCAGCCG AGGACGTCTA TGACTGCCAG GTGGAGCACT GGGGCCTGGA TGCGCCACTC
 CTCAGGCATT GGGAGCTCCA GGTGCCTATT CCACCACCAG ATGCCATGGA GACCCTGGTC
 TGTGCCCTGG GTCTGGCCAT CGGCCTGGTG GGCTTCCTCG TGGGCACCGT CCTCATCATC
 ATGGGCACAT ATGTGTCCAG TGTCCCCAGG TAA  
>DL;HLA:HLA00495
HLA:HLA00495 DOA*01:01:02:01 753 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCCGC CTTCTACCAG
 TCTTACGGCG CCTCGGGCCA GTTCACCCAT GAATTTGATG AGGAACAGCT GTTCTCTGTG
 GACCTGAAGA AAAGCGAGGC CGTGTGGCGT CTGCCTGAGT TTGGTGACTT TGCCCGCTTT
 GACCCGCAGG GCGGGCTGGC CGGCATCGCC GCAATCAAAG CCCATCTGGA CATCCTGGTG
 GAGCGCTCCA ACCGCAGCAG AGCCATCAAC GTGCCTCCAC GGGTGACCGT GCTCCCCAAG
 TCTCGGGTGG AGCTGGGCCA GCCCAACATC CTCATCTGCA TCGTGGACAA CATCTTCCCC
 CCTGTGATCA ATATCACCTG GCTGCGCAAC GGCCAAACTG TCACTGAGGG AGTGGCCCAG
 ACCAGCTTCT ATTCCCAGCC TGACCATTTG TTCCGCAAGT TCCACTACCT GCCCTTCGTG
 CCCTCAGCCG AGGACGTCTA TGACTGCCAG GTGGAGCACT GGGGCCTGGA TGCGCCACTC
 CTCAGGCATT GGGAGCTCCA GGTGCCTATT CCACCACCAG ATGCCATGGA GACCCTGGTC
 TGTGCCCTGG GCCTGGCCAT CGGCCTGGTG GGCTTCCTCG TGGGCACCGT CCTCATCATC
 ATGGGCACAT ATGTGTCCAG TGTCCCCAGG TAA  
>DL;HLA:HLA00496
HLA:HLA00496 DOA*01:01:02:02 753 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCCGC CTTCTACCAG
 TCTTACGGCG CCTCGGGCCA GTTCACCCAT GAATTTGATG AGGAACAGCT GTTCTCTGTG
 GACCTGAAGA AAAGCGAGGC CGTGTGGCGT CTGCCTGAGT TTGGTGACTT TGCCCGCTTT
 GACCCGCAGG GCGGGCTGGC CGGCATCGCC GCAATCAAAG CCCATCTGGA CATCCTGGTG
 GAGCGCTCCA ACCGCAGCAG AGCCATCAAC GTGCCTCCAC GGGTGACCGT GCTCCCCAAG
 TCTCGGGTGG AGCTGGGCCA GCCCAACATC CTCATCTGCA TCGTGGACAA CATCTTCCCC
 CCTGTGATCA ATATCACCTG GCTGCGCAAC GGCCAAACTG TCACTGAGGG AGTGGCCCAG
 ACCAGCTTCT ATTCCCAGCC TGACCATTTG TTCCGCAAGT TCCACTACCT GCCCTTCGTG
 CCCTCAGCCG AGGACGTCTA TGACTGCCAG GTGGAGCACT GGGGCCTGGA TGCGCCACTC
 CTCAGGCATT GGGAGCTCCA GGTGCCTATT CCACCACCAG ATGCCATGGA GACCCTGGTC
 TGTGCCCTGG GCCTGGCCAT CGGCCTGGTG GGCTTCCTCG TGGGCACCGT CCTCATCATC
 ATGGGCACAT ATGTGTCCAG TGTCCCCAGG TAA  
>DL;HLA:HLA00995
HLA:HLA00995 DOA*01:01:02:03 753 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCCGC CTTCTACCAG
 TCTTACGGCG CCTCGGGCCA GTTCACCCAT GAATTTGATG AGGAACAGCT GTTCTCTGTG
 GACCTGAAGA AAAGCGAGGC CGTGTGGCGT CTGCCTGAGT TTGGTGACTT TGCCCGCTTT
 GACCCGCAGG GCGGGCTGGC CGGCATCGCC GCAATCAAAG CCCATCTGGA CATCCTGGTG
 GAGCGCTCCA ACCGCAGCAG AGCCATCAAC GTGCCTCCAC GGGTGACCGT GCTCCCCAAG
 TCTCGGGTGG AGCTGGGCCA GCCCAACATC CTCATCTGCA TCGTGGACAA CATCTTCCCC
 CCTGTGATCA ATATCACCTG GCTGCGCAAC GGCCAAACTG TCACTGAGGG AGTGGCCCAG
 ACCAGCTTCT ATTCCCAGCC TGACCATTTG TTCCGCAAGT TCCACTACCT GCCCTTCGTG
 CCCTCAGCCG AGGACGTCTA TGACTGCCAG GTGGAGCACT GGGGCCTGGA TGCGCCACTC
 CTCAGGCATT GGGAGCTCCA GGTGCCTATT CCACCACCAG ATGCCATGGA GACCCTGGTC
 TGTGCCCTGG GCCTGGCCAT CGGCCTGGTG GGCTTCCTCG TGGGCACCGT CCTCATCATC
 ATGGGCACAT ATGTGTCCAG TGTCCCCAGG TAA  
>DL;HLA:HLA35127
HLA:HLA35127 DOA*01:01:02:04 753 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCCGC CTTCTACCAG
 TCTTACGGCG CCTCGGGCCA GTTCACCCAT GAATTTGATG AGGAACAGCT GTTCTCTGTG
 GACCTGAAGA AAAGCGAGGC CGTGTGGCGT CTGCCTGAGT TTGGTGACTT TGCCCGCTTT
 GACCCGCAGG GCGGGCTGGC CGGCATCGCC GCAATCAAAG CCCATCTGGA CATCCTGGTG
 GAGCGCTCCA ACCGCAGCAG AGCCATCAAC GTGCCTCCAC GGGTGACCGT GCTCCCCAAG
 TCTCGGGTGG AGCTGGGCCA GCCCAACATC CTCATCTGCA TCGTGGACAA CATCTTCCCC
 CCTGTGATCA ATATCACCTG GCTGCGCAAC GGCCAAACTG TCACTGAGGG AGTGGCCCAG
 ACCAGCTTCT ATTCCCAGCC TGACCATTTG TTCCGCAAGT TCCACTACCT GCCCTTCGTG
 CCCTCAGCCG AGGACGTCTA TGACTGCCAG GTGGAGCACT GGGGCCTGGA TGCGCCACTC
 CTCAGGCATT GGGAGCTCCA GGTGCCTATT CCACCACCAG ATGCCATGGA GACCCTGGTC
 TGTGCCCTGG GCCTGGCCAT CGGCCTGGTG GGCTTCCTCG TGGGCACCGT CCTCATCATC
 ATGGGCACAT ATGTGTCCAG TGTCCCCAGG TAA  
>DL;HLA:HLA35339
HLA:HLA35339 DOA*01:01:02:05 753 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCCGC CTTCTACCAG
 TCTTACGGCG CCTCGGGCCA GTTCACCCAT GAATTTGATG AGGAACAGCT GTTCTCTGTG
 GACCTGAAGA AAAGCGAGGC CGTGTGGCGT CTGCCTGAGT TTGGTGACTT TGCCCGCTTT
 GACCCGCAGG GCGGGCTGGC CGGCATCGCC GCAATCAAAG CCCATCTGGA CATCCTGGTG
 GAGCGCTCCA ACCGCAGCAG AGCCATCAAC GTGCCTCCAC GGGTGACCGT GCTCCCCAAG
 TCTCGGGTGG AGCTGGGCCA GCCCAACATC CTCATCTGCA TCGTGGACAA CATCTTCCCC
 CCTGTGATCA ATATCACCTG GCTGCGCAAC GGCCAAACTG TCACTGAGGG AGTGGCCCAG
 ACCAGCTTCT ATTCCCAGCC TGACCATTTG TTCCGCAAGT TCCACTACCT GCCCTTCGTG
 CCCTCAGCCG AGGACGTCTA TGACTGCCAG GTGGAGCACT GGGGCCTGGA TGCGCCACTC
 CTCAGGCATT GGGAGCTCCA GGTGCCTATT CCACCACCAG ATGCCATGGA GACCCTGGTC
 TGTGCCCTGG GCCTGGCCAT CGGCCTGGTG GGCTTCCTCG TGGGCACCGT CCTCATCATC
 ATGGGCACAT ATGTGTCCAG TGTCCCCAGG TAA  
>DL;HLA:HLA00996
HLA:HLA00996 DOA*01:01:03 671 bases
 CTGACCACAT GGGCTCCTAC GGACCCGCCT TCTACCAGTC TTACGGCGCC TCGGGCCAGT
 TCACCCATGA ATTTGATGAG GAACAGCTGT TCTCTGTGGA CCTGAAGAAA AGCGAGGCCG
 TGTGGCGTCT GCCTGAGTTT GGTGACTTTG CCCGCTTTGA CCCGCAGGGT GGGCTGGCCG
 GCATCGCCGC AATCAAAGCC CATCTGGACA TCCTGGTGGA GCGCTCCAAC CGCAGCAGAG
 CCATCAACGT GCCTCCACGG GTGACCGTGC TCCCCAAGTC TCGGGTGGAG CTGGGCCAGC
 CCAACATCCT CATCTGCATC GTGGACAACA TCTTCCCCCC TGTGATCAAT ATCACCTGGC
 TACGCAACGG CCAAACTGTC ACTGAGGGAG TGGCCCAGAC CAGCTTCTAT TCCCAGCCTG
 ACCATTTGTT CCGCAAGTTC CACTACCTGC CCTTCGTGCC CTCAGCCGAG GACGTCTATG
 ACTGCCAGGT GGAGCACTGG GGCCTGGATG CGCCACTCCT CAGGCATTGG GAGCTCCAGG
 TGCCTATTCC ACCACCAGAT GCCATGGAGA CCCTGGTCTG TGCCCTGGGC CTGGCCATCG
 GCCTGGTGGG CTTCCTCGTG GGCACCGTCC TCATCATCAT GGGCACATAT GTGTCCAGTG
 TCCCCAGGTA A    
>DL;HLA:HLA00997
HLA:HLA00997 DOA*01:01:04:01 753 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCCGC CTTCTACCAG
 TCTTACGGCG CCTCGGGCCA GTTCACCCAT GAATTTGATG AGGAACAGCT GTTCTCTGTG
 GACCTGAAGA AAAGCGAGGC CGTGTGGCGT CTGCCTGAGT TTGGTGACTT TGCCCGCTTT
 GACCCGCAGG GCGGGCTGGC CGGCATCGCC GCAATCAAAG CCCATCTGGA CATCCTGGTG
 GAGCGCTCCA ACCGCAGCAG AGCCATCAAC GTGCCTCCAC GGGTGACCGT GCTCCCCAAG
 TCTCGGGTGG AGCTGGGCCA GCCCAACATC CTCATCTGCA TCGTGGACAA CATCTTCCCC
 CCTGTGATCA ATATCACCTG GCTACGCAAC GGCCAAACTG TCACTGAGGG AGTGGCCCAG
 ACCAGCTTCT ATTCCCAGCC TGACCATTTG TTCCGCAAGT TCCACTACCT GCCCTTCGTG
 CCCTCAGCCG AGGACGTCTA TGACTGCCAG GTGGAGCACT GGGGCCTGGA TGCGCCACTC
 CTCAGGCATT GGGAGCTCCA GGTGCCTATT CCACCACCAG ATGCCATGGA GACCCTGGTC
 TGTGCCCTGG GCCTGGCCAT CGGCCTGGTG GGCTTCCTCG TGGGCACCGT CCTCATCATC
 ATGGGCACAT ATGTGTCCAG TGTCCCCAGG TAA  
>DL;HLA:HLA00998
HLA:HLA00998 DOA*01:01:04:02 671 bases
 CTGACCACAT GGGCTCCTAC GGACCCGCCT TCTACCAGTC TTACGGCGCC TCGGGCCAGT
 TCACCCATGA ATTTGATGAG GAACAGCTGT TCTCTGTGGA CCTGAAGAAA AGCGAGGCCG
 TGTGGCGTCT GCCTGAGTTT GGTGACTTTG CCCGCTTTGA CCCGCAGGGC GGGCTGGCCG
 GCATCGCCGC AATCAAAGCC CATCTGGACA TCCTGGTGGA GCGCTCCAAC CGCAGCAGAG
 CCATCAACGT GCCTCCACGG GTGACCGTGC TCCCCAAGTC TCGGGTGGAG CTGGGCCAGC
 CCAACATCCT CATCTGCATC GTGGACAACA TCTTCCCCCC TGTGATCAAT ATCACCTGGC
 TACGCAACGG CCAAACTGTC ACTGAGGGAG TGGCCCAGAC CAGCTTCTAT TCCCAGCCTG
 ACCATTTGTT CCGCAAGTTC CACTACCTGC CCTTCGTGCC CTCAGCCGAG GACGTCTATG
 ACTGCCAGGT GGAGCACTGG GGCCTGGATG CGCCACTCCT CAGGCATTGG GAGCTCCAGG
 TGCCTATTCC ACCACCAGAT GCCATGGAGA CCCTGGTCTG TGCCCTGGGC CTGGCCATCG
 GCCTGGTGGG CTTCCTCGTG GGCACCGTCC TCATCATCAT GGGCACATAT GTGTCCAGTG
 TCCCCAGGTA A    
>DL;HLA:HLA00999
HLA:HLA00999 DOA*01:01:05 753 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCCGC CTTCTACCAG
 TCTTACGGCG CCTCGGGCCA GTTCACCCAT GAATTTGATG AGGAACAGCT GTTCTCTGTG
 GACCTGAAGA AAAGCGAGGC CGTGTGGCGT CTGCCTGAGT TTGGCGACTT TGCCCGCTTT
 GACCCGCAGG GCGGGCTGGC CGGCATCGCC GCAATCAAAG CCCATCTGGA CATCCTGGTG
 GAGCGCTCCA ACCGCAGCAG AGCCATCAAC GTGCCTCCAC GGGTGACCGT GCTCCCCAAG
 TCTCGGGTGG AGCTGGGCCA GCCCAACATC CTCATCTGCA TCGTGGACAA CATCTTCCCC
 CCTGTGATCA ATATCACCTG GCTGCGCAAC GGCCAAACTG TCACTGAGGG AGTGGCCCAG
 ACCAGCTTCT ATTCCCAGCC TGACCATTTG TTCCGCAAGT TCCACTACCT GCCCTTCGTG
 CCCTCAGCCG AGGACGTCTA TGACTGCCAG GTGGAGCACT GGGGCCTGGA TGCGCCACTC
 CTCAGGCATT GGGAGCTCCA GGTGCCTATT CCACCACCAG ATGCCATGGA GACCCTGGTC
 TGTGCCCTGG GCCTGGCCAT CGGCCTGGTG GGCTTCCTCG TGGGCACCGT CCTCATCATC
 ATGGGCACAT ATGTGTCCAG TGTCCCCAGG TAA  
>DL;HLA:HLA02145
HLA:HLA02145 DOA*01:01:06 753 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCCGC CTTCTACCAG
 TCTTACGGCG CCTCAGGCCA GTTCACCCAT GAATTTGATG AGGAACAGCT GTTCTCTGTG
 GACCTGAAGA AAAGCGAGGC CGTGTGGCGT CTGCCTGAGT TTGGTGACTT TGCCCGCTTT
 GACCCGCAGG GTGGGCTGGC CGGCATCGCC GCAATCAAAG CCCATCTGGA CATCCTGGTG
 GAGCGCTCCA ACCGCAGCAG AGCCATCAAC GTGCCTCCAC GGGTGACCGT GCTCCCCAAG
 TCTCGGGTGG AGCTGGGCCA GCCCAACATC CTCATCTGCA TCGTGGACAA CATCTTCCCC
 CCTGTGATCA ATATCACCTG GCTACGCAAC GGCCAAACTG TCACTGAGGG AGTGGCCCAG
 ACCAGCTTCT ATTCCCAGCC TGACCATTTG TTCCGCAAGT TCCACTACCT GCCCTTCGTG
 CCCTCAGCCG AGGACGTCTA TGACTGCCAG GTGGAGCACT GGGGCCTGGA TGCGCCACTC
 CTCAGGCATT GGGAGCTCCA GGTGCCTATT CCACCACCAG ATGCCATGGA GACCCTGGTC
 TGTGCCCTGG GCCTGGCCAT CGGCCTGGTG GGCTTCCTCG TGGGCACCGT CCTCATCATC
 ATGGGCACAT ATGTGTCCAG TGTCCCCAGG TAA  
>DL;HLA:HLA02153
HLA:HLA02153 DOA*01:02 753 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCCGC CTTCTACCAG
 TCTTACGGCG CCTCGGGCCA GTTCACCCAT GAATTTGATG AGGAACAGCT GTTCTCTGTG
 GACCTGAAGA AAAGCGAGGC CGTGTGGCGT CTGCCTGAGT TTGGTGACTT TGCCCGCTTT
 GACCCGCAGG GCGGGCTGGC CGGCATCGCC GCAATCAAAG CCCATCTGGA CATCCTGGTG
 GAGCGCTCCA ACTGCAGCAG AGCCATCAAC GTGCCTCCAC GGGTGACCGT GCTCCCCAAG
 TCTCGGGTGG AGCTGGGCCA GCCCAACATC CTCATCTGCA TCGTGGACAA CATCTTCCCC
 CCTGTGATCA ATATCACCTG GCTACGCAAC GGCCAAACTG TCACTGAGGG AGTGGCCCAG
 ACCAGCTTCT ATTCCCAGCC TGACCATTTG TTCCGCAAGT TCCACTACCT GCCCTTCGTG
 CCCTCAGCCG AGGACGTCTA TGACTGCCAG GTGGAGCACT GGGGCCTGGA TGCGCCACTC
 CTCAGGCATT GGGAGCTCCA GGTGCCTATT CCACCACCAG ATGCCATGGA GACCCTGGTC
 TGTGCCCTGG GCCTGGCCAT CGGCCTGGTG GGCTTCCTCG TGGGCACCGT CCTCATCATC
 ATGGGCACAT ATGTGTCCAG TGTCCCCAGG TAA  
>DL;HLA:HLA02154
HLA:HLA02154 DOA*01:03 753 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCCGC CTTCTACCAG
 TCTTACGGCG CCTCGGGCCA GTTCACCCAT GAATTTGATG AGGAACAGCT GTTCTCTGTG
 GACCTGAAGA AAAGCGAGGC CGTGTGGCGT CTGCCTGAGT TTGGTGACTT TGCCCGCTTT
 GACCCGCAGG GCGGGCTGGC CGGCATCGCC GCAATCAAAG CCCATCTGGA CATCGTGGTG
 GAGCGCTCCA ACCGCAGCAG AGCCATCAAC GTGCCTCCAC GGGTGACCGT GCTCCCCAAG
 TCTCGGGTGG AGCTGGGCCA GCCCAACATC CTCATCTGCA TCGTGGACAA CATCTTCCCC
 CCTGTGATCA ATATCACCTG GCTGCGCAAC GGCCAAACTG TCACTGAGGG AGTGGCCCAG
 ACCAGCTTCT ATTCCCAGCC TGACCATTTG TTCCGCAAGT TCCACTACCT GCCCTTCGTG
 CCCTCAGCCG AGGACGTCTA TGACTGCCAG GTGGAGCACT GGGGCCTGGA TGCGCCACTC
 CTCAGGCATT GGGAGCTCCA GGTGCCTATT CCACCACCAG ATGCCATGGA GACCCTGGTC
 TGTGCCCTGG GCCTGGCCAT CGGCCTGGTG GGCTTCCTCG TGGGCACCGT CCTCATCATC
 ATGGGCACAT ATGTGTCCAG TGTCCCCAGG TAA  
>DL;HLA:HLA02155
HLA:HLA02155 DOA*01:04N 752 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCGCC TTCTACCAGT
 CTTACGGCGC CTCGGGCCAG TTCACCCATG AATTTGATGA GGAACAGCTG TTCTCTGTGG
 ACCTGAAGAA AAGCGAGGCC GTGTGGCGTC TGCCTGAGTT TGGTGACTTT GCCCGCTTTG
 ACCCGCAGGG CGGGCTGGCC GGCATCGCCG CAATCAAAGC CCATCTGGAC ATCCTGGTGG
 AGCGCTCCAA CCGCAGCAGA GCCATCAACG TGCCTCCACG GGTGACCGTG CTCCCCAAGT
 CTCGGGTGGA GCTGGGCCAG CCCAACATCC TCATCTGCAT CGTGGACAAC ATCTTCCCCC
 CTGTGATCAA TATCACCTGG CTGCGCAACG GCCAAACTGT CACTGAGGGA GTGGCCCAGA
 CCAGCTTCTA TTCCCAGCCT GACCATTTGT TCCGCAAGTT CCACTACCTG CCCTTCGTGC
 CCTCAGCCGA GGACGTCTAT GACTGCCAGG TGGAGCACTG GGGCCTGGAT GCGCCACTCC
 TCAGGCATTG GGAGCTCCAG GTGCCTATTC CACCACCAGA TGCCATGGAG ACCCTGGTCT
 GTGCCCTGGG CCTGGCCATC GGCCTGGTGG GCTTCCTCGT GGGCACCGTC CTCATCATCA
 TGGGCACATA TGTGTCCAGT GTCCCCAGGT AA  
>DL;HLA:HLA35354
HLA:HLA35354 DOA*01:05 753 bases
 ATGGCCCTCA GAGCAGGGCT GGTCCTGGGG TTCCACACCC TGATGACCCT CCTGAGCCCG
 CAGGAGGCAG GGGCCACCAA GGCTGACCAC ATGGGCTCCT ACGGACCCGC CTTCTACCAG
 TCTTACGGCG CCTCGGGCCA GTTCACCCAT GAATTTGATG AGGAACAGCT GTTCTCTGTG
 GACCTGAAGA AAAGCGAGGC CGTGTGGCGT CTGCCTGAGT TTGGTGACTT TGCCCGCTTT
 GACCCGCAGG GTGGGCTGGC CGGCATCGCC GCAATCAAAG CCCATCTGGA CATCCTGGTG
 GAGCGCTCCA ACCGCAGCAG AGCCATCAAC GTGCCTCCAC GGGTGACCGT GCTCCCCAAG
 TCTCGGGTGG AGCTGGGCCA GCCCAACATC CTCATCTGCA TCGTGGACAA CATCTTCCCC
 CCTGTGATCA ATATCACCTG GCTACGCAAC GGCCAAACTG TCACTGAGGG AGTGGCCCAG
 ACCAGCTTCT ATTCCCAGCC TGACCATTTG TTCCGCAAGT TCCACTACCT GCCCTTCGTG
 CCCTCAGCCG AGGACGTCTA TGACTGCCAG GTGGAGCACT GGGGCCTGGA TGCGCCACTC
 CTCAGGCATT GGGAGCTCCA GGTGCCTATT CCACCACCAG ATGCCATGGA GACCCTGGTC
 TGTGCCCTGG GCCTGGCCAT CGGCCTGGTG GGCTTCCTCG TGGGCACCAT CCTCATCATC
 ATGGGCACAT ATGTGTCCAG TGTCCCCAGG TAA  
