>P1;HLA:HLA00494
HLA:HLA00494 DOA*01:01:01 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR *    
>P1;HLA:HLA00495
HLA:HLA00495 DOA*01:01:02:01 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR *    
>P1;HLA:HLA00496
HLA:HLA00496 DOA*01:01:02:02 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR *    
>P1;HLA:HLA00995
HLA:HLA00995 DOA*01:01:02:03 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR *    
>P1;HLA:HLA00996
HLA:HLA00996 DOA*01:01:03 222 bases
 DHMGSYGPAF YQSYGASGQF THEFDEEQLF SVDLKKSEAV WRLPEFGDFA RFDPQGGLAG
 IAAIKAHLDI LVERSNRSRA INVPPRVTVL PKSRVELGQP NILICIVDNI FPPVINITWL
 RNGQTVTEGV AQTSFYSQPD HLFRKFHYLP FVPSAEDVYD CQVEHWGLDA PLLRHWELQV
 PIPPPDAMET LVCALGLAIG LVGFLVGTVL IIMGTYVSSV PR* 
>P1;HLA:HLA00997
HLA:HLA00997 DOA*01:01:04:01 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR *    
>P1;HLA:HLA00998
HLA:HLA00998 DOA*01:01:04:02 222 bases
 DHMGSYGPAF YQSYGASGQF THEFDEEQLF SVDLKKSEAV WRLPEFGDFA RFDPQGGLAG
 IAAIKAHLDI LVERSNRSRA INVPPRVTVL PKSRVELGQP NILICIVDNI FPPVINITWL
 RNGQTVTEGV AQTSFYSQPD HLFRKFHYLP FVPSAEDVYD CQVEHWGLDA PLLRHWELQV
 PIPPPDAMET LVCALGLAIG LVGFLVGTVL IIMGTYVSSV PR* 
>P1;HLA:HLA00999
HLA:HLA00999 DOA*01:01:05 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR *    
>P1;HLA:HLA02145
HLA:HLA02145 DOA*01:01:06 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR *    
>P1;HLA:HLA02153
HLA:HLA02153 DOA*01:02 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDILV ERSNCSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR *    
>P1;HLA:HLA02154
HLA:HLA02154 DOA*01:03 250 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPAFYQ SYGASGQFTH EFDEEQLFSV
 DLKKSEAVWR LPEFGDFARF DPQGGLAGIA AIKAHLDIVV ERSNRSRAIN VPPRVTVLPK
 SRVELGQPNI LICIVDNIFP PVINITWLRN GQTVTEGVAQ TSFYSQPDHL FRKFHYLPFV
 PSAEDVYDCQ VEHWGLDAPL LRHWELQVPI PPPDAMETLV CALGLAIGLV GFLVGTVLII
 MGTYVSSVPR *    
>P1;HLA:HLA02155
HLA:HLA02155 DOA*01:04N 62 bases
 MALRAGLVLG FHTLMTLLSP QEAGATKADH MGSYGPPSTS LTAPRASSPM NLMRNSCSLW
 TX*     
