>P1;HLA:HLA01098
HLA:HLA01098 DOB*01:01:01:01 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01227
HLA:HLA01227 DOB*01:01:01:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA06458
HLA:HLA06458 DOB*01:01:01:03 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA06455
HLA:HLA06455 DOB*01:01:01:04 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35204
HLA:HLA35204 DOB*01:01:01:05 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35201
HLA:HLA35201 DOB*01:01:01:06 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35152
HLA:HLA35152 DOB*01:01:01:07 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35012
HLA:HLA35012 DOB*01:01:01:08 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34997
HLA:HLA34997 DOB*01:01:01:09 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34963
HLA:HLA34963 DOB*01:01:01:10 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34975
HLA:HLA34975 DOB*01:01:01:11 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35049
HLA:HLA35049 DOB*01:01:01:12 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35038
HLA:HLA35038 DOB*01:01:01:13 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35047
HLA:HLA35047 DOB*01:01:01:14 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35081
HLA:HLA35081 DOB*01:01:01:15 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35069
HLA:HLA35069 DOB*01:01:01:16 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35206
HLA:HLA35206 DOB*01:01:01:17 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35187
HLA:HLA35187 DOB*01:01:01:18 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34836
HLA:HLA34836 DOB*01:01:01:19 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34929
HLA:HLA34929 DOB*01:01:01:20 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35264
HLA:HLA35264 DOB*01:01:01:21 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35308
HLA:HLA35308 DOB*01:01:01:22 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35325
HLA:HLA35325 DOB*01:01:01:23 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34826
HLA:HLA34826 DOB*01:01:01:24 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35338
HLA:HLA35338 DOB*01:01:01:25 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35306
HLA:HLA35306 DOB*01:01:01:26 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34873
HLA:HLA34873 DOB*01:01:01:27 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA37650
HLA:HLA37650 DOB*01:01:01:28 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA40646
HLA:HLA40646 DOB*01:01:01:29 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA40647
HLA:HLA40647 DOB*01:01:01:30 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42140
HLA:HLA42140 DOB*01:01:01:31 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42084
HLA:HLA42084 DOB*01:01:01:32 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42073
HLA:HLA42073 DOB*01:01:01:33 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42102
HLA:HLA42102 DOB*01:01:01:34 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42772
HLA:HLA42772 DOB*01:01:01:35 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42773
HLA:HLA42773 DOB*01:01:01:36 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42786
HLA:HLA42786 DOB*01:01:01:37 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42813
HLA:HLA42813 DOB*01:01:01:38 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42800
HLA:HLA42800 DOB*01:01:01:39 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42862
HLA:HLA42862 DOB*01:01:01:40 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42888
HLA:HLA42888 DOB*01:01:01:41 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42861
HLA:HLA42861 DOB*01:01:01:42 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42860
HLA:HLA42860 DOB*01:01:01:43 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42821
HLA:HLA42821 DOB*01:01:01:44 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42795
HLA:HLA42795 DOB*01:01:01:45 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA44339
HLA:HLA44339 DOB*01:01:01:46 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA44259
HLA:HLA44259 DOB*01:01:01:47 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA44248
HLA:HLA44248 DOB*01:01:01:48 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA44261
HLA:HLA44261 DOB*01:01:01:49 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01217
HLA:HLA01217 DOB*01:01:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA02013
HLA:HLA02013 DOB*01:01:03:01 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA06467
HLA:HLA06467 DOB*01:01:03:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35169
HLA:HLA35169 DOB*01:01:03:03 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35051
HLA:HLA35051 DOB*01:01:03:04 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34896
HLA:HLA34896 DOB*01:01:03:05 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35359
HLA:HLA35359 DOB*01:01:03:06 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35263
HLA:HLA35263 DOB*01:01:03:07 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34839
HLA:HLA34839 DOB*01:01:03:08 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA37652
HLA:HLA37652 DOB*01:01:03:09 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA41409
HLA:HLA41409 DOB*01:01:03:10 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42156
HLA:HLA42156 DOB*01:01:03:11 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42903
HLA:HLA42903 DOB*01:01:03:12 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42794
HLA:HLA42794 DOB*01:01:03:13 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA43389
HLA:HLA43389 DOB*01:01:03:14 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA43348
HLA:HLA43348 DOB*01:01:03:15 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA44315
HLA:HLA44315 DOB*01:01:03:16 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34753
HLA:HLA34753 DOB*01:01:04 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34702
HLA:HLA34702 DOB*01:01:05:01 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42117
HLA:HLA42117 DOB*01:01:05:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35153
HLA:HLA35153 DOB*01:01:06 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42798
HLA:HLA42798 DOB*01:01:07 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA44322
HLA:HLA44322 DOB*01:01:08 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01099
HLA:HLA01099 DOB*01:02:01:01 273 bases
 MGSGWVPWVV ALLVNLTQLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34823
HLA:HLA34823 DOB*01:02:01:02 273 bases
 MGSGWVPWVV ALLVNLTQLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35371
HLA:HLA35371 DOB*01:02:01:03 273 bases
 MGSGWVPWVV ALLVNLTQLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42133
HLA:HLA42133 DOB*01:02:01:04 273 bases
 MGSGWVPWVV ALLVNLTQLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01215
HLA:HLA01215 DOB*01:02:02 273 bases
 MGSGWVPWVV ALLVNLTQLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01100
HLA:HLA01100 DOB*01:03:01:01 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIIIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34861
HLA:HLA34861 DOB*01:03:01:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIIIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42103
HLA:HLA42103 DOB*01:03:01:03 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIIIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA43121
HLA:HLA43121 DOB*01:03:01:04 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIIIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42778
HLA:HLA42778 DOB*01:03:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIIIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01206
HLA:HLA01206 DOB*01:04:01:01 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01216
HLA:HLA01216 DOB*01:04:01:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA40648
HLA:HLA40648 DOB*01:04:01:03 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34691
HLA:HLA34691 DOB*01:04:02:01 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA41296
HLA:HLA41296 DOB*01:04:02:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35358
HLA:HLA35358 DOB*01:04:03:01 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA41257
HLA:HLA41257 DOB*01:04:03:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA43138
HLA:HLA43138 DOB*01:04:03:03 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA06460
HLA:HLA06460 DOB*01:05:01:01 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPI SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42874
HLA:HLA42874 DOB*01:05:01:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPI SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34738
HLA:HLA34738 DOB*01:06 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGTA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34688
HLA:HLA34688 DOB*01:07 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEKWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35070
HLA:HLA35070 DOB*01:08 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGKK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34904
HLA:HLA34904 DOB*01:09 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QSVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35276
HLA:HLA35276 DOB*01:10:01:01 273 bases
 MGSGWVPWVV ALLVNLTQLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLIGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42101
HLA:HLA42101 DOB*01:10:01:02 273 bases
 MGSGWVPWVV ALLVNLTQLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLIGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34902
HLA:HLA34902 DOB*01:11 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPYAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIIIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35369
HLA:HLA35369 DOB*01:12 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG SEVSRAVLLP QSC  
>P1;HLA:HLA34821
HLA:HLA34821 DOB*01:13 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NKVSRAVLLP QSC  
>P1;HLA:HLA34906
HLA:HLA34906 DOB*01:14 273 bases
 MGSGWVPWVV ALLVNLTRLD TSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34926
HLA:HLA34926 DOB*01:15 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRSGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA37425
HLA:HLA37425 DOB*01:16 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDVVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA40649
HLA:HLA40649 DOB*01:17 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYSE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA41353
HLA:HLA41353 DOB*01:18N 185 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TALSGMETGP
 FRLWX     
>P1;HLA:HLA42893
HLA:HLA42893 DOB*01:19 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KRYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA42880
HLA:HLA42880 DOB*01:20 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTNLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA43370
HLA:HLA43370 DOB*01:21 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTLGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
