>DL;HLA:HLA01098
HLA:HLA01098 DOB*01:01:01:01 1265 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AAGGTCCTCA CTGAAGCTTC
 TCTCTCTGGA GCCTGAAGTA GTGATGAGTA GTCTGGGCCC TGGGTGAGGT AAAGGACATT
 CATGAGGTCA ATGTTCTGGG AATAACTCTC TTCCCTGATC CTTGGAGGAG CCCGAACTGA
 TTCTGGAGCT CTGTGTTCTG AGATCATGCA TCTCCCACCC ATCTGCCCTT CTCCCTTCTA
 CGTGTACATC ATTAATCCCC ATTGCCAAGG GCATTGTCCA GAAACTCCCC TGAGACCTTA
 CTCCTTCCAG CCCCAAATCA TTTACTTTTC TGTGGTCCAG CCCTACTCCT ATAAGTCATG
 ATCTCCAAAG CTTTCTGTCT TCCAACTGCA GTCTCCACAG TCTTCAGAAG ACAAATGCTC
 AGGTAGTCAC TGTTTCCTTT TCACTGTTTT TAAAAACCTT TTATTGTCAA ATAAAATGGA
 GATAC*     
>DL;HLA:HLA01227
HLA:HLA01227 DOB*01:01:01:02 1265 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AAGGTCCTCA CTGAAGCTTC
 TCTCTCTGGA GCCTGAAGTA GTGATGAGTA GTCTGGGCCC TGGGTGAGGT AAAGGACATT
 CATGAGGTCA ATGTTCTGGG AATAACTCTC TTCCCTGATC CTTGGAGGAG CCCGAACTGA
 TTCTGGAGCT CTGTGTTCTG AGATCATGCA TCTCCCACCC ATCTGCCCTT CTCCCTTCTA
 CGTGTACATC ATTAATCCCC ATTGCCAAGG GCATTGTCCA GAAACTCCCC TGAGACCTTA
 CTCCTTCCAG TCCCAAATCA TTTACTTTTC TGTGGTCCAG CCCTACTCCT ATAAGTCATG
 ATCTCCAAAG CTTTCTGTCT TCCAACTGCA GTCTCCACAG TCTTCAGAAG ACAAATGCTC
 AGGTAGTCAC TGTTTCCTTT TCACTGTTTT TAAAAACCTT TTATTGTCAA ATAAAATGGA
 GATAC*     
>DL;HLA:HLA01217
HLA:HLA01217 DOB*01:01:02 1265 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAAAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AAGGTCCTCA CTGAAGCTTC
 TCTCTCTGGA GCCTGAAGTA GTGATGAGTA GTCTGGGCCC TGGGTGAGGT AAAGGACATT
 CATGAGGTCA ATGTTCTGGG AATAACTCTC TTCCCTGATC CTTGGAGGAG CCCGAACTGA
 TTCTGGAGCT CTGTGTTCTG AGATCATGCA TCTCCCACCC ATCTGCCCTT CTCCCTTCTA
 CGTGTACATC ATTAATCCCC ATTGCCAAGG GCATTGTCCA GAAACTCCCC TGAGACCTTA
 CTCCTTCCAG CCCCAAATCA TTTACTTTTC TGTGGTCCAG CCCTACTCCT ATAAGTCATG
 ATCTCCAAAG CTTTCTGTCT TCCAACTGCA GTCTCCACAG TCTTCAGAAG ACAAATGCTC
 AGGTAGTCAC TGTTTCCTTT TCACTGTTTT TAAAAACCTT TTATTGTCAA ATAAAATGGA
 GATAC*     
>DL;HLA:HLA02013
HLA:HLA02013 DOB*01:01:03 1265 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AAGGTCCTCA CTGAAGCTTC
 TCTCTCTGGA GCCTGAAGTA GTGATGAGTA GTCTGGGCCC TGGGTGAGGT AAAGGACATT
 CATGAGGTCA ATGTTCTGGG AATAACTCTC TTCCCTGATC CTTGGAGGAG CCCGAACTGA
 TTCTGGAGCT CTGTGTTCTG AGATCATGCA TCTCCCACCC ATCTGCCCTT CTCCCTTCTA
 CGTGTACATC ATTAATCCCC ATTGCCAAGG GCATTGTCCA GAAACTCCCC TGAGACCTTA
 CTCCTTCCAG CCCCAAATCA TTTACTTTTC TGTGGTCCAG CCCTACTCCT ATAAGTCATG
 ATCTCCAAAG CTTTCTGTCT TCCAACTGCA GTCTCCACAG TCTTCAGAAG ACAAATGCTC
 AGGTAGTCAC TGTTTCCTTT TCACTGTTTT TAAAAACCTT TTATTGTCAA ATAAAATGGA
 GATAC*     
>DL;HLA:HLA01099
HLA:HLA01099 DOB*01:02:01 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCAACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA* 
>DL;HLA:HLA01215
HLA:HLA01215 DOB*01:02:02 1265 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCAACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAAAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AAGGTCCTCA CTGAAGCTTC
 TCTCTCTGGA GCCTGAAGTA GTGATGAGTA GTCTGGGCCC TGGGTGAGGT AAAGGACATT
 CATGAGGTCA ATGTTCTGGG AATAACTCTC TTCCCTGATC CTTGGAGGAG CCCGAACTGA
 TTCTGGAGCT CTGTGTTCTG AGATCATGCA TCTCCCACCC ATCTGCCCTT CTCCCTTCTA
 CGTGTACATC ATTAATCCCC ATTGCCAAGG GCATTGTCCA GAAACTCCCC TGAGACCTTA
 CTCCTTCCAG TCCCAAATCA TTTACTTTTC TGTGGTCCAG CCCTACTCCT ATAAGTCATG
 ATCTCCAAAG CTTTCTGTCT TCCAACTGCA GTCTCCACAG TCTTCAGAAG ACAAATGCTC
 AGGTAGTCAC TGTTTCCTTT TCACTGTTTT TAAAAACCTT TTATTGTCAA ATAAAATGGA
 GATAC*     
>DL;HLA:HLA01100
HLA:HLA01100 DOB*01:03 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCA TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA* 
>DL;HLA:HLA01206
HLA:HLA01206 DOB*01:04:01:01 1265 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA TACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAT TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AAGGTCCTCA CTGAAGCTTC
 TCTCTCTGGA GCCTGAAGTA GTGATGAGTA GTCTGGGCCC TGGGTGAGGT AAAGGACATT
 CATGAGGTCA ATGTTCTGGG AATAACTCTC TTCCCTGATC CTTGGAGGAG CCCGAACTGA
 TTCTGGAGCT CTGTGTTCTG AGATCATGCA TCTCCCACCC ATCTGCCCTT CTCCCTTCTA
 CGTGTACATC ATTAATCCCC ATTGCCAAGG GCATTGTCCA GAAACTCCCC TGAGACCTTA
 CTCCTTCCAG CCCCAAATCA TTTACTTTTC TGTGGTCCAG CCCTACTCCT ATAAGTCATG
 ATCTCCAAAG CTTTCTGTCT TCCAACTGCA GTCTCCACAG TCTTCAGAAG ACAAATGCTC
 AGGTAGTCAC TGTTTCCTTT TCACTGTTTT TAAAAACCTT TTATTGTCAA ATAAAATGGA
 GATAC*     
>DL;HLA:HLA01216
HLA:HLA01216 DOB*01:04:01:02 1265 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA TACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAT TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AAGGTCCTCA CTGAAGCTTC
 TCTCTCTGGA GCCTGAAGTA GTGATGAGTA GTCTGGGCCC TGGGTGAGGT AAAGGACATT
 TATGAGGTCA ATGTTCTGGG AATAACTCTC TTCCCTGATC CTTGGAGGAG CCCGAACTGA
 TTCTGGAGCT CTGTGTTCTG AGATCATGCA TCTCCCACCC ATCTGCCCTT CTCCCTTCTA
 CGTGTACATC ATTAATCCCC ATTGCCAAGG GCATTGTCCA GAAACTCCCC TGAGACCTTA
 CTCCTTCCAG CCCCAAATCA TTTACTTTTC TGTGGTCCAG CCCTACTCCT ATAAGTCATG
 ATCTCCAAAG CTTTCTGTCT TCCAACTGCA GTCTCCACAG TCTTCAGAAG ACAAATGCTC
 AGGTAGTCAC TGTTTCCTTT TCACTGTTTT TAAAAACCTT TTATTGTCAA ATAAAATGGA
 GATAC*     
