>DL;HLA:HLA01098
HLA:HLA01098 DOB*01:01:01:01 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA01227
HLA:HLA01227 DOB*01:01:01:02 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA06458
HLA:HLA06458 DOB*01:01:01:03 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA06455
HLA:HLA06455 DOB*01:01:01:04 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35204
HLA:HLA35204 DOB*01:01:01:05 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35201
HLA:HLA35201 DOB*01:01:01:06 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35152
HLA:HLA35152 DOB*01:01:01:07 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35012
HLA:HLA35012 DOB*01:01:01:08 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34997
HLA:HLA34997 DOB*01:01:01:09 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34963
HLA:HLA34963 DOB*01:01:01:10 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34975
HLA:HLA34975 DOB*01:01:01:11 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35049
HLA:HLA35049 DOB*01:01:01:12 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35038
HLA:HLA35038 DOB*01:01:01:13 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35047
HLA:HLA35047 DOB*01:01:01:14 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35081
HLA:HLA35081 DOB*01:01:01:15 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35069
HLA:HLA35069 DOB*01:01:01:16 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35206
HLA:HLA35206 DOB*01:01:01:17 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35187
HLA:HLA35187 DOB*01:01:01:18 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34836
HLA:HLA34836 DOB*01:01:01:19 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34929
HLA:HLA34929 DOB*01:01:01:20 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35264
HLA:HLA35264 DOB*01:01:01:21 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35308
HLA:HLA35308 DOB*01:01:01:22 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35325
HLA:HLA35325 DOB*01:01:01:23 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34826
HLA:HLA34826 DOB*01:01:01:24 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35338
HLA:HLA35338 DOB*01:01:01:25 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35306
HLA:HLA35306 DOB*01:01:01:26 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34873
HLA:HLA34873 DOB*01:01:01:27 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA37650
HLA:HLA37650 DOB*01:01:01:28 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA40646
HLA:HLA40646 DOB*01:01:01:29 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA40647
HLA:HLA40647 DOB*01:01:01:30 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA01217
HLA:HLA01217 DOB*01:01:02 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAAAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA02013
HLA:HLA02013 DOB*01:01:03:01 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA06467
HLA:HLA06467 DOB*01:01:03:02 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35169
HLA:HLA35169 DOB*01:01:03:03 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35051
HLA:HLA35051 DOB*01:01:03:04 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34896
HLA:HLA34896 DOB*01:01:03:05 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35359
HLA:HLA35359 DOB*01:01:03:06 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35263
HLA:HLA35263 DOB*01:01:03:07 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34839
HLA:HLA34839 DOB*01:01:03:08 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA37652
HLA:HLA37652 DOB*01:01:03:09 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA41409
HLA:HLA41409 DOB*01:01:03:10 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34753
HLA:HLA34753 DOB*01:01:04 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG GGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34702
HLA:HLA34702 DOB*01:01:05 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGATTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35153
HLA:HLA35153 DOB*01:01:06 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAATGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA01099
HLA:HLA01099 DOB*01:02:01:01 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCAACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34823
HLA:HLA34823 DOB*01:02:01:02 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCAACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35371
HLA:HLA35371 DOB*01:02:01:03 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCAACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA01215
HLA:HLA01215 DOB*01:02:02 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCAACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAAAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA01100
HLA:HLA01100 DOB*01:03:01:01 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCA TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34861
HLA:HLA34861 DOB*01:03:01:02 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCA TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA01206
HLA:HLA01206 DOB*01:04:01:01 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA TACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAT TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA01216
HLA:HLA01216 DOB*01:04:01:02 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA TACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAT TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA40648
HLA:HLA40648 DOB*01:04:01:03 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA TACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAT TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34691
HLA:HLA34691 DOB*01:04:02:01 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAT TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA41296
HLA:HLA41296 DOB*01:04:02:02 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGACTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAT TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35358
HLA:HLA35358 DOB*01:04:03:01 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAT TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA41257
HLA:HLA41257 DOB*01:04:03:02 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAT TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA06460
HLA:HLA06460 DOB*01:05 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTATT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34738
HLA:HLA34738 DOB*01:06 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCACTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34688
HLA:HLA34688 DOB*01:07 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGAAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35070
HLA:HLA35070 DOB*01:08 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAAAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA TACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAT TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34904
HLA:HLA34904 DOB*01:09 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTCTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35276
HLA:HLA35276 DOB*01:10 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCAACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAA TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34902
HLA:HLA34902 DOB*01:11 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCATATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCA TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA35369
HLA:HLA35369 DOB*01:12 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA TACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAT TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AGTGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34821
HLA:HLA34821 DOB*01:13 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATAAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34906
HLA:HLA34906 DOB*01:14 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 ACCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA TACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAT TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA34926
HLA:HLA34926 DOB*01:15 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAGTGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA37425
HLA:HLA37425 DOB*01:16 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGTGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA40649
HLA:HLA40649 DOB*01:17 822 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACTCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGGCCCTA TCAGGAATGG AGACTGGACC
 TTTCAGACTG TGGTGATGCT AGAAATGACT CCTGAACTTG GACATGTCTA CACCTGCCTT
 GTCGATCACT CCAGCCTGCT GAGCCCTGTT TCTGTGGAGT GGAGAGCTCA GTCTGAATAT
 TCTTGGAGAA AGATGCTGAG TGGCATTGCA GCCTTCCTAC TTGGGCTAAT CTTCCTTCTG
 GTGGGAATCG TCATCCAGCT AAGGGCTCAG AAAGGATATG TGAGGACGCA GATGTCTGGT
 AATGAGGTCT CAAGAGCTGT TCTGCTCCCT CAGTCATGCT AA 
>DL;HLA:HLA41353
HLA:HLA41353 DOB*01:18N 821 bases
 ATGGGTTCTG GGTGGGTCCC CTGGGTGGTG GCTCTGCTAG TGAATCTGAC CCGACTGGAT
 TCCTCCATGA CTCAAGGCAC AGACTCTCCA GAAGATTTTG TGATTCAGGC AAAGGCTGAC
 TGTTACTTCA CCAACGGGAC AGAAAAGGTG CAGTTTGTGG TCAGATTCAT CTTTAACTTG
 GAGGAGTATG TACGTTTCGA CAGTGATGTG GGGATGTTTG TGGCATTGAC CAAGCTGGGG
 CAGCCAGATG CTGAGCAGTG GAACAGCCGG CTGGATCTCT TGGAGAGGAG CAGACAGGCC
 GTGGATGGGG TCTGTAGACA CAACTACAGG CTGGGCGCAC CCTTCACTGT GGGGAGAAAA
 GTGCAACCAG AGGTGACAGT GTACCCAGAG AGGACCCCAC TCCTGCACCA GCATAATCTG
 CTGCACTGCT CTGTGACAGG CTTCTATCCA GGGGATATCA AGATCAAGTG GTTCCTGAAT
 GGGCAGGAGG AGAGAGCTGG GGTCATGTCC ACTGCCCTAT CAGGAATGGA GACTGGACCT
 TTCAGACTGT GGTGATGCTA GAAATGACTC CTGAACTTGG ACATGTCTAC ACCTGCCTTG
 TCGATCACTC CAGCCTGCTG AGCCCTGTTT CTGTGGAGTG GAGAGCTCAG TCTGAATATT
 CTTGGAGAAA GATGCTGAGT GGCATTGCAG CCTTCCTACT TGGGCTAATC TTCCTTCTGG
 TGGGAATCGT CATCCAGCTA AGGGCTCAGA AAGGATATGT GAGGACGCAG ATGTCTGGTA
 ATGAGGTCTC AAGAGCTGTT CTGCTCCCTC AGTCATGCTA A 
