>P1;HLA:HLA01098
HLA:HLA01098 DOB*01:01:01:01 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01227
HLA:HLA01227 DOB*01:01:01:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA06458
HLA:HLA06458 DOB*01:01:01:03 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA06455
HLA:HLA06455 DOB*01:01:01:04 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35204
HLA:HLA35204 DOB*01:01:01:05 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35201
HLA:HLA35201 DOB*01:01:01:06 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35152
HLA:HLA35152 DOB*01:01:01:07 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35012
HLA:HLA35012 DOB*01:01:01:08 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34997
HLA:HLA34997 DOB*01:01:01:09 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34963
HLA:HLA34963 DOB*01:01:01:10 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34975
HLA:HLA34975 DOB*01:01:01:11 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35049
HLA:HLA35049 DOB*01:01:01:12 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35038
HLA:HLA35038 DOB*01:01:01:13 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35047
HLA:HLA35047 DOB*01:01:01:14 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35081
HLA:HLA35081 DOB*01:01:01:15 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35069
HLA:HLA35069 DOB*01:01:01:16 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35206
HLA:HLA35206 DOB*01:01:01:17 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35187
HLA:HLA35187 DOB*01:01:01:18 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34836
HLA:HLA34836 DOB*01:01:01:19 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34929
HLA:HLA34929 DOB*01:01:01:20 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35264
HLA:HLA35264 DOB*01:01:01:21 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35308
HLA:HLA35308 DOB*01:01:01:22 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35325
HLA:HLA35325 DOB*01:01:01:23 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34826
HLA:HLA34826 DOB*01:01:01:24 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35338
HLA:HLA35338 DOB*01:01:01:25 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35306
HLA:HLA35306 DOB*01:01:01:26 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34873
HLA:HLA34873 DOB*01:01:01:27 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA37650
HLA:HLA37650 DOB*01:01:01:28 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA40646
HLA:HLA40646 DOB*01:01:01:29 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA40647
HLA:HLA40647 DOB*01:01:01:30 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01217
HLA:HLA01217 DOB*01:01:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA02013
HLA:HLA02013 DOB*01:01:03:01 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA06467
HLA:HLA06467 DOB*01:01:03:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35169
HLA:HLA35169 DOB*01:01:03:03 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35051
HLA:HLA35051 DOB*01:01:03:04 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34896
HLA:HLA34896 DOB*01:01:03:05 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35359
HLA:HLA35359 DOB*01:01:03:06 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35263
HLA:HLA35263 DOB*01:01:03:07 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34839
HLA:HLA34839 DOB*01:01:03:08 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA37652
HLA:HLA37652 DOB*01:01:03:09 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34753
HLA:HLA34753 DOB*01:01:04 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34702
HLA:HLA34702 DOB*01:01:05 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35153
HLA:HLA35153 DOB*01:01:06 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01099
HLA:HLA01099 DOB*01:02:01:01 273 bases
 MGSGWVPWVV ALLVNLTQLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34823
HLA:HLA34823 DOB*01:02:01:02 273 bases
 MGSGWVPWVV ALLVNLTQLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35371
HLA:HLA35371 DOB*01:02:01:03 273 bases
 MGSGWVPWVV ALLVNLTQLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01215
HLA:HLA01215 DOB*01:02:02 273 bases
 MGSGWVPWVV ALLVNLTQLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01100
HLA:HLA01100 DOB*01:03:01:01 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIIIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34861
HLA:HLA34861 DOB*01:03:01:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIIIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01206
HLA:HLA01206 DOB*01:04:01:01 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA01216
HLA:HLA01216 DOB*01:04:01:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA40648
HLA:HLA40648 DOB*01:04:01:03 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34691
HLA:HLA34691 DOB*01:04:02 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35358
HLA:HLA35358 DOB*01:04:03 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA06460
HLA:HLA06460 DOB*01:05 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPI SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34738
HLA:HLA34738 DOB*01:06 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGTA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34688
HLA:HLA34688 DOB*01:07 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEKWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35070
HLA:HLA35070 DOB*01:08 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGKK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34904
HLA:HLA34904 DOB*01:09 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QSVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35276
HLA:HLA35276 DOB*01:10 273 bases
 MGSGWVPWVV ALLVNLTQLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLIGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34902
HLA:HLA34902 DOB*01:11 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPYAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIIIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA35369
HLA:HLA35369 DOB*01:12 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG SEVSRAVLLP QSC  
>P1;HLA:HLA34821
HLA:HLA34821 DOB*01:13 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NKVSRAVLLP QSC  
>P1;HLA:HLA34906
HLA:HLA34906 DOB*01:14 273 bases
 MGSGWVPWVV ALLVNLTRLD TSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLFGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA34926
HLA:HLA34926 DOB*01:15 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRSGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA37425
HLA:HLA37425 DOB*01:16 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDVVCRHNYR LGAPFTVGRK
 VQPEVTVYPE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
>P1;HLA:HLA40649
HLA:HLA40649 DOB*01:17 273 bases
 MGSGWVPWVV ALLVNLTRLD SSMTQGTDSP EDFVIQAKAD CYFTNGTEKV QFVVRFIFNL
 EEYVRFDSDV GMFVALTKLG QPDAEQWNSR LDLLERSRQA VDGVCRHNYR LGAPFTVGRK
 VQPEVTVYSE RTPLLHQHNL LHCSVTGFYP GDIKIKWFLN GQEERAGVMS TGPIRNGDWT
 FQTVVMLEMT PELGHVYTCL VDHSSLLSPV SVEWRAQSEY SWRKMLSGIA AFLLGLIFLL
 VGIVIQLRAQ KGYVRTQMSG NEVSRAVLLP QSC  
