>P1;HLA:HLA00499
HLA:HLA00499 DPA1*01:03:01:01 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA06604
HLA:HLA06604 DPA1*01:03:01:02 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA06605
HLA:HLA06605 DPA1*01:03:01:03 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA06607
HLA:HLA06607 DPA1*01:03:01:04 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA06606
HLA:HLA06606 DPA1*01:03:01:05 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA17376
HLA:HLA17376 DPA1*01:03:01:06 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA17374
HLA:HLA17374 DPA1*01:03:01:07 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA17375
HLA:HLA17375 DPA1*01:03:01:08 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA17771
HLA:HLA17771 DPA1*01:03:01:09 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA17777
HLA:HLA17777 DPA1*01:03:01:10 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA17967
HLA:HLA17967 DPA1*01:03:01:11 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA19503
HLA:HLA19503 DPA1*01:03:01:12 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA20140
HLA:HLA20140 DPA1*01:03:01:13 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA20591
HLA:HLA20591 DPA1*01:03:01:14 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA20734
HLA:HLA20734 DPA1*01:03:01:15 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA20694
HLA:HLA20694 DPA1*01:03:01:16 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA21120
HLA:HLA21120 DPA1*01:03:01:17 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA21133
HLA:HLA21133 DPA1*01:03:01:18Q 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA21369
HLA:HLA21369 DPA1*01:03:01:19 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA22701
HLA:HLA22701 DPA1*01:03:01:20 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA22726
HLA:HLA22726 DPA1*01:03:01:21 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA22715
HLA:HLA22715 DPA1*01:03:01:22 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA22799
HLA:HLA22799 DPA1*01:03:01:23 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA00500
HLA:HLA00500 DPA1*01:03:02 74 bases
 AFVQTHRPTG EFMFEFDEDE MFYVDLDKKE TVWHLEEFGQ AFSFEAQGGL ANIAILNNNL
 NTLIQRSNHT QATN*    
>P1;HLA:HLA01937
HLA:HLA01937 DPA1*01:03:03 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA03224
HLA:HLA03224 DPA1*01:03:04 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA14098
HLA:HLA14098 DPA1*01:03:05 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA21477
HLA:HLA21477 DPA1*01:03:06 226 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT NDPPEVTVFP KEPVELGQPN TLICHIDKFF PPVLNVTWLC
 NGELVTEGVA ESLFLPRTDY SFHKFHYLTF VPSAEDFYDC RVEHWGLDQP LLKHWEAQEP
 IQMPETTETV LCALGLVLGL VGIIVGTVLI IKSLRSGHDP RAQGTL* 
>P1;HLA:HLA21903
HLA:HLA21903 DPA1*01:03:07 226 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT NDPPEVTVFP KEPVELGQPN TLICHIDKFF PPVLNVTWLC
 NGELVTEGVA ESLFLPRTDY SFHKFHYLTF VPSAEDFYDC RVEHWGLDQP LLKHWEAQEP
 IQMPETTETV LCALGLVLGL VGIIVGTVLI IKSLRSGHDP RAQGTL* 
>P1;HLA:HLA21996
HLA:HLA21996 DPA1*01:03:08 226 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT NDPPEVTVFP KEPVELGQPN TLICHIDKFF PPVLNVTWLC
 NGELVTEGVA ESLFLPRTDY SFHKFHYLTF VPSAEDFYDC RVEHWGLDQP LLKHWEAQEP
 IQMPETTETV LCALGLVLGL VGIIVGTVLI IKSLRSGHDP RAQGTL* 
>P1;HLA:HLA22305
HLA:HLA22305 DPA1*01:03:09 226 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT NDPPEVTVFP KEPVELGQPN TLICHIDKFF PPVLNVTWLC
 NGELVTEGVA ESLFLPRTDY SFHKFHYLTF VPSAEDFYDC RVEHWGLDQP LLKHWEAQEP
 IQMPETTETV LCALGLVLGL VGIIVGTVLI IKSLRSGHDP RAQGTL* 
>P1;HLA:HLA00501
HLA:HLA00501 DPA1*01:04 220 bases
 AAFVQTHRPT GEFMFEFDDD EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN
 LNTLIQRSNH TQATNDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT
 EGVAESLFLP RTDYSFHKFH YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET
 TETVLCALGL VLGLVGIIVG TVLIIKSLRS GHDPRAQGTL * 
>P1;HLA:HLA00502
HLA:HLA00502 DPA1*01:05 75 bases
 AAFVQTHRPT GEFMFEFDED EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN
 LNTLIQRSNH TQAAN*    
>P1;HLA:HLA00503
HLA:HLA00503 DPA1*01:06:01 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA03401
HLA:HLA03401 DPA1*01:06:02 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA01000
HLA:HLA01000 DPA1*01:07 80 bases
 HVSTYAAFVQ THRPTGEFMF EFDEDEMFYV DLDKKETVWH LEEFGQTFSF EAQGGLANIA
 ILNNNLNTLI QRSNHTQATN *   
>P1;HLA:HLA01466
HLA:HLA01466 DPA1*01:08 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDDDEMFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA02058
HLA:HLA02058 DPA1*01:09 81 bases
 DHVSTYAAFV QTHRPTGEFT FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA03223
HLA:HLA03223 DPA1*01:10 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVC HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA07533
HLA:HLA07533 DPA1*01:11 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA09332
HLA:HLA09332 DPA1*01:12 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AISNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA12908
HLA:HLA12908 DPA1*01:13 81 bases
 DHVSTYAVFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA16642
HLA:HLA16642 DPA1*01:14 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPQAQGTL *   
>P1;HLA:HLA19156
HLA:HLA19156 DPA1*01:15 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQCSNHTQAT N*   
>P1;HLA:HLA19309
HLA:HLA19309 DPA1*01:16 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEKFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA20190
HLA:HLA20190 DPA1*01:17 93 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT NDPPQVTVFP KEP*  
>P1;HLA:HLA22709
HLA:HLA22709 DPA1*01:18 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVLPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA22735
HLA:HLA22735 DPA1*01:19 175 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT NDPPEVTVFP KEPVELGQPN TLICHIDKFF PPVLNVTWLC
 NGELVTEGVA ESLFLPRTDY SFHKFHYLTF MPSAEDFYDC RVEHWGLDQP LLKHW*
>P1;HLA:HLA00504
HLA:HLA00504 DPA1*02:01:01:01 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA14197
HLA:HLA14197 DPA1*02:01:01:02 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA17377
HLA:HLA17377 DPA1*02:01:01:03 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA17773
HLA:HLA17773 DPA1*02:01:01:04 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA17774
HLA:HLA17774 DPA1*02:01:01:05 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA19322
HLA:HLA19322 DPA1*02:01:01:06 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA20675
HLA:HLA20675 DPA1*02:01:01:07 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA20785
HLA:HLA20785 DPA1*02:01:01:08 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA20814
HLA:HLA20814 DPA1*02:01:01:09 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA22795
HLA:HLA22795 DPA1*02:01:01:10 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA22797
HLA:HLA22797 DPA1*02:01:01:11 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA00505
HLA:HLA00505 DPA1*02:01:02:01 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA17776
HLA:HLA17776 DPA1*02:01:02:02 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA00506
HLA:HLA00506 DPA1*02:01:03 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA00507
HLA:HLA00507 DPA1*02:01:04 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA01097
HLA:HLA01097 DPA1*02:01:05 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA01168
HLA:HLA01168 DPA1*02:01:06 86 bases
 IKADHVSTYA AFVQTHRPTG EFMFEFDEDE QFYVDLDKKE TVWHLEEFGR AFSFEAQGGL
 ANIAILNNNL NTLIQRSNHT QAANDP*   
>P1;HLA:HLA03999
HLA:HLA03999 DPA1*02:01:07 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA13623
HLA:HLA13623 DPA1*02:01:08:01 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA17775
HLA:HLA17775 DPA1*02:01:08:02 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA00509
HLA:HLA00509 DPA1*02:02:02:01 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA17378
HLA:HLA17378 DPA1*02:02:02:02 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA17379
HLA:HLA17379 DPA1*02:02:02:03 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA17772
HLA:HLA17772 DPA1*02:02:02:04 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA21114
HLA:HLA21114 DPA1*02:02:02:05 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA01001
HLA:HLA01001 DPA1*02:02:03 79 bases
 VSTYAMFVQT HRPTGEFMFE FDEDEQFYVD LDKKETVWHL EEFGRAFSFE AQGGLANIAI
 LNNNLNTLIQ RSNHTQAAN*    
>P1;HLA:HLA07089
HLA:HLA07089 DPA1*02:02:04 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA08603
HLA:HLA08603 DPA1*02:02:05 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA11062
HLA:HLA11062 DPA1*02:02:06 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA00510
HLA:HLA00510 DPA1*02:03 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA03187
HLA:HLA03187 DPA1*02:04 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNDLNTL IQRSNHTQAA N*   
>P1;HLA:HLA08415
HLA:HLA08415 DPA1*02:05 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQHSNHTQAA N*   
>P1;HLA:HLA14100
HLA:HLA14100 DPA1*02:06 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET METVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA15619
HLA:HLA15619 DPA1*02:07:01:01 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TMFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA17043
HLA:HLA17043 DPA1*02:07:01:02 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TMFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA17315
HLA:HLA17315 DPA1*02:07:01:03 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TMFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA17380
HLA:HLA17380 DPA1*02:08 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLHS GHDPRAQGPL *   
>P1;HLA:HLA17568
HLA:HLA17568 DPA1*02:09 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQCSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA18286
HLA:HLA18286 DPA1*02:10 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEAVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA18654
HLA:HLA18654 DPA1*02:11 175 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNSNLNTL IQRSNHTQAA NDPPEVTVFP KEPVELGQPN TLICHIDRFF PPVLNVTWLC
 NGEPVTEGVA ESLFLPRTDY SFHKFHYLTF VPSAEDVYDC RVEHWGLDQP LLKHW*
>P1;HLA:HLA19269
HLA:HLA19269 DPA1*02:12 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TMFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPQAQGPL *   
>P1;HLA:HLA22124
HLA:HLA22124 DPA1*02:13N 176 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA NDPPEVTVFP KEPVELGQPN TLICHIDRFF PPVLNVTWLC
 NGEPVTEGVA ESLFLPRTDY SFHKFHYLTF VPSAEDVYDC RVEHWGLDQP LLKHWX*
>P1;HLA:HLA22638
HLA:HLA22638 DPA1*02:14 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFLPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA22218
HLA:HLA22218 DPA1*02:15 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EQFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNTLIQRSNH TQAANDPPEV
 TVFPKEPVEL GQPNTLICHI DRFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET METVLCALGL VLGLVGIIVG
 TVLIIKSLCS GHDPRAQGPL *   
>P1;HLA:HLA22688
HLA:HLA22688 DPA1*02:16 203 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA NDPPEVTVFP KEPVELGQPN TLICHIDRFF PPVLNVTWLC
 NGEPVTEGVA ESLFLPRTDY SFHKFHYLTF VPSAEDVYDC RVEHWGLDQP LLKHWEAQEP
 IQMPETMETV LCALGLVLGL VGI*   
>P1;HLA:HLA00511
HLA:HLA00511 DPA1*03:01:01:01 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAISNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA22519
HLA:HLA22519 DPA1*03:01:01:02 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAISNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA22720
HLA:HLA22720 DPA1*03:01:01:03 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAISNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA22774
HLA:HLA22774 DPA1*03:01:01:04 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAISNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA22662
HLA:HLA22662 DPA1*03:01:01:05 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAISNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA17562
HLA:HLA17562 DPA1*03:01:02 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAISNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA00512
HLA:HLA00512 DPA1*03:02 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA01938
HLA:HLA01938 DPA1*03:03 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDDDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AISNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA22211
HLA:HLA22211 DPA1*03:04 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AMFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAISNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA00513
HLA:HLA00513 DPA1*04:01:01:01 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRTT GEFMFEFDDD
 EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNIAIQRSNH TQAANDPPEV
 TVFPKEAVEL GQPNTLICHI DKFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET AETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA22615
HLA:HLA22615 DPA1*04:01:01:02 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRTT GEFMFEFDDD
 EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNIAIQRSNH TQAANDPPEV
 TVFPKEAVEL GQPNTLICHI DKFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET AETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA22790
HLA:HLA22790 DPA1*04:01:01:03 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRTT GEFMFEFDDD
 EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNIAIQRSNH TQAANDPPEV
 TVFPKEAVEL GQPNTLICHI DKFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET AETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
>P1;HLA:HLA17563
HLA:HLA17563 DPA1*04:02 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRTT GEFMFEFDDD
 EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN LNIAIQRSNH TQAANDPPEV
 TVFPKEAVEL GQPNTLICHI DKFFPPVLNV TWLCNGEPVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGPL *   
