>P1;HLA:HLA00499
HLA:HLA00499 DPA1*01:03:01:01 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA06604
HLA:HLA06604 DPA1*01:03:01:02 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA06605
HLA:HLA06605 DPA1*01:03:01:03 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA06607
HLA:HLA06607 DPA1*01:03:01:04 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA06606
HLA:HLA06606 DPA1*01:03:01:05 260 bases
 MRPEDRMFHI RAVILRALSL AFLLSLRGAG AIKADHVSTY AAFVQTHRPT GEFMFEFDED
 EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN LNTLIQRSNH TQATNDPPEV
 TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT EGVAESLFLP RTDYSFHKFH
 YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET TETVLCALGL VLGLVGIIVG
 TVLIIKSLRS GHDPRAQGTL *   
>P1;HLA:HLA00500
HLA:HLA00500 DPA1*01:03:02 74 bases
 AFVQTHRPTG EFMFEFDEDE MFYVDLDKKE TVWHLEEFGQ AFSFEAQGGL ANIAILNNNL
 NTLIQRSNHT QATN*    
>P1;HLA:HLA01937
HLA:HLA01937 DPA1*01:03:03 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA03224
HLA:HLA03224 DPA1*01:03:04 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA00501
HLA:HLA00501 DPA1*01:04 220 bases
 AAFVQTHRPT GEFMFEFDDD EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN
 LNTLIQRSNH TQATNDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT
 EGVAESLFLP RTDYSFHKFH YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET
 TETVLCALGL VLGLVGIIVG TVLIIKSLRS GHDPRAQGTL * 
>P1;HLA:HLA00502
HLA:HLA00502 DPA1*01:05 75 bases
 AAFVQTHRPT GEFMFEFDED EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAILNNN
 LNTLIQRSNH TQAAN*    
>P1;HLA:HLA00503
HLA:HLA00503 DPA1*01:06:01 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA03401
HLA:HLA03401 DPA1*01:06:02 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA01000
HLA:HLA01000 DPA1*01:07 80 bases
 HVSTYAAFVQ THRPTGEFMF EFDEDEMFYV DLDKKETVWH LEEFGQTFSF EAQGGLANIA
 ILNNNLNTLI QRSNHTQATN *   
>P1;HLA:HLA01466
HLA:HLA01466 DPA1*01:08 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDDDEMFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA02058
HLA:HLA02058 DPA1*01:09 81 bases
 DHVSTYAAFV QTHRPTGEFT FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA03223
HLA:HLA03223 DPA1*01:10 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVC HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA07533
HLA:HLA07533 DPA1*01:11 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA09332
HLA:HLA09332 DPA1*01:12 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AISNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA00504
HLA:HLA00504 DPA1*02:01:01 229 bases
 IKADHVSTYA AFVQTHRPTG EFMFEFDEDE QFYVDLDKKE TVWHLEEFGR AFSFEAQGGL
 ANIAILNNNL NTLIQRSNHT QAANDPPEVT VFPKEPVELG QPNTLICHID RFFPPVLNVT
 WLCNGEPVTE GVAESLFLPR TDYSFHKFHY LTFVPSAEDV YDCRVEHWGL DQPLLKHWEA
 QEPIQMPETT ETVLCALGLV LGLVGIIVGT VLIIKSLRSG HDPRAQGPL* 
>P1;HLA:HLA00505
HLA:HLA00505 DPA1*02:01:02 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA00506
HLA:HLA00506 DPA1*02:01:03 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA00507
HLA:HLA00507 DPA1*02:01:04 74 bases
 AFVQTHRPTG EFMFEFDEDE QFYVDLDKKE TVWHLEEFGR AFSFEAQGGL ANIAILNNNL
 NTLIQRSNHT QAAN*    
>P1;HLA:HLA01097
HLA:HLA01097 DPA1*02:01:05 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA01168
HLA:HLA01168 DPA1*02:01:06 86 bases
 IKADHVSTYA AFVQTHRPTG EFMFEFDEDE QFYVDLDKKE TVWHLEEFGR AFSFEAQGGL
 ANIAILNNNL NTLIQRSNHT QAANDP*   
>P1;HLA:HLA03999
HLA:HLA03999 DPA1*02:01:07 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA00508
HLA:HLA00508 DPA1*02:02:01 222 bases
 TYAMFVQTHR PTGEFMFEFD EDEQFYVDLD KKETVWHLEE FGRAFSFEAQ GGLANIAILN
 NNLNTLIQRS NHTQAANDPP EVTVFPKEPV ELGQPNTLIC HIDRFFPPVL NVTWLCNGEP
 VTEGVAESLF LPRTDYSFHK FHYLTFVPSA EDVYDCRVEH WGLDQPLLKH WEAQEPIQMP
 ETTETVLCAL GLVLGLVGII VGTVLIIKSL RSGHDPRAQG PL* 
>P1;HLA:HLA00509
HLA:HLA00509 DPA1*02:02:02 226 bases
 DHVSTYAMFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA NDPPEVTVFP KEPVELGQPN TLICHIDRFF PPVLNVTWLC
 NGEPVTEGVA ESLFLPRTDY SFHKFHYLTF VPSAEDVYDC RVEHWGLDQP LLKHWEAQEP
 IQMPETTETV LCALGLVLGL VGIIVGTVLI IKSLRSGHDP RAQGPL* 
>P1;HLA:HLA01001
HLA:HLA01001 DPA1*02:02:03 79 bases
 VSTYAMFVQT HRPTGEFMFE FDEDEQFYVD LDKKETVWHL EEFGRAFSFE AQGGLANIAI
 LNNNLNTLIQ RSNHTQAAN*    
>P1;HLA:HLA07089
HLA:HLA07089 DPA1*02:02:04 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA08603
HLA:HLA08603 DPA1*02:02:05 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA00510
HLA:HLA00510 DPA1*02:03 81 bases
 DHVSTYAAFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAA N*   
>P1;HLA:HLA03187
HLA:HLA03187 DPA1*02:04 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNDLNTL IQRSNHTQAA N*   
>P1;HLA:HLA08415
HLA:HLA08415 DPA1*02:05 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDEDEQFY VDLDKKETVW HLEEFGRAFS FEAQGGLANI
 AILNNNLNTL IQHSNHTQAA N*   
>P1;HLA:HLA00511
HLA:HLA00511 DPA1*03:01 220 bases
 AMFVQTHRPT GEFMFEFDED EMFYVDLDKK ETVWHLEEFG QAFSFEAQGG LANIAISNNN
 LNTLIQRSNH TQATNDPPEV TVFPKEPVEL GQPNTLICHI DKFFPPVLNV TWLCNGELVT
 EGVAESLFLP RTDYSFHKFH YLTFVPSAED FYDCRVEHWG LDQPLLKHWE AQEPIQMPET
 TETVLCALGL VLGLVGIIVG TVLIIKSLRS GHDPRAQGTL * 
>P1;HLA:HLA00512
HLA:HLA00512 DPA1*03:02 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDEDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AILNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA01938
HLA:HLA01938 DPA1*03:03 81 bases
 DHVSTYAMFV QTHRPTGEFM FEFDDDEMFY VDLDKKETVW HLEEFGQAFS FEAQGGLANI
 AISNNNLNTL IQRSNHTQAT N*   
>P1;HLA:HLA00513
HLA:HLA00513 DPA1*04:01 220 bases
 AAFVQTHRTT GEFMFEFDDD EMFYVDLDKK ETVWHLEEFG RAFSFEAQGG LANIAILNNN
 LNIAIQRSNH TQAANDPPEV TVFPKEAVEL GQPNTLICHI DKFFPPVLNV TWLCNGEPVT
 EGVAESLFLP RTDYSFHKFH YLTFVPSAED VYDCRVEHWG LDQPLLKHWE AQEPIQMPET
 AETVLCALGL VLGLVGIIVG TVLIIKSLRS GHDPRAQGPL * 
