>DL;HLA:HLA00499
HLA:HLA00499 DPA1*01:03:01:01 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA CCAACGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAAGTTCT TCCCACCAGT GCTCAACGTC ACGTGGCTGT GCAACGGGGA GCTGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC TTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTCGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGACCCTG
 TGA*     
>DL;HLA:HLA06604
HLA:HLA06604 DPA1*01:03:01:02 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA CCAACGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAAGTTCT TCCCACCAGT GCTCAACGTC ACGTGGCTGT GCAACGGGGA GCTGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC TTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTCGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGACCCTG
 TGA*     
>DL;HLA:HLA06605
HLA:HLA06605 DPA1*01:03:01:03 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA CCAACGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAAGTTCT TCCCACCAGT GCTCAACGTC ACGTGGCTGT GCAACGGGGA GCTGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC TTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTCGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGACCCTG
 TGA*     
>DL;HLA:HLA06607
HLA:HLA06607 DPA1*01:03:01:04 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA CCAACGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAAGTTCT TCCCACCAGT GCTCAACGTC ACGTGGCTGT GCAACGGGGA GCTGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC TTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTCGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGACCCTG
 TGA*     
>DL;HLA:HLA06606
HLA:HLA06606 DPA1*01:03:01:05 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA CCAACGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAAGTTCT TCCCACCAGT GCTCAACGTC ACGTGGCTGT GCAACGGGGA GCTGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC TTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTCGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGACCCTG
 TGA*     
>DL;HLA:HLA00500
HLA:HLA00500 DPA1*01:03:02 222 bases
 GCGTTTGTAC AGACGCATAG ACCAACAGGA GAGTTTATGT TTGAATTTGA TGAAGATGAG
 ATGTTCTATG TGGATCTGGA CAAGAAGGAG ACCGTCTGGC ATCTGGAGGA GTTTGGCCAA
 GCCTTTTCCT TTGAGGCTCA GGGCGGGCTG GCTAACATTG CTATATTGAA CAACAACTTG
 AATACCTTGA TCCAGCGTTC CAACCACACT CAGGCCACCA AC* 
>DL;HLA:HLA01937
HLA:HLA01937 DPA1*01:03:03 246 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACCCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA
 CCAACG*     
>DL;HLA:HLA03224
HLA:HLA03224 DPA1*01:03:04 246 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CAAGCCTTTT CCTTTGAGGC TCAGGGTGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA
 CCAACG*     
>DL;HLA:HLA14098
HLA:HLA14098 DPA1*01:03:05 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA CCAACGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAAGTTCT TCCCACCAGT GCTCAACGTC ACGTGGCTGT GCAATGGGGA GCTGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC TTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTCGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGACCCTG
 TGA*     
>DL;HLA:HLA00501
HLA:HLA00501 DPA1*01:04 663 bases
 GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGACGAT
 GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA CCAACGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAAGTTCT TCCCACCAGT GCTCAACGTC ACGTGGCTGT GCAACGGGGA GCTGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC TTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTCGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGACCCTG
 TGA*     
>DL;HLA:HLA00502
HLA:HLA00502 DPA1*01:05 225 bases
 GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAAT* 
>DL;HLA:HLA00503
HLA:HLA00503 DPA1*01:06:01 246 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGCAGTTCT ATGTGGATCT GGATAAAAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA
 CCAACG*     
>DL;HLA:HLA03401
HLA:HLA03401 DPA1*01:06:02 246 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGCAGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA
 CCAACG*     
>DL;HLA:HLA01000
HLA:HLA01000 DPA1*01:07 241 bases
 CATGTGTCAA CTTATGCCGC GTTTGTACAG ACGCATAGAC CAACAGGGGA GTTTATGTTT
 GAATTTGATG AAGATGAGAT GTTCTATGTG GATCTGGACA AGAAGGAGAC CGTCTGGCAT
 CTGGAGGAGT TTGGCCAAAC CTTTTCCTTT GAGGCTCAGG GCGGGCTGGC TAACATTGCT
 ATATTGAACA ACAACTTGAA TACCTTGATC CAGCGTTCCA ACCACACTCA GGCCACCAAC
 G*     
>DL;HLA:HLA01466
HLA:HLA01466 DPA1*01:08 246 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGACGAT GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA
 CCAACG*     
>DL;HLA:HLA02058
HLA:HLA02058 DPA1*01:09 246 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA
 CGTTTGAATT TGATGAAGAT GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA
 CCAACG*     
>DL;HLA:HLA03223
HLA:HLA03223 DPA1*01:10 246 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GTCATCTGGA GGAGTTTGGC CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA
 CCAACG*     
>DL;HLA:HLA07533
HLA:HLA07533 DPA1*01:11 246 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA
 CCAACG*     
>DL;HLA:HLA09332
HLA:HLA09332 DPA1*01:12 246 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATC GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA
 CCAACG*     
>DL;HLA:HLA12908
HLA:HLA12908 DPA1*01:13 246 bases
 CGGACCATGT GTCAACTTAT GCCGTGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA
 CCAACG*     
>DL;HLA:HLA16642
HLA:HLA16642 DPA1*01:14 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA CCAACGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAAGTTCT TCCCACCAGT GCTCAACGTC ACGTGGCTGT GCAACGGGGA GCTGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC TTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTCGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCAGGCCCA GGGGACCCTG
 TGA*     
>DL;HLA:HLA00504
HLA:HLA00504 DPA1*02:01:01:01 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCGCGTTTG TACAGACCCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGCAGTTCT ATGTGGATCT GGATAAAAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAGGTTCT TCCCACCAGT GCTCAACGTC ACATGGCTGT GCAATGGGGA GCCAGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC GTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTGGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGCCCCTG
 TGA*     
>DL;HLA:HLA14197
HLA:HLA14197 DPA1*02:01:01:02 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCGCGTTTG TACAGACCCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGCAGTTCT ATGTGGATCT GGATAAAAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAGGTTCT TCCCACCAGT GCTCAACGTC ACATGGCTGT GCAATGGGGA GCCAGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC GTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTGGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGCCCCTG
 TGA*     
>DL;HLA:HLA00505
HLA:HLA00505 DPA1*02:01:02 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGCAGTTCT ATGTGGATCT GGATAAAAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAGGTTCT TCCCACCAGT GCTCAACGTC ACATGGCTGT GCAATGGGGA GCCGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC GTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTGGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGCCCCTG
 TGA*     
>DL;HLA:HLA00506
HLA:HLA00506 DPA1*02:01:03 246 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGCAGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG
 CCAATG*     
>DL;HLA:HLA00507
HLA:HLA00507 DPA1*02:01:04 222 bases
 GCGTTTGTAC AAACCCATAG ACCAACAGGG GAGTTTATGT TTGAATTTGA TGAAGATGAG
 CAGTTCTATG TGGATCTGGA TAAAAAGGAG ACCGTCTGGC ATCTGGAGGA GTTTGGCCGA
 GCCTTTTCCT TTGAGGCTCA GGGCGGGCTG GCTAACATTG CTATATTGAA CAACAACTTG
 AATACCTTGA TCCAGCGTTC CAACCACACT CAGGCCGCCA AT* 
>DL;HLA:HLA01097
HLA:HLA01097 DPA1*02:01:05 246 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACGCA TAGACCAACA GGAGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGCAGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG
 CCAATG*     
>DL;HLA:HLA01168
HLA:HLA01168 DPA1*02:01:06 257 bases
 ATCAAGGCGG ACCATGTGTC AACTTATGCC GCGTTTGTAC AGACCCATAG ACCAACAGGG
 GAGTTTATGT TTGAATTTGA TGAAGATGAG CAGTTCTATG TGGATCTGGA TAAGAAGGAG
 ACCGTCTGGC ATCTGGAGGA GTTTGGCCGA GCCTTTTCCT TTGAGGCTCA GGGCGGGCTG
 GCTAACATTG CTATATTGAA CAACAACTTG AATACCTTGA TCCAGCGTTC CAACCACACT
 CAGGCCGCCA ATGATCC*    
>DL;HLA:HLA03999
HLA:HLA03999 DPA1*02:01:07 246 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACCCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGCAGTTCT ATGTGGATCT GGATAAAAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CGAGCCTTTT CCTTTGAGGC TCAGGGTGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG
 CCAATG*     
>DL;HLA:HLA13623
HLA:HLA13623 DPA1*02:01:08 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCGCGTTTG TACAGACCCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGCAGTTCT ATGTGGATCT GGATAAAAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAGGTTCT TCCCACCAGT GCTCAACGTC ACATGGCTGT GCAATGGGGA GCCGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC GTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTGGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGCCCCTG
 TGA*     
>DL;HLA:HLA00509
HLA:HLA00509 DPA1*02:02:02 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCATGTTTG TACAGACCCA TAGACCAACA GGAGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGCAGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC CCCTGAGGTG
 ACGGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAGGTTCT TCCCACCAGT GCTCAATGTC ACATGGCTGT GCAATGGGGA GCCGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC GTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTGGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGCCCCTG
 TGA*     
>DL;HLA:HLA01001
HLA:HLA01001 DPA1*02:02:03 240 bases
 ATGTGTCAAC TTATGCCATG TTTGTACAGA CCCATAGACC AACAGGGGAG TTTATGTTTG
 AATTTGATGA AGATGAGCAG TTCTATGTGG ATCTGGACAA GAAGGAGACC GTCTGGCATC
 TGGAGGAGTT TGGCCGAGCC TTTTCCTTTG AGGCTCAGGG CGGGCTGGCT AACATTGCTA
 TATTGAACAA CAACTTGAAT ACCTTGATCC AGCGTTCCAA CCACACTCAG GCCGCCAATG
 *     
>DL;HLA:HLA07089
HLA:HLA07089 DPA1*02:02:04 246 bases
 CGGACCATGT GTCAACTTAT GCCATGTTTG TACAGACGCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGCAGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG
 CCAATG*     
>DL;HLA:HLA08603
HLA:HLA08603 DPA1*02:02:05 246 bases
 CGGACCATGT GTCAACTTAT GCCATGTTTG TACAGACCCA TAGACCAACA GGAGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGCAGTTCT ATGTGGATCT GGATAAAAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG
 CCAATG*     
>DL;HLA:HLA11062
HLA:HLA11062 DPA1*02:02:06 246 bases
 CGGACCATGT GTCAACTTAT GCCATGTTTG TACAGACCCA TAGACCAACA GGAGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGCAGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCGG
 CCAATG*     
>DL;HLA:HLA00510
HLA:HLA00510 DPA1*02:03 245 bases
 CGGACCATGT GTCAACTTAT GCCGCGTTTG TACAGACCCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG
 CCAAT*     
>DL;HLA:HLA03187
HLA:HLA03187 DPA1*02:04 246 bases
 CGGACCATGT GTCAACTTAT GCCATGTTTG TACAGACCCA TAGACCAACA GGAGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGCAGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACGAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG
 CCAATG*     
>DL;HLA:HLA08415
HLA:HLA08415 DPA1*02:05 246 bases
 CGGACCATGT GTCAACTTAT GCCATGTTTG TACAGACCCA TAGACCAACA GGAGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGCAGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCA TTCCAACCAC ACTCAGGCCG
 CCAATG*     
>DL;HLA:HLA14100
HLA:HLA14100 DPA1*02:06 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCATGTTTG TACAGACCCA TAGACCAACA GGAGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGCAGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC CCCTGAGGTG
 ACGGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAGGTTCT TCCCACCAGT GCTCAATGTC ACATGGCTGT GCAATGGGGA GCCGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC GTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ATGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTGGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGCCCCTG
 TGA*     
>DL;HLA:HLA15619
HLA:HLA15619 DPA1*02:07:01:01 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCATGTTTG TACAGACCCA TAGACCAACA GGAGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGCAGTTCT ATGTGGATCT GGATAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC CCCTGAGGTG
 ACCATGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAGGTTCT TCCCACCAGT GCTCAACGTC ACATGGCTGT GCAATGGGGA GCCGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC GTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTGGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGCCCCTG
 TGA*     
>DL;HLA:HLA17043
HLA:HLA17043 DPA1*02:07:01:02 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCATGTTTG TACAGACCCA TAGACCAACA GGAGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGCAGTTCT ATGTGGATCT GGATAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC CCCTGAGGTG
 ACCATGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAGGTTCT TCCCACCAGT GCTCAACGTC ACATGGCTGT GCAATGGGGA GCCGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC GTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTGGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGCCCCTG
 TGA*     
>DL;HLA:HLA00511
HLA:HLA00511 DPA1*03:01 783 bases
 ATGCGCCCTG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCATGTTTG TACAGACCCA TAGACCAACA GGGGAGTTTA TGTTTGAATT TGATGAAGAT
 GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATC GAACAACAAC
 TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA CCAACGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGCC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAAGTTCT TCCCACCAGT GCTCAACGTC ACGTGGCTGT GCAACGGGGA GCTGGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC TTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 ACGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTGGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGACCCTG
 TGA*     
>DL;HLA:HLA00512
HLA:HLA00512 DPA1*03:02 245 bases
 CGGACCATGT GTCAACTTAT GCCATGTTTG TACAGACCCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGAAGAT GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATT GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA
 CCAAC*     
>DL;HLA:HLA01938
HLA:HLA01938 DPA1*03:03 246 bases
 CGGACCATGT GTCAACTTAT GCCATGTTTG TACAGACCCA TAGACCAACA GGGGAGTTTA
 TGTTTGAATT TGATGACGAT GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT
 GGCATCTGGA GGAGTTTGGC CAAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA
 TTGCTATATC GAACAACAAC TTGAATACCT TGATCCAGCG TTCCAACCAC ACTCAGGCCA
 CCAACG*     
>DL;HLA:HLA00513
HLA:HLA00513 DPA1*04:01 783 bases
 ATGCGCCCAG AAGACAGAAT GTTCCATATC AGAGCTGTGA TCTTGAGAGC CCTCTCCTTG
 GCTTTCCTGC TGAGTCTCCG AGGAGCTGGG GCCATCAAGG CGGACCATGT GTCAACTTAT
 GCCGCGTTTG TACAGACGCA TAGAACAACA GGAGAGTTTA TGTTTGAGTT TGATGATGAT
 GAGATGTTCT ATGTGGATCT GGACAAGAAG GAGACCGTCT GGCATCTGGA GGAGTTTGGC
 CGAGCCTTTT CCTTTGAGGC TCAGGGCGGG CTGGCTAACA TTGCTATATT GAACAACAAC
 TTGAATATCG CTATCCAGCG TTCCAACCAC ACTCAGGCCG CCAATGATCC CCCTGAGGTG
 ACCGTGTTTC CCAAGGAGGC TGTGGAGCTG GGCCAGCCCA ACACCCTCAT CTGCCACATT
 GACAAGTTCT TCCCACCAGT GCTCAACGTC ACATGGCTGT GCAATGGGGA GCCAGTCACT
 GAGGGTGTCG CTGAGAGCCT CTTCCTGCCC AGAACAGATT ACAGCTTCCA CAAGTTCCAT
 TACCTGACCT TTGTGCCCTC AGCAGAGGAC GTCTATGACT GCAGGGTGGA GCACTGGGGC
 TTGGACCAGC CGCTCCTCAA GCACTGGGAG GCCCAAGAGC CAATCCAGAT GCCTGAGACA
 GCGGAGACTG TGCTCTGTGC CCTGGGCCTG GTGCTGGGCC TAGTGGGCAT CATCGTGGGC
 ACCGTCCTCA TCATAAAGTC TCTGCGTTCT GGCCATGACC CCCGGGCCCA GGGGCCCCTG
 TGA*     
