>DL;HLA:HLA16384
HLA:HLA16384 DPA2*01:01:01:01 733 bases
 ATGAGTGGTG TCATAAAGCT CCCAAGAGTT TACGTCTTTT GTGATTGGCT ACCAGCAGAC
 CATGTGTCAA CATATGCGGA GTTTGTGCAG ACGCACAGAC CCTCTGGGGA GTATATGTTT
 GAATTTGATG AGGAGGAGCA GTTCTACGTG AACCTGGATG AGAAGGAGAT GGTCTGGCCT
 CTACCAGAGT TTATTCACAC CTTTGACTTT GGTGCTCAGA GGGGTATTGC TGGCATCGTC
 ATGGCAAGGA AGCACTTGAA CACCCGGATC AATGGTCCAA ACAGACTTGG GCCACAAATG
 CCCCCACCGA GGTAAGCGTC TTTCCCAAGG AGCCTGTGGA TCTGGGCCAG CCCAACACCC
 TCGTCTGCCA TGTTGACAAG TTCTTCCCAC CAGTGCTGAA CATCACGTGG CTGCGCAATG
 GGGAGCCAGT CATTGAGGGT ATTGCAGAGA CCATCTTCCT GCCCAGCAAG AAACTCAGAT
 TACACAGGTT CCACTATCTG ACCCTCGTTC CCATGGCCGA GGACACCTGT GACCTCCAGG
 GGGAGCACTG GGGCCTGCAC CAGCCTCTCC TCAGGCACTG GGAGGTCCAT GAACTAATCC
 AGGTGCCTGA GACCATGGAG ATGCTGGTCT GTGCCCTCGG CCTGCTGGTG GGCCTGGCGG
 GGGTCCTTAA TGGCACCATT GTCTCAAAGA CCAAGCGATC TGACAGCATC CCCGGGTCCA
 GGGGCTCCTA TGA*    
>DL;HLA:HLA16387
HLA:HLA16387 DPA2*01:01:01:02 733 bases
 ATGAGTGGTG TCATAAAGCT CCCAAGAGTT TACGTCTTTT GTGATTGGCT ACCAGCAGAC
 CATGTGTCAA CATATGCGGA GTTTGTGCAG ACGCACAGAC CCTCTGGGGA GTATATGTTT
 GAATTTGATG AGGAGGAGCA GTTCTACGTG AACCTGGATG AGAAGGAGAT GGTCTGGCCT
 CTACCAGAGT TTATTCACAC CTTTGACTTT GGTGCTCAGA GGGGTATTGC TGGCATCGTC
 ATGGCAAGGA AGCACTTGAA CACCCGGATC AATGGTCCAA ACAGACTTGG GCCACAAATG
 CCCCCACCGA GGTAAGCGTC TTTCCCAAGG AGCCTGTGGA TCTGGGCCAG CCCAACACCC
 TCGTCTGCCA TGTTGACAAG TTCTTCCCAC CAGTGCTGAA CATCACGTGG CTGCGCAATG
 GGGAGCCAGT CATTGAGGGT ATTGCAGAGA CCATCTTCCT GCCCAGCAAG AAACTCAGAT
 TACACAGGTT CCACTATCTG ACCCTCGTTC CCATGGCCGA GGACACCTGT GACCTCCAGG
 GGGAGCACTG GGGCCTGCAC CAGCCTCTCC TCAGGCACTG GGAGGTCCAT GAAATAATCC
 AGGTGCCTGA GACCATGGAG ATGCTGGTCT GTGCCCTCGG CCTGCTGGTG GGCCTGGCGG
 GGGTCCTTAA TGGCACCATT GTCTCAAAGA CCAAGCGATC TGACAGCATC CCCGGGTCCA
 GGGGCTCCTA TGA*    
>DL;HLA:HLA16383
HLA:HLA16383 DPA2*01:01:01:03 733 bases
 ATGAGTGGTG TCATAAAGCT CCCAAGAGTT TACGTCTTTT GTGATTGGCT ACCAGCAGAC
 CATGTGTCAA CATATGCGGA GTTTGTGCAG ACGCACAGAC CCTCTGGGGA GTATATGTTT
 GAATTTGATG AGGAGGAGCA GTTCTACGTG AACCTGGATG AGAAGGAGAT GGTCTGGCCT
 CTACCAGAGT TTATTCACAC CTTTGACTTT GGTGCTCAGA GGGGTATTGC TGGCATCGTC
 ATGGCAAGGA AGCACTTGAA CACCCGGATC AATGGTCCAA ACAGACTTGG GCCACAAATG
 CCCCCACCGA GGTAAGCGTC TTTCCCAAGG AGCCTGTGGA TCTGGGCCAG CCCAACACCC
 TCGTCTGCCA TGTTGACAAG TTCTTCCCAC CAGTGCTGAA CATCACGTGG CTGCGCAATG
 GGGAGCCAGT CATTGAGGGT ATTGCAGAGA CCATCTTCCT GCCCAGCAAG AAACTCAGAT
 TACACAGGTT CCACTATCTG ACCCTCGTTC CCATGGCCGA GGACACCTGT GACCTCCAGG
 GGGAGCACTG GGGCCTGCAC CAGCCTCTCC TCAGGCACTG GGAGGTCCAT GAAATAATCC
 AGGTGCCTGA GACCATGGAG ATGCTGGTCT GTGCCCTCGG CCTGCTGGTG GGCCTGGCGG
 GGGTCCTTAA TGGCACCATT GTCTCAAAGA CCAAGCGATC TGACAGCATC CCCGGGTCCA
 GGGGCTCCTA TGA*    
>DL;HLA:HLA16385
HLA:HLA16385 DPA2*01:01:02 733 bases
 ATGAGTGGTG TCATAAAGCT CCCAAGAGTT TACGTCTTTT GTGATTGGCT ACCAGCAGAC
 CATGTGTCAA CATATGCAGA GTTTGTGCAG ACGCACAGAC CCTCTGGGGA GTATATGTTT
 GAATTTGATG AGGAGGAGCA GTTCTACGTG AACCTGGATG AGAAGGAGAT GGTCTGGCCT
 CTACCAGAGT TTATTCACAC CTTTGACTTT GGTGCTCAGA GGGGTATTGC TGGCATCGTC
 ATGGCAAGGA AGCACTTGAA CACCCGGATC AATGGTCCAA ACAGACTTGG GCCACAAATG
 CCCCCACCGA GGTAAGCGTC TTTCCCAAGG AGCCTGTGGA TCTGGGCCAG CCCAACACCC
 TCGTCTGCCA TGTTGACAAG TTCTTCCCAC CAGTGCTGAA CATCACGTGG CTGTGCAATG
 GGGAGCCAGT CATTGAGGGT ATTGCAGAGA CCATCTTCCT GCCCAGCAAG AAACTCAGAT
 TCCACAGGTT CCACTATCTG ACCCTCGTTC CCATGGCCGA GGACACCTGT GACCTCCAGG
 GGGAGCACTG GGGCCTGCAC CAGCCTCTCC TCAGGCACTG GGAGGTCCAT GAACTAATCC
 AGGTGCCTGA GACCATGGAG ATGCTGGTCT GTGCCCTGGG CCTGCTGGTG GGCCTGGCGG
 GGGTCCTTAA TGGCACCATT GTCTCAAAGA CCAAGCGATC TGACAGCATC CCCGGGTCCA
 GGGGCTCCTA TGA*    
>DL;HLA:HLA16386
HLA:HLA16386 DPA2*02:01 733 bases
 ATGAGTGGTG TCATAAAGCT CCCAAGAGTT TACGTCTTTT GTGATTGGCT ACCAGCAGAC
 CATGTGTCAA CATATGCGGA GTTTGTGCAG ACGCACAGAA CCTCTGGGGA GTATATGTTT
 GAATTTGATG AGGAGGAGCA GTTCTACGTG AACCTGGATG AGAAGGAGAT GGTCTGGCCT
 CTACCAGAGT TTATTCACAC CTTTGACTTT GGTGCTCAGA GGGGTATTGC TGGCATCGTC
 ATGGCAAGGA AGCACTTGAA CACCCGGATC AATGGTCCAA ACAGACTTGG GCCACAAATG
 CCCCCACCGA GGTAAGCGTC TTTCCCAAGG AGCCTGTGGA TCTGGGCCAG CCCAACACCC
 TCGTCTGCCA TGTTGACAAG TTCTTCCCAC CAGTGCTGAA CATCACGTGG CTGCGCAATG
 GGGAGCCAGT CATTGAGGGT ATTGCAGAGA CCATCTTCCT GCCCAGCAAG AAACTCAGAT
 TACACAGGTT CCACTATCTG ACCCTCGTTC CCATGGCCGA GGACACCTGT GACCTCCAGG
 GGGAGCACTG GGGCCTGCAC CAGCCTCTCC TCAGGCACTG GGAGGTCCAT GAACTAATCC
 AGGTGCCTGA GACCATGGAG ATGCTGGTCT GTGCCCTCGG CCTGCTGGTG GGCCTGGCGG
 GGGTCCTTAA TGGCACCATT GTCTCAAAGA CCAAGCGATC TGACAGCATC CCCGGGTCCA
 GGGGCTCCTA TGA*    
