>P1;HLA:HLA00514
HLA:HLA00514 DPB1*01:01:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVYQG RQECYAFNGT QRFLERYIYN
 REEYARFDSD VGEFRAVTEL GRPAAEYWNS QKDILEEKRA VPDRVCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SAQSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00515
HLA:HLA00515 DPB1*01:01:02 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVYQG RQECYAFNGT QRFLERYIYN
 REEYARFDSD VGEFRAVTEL GRPAAEYWNS QKDILEEKRA VPDRVCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SAQSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA02006
HLA:HLA02006 DPB1*01:01:03 88 bases
 ENYVYQGRQE CYAFNGTQRF LERYIYNREE YARFDSDVGE FRAVTELGRP AAEYWNSQKD
 ILEEKRAVPD RVCRHNYELD EAVTLQRR*   
>P1;HLA:HLA00517
HLA:HLA00517 DPB1*02:01:02 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYLFQG RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEEYWNS QKDILEEERA VPDRMCRHNY ELGGPMTLQR
 RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYTC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00518
HLA:HLA00518 DPB1*02:01:03 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA01473
HLA:HLA01473 DPB1*02:01:04 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA01592
HLA:HLA01592 DPB1*02:01:05 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA01615
HLA:HLA01615 DPB1*02:01:06 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA03491
HLA:HLA03491 DPB1*02:01:07 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA08801
HLA:HLA08801 DPB1*02:01:08 181 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA00519
HLA:HLA00519 DPB1*02:02 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYLFQG RQECYAFNGT QRFLERYIYN
 REELVRFDSD VGEFRAVTEL GRPEAEYWNS QKDILEEERA VPDRMCRHNY ELGGPMTLQR
 RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYTC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00520
HLA:HLA00520 DPB1*03:01:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVYQL RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEDYWNS QKDLLEEKRA VPDRVCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA01306
HLA:HLA01306 DPB1*03:01:02 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00521
HLA:HLA00521 DPB1*04:01:01:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYLFQG RQECYAFNGT QRFLERYIYN
 REEFARFDSD VGEFRAVTEL GRPAAEYWNS QKDILEEKRA VPDRMCRHNY ELGGPMTLQR
 RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYTC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA06633
HLA:HLA06633 DPB1*04:01:01:02 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYLFQG RQECYAFNGT QRFLERYIYN
 REEFARFDSD VGEFRAVTEL GRPAAEYWNS QKDILEEKRA VPDRMCRHNY ELGGPMTLQR
 RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYTC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA01766
HLA:HLA01766 DPB1*04:01:02 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA07382
HLA:HLA07382 DPB1*04:01:03 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA00522
HLA:HLA00522 DPB1*04:02:01:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYLFQG RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEEYWNS QKDILEEKRA VPDRMCRHNY ELGGPMTLQR
 RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYTC QVEHTSMDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA06634
HLA:HLA06634 DPB1*04:02:01:02 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYLFQG RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEEYWNS QKDILEEKRA VPDRMCRHNY ELGGPMTLQR
 RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYTC QVEHTSMDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00523
HLA:HLA00523 DPB1*05:01:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYLFQG RQECYAFNGT QRFLERYIYN
 REELVRFDSD VGEFRAVTEL GRPEAEYWNS QKDILEEKRA VPDRMCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFMLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA03630
HLA:HLA03630 DPB1*05:01:02 181 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPE AEYWNSQKDI
 LEEKRAVPDR MCRHNYELDE AVTLQRRVQP KVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYICQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA00524
HLA:HLA00524 DPB1*06:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVYQL RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEDYWNS QKDLLEEERA VPDRMCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00525
HLA:HLA00525 DPB1*08:01 83 bases
 LFQGRQECYA FNGTQRFLER YIYNREEFVR FDSDVGEFRA VTELGRPDEE YWNSQKDILE
 EERAVPDRVC RHNYELDEAV TLQ*   
>P1;HLA:HLA00526
HLA:HLA00526 DPB1*09:01:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVHQL RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEDYWNS QKDILEEERA VPDRVCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA09088
HLA:HLA09088 DPB1*09:01:02 87 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDI
 LEEERAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA01837
HLA:HLA01837 DPB1*100:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPE AEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA01895
HLA:HLA01895 DPB1*101:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPE AEYWHSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA01947
HLA:HLA01947 DPB1*102:01 84 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDL
 LEEKRAVPDR MCRHNYELDE AVTL*   
>P1;HLA:HLA02042
HLA:HLA02042 DPB1*103:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEERAVPDR MCRHNYELDE AVTLQRR*   
>P1;HLA:HLA02046
HLA:HLA02046 DPB1*104:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVYQL RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEDYWNS QKDLLEEKRA VPDRVCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFMLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA02047
HLA:HLA02047 DPB1*105:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYLFQG RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEEYWNS QKDILEEKRA VPDRMCRHNY ELGGPMTLQR
 RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYTC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA02048
HLA:HLA02048 DPB1*106:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYLFQG RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPEAEYWNS QKDILEEERA VPDRICRHNY ELDEAVTLQR
 RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYTC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA02050
HLA:HLA02050 DPB1*107:01 258 bases
 MMVLQVSAAP RTVALMALLM VLLTSVVQGR ATPENYVYQL RQECYAFNGT QRFLERYIYN
 REEYARFDSD VGEFRAVTEL GRPAAEYWNS QKDILEEERA VPDRICRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA02080
HLA:HLA02080 DPB1*108:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA02115
HLA:HLA02115 DPB1*109:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA00527
HLA:HLA00527 DPB1*10:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVHQL RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEEYWNS QKDILEEERA VPDRVCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA02243
HLA:HLA02243 DPB1*110:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEERAVPDR ICRHNYELDE AVTLQRR*   
>P1;HLA:HLA02294
HLA:HLA02294 DPB1*111:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNPEEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA02403
HLA:HLA02403 DPB1*112:01 88 bases
 ENYLFQGRQE CYAFNGTQRF LERYIYNREE LVRFDSDVGE FRAVTELGRP AAEYWNSQKD
 ILEEKRAVPD RMCRHNYELG GPMTLQRR*   
>P1;HLA:HLA02447
HLA:HLA02447 DPB1*113:01 87 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA02451
HLA:HLA02451 DPB1*114:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPE AEYWNSQKDL
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA02493
HLA:HLA02493 DPB1*115:01 87 bases
 NYLFQGRQEC YTFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA02579
HLA:HLA02579 DPB1*116:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA02738
HLA:HLA02738 DPB1*117:01 88 bases
 ENYVYQLRQE CYAFNGTQRF LERYIYNREE YARFDSDVGE FRAVTELGRP AAEYWNSQKD
 ILEEERAVPD RMCRHNYELG GPMTLQRR*   
>P1;HLA:HLA02951
HLA:HLA02951 DPB1*118:01 88 bases
 ENYVYQGRQE CYAFNGTQRF LERYIYNPEE YARFDSDVGE FRAVTELGRP AAEYWNSQKD
 ILEEKRAVPD RVCRHNYELD EAVTLQRR*   
>P1;HLA:HLA03490
HLA:HLA03490 DPB1*119:01 87 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR VCRHNYELNE AVTLQRR*   
>P1;HLA:HLA00528
HLA:HLA00528 DPB1*11:01:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVYQL RQECYAFNGT QRFLERYIYN
 RQEYARFDSD VGEFRAVTEL GRPAAEYWNS QKDLLEERRA VPDRMCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00529
HLA:HLA00529 DPB1*11:01:02 85 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNRQEY ARFDSDVGEF RAVTELGRPA AEYWNSQKDL
 LEERRAVPDR MCRHNYELDE AVTLQ*   
>P1;HLA:HLA03492
HLA:HLA03492 DPB1*120:01N 5 bases
 NYLFX*     
>P1;HLA:HLA03575
HLA:HLA03575 DPB1*121:01 181 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFYSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA03822
HLA:HLA03822 DPB1*122:01 87 bases
 NYVYQGRQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA03838
HLA:HLA03838 DPB1*123:01 181 bases
 NYLFQGRQEG YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA04416
HLA:HLA04416 DPB1*124:01 181 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR VCRHNYELDE AVTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA04398
HLA:HLA04398 DPB1*125:01 87 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA05133
HLA:HLA05133 DPB1*126:01 181 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSMDSPVTVE
 W*     
>P1;HLA:HLA05357
HLA:HLA05357 DPB1*127:01 87 bases
 NYVYQGWQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA05358
HLA:HLA05358 DPB1*128:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MRRHNYELGG PMTLQRR*   
>P1;HLA:HLA05760
HLA:HLA05760 DPB1*129:01 87 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA06049
HLA:HLA06049 DPB1*130:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNWEEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR MCRHNYELDE AVTLQRR*   
>P1;HLA:HLA06078
HLA:HLA06078 DPB1*131:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVHQL RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEDYWNS QKDILEEERA VPDRMCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SAQSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA06140
HLA:HLA06140 DPB1*132:01 181 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDI
 LEEKRAVPDR VCRHNYELDE AVTLQRRVQP KVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYICQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA06672
HLA:HLA06672 DPB1*133:01 181 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEERAVPDR ICRHNYELDE AVTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA06673
HLA:HLA06673 DPB1*134:01 181 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCTHNYELGG PMTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA07334
HLA:HLA07334 DPB1*135:01 224 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPE AEYWNSQKDI
 LEEKRAVPDR MCRHNYELDE AVTLQRRVQP KVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYICQVEH TSLDSPVTVE
 WKAQSDSARS KTLTGAGGFV LGLIICGVGI FMHRRSKKVQ RGSA* 
>P1;HLA:HLA07366
HLA:HLA07366 DPB1*136:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDL
 LEERRAVPDR MCRHNYELDE AVTLQRR*   
>P1;HLA:HLA07534
HLA:HLA07534 DPB1*137:01 181 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELDE AVTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA07798
HLA:HLA07798 DPB1*138:01 218 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSMDSPVTVE
 WKAQSDSARS KTLTGAGGFV LGLIICGVGI FMHRRSKK*  
>P1;HLA:HLA07816
HLA:HLA07816 DPB1*139:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPE AEYWNSQKDL
 LEEKRAVPDR MCRHNYELVG PMTLQRR*   
>P1;HLA:HLA00530
HLA:HLA00530 DPB1*13:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVYQL RQECYAFNGT QRFLERYIYN
 REEYARFDSD VGEFRAVTEL GRPAAEYWNS QKDILEEERA VPDRICRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA08416
HLA:HLA08416 DPB1*140:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPE AEYWNSQKDI
 LEEKRAVPDR MCRHNYELDE AVTLQRP*   
>P1;HLA:HLA08802
HLA:HLA08802 DPB1*141:01 181 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVQWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA00531
HLA:HLA00531 DPB1*14:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVHQL RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEDYWNS QKDLLEEKRA VPDRVCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00532
HLA:HLA00532 DPB1*15:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVYQG RQECYAFNGT QRFLERYIYN
 RQEYARFDSD VGEFRAVTEL GRPAAEYWNS QKDLLEERRA VPDRMCRHNY ELVGPMTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGTFMHRRS KKVQRGSA*    
>P1;HLA:HLA00533
HLA:HLA00533 DPB1*16:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYLFQG RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEEYWNS QKDILEEERA VPDRMCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00534
HLA:HLA00534 DPB1*17:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVHQL RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEDYWNS QKDILEEERA VPDRMCRHNY ELDEAVTLQR
 RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYTC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00535
HLA:HLA00535 DPB1*18:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVYQG RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPDEEYWNS QKDILEEKRA VPDRMCRHNY ELVGPMTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGTFMHRRS KKVQRGSA*    
>P1;HLA:HLA00536
HLA:HLA00536 DPB1*19:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYLFQG RQECYAFNGT QRFLERYIYN
 REEFVRFDSD VGEFRAVTEL GRPEAEYWNS QKDILEEERA VPDRICRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFMLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00537
HLA:HLA00537 DPB1*20:01:01 181 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR MCRHNYELDE AVTLQRRVQP KVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYICQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA00538
HLA:HLA00538 DPB1*20:01:02 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR MCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00539
HLA:HLA00539 DPB1*21:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVYQL RQECYAFNGT QRFLERYIYN
 REELVRFDSD VGEFRAVTEL GRPEAEYWNS QKDILEEERA VPDRMCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00540
HLA:HLA00540 DPB1*22:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPE AEYWNSQKDI
 LEEERAVPDR MCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00541
HLA:HLA00541 DPB1*23:01 181 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA00542
HLA:HLA00542 DPB1*24:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPE AEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA00543
HLA:HLA00543 DPB1*25:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDL
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00544
HLA:HLA00544 DPB1*26:01:01 85 bases
 VYQLRQECYA FNGTQRFLER YIYNREEYAR FDSDVGEFRA VTELGRPAAE YWNSQKDILE
 EKRAVPDRVC RHNYELDEAV TLQRR*   
>P1;HLA:HLA00545
HLA:HLA00545 DPB1*26:01:02 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVYQL RQECYAFNGT QRFLERYIYN
 REEYARFDSD VGEFRAVTEL GRPAAEYWNS QKDILEEKRA VPDRVCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SAQSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00546
HLA:HLA00546 DPB1*27:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYVYQL RQECYAFNGT QRFLERYIYN
 REEYARFDSD VGEFRAVTEL GRPAAEYWNS QKDILEEKRA VPDRMCRHNY ELDEAVTLQR
 RVQPKVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYIC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00547
HLA:HLA00547 DPB1*28:01 181 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPD EEYWNSQKDL
 LEEKRAVPDR MCRHNYELVG PMTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA00548
HLA:HLA00548 DPB1*29:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEERAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00549
HLA:HLA00549 DPB1*30:01 181 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPE AEYWNSQKDI
 LEEERAVPDR MCRHNYELDE AVTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA00550
HLA:HLA00550 DPB1*31:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDL
 LEEKRALPDR MCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00551
HLA:HLA00551 DPB1*32:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EVYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA00552
HLA:HLA00552 DPB1*33:01 181 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA00553
HLA:HLA00553 DPB1*34:01 85 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPA AEYWNSQKDL
 LEEKRALPDR MCRHNYELVG PMTLQ*   
>P1;HLA:HLA00554
HLA:HLA00554 DPB1*35:01:01 85 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDI
 LEEKRAVPDR VCRHNYELDE AVTLQ*   
>P1;HLA:HLA04110
HLA:HLA04110 DPB1*35:01:02 181 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDI
 LEEKRAVPDR VCRHNYELDE AVTLQSRVQP KVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYICQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA00555
HLA:HLA00555 DPB1*36:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPE AEYWNSQKDI
 LEEKRAVPDR MCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00556
HLA:HLA00556 DPB1*37:01 85 bases
 VYQLRQECYA FNGTQRFLER YIYNREEFVR FDSDVGEFRA VTELGRPDEE YWNSQKDILE
 EERAVPDRVC RHNYELDEAV TLQRR*   
>P1;HLA:HLA00557
HLA:HLA00557 DPB1*38:01 83 bases
 LFQGRQECYP FNGTQRFLER YIYNREELVR FDSDVGEFRA VTELGRPEAE YWNSQKDILE
 EKRAVPDRMC RHNYELDEAV TLQ*   
>P1;HLA:HLA00558
HLA:HLA00558 DPB1*39:01 258 bases
 MMVLQVSAAP RTVALTALLM VLLTSVVQGR ATPENYLFQG RQECYAFNGT QRFLERYIYN
 REEYARFDSD VGEFRAVTEL GRPAAEYWNS QKDILEEKRA VPDRMCRHNY ELGGPMTLQR
 RVQPRVNVSP SKKGPLQHHN LLVCHVTDFY PGSIQVRWFL NGQEETAGVV STNLIRNGDW
 TFQILVMLEM TPQQGDVYTC QVEHTSLDSP VTVEWKAQSD SARSKTLTGA GGFVLGLIIC
 GVGIFMHRRS KKVQRGSA*    
>P1;HLA:HLA00559
HLA:HLA00559 DPB1*40:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELVG PMTLQRR*   
>P1;HLA:HLA00560
HLA:HLA00560 DPB1*41:01:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDF
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA03155
HLA:HLA03155 DPB1*41:01:02 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDF
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA00563
HLA:HLA00563 DPB1*44:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEERAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00564
HLA:HLA00564 DPB1*45:01 181 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDL
 LEEKRAVPDR VCRHNYELDE AVTLQRRVQP KVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYICQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA00565
HLA:HLA00565 DPB1*46:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA00566
HLA:HLA00566 DPB1*47:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPE AEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA00567
HLA:HLA00567 DPB1*48:01 85 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQ*   
>P1;HLA:HLA00568
HLA:HLA00568 DPB1*49:01 85 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQ*   
>P1;HLA:HLA00569
HLA:HLA00569 DPB1*50:01 181 bases
 NYVYQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR VCRHNYELDE AVTLQRRVQP KVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYICQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA00570
HLA:HLA00570 DPB1*51:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA00571
HLA:HLA00571 DPB1*52:01 85 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPA AEYWNSQKDL
 LEEKRAVPDR VCRHNYELDE AVTLQ*   
>P1;HLA:HLA00572
HLA:HLA00572 DPB1*53:01 85 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEKRAVPDR MCRHNYELVG PMTLQ*   
>P1;HLA:HLA00573
HLA:HLA00573 DPB1*54:01 85 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPE AEYWNSQKDI
 LEEERAVPDR VCRHNYELDE AVTLQ*   
>P1;HLA:HLA00574
HLA:HLA00574 DPB1*55:01 181 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEERAVPDR MCRHNYELDE AVTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA00575
HLA:HLA00575 DPB1*56:01 83 bases
 VYQLRQECYA FNGTQRFLER YIYNREEFAR FDSDVGEFRA VTELGRPAAE YWNSQKDLLE
 EKRAVPDRVC RHNYELDEAV TLQ*   
>P1;HLA:HLA00576
HLA:HLA00576 DPB1*57:01 79 bases
 LFQGRQECYA FNGTQRFLER YIYNREEFVR FDSDVGEFRA VTELGRPDED YWNSQKDLLE
 EKRAVPDRVC RHNYELDEA*    
>P1;HLA:HLA00577
HLA:HLA00577 DPB1*58:01 85 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEERAVPDR MCRHNYELDE AVTLQ*   
>P1;HLA:HLA00578
HLA:HLA00578 DPB1*59:01 181 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDL
 LEEKRAVPDR MCRHNYELGG PMTLQRRVQP RVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYTCQVEH TSMDSPVTVE
 W*     
>P1;HLA:HLA00579
HLA:HLA00579 DPB1*60:01 85 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDN
 LEEKRAVPDR MCRHNYELGG PMTLQ*   
>P1;HLA:HLA00580
HLA:HLA00580 DPB1*61:01N 62 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LX*     
>P1;HLA:HLA00581
HLA:HLA00581 DPB1*62:01 85 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELVG PMTLQ*   
>P1;HLA:HLA00582
HLA:HLA00582 DPB1*63:01 85 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELDE AVTLQ*   
>P1;HLA:HLA00583
HLA:HLA00583 DPB1*64:01N 2 bases
 NX*     
>P1;HLA:HLA00584
HLA:HLA00584 DPB1*65:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00585
HLA:HLA00585 DPB1*66:01 87 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA00586
HLA:HLA00586 DPB1*67:01 87 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPA AEYWNSQKDL
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00587
HLA:HLA00587 DPB1*68:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00588
HLA:HLA00588 DPB1*69:01 83 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEERRAVPDR MCRHNYELDE AVT*   
>P1;HLA:HLA00589
HLA:HLA00589 DPB1*70:01 85 bases
 NYVDQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR VCRHNYELDE AVTLQ*   
>P1;HLA:HLA00590
HLA:HLA00590 DPB1*71:01 85 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQ*   
>P1;HLA:HLA00591
HLA:HLA00591 DPB1*72:01 85 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDL
 LEEKRAVPDR MCRHNYELGG PMTLQ*   
>P1;HLA:HLA00592
HLA:HLA00592 DPB1*73:01 85 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDL
 LEEKRAVPDR VCRHNYELGG PMTLQ*   
>P1;HLA:HLA00593
HLA:HLA00593 DPB1*74:01 83 bases
 VYQLRQECYA FNGTQRFLER YIYNRQEYAR FDSDVGEFRA VTELGRPAAE YWNSQKDLLE
 ERRAVPDRMC RHNYELVGPM TLQ*   
>P1;HLA:HLA00594
HLA:HLA00594 DPB1*75:01 83 bases
 LFQGRQECYA FNGTQRFLER YIYNREEFVR FDSDVGEFRA VTELGRPDEE YWNSQKDILE
 EKRAVPDRVC RHNYELGGPM TLQ*   
>P1;HLA:HLA00595
HLA:HLA00595 DPB1*76:01 85 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR VCRHNYELDE AVTLQ*   
>P1;HLA:HLA00596
HLA:HLA00596 DPB1*77:01 87 bases
 NYLFQGLQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA00597
HLA:HLA00597 DPB1*78:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVLDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00598
HLA:HLA00598 DPB1*79:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA00599
HLA:HLA00599 DPB1*80:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA00600
HLA:HLA00600 DPB1*81:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA01002
HLA:HLA01002 DPB1*82:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQHR*   
>P1;HLA:HLA01084
HLA:HLA01084 DPB1*83:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDF
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA01085
HLA:HLA01085 DPB1*84:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPE EEYWNSQKDI
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA01162
HLA:HLA01162 DPB1*85:01 181 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELDE AVTLQHRVQP KVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYICQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA01234
HLA:HLA01234 DPB1*86:01 87 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDI
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA01308
HLA:HLA01308 DPB1*87:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPA AEYWNSQKDL
 LEEKRAVPDR MCRHNYELDE AVTLQRR*   
>P1;HLA:HLA01304
HLA:HLA01304 DPB1*88:01 181 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDI
 LEEERAVPDR VCRHNYELDE AVTLQRRVQP KVNVSPSKKG PLQHHNLLVC HVTDFYPGSI
 QVRWFLNGQE ETAGVVSTNL IRNGDWTFQI LVMLEMTPQQ GDVYICQVEH TSLDSPVTVE
 W*     
>P1;HLA:HLA01360
HLA:HLA01360 DPB1*89:01 87 bases
 NYVYQGRQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELDE AVTLQRR*   
>P1;HLA:HLA01441
HLA:HLA01441 DPB1*90:01 87 bases
 NYVYQGRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA01475
HLA:HLA01475 DPB1*91:01 87 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR MCRHNYELDE AVTLQRR*   
>P1;HLA:HLA01597
HLA:HLA01597 DPB1*92:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF ARFDSDVGEF RAVTELGRPD EDYWNSQKDL
 LEEKRAVPDR VCRHNYELDE AVTLQRR*   
>P1;HLA:HLA01637
HLA:HLA01637 DPB1*93:01 87 bases
 NYVYQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEERAVPDR MCRHNYELDE AVTLQRR*   
>P1;HLA:HLA01669
HLA:HLA01669 DPB1*94:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EEYWNSQKDI
 LEEKWAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA01670
HLA:HLA01670 DPB1*95:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEL VRFDSDVGEF RAVTELGRPA AEYWNSQKDL
 LEEERAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA01684
HLA:HLA01684 DPB1*96:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERYIYNREEY ARFDSDVGEF RAVTELGRPA AEYWNSQKHI
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
>P1;HLA:HLA01753
HLA:HLA01753 DPB1*97:01 88 bases
 ENYLFQGRQE CYAFNGTQRF LERYIYNREE LVRFDSDVWE FRAVTELGRP EAEYWNSQKD
 ILEEKRAVPD RMCRHNYELD EAVTLQRR*   
>P1;HLA:HLA01762
HLA:HLA01762 DPB1*98:01 87 bases
 NYVHQLRQEC YAFNGTQRFL ERYIYNREEF VRFDSDVGEF RAVTELGRPD EDYWNSQKDI
 LEEKRAVPDR MCRHNYELDE AVTLQRR*   
>P1;HLA:HLA01830
HLA:HLA01830 DPB1*99:01 87 bases
 NYLFQGRQEC YAFNGTQRFL ERDIYNREEF ARFDSDVGEF RAVTELGRPA AEYWNSQKDI
 LEEKRAVPDR MCRHNYELGG PMTLQRR*   
