>DL;HLA:HLA14837
HLA:HLA14837 DPB2*01:01:01 776 bases
 ATGATGATCC TGCAGGTTTC AGGGGGCCCC TGGACAGTGG CTCTGACAGC ATTACTGATG
 GTGCTGCTCA TATCTGTGGT CCAGAGCAGG GCCACTCCAG AGAATTCCGT CTACCAGGAA
 CGGCAGGAAT GCTATGCGTT CAATGGGACT CAGCGCGTTG TGGACGGGCT CATCTACAAC
 CGGGAGGAAT ACGTGCATTT TGACAGCGCA GTGGGGGAGT TCCTAGCAGT GATGGAGCTG
 GGGCGGCCCA TAGGCGAGTA CTTCAATAGC CAGAAGGACT TTATGGAACG GAAGCGAGCC
 GAGGTGGACA AGGTGTGCAG ACACAAGTAC GAGCTGATGG AGCCACTCAT CCGGCAGCGC
 CGAGTCCAGC CTAGGGTGAA CATCCCCCCT CCAAGAAGGA GCCCCGGCAG CACCACGACC
 TGCTTGTCTA CCACGTGACA GATTTCTACC CAGGCAGCAT TCAAGTCCGA TGCTTCCTGA
 ATGGACAGGA GGAAACAGCT GGGGTCATGT CCACCAAGCT GATCCGTAAT GAAGACTGGA
 CCTTCCAGAT CCTGGAGATG CTGGAAATGA TCCCCCAGCA GGGAAACATC TACACCTGCC
 AAGTGAAGCA CCCCAGCCTG GACAGTCCTG TCACCGTGGA GTGGAAGGCA CAGTCTGATT
 TTGTGCAGAG CAAGATGCTG ACAGGAGCCA GGGGCTTCAT GCTGGGGCTC ATCATCTGTG
 GAGTGGACAT CTTCACGCAC AGAAGGAGCA AGAAAGTTCA ACAAGGATCT GCATAA*
>DL;HLA:HLA14838
HLA:HLA14838 DPB2*01:01:02 776 bases
 ATGATGATCC TGCAGGTTTC AGGGGGCCCC TGGACAGTGG CTCTGACAGC ATTACTGATG
 GTGCTGCTCA TATCTGTGGT CCAGAGCAGG GCCACTCCAG AGAATTCCGT CTACCAGGAA
 CGGCAGGAAT GCTATGCGTT CAATGGGACT CAGCGCGTTG TGGACGGGCT CATCTACAAC
 CGGGAGGAAT ACGTGCATTT TGACAGCGCA GTGGGGGAGT TCCTAGCAGT GATGGAGCTG
 GGGCGGCCCA TAGGCGAGTA CTTCAATAGC CAGAAGGACT TTATGGAACG GAAGCGAGCC
 GAGGTGGACA AGGTGTGCAG ACACAAGTAC GAGCTGATGG AGCCACTCAT CCGGCAGCGC
 CGAGTCCAGC CTAGGGTGAA CATCCCCCCT CCAAGAAGGA GCCCCGGCAG CACCACCACC
 TGCTTGTCTA CCACGTGACA GATTTCTACC CAGGCAGCAT TCAAGTCCGA TGCTTCCTGA
 ATGGACAGGA GGAAACAGCT GGGGTCATGT CCACCAAGCT GATCCGTAAT GGAGACTGGA
 CCTTCCAGAT CCTGGAGATG CTGGAAATGA TCCCCCAGCA GGGAAACATC TACACCTGCC
 AAGTGAAGCA CCCCAGCCTG GACAGTCCTG TCACCGTGGA GTGGAAGGCA CAGTCTGATT
 TTGTGCAGAG CAAGATGCTG ACAGGAGCCA GGGGCTTCAT GCTGGGGCTC ATCATCTGTG
 GAGTGGACAT CTTCACGCAC AGAAGGAGCA AGAAAGTTCA ACAAGGATCT GCATAA*
>DL;HLA:HLA14842
HLA:HLA14842 DPB2*02:01 776 bases
 ATGATGATCC TGCAGGTTTC AGCGGGCCCC CGGACAGTGG CTCTGACAGC ATTACTGATG
 GTGCGGCTCA TATCTGTGGT CCAGAGCAGG ACCACTCCAG AGAATTCCGT CTACCAGGAA
 CGGCAGGAAT GCTATGCGTT CAATGGGACT CAGCGCGTTG TGGACGGGCT CATCTACAAC
 CGGGAGGAAT ACGTGCATTT TGACAGCGCA GTGGGGGAGT TCCTAGCAGT GATGGAGCTG
 GGGCGGCCCA TAGGCGAGTA CTTCAATAGC CAGAAGGACT TTATGGAACG GAAGCGAGCC
 GAGGTGGACA AGGTGTGCAG ACACAAGTAC GAGCTGATGG AGCCACTCAT CCGGCAGCGC
 CGAGTCCAGC CTAGGGTGAA CATCTCCCCT CCAAGAAGGA GCCCCAGCAG CACCACGACC
 TGCTTGTCTA CCACGTGACA GATTTCTACC CAGACAGCAT TCAAGTCCGA TGCTTCCTGA
 ATGGACAGGA GGAAACAGCT GGGGTCGTGT CCACCAACCT GATCCGTAAT GGAGACTGGA
 CCTTCCAGAT CCTGGAGATG CTGGAAATGA CCCCCCAGCA GGGAAACATC TACACCTGCC
 AAGTGGAGCA CCCCAGCCTG GACAGTCCTG TCACCGTGGA GTGGAAGGCA CAGTCTGATT
 CTGTGCAGAG CAAGATGCTG ACAGGAGCTA GGGGCTTCAT GCTGGGGCTC ATCATCTGTG
 GAGTGGACAT CTTCACGCAC AGAAGGAGGA AGAAAGTTCA ACAAGGACCT GCATAA*
>DL;HLA:HLA14839
HLA:HLA14839 DPB2*03:01:01:01 776 bases
 ATGATGATCC TGCAGGTTTC AGGGGGCCCC TGGACAGTGG CTCTGACAGC ATTACTGATG
 GTGCTGCTCA TATCTGTGGT CCAGAGCAGG GCCACTCCAG AGAATTCCGT CTACCAGGAA
 CGGCAGGAAT GCTATGCGTT CAATGGGACT CAGCGCGTTG TGGACGGGCT CATCTACAAC
 CGGGAGGAAT ACGTGCATTT TGACAGCGCA GTGGGGGAGT TCCTAGCAGT GATGGAGCTG
 GGGCGGCCCA TAGGCGAGTA CTTCAATAGC CAGAAGGACT TTATGGAACG GAAGCGAGCC
 GAGGTGGACA AGGTGTGCAG ACACAAGTAC GAGCTGATGG AGCCACTCAT CCGGCAGCGC
 CGAGTCCAGC CTAGGGTGAA CATCTCCCCT CCAAGAAGGA GCCCCAGCAG CACCACGACC
 TGCTTGTCTA CCACGTGACA GATTTCTACC CAGACAGCAT TCAAGTCCGA TGCTTCCTGA
 ATGGACAGGA GGAAACAGCT GGGGTCGTGT CCACCAACCT GATCCGTAAT GGAGACTGGA
 CCTTCCAGAT CCTGGAGATG CTGGAAATGA CCCCCCAGCA GGGAAACATC TACACCTGCC
 AAGTGGAGCA CCCCAGCCTG GACAGTCCTG TCACCGTGGA GTGGAAGGCA CAGTCTGATT
 CTGTGCAGAG CAAGATGCTG ACAGGAGCCA GGGGCTTCAT GCTGGGGCTC ATCATCTGTG
 GAGTGGACAT CTTCACGCAC AGAAGGAGGA AGAAAGTTCA ACAAGGATCT GCATAA*
>DL;HLA:HLA14840
HLA:HLA14840 DPB2*03:01:01:02 776 bases
 ATGATGATCC TGCAGGTTTC AGGGGGCCCC TGGACAGTGG CTCTGACAGC ATTACTGATG
 GTGCTGCTCA TATCTGTGGT CCAGAGCAGG GCCACTCCAG AGAATTCCGT CTACCAGGAA
 CGGCAGGAAT GCTATGCGTT CAATGGGACT CAGCGCGTTG TGGACGGGCT CATCTACAAC
 CGGGAGGAAT ACGTGCATTT TGACAGCGCA GTGGGGGAGT TCCTAGCAGT GATGGAGCTG
 GGGCGGCCCA TAGGCGAGTA CTTCAATAGC CAGAAGGACT TTATGGAACG GAAGCGAGCC
 GAGGTGGACA AGGTGTGCAG ACACAAGTAC GAGCTGATGG AGCCACTCAT CCGGCAGCGC
 CGAGTCCAGC CTAGGGTGAA CATCTCCCCT CCAAGAAGGA GCCCCAGCAG CACCACGACC
 TGCTTGTCTA CCACGTGACA GATTTCTACC CAGACAGCAT TCAAGTCCGA TGCTTCCTGA
 ATGGACAGGA GGAAACAGCT GGGGTCGTGT CCACCAACCT GATCCGTAAT GGAGACTGGA
 CCTTCCAGAT CCTGGAGATG CTGGAAATGA CCCCCCAGCA GGGAAACATC TACACCTGCC
 AAGTGGAGCA CCCCAGCCTG GACAGTCCTG TCACCGTGGA GTGGAAGGCA CAGTCTGATT
 CTGTGCAGAG CAAGATGCTG ACAGGAGCCA GGGGCTTCAT GCTGGGGCTC ATCATCTGTG
 GAGTGGACAT CTTCACGCAC AGAAGGAGGA AGAAAGTTCA ACAAGGATCT GCATAA*
>DL;HLA:HLA14841
HLA:HLA14841 DPB2*03:01:01:03 776 bases
 ATGATGATCC TGCAGGTTTC AGGGGGCCCC TGGACAGTGG CTCTGACAGC ATTACTGATG
 GTGCTGCTCA TATCTGTGGT CCAGAGCAGG GCCACTCCAG AGAATTCCGT CTACCAGGAA
 CGGCAGGAAT GCTATGCGTT CAATGGGACT CAGCGCGTTG TGGACGGGCT CATCTACAAC
 CGGGAGGAAT ACGTGCATTT TGACAGCGCA GTGGGGGAGT TCCTAGCAGT GATGGAGCTG
 GGGCGGCCCA TAGGCGAGTA CTTCAATAGC CAGAAGGACT TTATGGAACG GAAGCGAGCC
 GAGGTGGACA AGGTGTGCAG ACACAAGTAC GAGCTGATGG AGCCACTCAT CCGGCAGCGC
 CGAGTCCAGC CTAGGGTGAA CATCTCCCCT CCAAGAAGGA GCCCCAGCAG CACCACGACC
 TGCTTGTCTA CCACGTGACA GATTTCTACC CAGACAGCAT TCAAGTCCGA TGCTTCCTGA
 ATGGACAGGA GGAAACAGCT GGGGTCGTGT CCACCAACCT GATCCGTAAT GGAGACTGGA
 CCTTCCAGAT CCTGGAGATG CTGGAAATGA CCCCCCAGCA GGGAAACATC TACACCTGCC
 AAGTGGAGCA CCCCAGCCTG GACAGTCCTG TCACTGTGGA GTGGAAGGCA CAGTCTGATT
 CTGTGCAGAG CAAGATGCTG ACAGGAGCCA GGGGCTTCAT GCTGGGGCTC ATCATCTGTG
 GAGTGGGCAT CTTCACGCAC AGAAGGAGCA AGAAAGTTCA ACAAGGATCT GCATAA*
