>P1;HLA:HLA14837
HLA:HLA14837 DPB2*01:01:01 145 bases
 MMILQVSGGP WTVALTALLM VLLISVVQSR ATPENSVYQE RQECYAFNGT QRVVDGLIYN
 REEYVHFDSA VGEFLAVMEL GRPIGEYFNS QKDFMERKRA EVDKVCRHKY ELMEPLIRQR
 RVQPRVNIPP PRRSPGSTTT CLSTT*   
>P1;HLA:HLA14838
HLA:HLA14838 DPB2*01:01:02 145 bases
 MMILQVSGGP WTVALTALLM VLLISVVQSR ATPENSVYQE RQECYAFNGT QRVVDGLIYN
 REEYVHFDSA VGEFLAVMEL GRPIGEYFNS QKDFMERKRA EVDKVCRHKY ELMEPLIRQR
 RVQPRVNIPP PRRSPGSTTT CLSTT*   
>P1;HLA:HLA14842
HLA:HLA14842 DPB2*02:01 145 bases
 MMILQVSAGP RTVALTALLM VRLISVVQSR TTPENSVYQE RQECYAFNGT QRVVDGLIYN
 REEYVHFDSA VGEFLAVMEL GRPIGEYFNS QKDFMERKRA EVDKVCRHKY ELMEPLIRQR
 RVQPRVNISP PRRSPSSTTT CLSTT*   
>P1;HLA:HLA14839
HLA:HLA14839 DPB2*03:01:01:01 145 bases
 MMILQVSGGP WTVALTALLM VLLISVVQSR ATPENSVYQE RQECYAFNGT QRVVDGLIYN
 REEYVHFDSA VGEFLAVMEL GRPIGEYFNS QKDFMERKRA EVDKVCRHKY ELMEPLIRQR
 RVQPRVNISP PRRSPSSTTT CLSTT*   
>P1;HLA:HLA14840
HLA:HLA14840 DPB2*03:01:01:02 145 bases
 MMILQVSGGP WTVALTALLM VLLISVVQSR ATPENSVYQE RQECYAFNGT QRVVDGLIYN
 REEYVHFDSA VGEFLAVMEL GRPIGEYFNS QKDFMERKRA EVDKVCRHKY ELMEPLIRQR
 RVQPRVNISP PRRSPSSTTT CLSTT*   
>P1;HLA:HLA14841
HLA:HLA14841 DPB2*03:01:01:03 145 bases
 MMILQVSGGP WTVALTALLM VLLISVVQSR ATPENSVYQE RQECYAFNGT QRVVDGLIYN
 REEYVHFDSA VGEFLAVMEL GRPIGEYFNS QKDFMERKRA EVDKVCRHKY ELMEPLIRQR
 RVQPRVNISP PRRSPSSTTT CLSTT*   
