>P1;HLA:HLA00601
HLA:HLA00601 DQA1*01:01:01:01 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA14786
HLA:HLA14786 DQA1*01:01:01:02 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA14787
HLA:HLA14787 DQA1*01:01:01:03 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA17304
HLA:HLA17304 DQA1*01:01:01:04 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA17305
HLA:HLA17305 DQA1*01:01:01:05 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA01409
HLA:HLA01409 DQA1*01:01:02 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA12906
HLA:HLA12906 DQA1*01:01:03 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA00602
HLA:HLA00602 DQA1*01:02:01:01 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA06598
HLA:HLA06598 DQA1*01:02:01:02 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA06594
HLA:HLA06594 DQA1*01:02:01:03 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA06599
HLA:HLA06599 DQA1*01:02:01:04 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA14846
HLA:HLA14846 DQA1*01:02:01:05 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA14847
HLA:HLA14847 DQA1*01:02:01:06 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA14848
HLA:HLA14848 DQA1*01:02:01:07 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA17306
HLA:HLA17306 DQA1*01:02:01:08 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA00603
HLA:HLA00603 DQA1*01:02:02 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA02338
HLA:HLA02338 DQA1*01:02:03 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA02432
HLA:HLA02432 DQA1*01:02:04 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA00604
HLA:HLA00604 DQA1*01:03:01:01 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQFTH EFDGDEQFYV
 DLEKKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHAVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA06601
HLA:HLA06601 DQA1*01:03:01:02 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQFTH EFDGDEQFYV
 DLEKKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHAVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA14788
HLA:HLA14788 DQA1*01:03:01:03 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQFTH EFDGDEQFYV
 DLEKKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHAVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA14789
HLA:HLA14789 DQA1*01:03:01:04 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQFTH EFDGDEQFYV
 DLEKKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHAVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA14790
HLA:HLA14790 DQA1*01:03:01:05 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQFTH EFDGDEQFYV
 DLEKKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHAVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA14791
HLA:HLA14791 DQA1*01:03:01:06 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQFTH EFDGDEQFYV
 DLEKKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHAVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA17307
HLA:HLA17307 DQA1*01:03:01:07 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQFTH EFDGDEQFYV
 DLEKKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHAVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA17308
HLA:HLA17308 DQA1*01:03:01:08 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQFTH EFDGDEQFYV
 DLEKKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHAVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA00605
HLA:HLA00605 DQA1*01:04:01:01 255 bases
 MILNKALLLG ALALTTMMSP CGGEGIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CTLGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA06597
HLA:HLA06597 DQA1*01:04:01:02 255 bases
 MILNKALLLG ALALTTMMSP CGGEGIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CTLGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA14792
HLA:HLA14792 DQA1*01:04:01:03 255 bases
 MILNKALLLG ALALTTMMSP CGGEGIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CTLGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA14793
HLA:HLA14793 DQA1*01:04:01:04 255 bases
 MILNKALLLG ALALTTMMSP CGGEGIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CTLGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA01376
HLA:HLA01376 DQA1*01:04:02 255 bases
 MILNKALLLG ALALTTMMSP CGGEGIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CTLGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA00606
HLA:HLA00606 DQA1*01:05:01 255 bases
 MILNKALLLG ALALTTMMSP CGGEGIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA11066
HLA:HLA11066 DQA1*01:05:02 255 bases
 MILNKALLLG ALALTTMMSP CGGEGIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA01003
HLA:HLA01003 DQA1*01:06 82 bases
 DHVASCGVNL YQFYGPSGQY THEFDGDEQF YVDLERKEAA WRWPEFSKFG GFDPQGALRN
 MAVAKHNLNI MIKRYNSTAA TN*   
>P1;HLA:HLA01905
HLA:HLA01905 DQA1*01:07Q 255 bases
 MILNKALLLG ALALTTMMSP CGGEGIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEEFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KCYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CTLGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA07277
HLA:HLA07277 DQA1*01:08 176 bases
 DHVASCGVNL YQFYGPSGQY THEFDGDEQF YVDLERKETA WRWPEFSKFG GFDPQGALRN
 MAVAKHNLNI MIKRYNSTAA TNEVPEVTVF SKSPVTLGQP NTLICLVDNI FPPVVNITWL
 SNGQSVTEAV SETSFLSKSD HSFFKISYLT FLPSADEIYD CKVEHWGLDQ PLLKHW*
>P1;HLA:HLA07278
HLA:HLA07278 DQA1*01:09 176 bases
 DHVASCGVNL YQFYGPSGQY THEFDGDEQF YVDLERKETA WRWPEFSKFG GFDPQGALRN
 MAVAKHNLNI MIKRYNSTAA TNEVPEVTVF SKSPVTLDQP NTLICLVDNI FPPVVNITWL
 SNGQSVTEGV SETSFLSKSD HSFFKISYLT FLPSADEIYD CKVEHWGLDQ PLLKHW*
>P1;HLA:HLA08431
HLA:HLA08431 DQA1*01:10 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQFTH EFDGDEQFYV
 DLEKKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTTATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHAVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA08433
HLA:HLA08433 DQA1*01:11 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GQSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEILA PMSELTETVV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA09875
HLA:HLA09875 DQA1*01:12 176 bases
 DHVASCGVNL YQFYGPSGQY THEFDGDEEF YVDLERKETA WRWPEFSKFG GFDPQGALRN
 MAVAKHNLNI MIKRYNSTAA TNEVPEVTVF SKSPVTLGQP NTLICLVDNI FPPVVNITWL
 SNGQSVTEGV SETSFLSKSD HSFFKISYLT FLPSADEIYD CKVQHWGLDQ PLLKHW*
>P1;HLA:HLA14208
HLA:HLA14208 DQA1*01:13 176 bases
 DHVASCGVNL YQFYGPSGQY THEFDGDEQF YVDLERKETA WRWPEFSKFG GFDPQGALRN
 MAVAKHNLNI MIKCYNSTAA TNEVPEVTVF SKSPVTLGQP NTLICLVDNI FPPVVNITWL
 SNGQSVTEGV SETSFLSKSD HSFFKISYLT FLPSADEIYD CKVEHWGLDQ PLLKHW*
>P1;HLA:HLA15632
HLA:HLA15632 DQA1*01:14 255 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNFYQ FYGPSGQFTH EFDGDEQFYV
 DLEKKETAWR WPEFSKFGGF DPQGALRNMA VAKHNLNIMI KRYNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHAVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDQPL LKHWEPEIPA PMSELTETVV CALGLSVGLV GIVVGTVFII
 QGLRSVGASR HQGPL*    
>P1;HLA:HLA16313
HLA:HLA16313 DQA1*01:15N 43 bases
 DHVASCGVNL YQFYGPSGQF THEFDGDEQF YVDLEKKETA WRX* 
>P1;HLA:HLA17279
HLA:HLA17279 DQA1*01:16N 86 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASCGVNLYQ FYGPSGQYTH EFDGDEQFYV
 DLERKETAWR WPEFSKFGVL TRRVHX*   
>P1;HLA:HLA00607
HLA:HLA00607 DQA1*02:01:01:01 254 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQFTH EFDGDEEFYV
 DLERKETVWK LPLFHRLRFD PQFALTNIAV LKHNLNILIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTFLP
 SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVLIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA14794
HLA:HLA14794 DQA1*02:01:01:02 254 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQFTH EFDGDEEFYV
 DLERKETVWK LPLFHRLRFD PQFALTNIAV LKHNLNILIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTFLP
 SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVLIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA17070
HLA:HLA17070 DQA1*02:01:02 81 bases
 DHVASYGVNL YQSYGPSGQF THEFDGDEEF YVDLERKETV WKLPLFHRLR FDPQFALTNI
 AVLKHNLNIL IKRSNSTAAT N*   
>P1;HLA:HLA00608
HLA:HLA00608 DQA1*03:01:01 255 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYSH EFDGDEEFYV
 DLERKETVWQ LPLFRRFRRF DPQFALTNIA VLKHNLNIVI KRSNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPT PMSELTETVV CALGLSVGLV GIVVGTVLII
 RGLRSVGASR HQGPL*    
>P1;HLA:HLA13330
HLA:HLA13330 DQA1*03:01:03 176 bases
 DHVASYGVNL YQSYGPSGQY SHEFDGDEEF YVDLERKETV WQLPLFRRFR RFDPQFALTN
 IAVLKHNLNI VIKRSNSTAA TNEVPEVTVF SKSPVTLGQP NTLICLVDNI FPPVVNITWL
 SNGHSVTEGV SETSFLSKSD HSFFKISYLT FLPSADEIYD CKVEHWGLDE PLLKHW*
>P1;HLA:HLA00610
HLA:HLA00610 DQA1*03:02:01:01 255 bases
 MILNKALMLG ALALTTVTSP CGGEDIVADH VASYGVNLYQ SYGPSGQYSH EFDGDEEFYV
 DLERKETVWQ LPLFRRFRRF DPQFALTNIA VLKHNLNIVI KRSNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSDDEIYDCK VEHWGLDEPL LKHWEPEIPT PMSELTETVV CALGLSVGLV GIVVGTVLII
 RGLRSVGASR HQGPL*    
>P1;HLA:HLA17309
HLA:HLA17309 DQA1*03:02:01:02 255 bases
 MILNKALMLG ALALTTVTSP CGGEDIVADH VASYGVNLYQ SYGPSGQYSH EFDGDEEFYV
 DLERKETVWQ LPLFRRFRRF DPQFALTNIA VLKHNLNIVI KRSNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSDDEIYDCK VEHWGLDEPL LKHWEPEIPT PMSELTETVV CALGLSVGLV GIVVGTVLII
 RGLRSVGASR HQGPL*    
>P1;HLA:HLA17310
HLA:HLA17310 DQA1*03:02:01:03 255 bases
 MILNKALMLG ALALTTVTSP CGGEDIVADH VASYGVNLYQ SYGPSGQYSH EFDGDEEFYV
 DLERKETVWQ LPLFRRFRRF DPQFALTNIA VLKHNLNIVI KRSNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSDDEIYDCK VEHWGLDEPL LKHWEPEIPT PMSELTETVV CALGLSVGLV GIVVGTVLII
 RGLRSVGASR HQGPL*    
>P1;HLA:HLA00611
HLA:HLA00611 DQA1*03:03:01:01 255 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYSH EFDGDEEFYV
 DLERKETVWQ LPLFRRFRRF DPQFALTNIA VLKHNLNIVI KRSNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSDDEIYDCK VEHWGLDEPL LKHWEPEIPT PMSELTETVV CALGLSVGLV GIVVGTVLII
 RGLRSVGASR HQGPL*    
>P1;HLA:HLA14795
HLA:HLA14795 DQA1*03:03:01:02 255 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYSH EFDGDEEFYV
 DLERKETVWQ LPLFRRFRRF DPQFALTNIA VLKHNLNIVI KRSNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSDDEIYDCK VEHWGLDEPL LKHWEPEIPT PMSELTETVV CALGLSVGLV GIVVGTVLII
 RGLRSVGASR HQGPL*    
>P1;HLA:HLA14797
HLA:HLA14797 DQA1*03:03:01:03 255 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYSH EFDGDEEFYV
 DLERKETVWQ LPLFRRFRRF DPQFALTNIA VLKHNLNIVI KRSNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSDDEIYDCK VEHWGLDEPL LKHWEPEIPT PMSELTETVV CALGLSVGLV GIVVGTVLII
 RGLRSVGASR HQGPL*    
>P1;HLA:HLA07419
HLA:HLA07419 DQA1*03:03:02 255 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYSH EFDGDEEFYV
 DLERKETVWQ LPLFRRFRRF DPQFALTNIA VLKHNLNIVI KRSNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSDDEIYDCK VEHWGLDEPL LKHWEPEIPT PMSELTETVV CALGLSVGLV GIVVGTVLII
 RGLRSVGASR HQGPL*    
>P1;HLA:HLA17290
HLA:HLA17290 DQA1*03:04 255 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYSH EFDGDEEFYV
 DLERKETVWQ LPLFRRFRRF DPQFALTNIA VLKHNLNIVI KRSNSTAATN EVPEVTVFSK
 SPVTLGQPNT LICLVDNIFP PVVNITWLRN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSDDEIYDCK VEHWGLDEPL LKHWEPEIPT PMSELTETVV CALGLSVGLV GIVVGTVLII
 RGLRSVGASR HQGPL*    
>P1;HLA:HLA00612
HLA:HLA00612 DQA1*04:01:01:01 254 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV TKHNLNILIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTFLP
 SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA17311
HLA:HLA17311 DQA1*04:01:01:02 254 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV TKHNLNILIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTFLP
 SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA17312
HLA:HLA17312 DQA1*04:01:01:03 254 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV TKHNLNILIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTFLP
 SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA01694
HLA:HLA01694 DQA1*04:01:02:01 254 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV TKHNLNILIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTFLP
 SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA09342
HLA:HLA09342 DQA1*04:01:02:02 254 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV TKHNLNILIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTFLP
 SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA01697
HLA:HLA01697 DQA1*04:02 254 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV TKHNLNILIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSEI SFLSKSDHSF FKISYLTFLP
 SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA01774
HLA:HLA01774 DQA1*04:03N 48 bases
 DHVASYGVNL YQSYGPSGQY THEFDGDEQF YVDLGRKETV WCLPVLRX* 
>P1;HLA:HLA01874
HLA:HLA01874 DQA1*04:04 175 bases
 DHVASYGVNL YQSYGPSGQY THEFDGDEQF YVDLGRKETV WCLPVLRQFR FDPQFALTNI
 AVTKHNLNIL IKRSNSTAAT NEVPEVTVFS KSPVTLGQPN TLICLVDNIF PPVVNITWLS
 NGHSVTEGVS ETSFLSKSDH SFFKISHLTF LPSADEIYDC KVEHWGLDEP LLKHW*
>P1;HLA:HLA00613
HLA:HLA00613 DQA1*05:01:01:01 254 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA06618
HLA:HLA06618 DQA1*05:01:01:02 254 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA14799
HLA:HLA14799 DQA1*05:01:01:03 254 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA00614
HLA:HLA00614 DQA1*05:01:02 86 bases
 EDIVADHVAS YGVNLYQSYG PSGQYTHEFD GDEQFYVDLG RKETVWCLPV LRQFRFDPQF
 ALTNIAVLKH NLNSLIKRSN STAATN*   
>P1;HLA:HLA00616
HLA:HLA00616 DQA1*05:02 74 bases
 GVNLYQSYGP SGQYTHEFDG DEQFYVDLGR KETVWCLPVL RQFRFDRQFA LTNIAVLKHN
 LNSLIKRSNS TAAT*    
>P1;HLA:HLA00617
HLA:HLA00617 DQA1*05:03:01:01 254 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SSEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA17360
HLA:HLA17360 DQA1*05:03:01:02 254 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SSEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA00618
HLA:HLA00618 DQA1*05:04 81 bases
 DHVASYGVNL YQSYGLSGQY THEFDGDEQF YVDLGRKETV WCLPVLRQFR FDPQFALTNI
 AVLKHNLNSL IKRSNSTAAT N*   
>P1;HLA:HLA00619
HLA:HLA00619 DQA1*05:05:01:01 254 bases
 MILNKALMLG TLALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA06614
HLA:HLA06614 DQA1*05:05:01:02 254 bases
 MILNKALMLG TLALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA06609
HLA:HLA06609 DQA1*05:05:01:03 254 bases
 MILNKALMLG TLALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA14801
HLA:HLA14801 DQA1*05:05:01:04 254 bases
 MILNKALMLG TLALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA14805
HLA:HLA14805 DQA1*05:05:01:05 254 bases
 MILNKALMLG TLALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA14849
HLA:HLA14849 DQA1*05:05:01:06 254 bases
 MILNKALMLG TLALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA15562
HLA:HLA15562 DQA1*05:05:01:07 254 bases
 MILNKALMLG TLALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA15563
HLA:HLA15563 DQA1*05:05:01:08 254 bases
 MILNKALMLG TLALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA17361
HLA:HLA17361 DQA1*05:05:01:09 254 bases
 MILNKALMLG TLALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA17362
HLA:HLA17362 DQA1*05:05:01:10 254 bases
 MILNKALMLG TLALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA02339
HLA:HLA02339 DQA1*05:06:01:01 254 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTVGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SSEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA17363
HLA:HLA17363 DQA1*05:06:01:02 254 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTVGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SSEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA02340
HLA:HLA02340 DQA1*05:07 254 bases
 MILNKALMLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SSEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVC IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA02341
HLA:HLA02341 DQA1*05:08 254 bases
 MILNKALMLG TLALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET IFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA02433
HLA:HLA02433 DQA1*05:09 254 bases
 MILNKALMLG TLALTTVMSP CGGKDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA04360
HLA:HLA04360 DQA1*05:10 175 bases
 DHVASYGVNL YQSYGPSGQY THEFDGDEQF YVDLGRKETV WCLPVLRQFR FDPQFALTNI
 AVLKHNLNSL VKRSNSTAAT NEVPEVTVFS KSPVTLGQPN ILICLVDNIF PPVVNITWLS
 NGHSVTEGVS ETSFLSKSDH SFFKISYLTL LPSAEESYDC KVEHWGLDKP LLKHW*
>P1;HLA:HLA06617
HLA:HLA06617 DQA1*05:11 254 bases
 MILNKALMLG TLALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQYTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV LKHNLNSLIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNIL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTLLP
 SAEESYDCKV EHWGLDKPLL KHWEPEIPAP MSELTGTVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA00620
HLA:HLA00620 DQA1*06:01:01:01 254 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQFTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV TKHNLNILIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTFLP
 SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA17364
HLA:HLA17364 DQA1*06:01:01:02 254 bases
 MILNKALLLG ALALTTVMSP CGGEDIVADH VASYGVNLYQ SYGPSGQFTH EFDGDEQFYV
 DLGRKETVWC LPVLRQFRFD PQFALTNIAV TKHNLNILIK RSNSTAATNE VPEVTVFSKS
 PVTLGQPNTL ICLVDNIFPP VVNITWLSNG HSVTEGVSET SFLSKSDHSF FKISYLTFLP
 SADEIYDCKV EHWGLDEPLL KHWEPEIPAP MSELTETVVC ALGLSVGLVG IVVGTVFIIR
 GLRSVGASRH QGPL*    
>P1;HLA:HLA00621
HLA:HLA00621 DQA1*06:01:02 75 bases
 GVNLYQSYGP SGQFTHEFDG DEQFYVDLGR KETVWCLPVL RQFRFDPQFA LTNIAVTKHN
 LNILIKRSNS TAATN*    
>P1;HLA:HLA01861
HLA:HLA01861 DQA1*06:02 175 bases
 DHVASYGVNL YQSYGPSGQF THEFDGDEQF YVDLGRKETV WCLPVLRQFR FDPQFALTNI
 AVTKHNLNIL IKRSNSTAAT NEVPEVTVFS KSPVTLGQPN TLICLVDNIF PPVVNITWLS
 NGHSVTEGVS ETRFLSKSDH SFFKISYLTF LPSADEIYDC KVEHWGLDEP LLKHW*
