>DL;HLA:HLA26079
HLA:HLA26079 DQA2*01:01:01:01 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA GTTCTATGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26176
HLA:HLA26176 DQA2*01:01:01:02 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA GTTCTATGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26080
HLA:HLA26080 DQA2*01:01:01:03 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA GTTCTATGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26192
HLA:HLA26192 DQA2*01:01:02:01 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA GTTCTACGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26105
HLA:HLA26105 DQA2*01:01:02:02 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA GTTCTACGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26171
HLA:HLA26171 DQA2*01:01:02:03 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA GTTCTACGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26138
HLA:HLA26138 DQA2*01:01:03 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCACAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26173
HLA:HLA26173 DQA2*01:01:04 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26127
HLA:HLA26127 DQA2*01:02 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACCAGGA GTTCTATGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26119
HLA:HLA26119 DQA2*01:03 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA GTTCTACGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGA TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26157
HLA:HLA26157 DQA2*01:04:01:01 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGC GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTGTGA* 
>DL;HLA:HLA26143
HLA:HLA26143 DQA2*01:04:01:02 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGC GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTGTGA* 
>DL;HLA:HLA26099
HLA:HLA26099 DQA2*01:05 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA GTTCTATGTG
 GACCTGGAGA TGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26087
HLA:HLA26087 DQA2*01:06 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGATGAGGA GTTCTACGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCACCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26212
HLA:HLA26212 DQA2*01:07 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA GTTCTACGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCACAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CAAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGC GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTGTGA* 
>DL;HLA:HLA26203
HLA:HLA26203 DQA2*01:08 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA GTTCTATGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 GGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CGCTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCATG GGCATTGTGG TGGGCACTGT CTTCATCATC
 CAAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
>DL;HLA:HLA26115
HLA:HLA26115 DQA2*01:09 768 bases
 ATGATCCTAA ACAAAGCTCT GCTGCTGGGG GCCCTCGCCC TGACTGCCGT GATGAGCCCC
 TGTGGAGGTG AAGACATTGT GGCTGACCAT GTTGCCTCCT ATGGTGTGAA CTTCTACCAG
 TCTCACGGTC CCTCTGGCCA GTACACCCAT GAATTTGATG GAGACGAGGA GTTCTATGTG
 GACCTGGAGA CGAAAGAGAC TGTCTGGCAG TTGCCTATGT TTAGCAAATT TATAAGTTTT
 GACCCGCAGA GTGCACTGAG AAATATGGCT GTGGGAAAAC ACACCTTGGA ATTCATGATG
 AGACAGTCCA ACTCTACCGC TGCCACCAAT GAGGTTCCTG AGGTCACAGT GTTTTCCAAG
 TTTCCTGTGA CACTGGGTCA GCCCAACACC CTCATCTGTC TTGTGGACAA CATCTTTCCT
 CCTGTGGTCA ACATCACCTG GCTGAGCAAT GGGCACTCAG TCACAGAAGG TGTTTCTGAG
 ACCAGCTTCC TCTCCAAGAG TGATCATTCC TTCTTCAAGA TCAGTTACCT CACCTTCCTC
 CCTTCTGCTG ATGAGATTTA TGACTGCAAG GTGGAGCACT GGGGCCTGGA CGAGCCTCTT
 CTGAAACACT GGGAGCCTGA GATTCCAGCC CCTATGTCAG AGCTCACAGA GACTTTGGTC
 TGCGCCCTGG GGTTGTCTGT GGGCCTCGTG GGCATTGTGG TGGCGACTGT CTTCATCATC
 CGAGGCCTGC GTTCAGTTGG TGCTTCCAGA CACCAAGGGC TCTTATGA* 
