>P1;HLA:HLA26079
HLA:HLA26079 DQA2*01:01:01:01 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26176
HLA:HLA26176 DQA2*01:01:01:02 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26080
HLA:HLA26080 DQA2*01:01:01:03 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26192
HLA:HLA26192 DQA2*01:01:02:01 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26105
HLA:HLA26105 DQA2*01:01:02:02 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26171
HLA:HLA26171 DQA2*01:01:02:03 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26138
HLA:HLA26138 DQA2*01:01:03 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26173
HLA:HLA26173 DQA2*01:01:04 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26127
HLA:HLA26127 DQA2*01:02 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDQEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26119
HLA:HLA26119 DQA2*01:03 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLM GIVVGTVFII
 QGLRSVDASR HQGLL*    
>P1;HLA:HLA26157
HLA:HLA26157 DQA2*01:04:01:01 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSAGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26143
HLA:HLA26143 DQA2*01:04:01:02 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSAGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26099
HLA:HLA26099 DQA2*01:05 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLEMKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26087
HLA:HLA26087 DQA2*01:06 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CTLGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26212
HLA:HLA26212 DQA2*01:07 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDKPL LKHWEPEIPA PMSELTETLV CALGLSAGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26203
HLA:HLA26203 DQA2*01:08 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM GQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLM GIVVGTVFII
 QGLRSVGASR HQGLL*    
>P1;HLA:HLA26115
HLA:HLA26115 DQA2*01:09 255 bases
 MILNKALLLG ALALTAVMSP CGGEDIVADH VASYGVNFYQ SHGPSGQYTH EFDGDEEFYV
 DLETKETVWQ LPMFSKFISF DPQSALRNMA VGKHTLEFMM RQSNSTAATN EVPEVTVFSK
 FPVTLGQPNT LICLVDNIFP PVVNITWLSN GHSVTEGVSE TSFLSKSDHS FFKISYLTFL
 PSADEIYDCK VEHWGLDEPL LKHWEPEIPA PMSELTETLV CALGLSVGLV GIVVATVFII
 RGLRSVGASR HQGLL*    
