>P1;HLA:HLA00622
HLA:HLA00622 DQB1*02:01:01 261 bases
 MSWKKALRIP GGLRAATVTL MLSMLSTPVA EGRDSPEDFV YQFKGMCYFT NGTERVRLVS
 RSIYNREEIV RFDSDVGEFR AVTLLGLPAA EYWNSQKDIL ERKRAAVDRV CRHNYQLELR
 TTLQRRVEPT VTISPSRTEA LNHHNLLVCS VTDFYPAQIK VRWFRNDQEE TAGVVSTPLI
 RNGDWTFQIL VMLEMTPQRG DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGFVL
 GLIFLGLGLI IHHRSQKGLL H*   
>P1;HLA:HLA01934
HLA:HLA01934 DQB1*02:01:02 89 bases
 DFVYQFKGMC YFTNGTERVR LVSRSIYNRE EIVRFDSDVG EFRAVTLLGL PAAEYWNSQK
 DILERKRAAV DRVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA05758
HLA:HLA05758 DQB1*02:01:03 89 bases
 DFVYQFKGMC YFTNGTERVR LVSRSIYNRE EIVRFDSDVG EFRAVTLLGL PAAEYWNSQK
 DILERKRAAV DRVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA00623
HLA:HLA00623 DQB1*02:02 261 bases
 MSWKKALRIP GGLRAATVTL MLSMLSTPVA EGRDSPEDFV YQFKGMCYFT NGTERVRLVS
 RSIYNREEIV RFDSDVGEFR AVTLLGLPAA EYWNSQKDIL ERKRAAVDRV CRHNYQLELR
 TTLQRRVEPT VTISPSRTEA LNHHNLLVCS VTDFYPAQIK VRWFRNGQEE TAGVVSTPLI
 RNGDWTFQIL VMLEMTPQRG DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGIGGFVL
 GLIFLGLGLI IHHRSQKGLL H*   
>P1;HLA:HLA00624
HLA:HLA00624 DQB1*02:03 89 bases
 DFVYQFKGMC YFTNGTERVR LVSRSIYNRE EIVRFDSDVG EFRAVTLLGL PDAEYWNSQK
 DILERKRAAV DRVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA02136
HLA:HLA02136 DQB1*02:04 183 bases
 DFVYQFKGMC YFTNGTERVR LVSRSIYNRE EIVRFDSDVG EFRAVTLLGL PAAEYWNSQK
 DILERKRAAV DRVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVRWFRND EEETAGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQSPIT
 VEW*     
>P1;HLA:HLA02890
HLA:HLA02890 DQB1*02:05 89 bases
 DFVYQFKGMC YFTNGTERVR LVSRSIYNRE EIVRFDSDVG EFRAVTLLGL PAAEYWNSQK
 DILERKRAAV DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA00625
HLA:HLA00625 DQB1*03:01:01 261 bases
 MSWKKALRIP GGLRAATVTL MLAMLSTPVA EGRDSPEDFV YQFKAMCYFT NGTERVRYVT
 RYIYNREEYA RFDSDVEVYR AVTPLGPPDA EYWNSQKEVL ERTRAELDTV CRHNYQLELR
 TTLQRRVEPT VTISPSRTEA LNHHNLLVCS VTDFYPAQIK VRWFRNDQEE TTGVVSTPLI
 RNGDWTFQIL VMLEMTPQHG DVYTCHVEHP SLQNPITVEW RAQSESAQSK MLSGIGGFVL
 GLIFLGLGLI IHHRSQKGLL H*   
>P1;HLA:HLA00626
HLA:HLA00626 DQB1*03:01:02 86 bases
 YQFKAMCYFT NGTERVRYVT RYIYNREEYA RFDSDVEVYR AVTPLGPPDA EYWNSQKEVL
 ERTRAELDTV CRHNYQLELR TTLQRR*   
>P1;HLA:HLA02688
HLA:HLA02688 DQB1*03:01:03 89 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVE VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA03175
HLA:HLA03175 DQB1*03:01:04 183 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVE VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVRWFRND QEETTGVVST PLIRNGDWTF QILVMLEMTP QHGDVYTCHV EHPSLQNPIT
 VEW*     
>P1;HLA:HLA05773
HLA:HLA05773 DQB1*03:01:05 183 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVE VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVRWFRND QEETTGVVST PLIRNGDWTF QILVMLEMTP QHGDVYTCHV EHPSLQNPIT
 VEW*     
>P1;HLA:HLA00627
HLA:HLA00627 DQB1*03:02:01 261 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVA EGRDSPEDFV YQFKGMCYFT NGTERVRLVT
 RYIYNREEYA RFDSDVGVYR AVTPLGPPAA EYWNSQKEVL ERTRAELDTV CRHNYQLELR
 TTLQRRVEPT VTISPSRTEA LNHHNLLVCS VTDFYPAQIK VRWFRNDQEE TTGVVSTPLI
 RNGDWTFQIL VMLEMTPQRG DVYTCHVEHP SLQNPIIVEW RAQSESAQSK MLSGIGGFVL
 GLIFLGLGLI IHHRSQKGLL H*   
>P1;HLA:HLA01770
HLA:HLA01770 DQB1*03:02:02 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PAAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA02625
HLA:HLA02625 DQB1*03:02:03 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PAAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA02722
HLA:HLA02722 DQB1*03:02:04 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PAAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA05108
HLA:HLA05108 DQB1*03:02:05 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PAAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA00629
HLA:HLA00629 DQB1*03:03:02 261 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVA EGRDSPEDFV YQFKGMCYFT NGTERVRLVT
 RYIYNREEYA RFDSDVGVYR AVTPLGPPDA EYWNSQKEVL ERTRAELDTV CRHNYQLELR
 TTLQRRVEPT VTISPSRTEA LNHHNLLVCS VTDFYPAQIK VRWFRNDQEE TTGVVSTPLI
 RNGDWTFQIL VMLEMTPQRG DVYTCHVEHP SLQNPIIVEW RAQSESAQSK MLSGIGGFVL
 GLIFLGLGLI IHHRSQKGLL H*   
>P1;HLA:HLA01004
HLA:HLA01004 DQB1*03:03:03 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA00630
HLA:HLA00630 DQB1*03:04 199 bases
 RDSPEDFVYQ FKAMCYFTNG TERVRYVTRY IYNREEYARF DSDVEVYRAV TPLGPPAAEY
 WNSQKEVLER TRAELDTVCR HNYQLELRTT LQRRVEPTVT ISPSRTEALN HHNLLVCSVT
 DFYPAQIKVR WFRNDQEETT GVVSTPLIRN GDWTFQILVM LEMTPQHGDV YTCHVEHPSL
 QNPITVEWRA QSESAQSKM*    
>P1;HLA:HLA00631
HLA:HLA00631 DQB1*03:05:01 195 bases
 EDFVYQFKGM CYFTNGTERV RGVTRYIYNR EEYARFDSDV GVYRAVTPLG PPAAEYWNSQ
 KEVLERTRAE LDTVCRHNYQ LELRTTLQRR VEPTVTISPS RTEALNHHNL LVCSVTDFYP
 AQIKVRWFRN DQEETTGVVS TPLIRNGDWT FQILVMLEMT PQRGDVYTCH VEHPSLQNPI
 IVEWRAQSES AQSKM*    
>P1;HLA:HLA01443
HLA:HLA01443 DQB1*03:05:02 89 bases
 DFVYQFKGMC YFTNGTERVR GVTRYIYNRE EYARFDSDVG VYRAVTPLGP PAAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA01744
HLA:HLA01744 DQB1*03:05:03 89 bases
 DFVYQFKGMC YFTNGTERVR GVTRYIYNRE EYARFDSDVG VYRAVTPLGP PAAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA02497
HLA:HLA02497 DQB1*03:05:04 89 bases
 DFVYQFKGMC YFTNGTERVR GVTRYIYNRE EYARFDSDVG VYRAVTPLGP PAAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA00632
HLA:HLA00632 DQB1*03:06 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PDAEYWNSQK
 DILEEDRASV DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA00633
HLA:HLA00633 DQB1*03:07 90 bases
 EDFVYQFKGM CYFTNGTERV RLVTRYIYNR EEYARFDSDV GVYRVVTPLG PPAAEYWNSQ
 KEVLERTRAE LDTVCRHNYQ LELRTTLQRR *  
>P1;HLA:HLA00634
HLA:HLA00634 DQB1*03:08 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PAAEYWNSQK
 EVLEGTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA00635
HLA:HLA00635 DQB1*03:09 228 bases
 RDSPEDFVYQ FKAMCYFTNG TERVRYVTRY IYNREEYARF DSDVEVYRAV TPLGPPDAEY
 WNSQKEVLER TRAELDTVCR HNYQLELRTT LQRRVEPTVT ISPSRTEALN HHNLLVCSVT
 DFYPAQIKVR WFRNDQEETT GVVSTPLIRN GDWTFQILVM LEMTPQHAVY TCHVEHPSLQ
 NPITVEWRAQ SESAQSKMLS GIGGFVLGLI FLGLGLIIHH RSQKGLLH* 
>P1;HLA:HLA01164
HLA:HLA01164 DQB1*03:10 229 bases
 RDSPEDFVYQ FKAMCYFTNG TERVRYVTRY IYNREEYARF DSDVGVYRAV TPLGPPDAEY
 WNSQKEVLER TRAELDTVCR HNYQLELRTT LQRRVEPTVT ISPSRTEALN HHNLLVCSVT
 DFYPAQIKVR WFRNDQEETT GVVSTPLIRN GDWTFQILVM LEMTPQHGDV YTCHVEHPSL
 QNPITVEWRA QSESAQSKML SGIGGFVLGL IFLGLGLIIH HRSQKGLLH* 
>P1;HLA:HLA01538
HLA:HLA01538 DQB1*03:11 89 bases
 DFVYQFKGLC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PAAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA01574
HLA:HLA01574 DQB1*03:12 89 bases
 DFVYQFKAMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA01589
HLA:HLA01589 DQB1*03:13 89 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVE VYRAVTPLGP PDAEYWNSQK
 EDLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA02026
HLA:HLA02026 DQB1*03:14 89 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVG VYRAVTPLGP PAAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA02029
HLA:HLA02029 DQB1*03:15 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PDAEYWNRQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA02208
HLA:HLA02208 DQB1*03:16 89 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVE VYRAVTPLGQ PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA02323
HLA:HLA02323 DQB1*03:17 89 bases
 DFVYQFKGMC YFTNGTERVR GVTRYIYNRE EYARFDSDVG VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA02372
HLA:HLA02372 DQB1*03:18 89 bases
 DFVYQFKGMC YFTNGTERVR LLTRYIYNRE EYARFDSDVG VYRAVTPLGP PAAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA02690
HLA:HLA02690 DQB1*03:19 183 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVE VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVRWFRND QEETTGVVST PLIRNGDWTF QILVMLEMTP QHGDVYTCHV EHPSLQNPII
 VEW*     
>P1;HLA:HLA02887
HLA:HLA02887 DQB1*03:20 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYTRFDSDVG VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA03174
HLA:HLA03174 DQB1*03:21 183 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVE VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVRWFWND QEETTGVVST PLIRNGDWTF QILVMLEMTP QHGDVYTCHV EHPSLQNPIT
 VEW*     
>P1;HLA:HLA03295
HLA:HLA03295 DQB1*03:22 183 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVE VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVQWFRND QEETTGVVST PLIRNGDWTF QILVMLEMTP QHGDVYTCHV EHPSLQNPIT
 VEW*     
>P1;HLA:HLA03451
HLA:HLA03451 DQB1*03:23 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA03596
HLA:HLA03596 DQB1*03:24 183 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVE VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVRWFRND QEETTGVVST PLIRNGDWTF QILVMLEMTP QHGDIYTCHV EHPSLQNPIT
 VEW*     
>P1;HLA:HLA03745
HLA:HLA03745 DQB1*03:25 183 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGR LDAEYWNSQK
 DILEEDRASV DTVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVRWFRND QEETTGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQNPII
 VEW*     
>P1;HLA:HLA04356
HLA:HLA04356 DQB1*03:26 89 bases
 DFVYQFKGLC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA05374
HLA:HLA05374 DQB1*03:27 89 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVE VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNHQL ELRTTLQRR*   
>P1;HLA:HLA05767
HLA:HLA05767 DQB1*03:28 183 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVE VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DAVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVRWFRND QEETTGVVST PLIRNGDWTF QILVMLEMTP QHGDVYTCHV EHPSLQNPIT
 VEW*     
>P1;HLA:HLA05771
HLA:HLA05771 DQB1*03:29 183 bases
 DFVYQFKAMC YFTNGTERVR YVTRYIYNRE EYARFDSDVE VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVRWFRND QEETTGVVST PLIRNGDWTF QILVMLEMTP QHGDVYTCHV EHPSLQSPIT
 VEW*     
>P1;HLA:HLA05774
HLA:HLA05774 DQB1*03:30 183 bases
 DFVFQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVRWFRND QEETTGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQNPII
 VEW*     
>P1;HLA:HLA05761
HLA:HLA05761 DQB1*03:31 205 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGP PDAEYWNSQK
 EVLERTRAEL DTVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL ICSVTDFYPA
 QIKVRWFRND QEETTGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQNPII
 VEWRAQSESA QSKMLSGIGG FVLGL*   
>P1;HLA:HLA00636
HLA:HLA00636 DQB1*04:01:01 261 bases
 MSWKKALRIP GGLRVATVTL MLAMLSAPVA EGRDSPEDFV FQFKGMCYFT NGTELVRGVT
 RYIYNREEYA RFDSDVGVYR AVTPLGRLDA EYWNSQKDIL EEDRASVDTV CRHNYQLELR
 TTLQRRVEPT VTISPSRTEA LNHHNLLVCS VTDFYPAQIK VRWFRNDQEE TTGVVSTPLI
 RNGDWTFQIL VMLEMTPQRG DVYTCHVEHP SLQNPIIVEW RAQSESAQSK MLSGIGGFVL
 GLIFLGLGLI IHHRSQKGLL H*   
>P1;HLA:HLA03782
HLA:HLA03782 DQB1*04:01:02 89 bases
 DFVFQFKGMC YFTNGTELVR GVTRYIYNRE EYARFDSDVG VYRAVTPLGR LDAEYWNSQK
 DILEEDRASV DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA00637
HLA:HLA00637 DQB1*04:02:01 261 bases
 MSWKKALRIP GGLRVATVTL MLAMLSTPVA EGRDSPEDFV FQFKGMCYFT NGTERVRGVT
 RYIYNREEYA RFDSDVGVYR AVTPLGRLDA EYWNSQKDIL EEDRASVDTV CRHNYQLELR
 TTLQRRVEPT VTISPSRTEA LNHHNLLVCS VTDFYPAQIK VRWFRNDQEE TTGVVSTPLI
 RNGDWTFQIL VMLEMTPQRG DVYTCHVEHP SLQNPIIVEW RAQSESAQSK MLSGIGGFVL
 GLIFLGLGLI IHHRSQKGLL H*   
>P1;HLA:HLA05770
HLA:HLA05770 DQB1*04:02:02 183 bases
 DFVFQFKGMC YFTNGTERVR GVTRYIYNRE EYARFDSDVG VYRAVTPLGR LDAEYWNSQK
 DILEEDRASV DTVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVRWFRND QEETTGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQNPII
 VEW*     
>P1;HLA:HLA03234
HLA:HLA03234 DQB1*04:03:01 89 bases
 DFVFQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGR LDAEYWNSQK
 DILEEDRASV DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA04125
HLA:HLA04125 DQB1*04:03:02 89 bases
 DFVFQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGR LDAEYWNSQK
 DILEEDRASV DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA04390
HLA:HLA04390 DQB1*04:04 89 bases
 DFVYQFKGMC YFTNGTERVR GVTRYIYNRE EYARFDSDVG VYRAVTPLGR LDAEYWNSQK
 DILEEDRASV DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA05136
HLA:HLA05136 DQB1*04:05 89 bases
 DFVYQFKGMC YFTNGTELVR GVTRYIYNRE EYARFDSDVG VYRAVTPLGR LDAEYWNSQK
 DILEEDRASV DTVCRHNYQL ELRTTLQRR*   
>P1;HLA:HLA05765
HLA:HLA05765 DQB1*04:06 183 bases
 DFVFQFKGMC YFTNGTELVR GVTRYIYNRE EYARFDSDVG VYRAVTPLGW LDAEYWNSQK
 DILEEDRASV DTVCRHNYQL ELRTTLQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPA
 QIKVRWFRND QEETTGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQNPII
 VEW*     
>P1;HLA:HLA00638
HLA:HLA00638 DQB1*05:01:01 261 bases
 MSWKKSLRIP GDLRVATVTL MLAILSSSLA EGRDSPEDFV YQFKGLCYFT NGTERVRGVT
 RHIYNREEYV RFDSDVGVYR AVTPQGRPVA EYWNSQKEVL EGARASVDRV CRHNYEVAYR
 GILQRRVEPT VTISPSRTEA LNHHNLLICS VTDFYPSQIK VRWFRNDQEE TAGVVSTPLI
 RNGDWTFQIL VMLEMTPQRG DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL
 GLIFLGLGLI IRQRSRKGLL H*   
>P1;HLA:HLA01086
HLA:HLA01086 DQB1*05:01:02 90 bases
 PEDFVYQFKG LCYFTNGTER VRGVTRHIYN REEYVRFDSD VGVYRAVTPQ GRPVAEYWNS
 QKEVLEGARA SVDRVCRHNY EVAYRGILQR *  
>P1;HLA:HLA05548
HLA:HLA05548 DQB1*05:01:03 183 bases
 DFVYQFKGLC YFTNGTERVR GVTRHIYNRE EYVRFDSDVG VYRAVTPQGR PVAEYWNSQK
 EVLEGARASV DRVCRHNYEV AYRGILQRRV EPTVTISPSR TEALNHHNLL ICSVTDFYPS
 QIKVRWFRND QEETAGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQSPIT
 VEW*     
>P1;HLA:HLA00639
HLA:HLA00639 DQB1*05:02:01 261 bases
 MSWKKSLRIP GDLRVATVTL MLAILSSSLA EGRDSPEDFV YQFKGLCYFT NGTERVRGVT
 RHIYNREEYV RFDSDVGVYR AVTPQGRPSA EYWNSQKEVL EGARASVDRV CRHNYEVAYR
 GILQRRVEPT VTISPSRTEA LNHHNLLICS VTDFYPSHIK VRWFRNDQEE TAGVVSTPLI
 RNGDWTFQIL VMLEMTPQRG DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL
 GLIFLGLGLI IRQRSRKGLL H*   
>P1;HLA:HLA01573
HLA:HLA01573 DQB1*05:02:02 85 bases
 YQFKGLCYFT NGTERVRGVT RHIYNREEYV RFDSDVGVYR AVTPQGRPSA EYWNSQKEVL
 EGARASVDRV CRHNYEVAYR GILQR*   
>P1;HLA:HLA05766
HLA:HLA05766 DQB1*05:02:03 183 bases
 DFVYQFKGLC YFTNGTERVR GVTRHIYNRE EYVRFDSDVG VYRAVTPQGR PSAEYWNSQK
 EVLEGARASV DRVCRHNYEV AYRGILQRRV EPTVTISPSR TEALNHHNLL ICSVTDFYPS
 HIKVRWFRND QEETAGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQSPIT
 VEW*     
>P1;HLA:HLA00640
HLA:HLA00640 DQB1*05:03:01 237 bases
 RDSPEDFVYQ FKGLCYFTNG TERVRGVTRH IYNREEYVRF DSDVGVYRAV TPQGRPDAEY
 WNSQKEVLEG ARASVDRVCR HNYEVAYRGI LQRRVEPTVT ISPSRTEALN HHNLLICSVT
 DFYPSQIKVR WFRNDQEETA GVVSTPLIRN GDWTFQILVM LEMTPQRGDV YTCHVEHPSL
 QSPITVEWRA QSESAQSKML SGVGGFVLGL IFLGLGLIIR QRSRKGPQGP PPAGLLH*
>P1;HLA:HLA00641
HLA:HLA00641 DQB1*05:03:02 49 bases
 TERVRGVTRH IYNREEYVRF DSDVGVYRAV TPQGRPDAEY WNSQKEVLE* 
>P1;HLA:HLA05769
HLA:HLA05769 DQB1*05:03:03 183 bases
 DFVYQFKGLC YFTNGTERVR GVTRHIYNRE EYVRFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGARASV DRVCRHNYEV AYRGILQRRV EPTVTISPSR TEALNHHNLL ICSVTDFYPS
 QIKVRWFRND QEETAGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQSPIT
 VEW*     
>P1;HLA:HLA00642
HLA:HLA00642 DQB1*05:04 74 bases
 YQFKGLCYFT NGTERVRGVT RYIYNREEYV RFDSDVGVYR AVTPQGRPSA EYWNSQKDIL
 EEDRASVDRV CRHN*    
>P1;HLA:HLA02689
HLA:HLA02689 DQB1*05:05 89 bases
 DFVYQFKGLC YFTNGTERVR GVTRHIYNRE EYARFDSDVG VYRAVTPQGR PSAEYWNSQK
 EVLEGARASV DRVCRHNYEV AYRGILQRR*   
>P1;HLA:HLA05383
HLA:HLA05383 DQB1*05:06 89 bases
 DFVYQFKGLC YFTNGTERVR GVTRHIYNRE EYVRLDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGARASV DRVCRHNYEV AYRGILQRR*   
>P1;HLA:HLA05772
HLA:HLA05772 DQB1*05:07 183 bases
 DFVYQFKGLC YFTNGTERVR GVTRHIYNRE EYVHFDSDVG VYRAVTPQGR PVAEYWNSQK
 EVLEGARASV DRVCRHNYEV AYRGILQRRV EPTVTISPSR TEALNHHNLL ICSVTDFYPS
 QIKVRWFRND QEETAGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQSPIT
 VEW*     
>P1;HLA:HLA05775
HLA:HLA05775 DQB1*05:08 183 bases
 DFVYQFKGLC YFTNGTERVR GVTRHIYNRE EYVRFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGARASV DRVCRHNYEV AYRGILQRRV EPTVTISPSR TEALNHHNLL ICSVTDFYPS
 QIKVRWFRND QEETAGVVST PLIRNGDWTF QILVMLEMTP QHGDVYTCHV EHPSLQSPIT
 VEW*     
>P1;HLA:HLA00643
HLA:HLA00643 DQB1*06:01:01 237 bases
 RDPPEDFVLQ FKAMCYFTNG TERVRYVTRY IYNREEDVRF DSDVGVYRAV TPQGRPDAEY
 WNSQKDILER TRAELDTVCR HNYEVAFRGI LQRRVEPTVT ISPSRTEALN HHNLLVCSVT
 DFYPGQIKVR WFRNDQEETA GVVSTPLIRN GDWTFQILVM LEMTPQHGDV YTCHVEHPSL
 QSPITVEWRA QSESAQNKML SGIGGFVLGL IFLGLGLIIR QRSQKGPQGP PPAGLLH*
>P1;HLA:HLA00644
HLA:HLA00644 DQB1*06:01:02 68 bases
 AMCYFTNGTE RVRYVTRYIY NREEDVRFDS DVGVYRAVTP QGRPDAEYWN SQKDILERTR
 AELDTVCR*     
>P1;HLA:HLA00645
HLA:HLA00645 DQB1*06:01:03 225 bases
 RDPPEDFVLQ FKAMCYFTNG TERVRYVTRY IYNREEDVRF DSDVGVYRAV TPQGRPDAEY
 WNSQKDILER TRAELDTVCR HNYEVAFRGI LQRRVEPTVT ISPSRTEALN HHNLLVCSVT
 DFYPGQIKVR WFRNDQEETA GVVSTPLIRN GDWTFQILVM LEMTPQHGDV YTCHVEHPSL
 QSPITVEWRA QSESAQNKML SGIGGFVLGL IFLGLGLIIR QRSQK* 
>P1;HLA:HLA03307
HLA:HLA03307 DQB1*06:01:04 89 bases
 DFVLQFKAMC YFTNGTERVR YVTRYIYNRE EDVRFDSDVG VYRAVTPQGR PDAEYWNSQK
 DILERTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA03991
HLA:HLA03991 DQB1*06:01:05 183 bases
 DFVLQFKAMC YFTNGTERVR YVTRYIYNRE EDVRFDSDVG VYRAVTPQGR PDAEYWNSQK
 DILERTRAEL DTVCRHNYEV AFRGILQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPG
 QIKVRWFRND QEETAGVVST PLIRNGDWTF QILVMLEMTP QHGDVYTCHV EHPSLQSPIT
 VEW*     
>P1;HLA:HLA05776
HLA:HLA05776 DQB1*06:01:06 183 bases
 DFVLQFKAMC YFTNGTERVR YVTRYIYNRE EDVRFDSDVG VYRAVTPQGR PDAEYWNSQK
 DILERTRAEL DTVCRHNYEV AFRGILQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPG
 QIKVRWFRND QEETAGVVST PLIRNGDWTF QILVMLEMTP QHGDVYTCHV EHPSLQSPIT
 VEW*     
>P1;HLA:HLA00646
HLA:HLA00646 DQB1*06:02:01 261 bases
 MSWKKALRIP GDLRVATVTL MLAMLSSLLA EGRDSPEDFV FQFKGMCYFT NGTERVRLVT
 RYIYNREEYA RFDSDVGVYR AVTPQGRPDA EYWNSQKEVL EGTRAELDTV CRHNYEVAFR
 GILQRRVEPT VTISPSRTEA LNHHNLLVCS VTDFYPGQIK VRWFRNDQEE TAGVVSTPLI
 RNGDWTFQIL VMLEMTPQRG DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL
 GLIFLGLGLI IRQRSQKGLL H*   
>P1;HLA:HLA03156
HLA:HLA03156 DQB1*06:02:02 89 bases
 DFVFQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA00647
HLA:HLA00647 DQB1*06:03:01 229 bases
 RDSPEDFVYQ FKGMCYFTNG TERVRLVTRH IYNREEYARF DSDVGVYRAV TPQGRPDAEY
 WNSQKEVLEG TRAELDTVCR HNYEVAFRGI LQRRVEPTVT ISPSRTEALN HHNLLVCSVT
 DFYPGQIKVR WFRNDQEETA GVVSTPLIRN GDWTFQILVM LEMTPQRGDV YTCHVEHPSL
 QSPITVEWRA QSESAQSKML SGVGGFVLGL IFLGLGLIIR QRSQKGLLH* 
>P1;HLA:HLA02638
HLA:HLA02638 DQB1*06:03:02 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA00648
HLA:HLA00648 DQB1*06:04:01 229 bases
 RDSPEDFVYQ FKGMCYFTNG TERVRLVTRH IYNREEYARF DSDVGVYRAV TPQGRPVAEY
 WNSQKEVLER TRAELDTVCR HNYEVGYRGI LQRRVEPTVT ISPSRTEALN HHNLLVCSVT
 DFYPGQIKVQ WFRNDQEETA GVVSTPLIRN GDWTFQILVM LEMTPQRGDV YTCHVEHPSL
 QSPITVEWRA QSESAQSKML SGVGGFVLGL IFLGLGLIIR QRSQKGLLH* 
>P1;HLA:HLA01005
HLA:HLA01005 DQB1*06:04:02 106 bases
 SPEDFVYQFK GMCYFTNGTE RVRLVTRHIY NREEYARFDS DVGVYRAVTP QGRPVAEYWN
 SQKEVLERTR AELDTVCRHN YEVGYRGILQ RRVEPTVTIS PSRTEA* 
>P1;HLA:HLA02602
HLA:HLA02602 DQB1*06:04:03 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PVAEYWNSQK
 EVLERTRAEL DTVCRHNYEV GYRGILQRR*   
>P1;HLA:HLA00649
HLA:HLA00649 DQB1*06:05:01 108 bases
 RDSPEDFVYQ FKGLCYFTNG TERVRLVTRY IYNREEYARF DSDVGVYRAV TPQGRPVAEY
 WNSQKEVLER TRAELDTVCR HNYEVGYRGI LQRRVEPTVT ISPSRTEA* 
>P1;HLA:HLA00650
HLA:HLA00650 DQB1*06:05:02 57 bases
 TERVRLVTRY IYNREEYARF DSDVGVYRAV TPQGRPVAEY WNSQKEVLER TRAELDT*
>P1;HLA:HLA00651
HLA:HLA00651 DQB1*06:06 58 bases
 TERVRLVTRY IYNREEYARF DSDVGVYRAV TPQGRPVAEY WNSQKEVLER TRAAVDRV*
>P1;HLA:HLA00652
HLA:HLA00652 DQB1*06:07:01 82 bases
 YQFKGMCYFT NGTERVRLVT RHIYNREEYA RFDSDVGVYR AVTPQGRPDA EYWNSQKEVL
 ERTRAELDTV CRHNYEVGYR GI*   
>P1;HLA:HLA05768
HLA:HLA05768 DQB1*06:07:02 183 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLERTRAEL DTVCRHNYEV GYRGILQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPG
 QIKVQWFRND QEETAGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQSPIT
 VEW*     
>P1;HLA:HLA00653
HLA:HLA00653 DQB1*06:08:01 82 bases
 YQFKGMCYFT NGTERVRLVT RHIYNREEYA RFDSDVGVYR AVTPQGRPVA EYWNSQKEVL
 EGTRAELDTV CRHNYEVAFR GI*   
>P1;HLA:HLA02609
HLA:HLA02609 DQB1*06:08:02 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PVAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA00654
HLA:HLA00654 DQB1*06:09 229 bases
 RDSPEDFVYQ FKGMCYFTNG TERVRLVTRY IYNREEYARF DSDVGVYRAV TPQGRPVAEY
 WNSQKEVLER TRAELDTVCR HNYEVGYRGI LQRRVEPTVT ISPSRTEALN HHNLLVCSVT
 DFYPGQIKVQ WFRNDQEETA GVVSTPLIRN GDWTFQILVM LEMTPQRGDV YTCHVEHPSL
 QSPITVEWRA QSESAQSKML SGVGGFVLGL IFLGLGLIIR QRSQKGLLH* 
>P1;HLA:HLA00655
HLA:HLA00655 DQB1*06:10 89 bases
 DFVFQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPQGR PSAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA00656
HLA:HLA00656 DQB1*06:11:01 85 bases
 YQFKGMCYFT NGTERVRLVT RYIYNREEYA RFDSDVGVYR AVTPQGRPDA EYWNSQKEVL
 EGTRAELDTV CRHNYEVAFR GILQR*   
>P1;HLA:HLA00657
HLA:HLA00657 DQB1*06:11:02 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA00658
HLA:HLA00658 DQB1*06:12 261 bases
 MSWKKALRIP GDLRVATVTL MLAMLSSLLA EGRDSPEDFV YQFKGMCYFT NGTERVRLVT
 RYIYNREEYA RFDSDVGVYR AVTPQGRPVA EYWNSQKEVL EGTRAELDTV CRHNYEVGYR
 GILQRRVEPT VTISPSRTEA LNHHNLLVCS VTDFYPGQIK VQWFRNDQEE TAGVVSTPLI
 RNGDWTFQIL VMLEMTPQRG DVYTCHVEHP SLQSPITVEW RAQSESAQSK MLSGVGGFVL
 GLIFLGLGLI IRQRSQKGLL H*   
>P1;HLA:HLA00659
HLA:HLA00659 DQB1*06:13 85 bases
 EDFVFQFKGM CYFTNGTERV RLVTRYIYNR EEYARFDSDV GVYRAVTPQG RPVAEYWNSQ
 KEVLEGTRAE LDTVCRHNYE VAFRG*   
>P1;HLA:HLA00660
HLA:HLA00660 DQB1*06:14:01 86 bases
 FQFKGMCYFT NGTERVRLVT RHIYNREEYA RFDSDVGVYR AVTPQGRPDA EYWNSQKEVL
 EGTRAELDTV CRHNYEVAFR GILQRR*   
>P1;HLA:HLA03431
HLA:HLA03431 DQB1*06:14:02 89 bases
 DFVFQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA00661
HLA:HLA00661 DQB1*06:15 89 bases
 DFVFQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLERTRAEL DTVCRHNYEV GYRGILQRR*   
>P1;HLA:HLA01006
HLA:HLA01006 DQB1*06:16 89 bases
 DFVFQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPQGR PDAENWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA01175
HLA:HLA01175 DQB1*06:17 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PVAEYWNSQK
 EVLEGARAEL DTVCRHNYEV GYRGILQRR*   
>P1;HLA:HLA01446
HLA:HLA01446 DQB1*06:18 85 bases
 YQFKGMCYFT NGTERVRLVT RYIYNREEYA RFDSDVGVYR AVTPQGRPVA EYWNSQKEVL
 ERTRAELDTV CRHNYEVAFR GILQR*   
>P1;HLA:HLA01460
HLA:HLA01460 DQB1*06:19 89 bases
 DFVFQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPLGR PDAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA01612
HLA:HLA01612 DQB1*06:20 80 bases
 FQFKGLCYFT NGTERVRLVT RYIYNREEYA RFDSDVGVYR AVTPQGRPDA EYWNSQKEVL
 EGTRAELDTV CRHNYEVAFR *   
>P1;HLA:HLA01776
HLA:HLA01776 DQB1*06:21 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PVAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV GYRGILQRR*   
>P1;HLA:HLA01967
HLA:HLA01967 DQB1*06:22 89 bases
 DFVFQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPQGR PVAEYWNSQK
 EVLERTRAEL DTVCRHNYEV GYRGILQRR*   
>P1;HLA:HLA02005
HLA:HLA02005 DQB1*06:23 89 bases
 DFVFQFKGMC YFTNGTERVR GVTRYIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA02182
HLA:HLA02182 DQB1*06:24 89 bases
 DFVFQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGARAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA02195
HLA:HLA02195 DQB1*06:25 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PSAEYWNSQK
 EVLERTRAEL DTVCRHNYEV GYRGILQRR*   
>P1;HLA:HLA02221
HLA:HLA02221 DQB1*06:26N 24 bases
 DFVYQFKGMC YFTNGTERVR LVTX*   
>P1;HLA:HLA02291
HLA:HLA02291 DQB1*06:27 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PVAEYWNSQK
 EVLERTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA02453
HLA:HLA02453 DQB1*06:28 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYVRFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA02696
HLA:HLA02696 DQB1*06:29 89 bases
 DFVFQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPQGP PAAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA02740
HLA:HLA02740 DQB1*06:30 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGARAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA02917
HLA:HLA02917 DQB1*06:31 89 bases
 DFVYQFKGLC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA02950
HLA:HLA02950 DQB1*06:32 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLERTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA02970
HLA:HLA02970 DQB1*06:33 89 bases
 DFVFQLKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA03114
HLA:HLA03114 DQB1*06:34 185 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PVAEYWNSQK
 EVLERTRAEL DTVCRHNYEV GYRGILQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPG
 QIKVQWFRND QEETAGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQSPIT
 VEWWA*     
>P1;HLA:HLA03809
HLA:HLA03809 DQB1*06:35 89 bases
 DFVLQFKAMC YFTNGTERVR YVTRYIYNRE EDVRFDSDVE VYRAVTPLGR PDAEYWNSQK
 DILERTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA03979
HLA:HLA03979 DQB1*06:36 220 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PVAEYWNSQK
 EVLERTRAEL DTVCRHNYEV GYRGILQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPG
 QIKVQWFRND QEETAGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQSPIT
 AEWRAQSESA QSKMLSGVGG FVLGLIFLGL GLIIRQRSQK * 
>P1;HLA:HLA04119
HLA:HLA04119 DQB1*06:37 89 bases
 DFVFQFKGMC YFTNGTERVR LVTRYIYNRE EYARFDSDVG VYRAVTPQGR PDAEYWKSQK
 EVLERTRAEL DTVCRHNYEV AFRGILQRR*   
>P1;HLA:HLA04357
HLA:HLA04357 DQB1*06:38 183 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PVAEYWNSQK
 EVLERTRAEL DTVCRHNYEV GYRGILQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPG
 QIKVQWFQND QEETAGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQSPIT
 VEW*     
>P1;HLA:HLA04358
HLA:HLA04358 DQB1*06:39 183 bases
 DFVYQFKGMC YFTNGTERVR LVTRHIYNRE EYARFDSDVG VYRAVTPQGR PVAEYWNSQK
 EVLERTRAEL DTVCRHNYEV GYRGILQRRV EPTVTISPSR TEALNHHNLL VCSVTDFYPG
 QIKVRWFRND QEETAGVVST PLIRNGDWTF QILVMLEMTP QRGDVYTCHV EHPSLQSPIT
 VEW*     
>P1;HLA:HLA04737
HLA:HLA04737 DQB1*06:40 89 bases
 DFVYQFKGMC YFTNGTERVR LVTRHVYNRE EYARFDSDVG VYRAVTPQGR PDAEYWNSQK
 EVLEGTRAEL DTVCRHNYEV AFRGILQRR*   
