>DL;HLA:HLA00622
HLA:HLA00622 DQB1*02:01:01 786 bases
 ATGTCTTGGA AAAAGGCTTT GCGGATCCCC GGAGGCCTTC GGGCAGCAAC TGTGACCTTG
 ATGCTGTCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG TCTTGTGAGC
 AGAAGCATCT ATAACCGAGA AGAGATCGTG CGCTTCGACA GCGACGTGGG GGAGTTCCGG
 GCGGTGACGC TGCTGGGGCT GCCTGCCGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGGAAAC GGGCGGCGGT GGACAGGGTG TGCAGACACA ACTACCAGTT GGAGCTCCGC
 ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCG GTGACAGATT TCTATCCAGC CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC CCCCCTTATT
 AGGAATGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC CGTGGAGTGG
 CGGGCTCAAT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTCGGGCT GGGCCTTATC ATCCATCACA GGAGTCAGAA AGGGCTCCTG
 CACTGA*     
>DL;HLA:HLA01934
HLA:HLA01934 DQB1*02:01:02 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACA GAGCGCGTGC
 GTCTTGTGAG CAGAAGCATC TATAACCGAG AAGAGATCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTTCCG GGCGGTGACG CTGCTGGGGC TGCCTGCCGC CGAGTATTGG AACAGCCAGA
 AGGACATCCT GGAGAGGAAA CGGGCGGCGG TGGACAGGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA05758
HLA:HLA05758 DQB1*02:01:03 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACA GAGCGCGTGC
 GTCTTGTGAG CAGAAGCATC TATAACCGAG AAGAGATCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTTCCG GGCAGTGACG CTGCTGGGGC TGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGAAA CGGGCGGCGG TGGACAGGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA05923
HLA:HLA05923 DQB1*02:01:04 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACA GAGCGCGTGC
 GTCTTGTGAG CAGAAGCATC TATAACCGAG AAGAGATCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTTCCG GGCGGTGACG CTGCTGGGGC TGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAAAGGAAA CGGGCGGCGG TGGACAGGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAGCTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA08310
HLA:HLA08310 DQB1*02:01:05 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACA GAGCGCGTGC
 GTCTTGTGAG CAGAAGCATC TATAACCGAG AAGAGATCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTTCCG GGCGGTGACG CTGCTGGGGC TGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGAAA CGGGCAGCGG TGGACAGGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAGCTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA00623
HLA:HLA00623 DQB1*02:02 786 bases
 ATGTCTTGGA AAAAGGCTTT GCGGATCCCC GGAGGCCTTC GGGCAGCAAC TGTGACCTTG
 ATGCTGTCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG TCTTGTGAGC
 AGAAGCATCT ATAACCGAGA AGAGATCGTG CGCTTCGACA GCGACGTGGG GGAGTTCCGG
 GCGGTGACGC TGCTGGGGCT GCCTGCCGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGGAAAC GGGCGGCGGT GGACAGGGTG TGCAGACACA ACTACCAGTT GGAGCTCCGC
 ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCG GTGACAGATT TCTATCCAGC CCAGATCAAA
 GTCCGGTGGT TTCGGAATGG CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC CCCCCTTATT
 AGGAATGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC CGTGGAGTGG
 CGGGCTCAAT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTCGGGCT GGGCCTTATC ATCCATCACA GGAGTCAGAA AGGGCTCCTG
 CACTGA*     
>DL;HLA:HLA00624
HLA:HLA00624 DQB1*02:03 269 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACA GAGCGCGTGC
 GTCTTGTGAG CAGAAGCATC TATAACCGAG AAGAGATCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTTCCG GGCGGTGACG CTGCTGGGGC TGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGAAA CGGGCGGCGG TGGACAGGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGA*   
>DL;HLA:HLA02136
HLA:HLA02136 DQB1*02:04 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACA GAGCGCGTGC
 GTCTTGTGAG CAGAAGCATC TATAACCGAG AAGAGATCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTTCCG GGCGGTGACG CTGCTGGGGC TGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGAAA CGGGCGGCGG TGGACAGGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACGAGGAGGA GACAGCTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA02890
HLA:HLA02890 DQB1*02:05 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACA GAGCGCGTGC
 GTCTTGTGAG CAGAAGCATC TATAACCGAG AAGAGATCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTTCCG GGCGGTGACG CTGCTGGGGC TGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGAAA CGGGCGGCGG TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA06141
HLA:HLA06141 DQB1*02:06 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACA GAGCGCGTGC
 GTCTTGTGAG CAGAAGCATC TATAACCGAG AAGAGATCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTTCCG GGCGGTGACG CTGCTGGGGC TGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGAAA CGGGCGGCGG TGGACAGGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG GCCAGGAGGA GACAGCTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACATCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA08083
HLA:HLA08083 DQB1*02:07 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACA GAGCGCGTGC
 GTCTTGTGAG CAGAAGCATC TATAACCGAG AAGAGATCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTTCCG GGCGGTGACG CTGCTGGGGC TGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGAAA CGGGCGGCGG TGGACAGGGT GTGCAGACCC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAGCTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA00625
HLA:HLA00625 DQB1*03:01:01:01 786 bases
 ATGTCTTGGA AAAAGGCTTT GCGGATCCCC GGAGGCCTTC GGGCAGCAAC TGTTACCTTG
 ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGCCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TTATGTGACC
 AGATACATCT ATAACCGAGA GGAGTACGCA CGCTTCGACA GCGACGTGGA GGTGTACCGG
 GCGGTGACGC CGCTGGGGCC GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGAGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACCAGTT GGAGCTCCGC
 ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCA GTGACAGATT TCTATCCAGC CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA CCAGGAGGAG ACAACCGGCG TTGTGTCCAC CCCCCTTATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCATGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA ACCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTCATCT TCCTCGGGCT GGGCCTTATT ATCCATCACA GGAGTCAGAA AGGGCTCCTG
 CACTGA*     
>DL;HLA:HLA06613
HLA:HLA06613 DQB1*03:01:01:02 786 bases
 ATGTCTTGGA AAAAGGCTTT GCGGATCCCC GGAGGCCTTC GGGCAGCAAC TGTTACCTTG
 ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGCCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TTATGTGACC
 AGATACATCT ATAACCGAGA GGAGTACGCA CGCTTCGACA GCGACGTGGA GGTGTACCGG
 GCGGTGACGC CGCTGGGGCC GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGAGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACCAGTT GGAGCTCCGC
 ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCA GTGACAGATT TCTATCCAGC CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA CCAGGAGGAG ACAACCGGCG TTGTGTCCAC CCCCCTTATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCATGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA ACCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTCATCT TCCTCGGGCT GGGCCTTATT ATCCATCACA GGAGTCAGAA AGGGCTCCTG
 CACTGA*     
>DL;HLA:HLA06616
HLA:HLA06616 DQB1*03:01:01:03 786 bases
 ATGTCTTGGA AAAAGGCTTT GCGGATCCCC GGAGGCCTTC GGGCAGCAAC TGTTACCTTG
 ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGCCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TTATGTGACC
 AGATACATCT ATAACCGAGA GGAGTACGCA CGCTTCGACA GCGACGTGGA GGTGTACCGG
 GCGGTGACGC CGCTGGGGCC GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGAGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACCAGTT GGAGCTCCGC
 ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCA GTGACAGATT TCTATCCAGC CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA CCAGGAGGAG ACAACCGGCG TTGTGTCCAC CCCCCTTATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCATGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA ACCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTCATCT TCCTCGGGCT GGGCCTTATT ATCCATCACA GGAGTCAGAA AGGGCTCCTG
 CACTGA*     
>DL;HLA:HLA00626
HLA:HLA00626 DQB1*03:01:02 261 bases
 TGTACCAGTT TAAGGCCATG TGCTACTTCA CCAACGGGAC GGAGCGCGTG CGTTATGTGA
 CCAGATACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA CAGCGACGTG GAGGTGTACC
 GGGCGGTGAC GCCGCTGGGG CCGCCTGACG CCGAGTACTG GAACAGCCAG AAGGAAGTCC
 TGGAGAGGAC CCGGGCGGAG TTGGACACGG TGTGCAGACA CAACTACCAG TTGGAGCTCC
 GCACGACCTT GCAGCGGCGA G*   
>DL;HLA:HLA02688
HLA:HLA02688 DQB1*03:01:03 270 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CCCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA03175
HLA:HLA03175 DQB1*03:01:04 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA05773
HLA:HLA05773 DQB1*03:01:05 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGT GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA06142
HLA:HLA06142 DQB1*03:01:06 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGTAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA00627
HLA:HLA00627 DQB1*03:02:01 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCT GGAGGCCTTC GGGTAGCAAC TGTGACCTTG
 ATGCTGGCGA TGCTGAGCAC CCCGGTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TCTTGTGACC
 AGATACATCT ATAACCGAGA GGAGTACGCA CGCTTCGACA GCGACGTGGG GGTGTATCGG
 GCGGTGACGC CGCTGGGGCC GCCTGCCGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGAGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACCAGTT GGAGCTCCGC
 ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCA GTGACAGATT TCTATCCAGC CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA CCAGGAGGAG ACAACTGGCG TTGTGTCCAC CCCCCTTATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA ACCCCATCAT CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTCGGGCT GGGCCTTATT ATCCATCACA GGAGTCAGAA AGGGCTCCTG
 CACTGA*     
>DL;HLA:HLA01770
HLA:HLA01770 DQB1*03:02:02 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGC TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA02625
HLA:HLA02625 DQB1*03:02:03 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA02722
HLA:HLA02722 DQB1*03:02:04 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAATCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA05108
HLA:HLA05108 DQB1*03:02:05 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA00629
HLA:HLA00629 DQB1*03:03:02:01 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCT GGAGGCCTTC GGGTAGCAAC TGTGACCTTG
 ATGCTGGCGA TGCTGAGCAC CCCGGTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TCTTGTGACC
 AGATACATCT ATAACCGAGA GGAGTACGCA CGCTTCGACA GCGACGTGGG GGTGTATCGG
 GCGGTGACGC CGCTGGGGCC GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGAGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACCAGTT GGAGCTCCGC
 ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCA GTGACAGATT TCTATCCAGC CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA CCAGGAGGAG ACAACTGGCG TTGTGTCCAC CCCCCTTATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA ACCCCATCAT CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTCGGGCT GGGCCTTATT ATCCATCACA GGAGTCAGAA AGGGCTCCTG
 CACTGA*     
>DL;HLA:HLA06620
HLA:HLA06620 DQB1*03:03:02:02 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCT GGAGGCCTTC GGGTAGCAAC TGTGACCTTG
 ATGCTGGCGA TGCTGAGCAC CCCGGTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TCTTGTGACC
 AGATACATCT ATAACCGAGA GGAGTACGCA CGCTTCGACA GCGACGTGGG GGTGTATCGG
 GCGGTGACGC CGCTGGGGCC GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGAGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACCAGTT GGAGCTCCGC
 ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCA GTGACAGATT TCTATCCAGC CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA CCAGGAGGAG ACAACTGGCG TTGTGTCCAC CCCCCTTATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA ACCCCATCAT CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTCGGGCT GGGCCTTATT ATCCATCACA GGAGTCAGAA AGGGCTCCTG
 CACTGA*     
>DL;HLA:HLA06623
HLA:HLA06623 DQB1*03:03:02:03 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCT GGAGGCCTTC GGGTAGCAAC TGTGACCTTG
 ATGCTGGCGA TGCTGAGCAC CCCGGTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TCTTGTGACC
 AGATACATCT ATAACCGAGA GGAGTACGCA CGCTTCGACA GCGACGTGGG GGTGTATCGG
 GCGGTGACGC CGCTGGGGCC GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGAGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACCAGTT GGAGCTCCGC
 ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCA GTGACAGATT TCTATCCAGC CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA CCAGGAGGAG ACAACTGGCG TTGTGTCCAC CCCCCTTATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA ACCCCATCAT CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTCGGGCT GGGCCTTATT ATCCATCACA GGAGTCAGAA AGGGCTCCTG
 CACTGA*     
>DL;HLA:HLA01004
HLA:HLA01004 DQB1*03:03:03 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA06822
HLA:HLA06822 DQB1*03:03:04 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA00630
HLA:HLA00630 DQB1*03:04 597 bases
 AGAGACTCTC CCGAGGATTT CGTGTACCAG TTTAAGGCCA TGTGCTACTT CACCAACGGG
 ACGGAGCGCG TGCGTTATGT GACCAGATAC ATCTATAACC GAGAGGAGTA CGCACGCTTC
 GACAGCGACG TGGAGGTGTA CCGGGCGGTG ACGCCGCTGG GGCCGCCTGC CGCCGAGTAC
 TGGAACAGCC AGAAGGAAGT CCTGGAGAGG ACCCGGGCGG AGTTGGACAC GGTGTGCAGA
 CACAACTACC AGTTGGAGCT CCGCACGACC TTGCAGCGGC GAGTGGAGCC CACAGTGACC
 ATCTCCCCAT CCAGGACAGA GGCCCTCAAC CACCACAACC TGCTGGTCTG CTCAGTGACA
 GATTTCTATC CAGCCCAGAT CAAAGTCCGG TGGTTTCGGA ATGACCAGGA GGAGACAACC
 GGCGTTGTGT CCACCCCCCT TATTAGGAAC GGTGACTGGA CCTTCCAGAT CCTGGTGATG
 CTGGAAATGA CTCCCCAGCA TGGAGACGTC TACACCTGCC ACGTGGAGCA CCCCAGCCTC
 CAGAACCCCA TCACCGTGGA GTGGCGGGCT CAGTCTGAAT CTGCCCAGAG CAAGATG*
>DL;HLA:HLA00631
HLA:HLA00631 DQB1*03:05:01 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCT GGAGGCCTTC GGGTAGCAAC TGTGACCTTG
 ATGCTGGCGA TGCTGAGCAC CCCGGTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACCG AGCGCGTGCG GGGTGTGACC
 AGATACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA GCGACGTGGG GGTGTATCGG
 GCGGTGACGC CGCTGGGGCC GCCTGCCGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGAGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACCAGTT GGAGCTCCGC
 ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCA GTGACAGATT TCTATCCAGC CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA CCAGGAGGAG ACAACTGGCG TTGTGTCCAC CCCCCTTATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA ACCCCATCAT CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTCGGGCT GGGCCTTATT ATCCATCACA GGAGTCAGAA AGGGCTCCTG
 CACTGA*     
>DL;HLA:HLA01443
HLA:HLA01443 DQB1*03:05:02 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA01744
HLA:HLA01744 DQB1*03:05:03 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACC GAGCGCGTGC
 GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA02497
HLA:HLA02497 DQB1*03:05:04 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA00632
HLA:HLA00632 DQB1*03:06 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AATAGCCAGA
 AGGACATCCT GGAGGAGGAC CGGGCGTCGG TGGACACCGT ATGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA00633
HLA:HLA00633 DQB1*03:07 270 bases
 GAGGATTTCG TGTACCAGTT TAAGGGCATG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCTTGTGA CCAGATACAT CTATAACCGA GAGGAGTACG CACGCTTCGA CAGCGACGTG
 GGGGTGTATC GGGTGGTGAC GCCGCTGGGG CCGCCTGCCG CCGAGTACTG GAACAGCCAG
 AAGGAAGTCC TGGAGAGGAC CCGGGCGGAG TTGGACACGG TGTGCAGACA CAACTACCAG
 TTGGAGCTCC GCACGACCTT GCAGCGGCGA *  
>DL;HLA:HLA00634
HLA:HLA00634 DQB1*03:08 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA00635
HLA:HLA00635 DQB1*03:09 687 bases
 AGAGACTCTC CCGAGGATTT CGTGTACCAG TTTAAGGCCA TGTGCTACTT CACCAACGGG
 ACGGAGCGCG TGCGTTATGT GACCAGATAC ATCTATAACC GAGAGGAGTA CGCACGCTTC
 GACAGCGACG TGGAGGTGTA CCGGGCGGTG ACGCCGCTGG GGCCGCCTGA CGCCGAGTAC
 TGGAACAGCC AGAAGGAAGT CCTGGAGAGG ACCCGGGCGG AGTTGGACAC GGTGTGCAGA
 CACAACTACC AGTTGGAGCT CCGCACGACC TTGCAGCGGC GAGTGGAGCC CACAGTGACC
 ATCTCCCCAT CCAGGACAGA GGCCCTCAAC CACCACAACC TGCTGGTCTG CTCAGTGACA
 GATTTCTATC CAGCCCAGAT CAAAGTCCGG TGGTTTCGGA ATGACCAGGA GGAGACAACC
 GGCGTTGTGT CCACCCCCCT TATTAGGAAC GGTGACTGGA CCTTCCAGAT CCTGGTGATG
 CTGGAAATGA CTCCCCAGCA TGCCGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG
 AACCCCATCA CCGTGGAGTG GCGGGCTCAG TCTGAATCTG CCCAGAGCAA GATGCTGAGT
 GGCATTGGAG GCTTCGTGCT GGGGCTCATC TTCCTCGGGC TGGGCCTTAT TATCCATCAC
 AGGAGTCAGA AAGGGCTCCT GCACTGA*   
>DL;HLA:HLA01164
HLA:HLA01164 DQB1*03:10 690 bases
 AGAGACTCTC CCGAGGATTT CGTGTACCAG TTTAAGGCCA TGTGCTACTT CACCAACGGG
 ACGGAGCGCG TGCGTTATGT GACCAGATAC ATCTATAACC GAGAGGAGTA CGCACGCTTC
 GACAGCGACG TGGGGGTGTA TCGGGCGGTG ACGCCGCTGG GGCCGCCTGA CGCCGAGTAC
 TGGAACAGCC AGAAGGAAGT CCTGGAGAGG ACCCGGGCGG AGTTGGACAC GGTGTGCAGA
 CACAACTACC AGTTGGAGCT CCGCACGACC TTGCAGCGGC GAGTGGAGCC CACAGTGACC
 ATCTCCCCAT CCAGGACAGA GGCCCTCAAC CACCACAACC TGCTGGTCTG CTCAGTGACA
 GATTTCTATC CAGCCCAGAT CAAAGTCCGG TGGTTTCGGA ATGACCAGGA GGAGACAACC
 GGCGTTGTGT CCACCCCCCT TATTAGGAAC GGTGACTGGA CCTTCCAGAT CCTGGTGATG
 CTGGAAATGA CTCCCCAGCA TGGAGACGTC TACACCTGCC ACGTGGAGCA CCCCAGCCTC
 CAGAACCCCA TCACCGTGGA GTGGCGGGCT CAGTCTGAAT CTGCCCAGAG CAAGATGCTG
 AGTGGCATTG GAGGCTTCGT GCTGGGGCTC ATCTTCCTCG GGCTGGGCCT TATTATCCAT
 CACAGGAGTC AGAAAGGGCT CCTGCACTGA *  
>DL;HLA:HLA01538
HLA:HLA01538 DQB1*03:11 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA01574
HLA:HLA01574 DQB1*03:12 270 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA01589
HLA:HLA01589 DQB1*03:13 270 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGACCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA02026
HLA:HLA02026 DQB1*03:14 270 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA02029
HLA:HLA02029 DQB1*03:15 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGGCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA02208
HLA:HLA02208 DQB1*03:16 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC AGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA02323
HLA:HLA02323 DQB1*03:17 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACC GAGCGCGTGC
 GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA02372
HLA:HLA02372 DQB1*03:18 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTCTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA02690
HLA:HLA02690 DQB1*03:19 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA02887
HLA:HLA02887 DQB1*03:20 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACAC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA03174
HLA:HLA03174 DQB1*03:21 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTTGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA03295
HLA:HLA03295 DQB1*03:22 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCAGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA03451
HLA:HLA03451 DQB1*03:23 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA03596
HLA:HLA03596 DQB1*03:24 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACATCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA03745
HLA:HLA03745 DQB1*03:25 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC GGCTTGACGC CGAGTACTGG AATAGCCAGA
 AGGACATCCT GGAGGAGGAC CGGGCGTCGG TGGACACCGT ATGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA04356
HLA:HLA04356 DQB1*03:26 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA05374
HLA:HLA05374 DQB1*03:27 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACCACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA05767
HLA:HLA05767 DQB1*03:28 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACGCGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA05771
HLA:HLA05771 DQB1*03:29 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA05774
HLA:HLA05774 DQB1*03:30 552 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA05761
HLA:HLA05761 DQB1*03:31 618 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GCGGGCTCAG TCTGAATCTG CCCAGAGCAA GATGCTGAGT GGCATTGGAG
 GCTTCGTGCT GGGGCTGA*    
>DL;HLA:HLA06143
HLA:HLA06143 DQB1*03:32 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTAGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA06144
HLA:HLA06144 DQB1*03:33 522 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCA
 CCCCCTTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CA* 
>DL;HLA:HLA06145
HLA:HLA06145 DQB1*03:34 522 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACAGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CA* 
>DL;HLA:HLA06176
HLA:HLA06176 DQB1*03:35 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AATCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA06177
HLA:HLA06177 DQB1*03:36 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCATGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA06516
HLA:HLA06516 DQB1*03:37 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGACTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA06880
HLA:HLA06880 DQB1*03:38 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGACACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA07411
HLA:HLA07411 DQB1*03:39 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATGAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA07799
HLA:HLA07799 DQB1*03:40 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGTTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA08084
HLA:HLA08084 DQB1*03:41 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGT
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA08113
HLA:HLA08113 DQB1*03:42 552 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAGTGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA08246
HLA:HLA08246 DQB1*03:43 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC CTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA08289
HLA:HLA08289 DQB1*03:44 270 bases
 AGGATTTCGT GTACCAGTTT AAGGCCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TGTAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC CGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA00636
HLA:HLA00636 DQB1*04:01:01 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCT GGAGGCCTTC GGGTAGCAAC TGTGACCTTG
 ATGCTGGCGA TGCTGAGCGC CCCGGTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACCG AGCTCGTGCG GGGTGTGACC
 AGATACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA GCGACGTGGG GGTGTATCGG
 GCGGTGACGC CGCTGGGGCG GCTTGACGCC GAGTACTGGA ATAGCCAGAA GGACATCCTG
 GAGGAGGACC GGGCGTCGGT GGACACCGTA TGCAGACACA ACTACCAGTT GGAGCTCCGC
 ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCA GTGACAGATT TCTATCCAGC CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA CCAGGAGGAG ACAACTGGCG TTGTGTCCAC CCCCCTTATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA ACCCCATCAT CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTCGGGCT GGGCCTTATT ATCCATCACA GGAGTCAGAA AGGGCTCCTG
 CACTGA*     
>DL;HLA:HLA03782
HLA:HLA03782 DQB1*04:01:02 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACC GAGCTCGTGC
 GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC GGCTTGACGC CGAGTACTGG AATAGCCAGA
 AGGACATCCT GGAGGAGGAC CGGGCGTCGG TTGACACCGT ATGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA00637
HLA:HLA00637 DQB1*04:02:01 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCT GGAGGCCTTC GGGTAGCAAC TGTGACCTTG
 ATGCTGGCGA TGCTGAGCAC CCCGGTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACCG AGCGCGTGCG GGGTGTGACC
 AGATACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA GCGACGTGGG GGTGTATCGG
 GCGGTGACGC CGCTGGGGCG GCTTGACGCC GAGTACTGGA ATAGCCAGAA GGACATCCTG
 GAGGAGGACC GGGCGTCGGT GGACACCGTA TGCAGACACA ACTACCAGTT GGAGCTCCGC
 ACGACCTTGC AGCGGCGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCA GTGACAGATT TCTATCCAGC CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA CCAGGAGGAG ACAACTGGCG TTGTGTCCAC CCCCCTTATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA ACCCCATCAT CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTCGGGCT GGGCCTTATT ATCCATCACA GGAGTCAGAA AGGGCTCCTG
 CACTGA*     
>DL;HLA:HLA05770
HLA:HLA05770 DQB1*04:02:02 552 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACA GAGCGCGTGC
 GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC GGCTTGACGC CGAGTACTGG AATAGCCAGA
 AGGACATCCT GGAGGAGGAC CGGGCGTCGG TGGACACCGT ATGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA03234
HLA:HLA03234 DQB1*04:03:01 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACC GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC GGCTTGACGC CGAGTACTGG AATAGCCAGA
 AGGACATCCT GGAGGAGGAC CGGGCGTCGG TGGACACCGT ATGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA04125
HLA:HLA04125 DQB1*04:03:02 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC GGCTTGACGC CGAGTACTGG AATAGCCAGA
 AGGACATCCT GGAGGAGGAC CGGGCGTCGG TGGACACCGT ATGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA04390
HLA:HLA04390 DQB1*04:04 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACC GAGCGCGTGC
 GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC GGCTTGACGC CGAGTACTGG AATAGCCAGA
 AGGACATCCT GGAGGAGGAC CGGGCGTCGG TGGACACCGT ATGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA05136
HLA:HLA05136 DQB1*04:05 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACC GAGCTCGTGC
 GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC GGCTTGACGC CGAGTACTGG AATAGCCAGA
 AGGACATCCT GGAGGAGGAC CGGGCGTCGG TGGACACCGT ATGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG *  
>DL;HLA:HLA05765
HLA:HLA05765 DQB1*04:06 552 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACC GAGCTCGTGC
 GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGT GGCTTGACGC CGAGTACTGG AATAGCCAGA
 AGGACATCCT GGAGGAGGAC CGGGCGTCGG TGGACACCGT ATGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA06146
HLA:HLA06146 DQB1*04:07 552 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACC GAGCTCGTGC
 GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC GGCTTGACGC CGAGTACTGG AATAGCCAGA
 AGGACATCCT GGAGGAGGAC CGGGCGTCGG TGGACACCGT ATGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCG
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA06178
HLA:HLA06178 DQB1*04:08 552 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACC GAGCTCGTGC
 GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC GGCTTGACGC CGAGTACTGG AATAGCCAGA
 AGGACATCCT GGAGGAGGAC CGGGCGTCGG TGGACACCGT ATGCAGACAC AACTACCAGT
 TGGAGCTCCG CACGACCTTG CAGCGGCGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC AGTGACAGAT TTCTATCCAG
 CCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAACTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AACCCCATCA
 TCGTGGAGTG GC*    
>DL;HLA:HLA00638
HLA:HLA00638 DQB1*05:01:01:01 786 bases
 ATGTCTTGGA AGAAGTCTTT GCGGATCCCC GGAGACCTTC GGGTAGCAAC TGTCACCTTG
 ATGCTGGCGA TCCTGAGCTC CTCACTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCCTGTG CTACTTCACC AACGGGACGG AGCGCGTGCG GGGTGTGACC
 AGACACATCT ATAACCGAGA GGAGTACGTG CGCTTCGACA GCGACGTGGG GGTGTACCGG
 GCAGTGACGC CGCAGGGGCG GCCTGTTGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGGGGGCCC GGGCGTCGGT GGACAGGGTG TGCAGACACA ACTACGAGGT GGCGTACCGC
 GGGATCCTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GATCTGCTCG GTGACAGATT TCTATCCAAG CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA TCAGGAGGAG ACAGCCGGCG TTGTGTCCAC CCCCCTCATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCGTTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTTGGGCT TGGCCTTATC ATCCGTCAAA GGAGTCGGAA AGGGCTTCTG
 CACTGA*     
>DL;HLA:HLA06615
HLA:HLA06615 DQB1*05:01:01:02 786 bases
 ATGTCTTGGA AGAAGTCTTT GCGGATCCCC GGAGACCTTC GGGTAGCAAC TGTCACCTTG
 ATGCTGGCGA TCCTGAGCTC CTCACTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCCTGTG CTACTTCACC AACGGGACGG AGCGCGTGCG GGGTGTGACC
 AGACACATCT ATAACCGAGA GGAGTACGTG CGCTTCGACA GCGACGTGGG GGTGTACCGG
 GCAGTGACGC CGCAGGGGCG GCCTGTTGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGGGGGCCC GGGCGTCGGT GGACAGGGTG TGCAGACACA ACTACGAGGT GGCGTACCGC
 GGGATCCTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GATCTGCTCG GTGACAGATT TCTATCCAAG CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA TCAGGAGGAG ACAGCCGGCG TTGTGTCCAC CCCCCTCATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCGTTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTTGGGCT TGGCCTTATC ATCCGTCAAA GGAGTCGGAA AGGGCTTCTG
 CACTGA*     
>DL;HLA:HLA01086
HLA:HLA01086 DQB1*05:01:02 271 bases
 TCCCGAGGAT TTCGTGTACC AGTTTAAGGG CCTGTGCTAC TTCACCAACG GGACGGAGCG
 CGTGCGGGGT GTGACCAGAC ACATCTATAA CCGAGAGGAG TACGTGCGCT TCGACAGCGA
 CGTGGGGGTG TACCGGGCGG TGACGCCGCA GGGGCGGCCT GTTGCCGAGT ACTGGAACAG
 CCAGAAGGAA GTCCTGGAGG GGGCCCGGGC GTCGGTGGAC AGAGTGTGCA GACACAACTA
 CGAGGTGGCG TACCGCGGGA TCCTGCAGAG G*  
>DL;HLA:HLA05548
HLA:HLA05548 DQB1*05:01:03 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCAGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC GGTGACAGAT TTCTATCCAA
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTCAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA00639
HLA:HLA00639 DQB1*05:02:01 786 bases
 ATGTCTTGGA AGAAGTCTTT GCGGATCCCC GGAGACCTTC GGGTAGCAAC TGTCACCTTG
 ATGCTGGCGA TCCTGAGCTC CTCACTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCCTGTG CTACTTCACC AACGGGACGG AGCGCGTGCG GGGTGTGACC
 AGACACATCT ATAACCGAGA GGAGTACGTG CGCTTCGACA GCGACGTGGG GGTGTACCGG
 GCGGTGACGC CGCAGGGGCG GCCTAGCGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGGGGGCCC GGGCGTCGGT GGACAGAGTG TGCAGACACA ACTACGAGGT GGCGTACCGC
 GGGATCCTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GATCTGCTCG GTGACAGATT TCTATCCAAG CCACATCAAA
 GTCCGGTGGT TTCGGAATGA TCAGGAGGAG ACAGCCGGCG TTGTGTCCAC CCCCCTCATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCGTTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTTGGGCT TGGCCTTATC ATCCGTCAAA GGAGTCGGAA AGGGCTTCTG
 CACTGA*     
>DL;HLA:HLA01573
HLA:HLA01573 DQB1*05:02:02 258 bases
 TGTACCAGTT TAAGGGCCTG TGCTACTTCA CCAACGGGAC GGAGCGCGTG CGGGGTGTGA
 CCAGACACAT CTATAACCGA GAGGAGTACG TGCGCTTCGA CAGCGACGTG GGGGTGTATC
 GGGCGGTGAC GCCGCAGGGG CGGCCTAGCG CCGAGTACTG GAACAGCCAG AAGGAAGTCC
 TGGAGGGGGC CCGGGCGTCG GTGGACAGAG TGTGCAGACA CAACTACGAG GTGGCGTACC
 GCGGGATCCT GCAGAGGA*    
>DL;HLA:HLA05766
HLA:HLA05766 DQB1*05:02:03 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTAGCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC GGTGACAGAT TTCTATCCAA
 GCCACATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA00640
HLA:HLA00640 DQB1*05:03:01:01 810 bases
 ATGTCTTGGA AGAAGTCTTT GCGGATCCCC GGAGACCTTC GGGTAGCAAC TGTCACCTTG
 ATGCTGGCGA TCCTGAGCTC CTCACTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCCTGTG CTACTTCACC AACGGGACGG AGCGCGTGCG GGGTGTGACC
 AGACACATCT ATAACCGAGA GGAGTACGTG CGCTTCGACA GCGACGTGGG GGTGTATCGG
 GCGGTGACGC CGCAGGGGCG GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGGGGGCCC GGGCGTCGGT GGACAGAGTG TGCAGACACA ACTACGAGGT GGCGTACCGC
 GGGATCCTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GATCTGCTCG GTGACAGATT TCTATCCAAG CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA TCAGGAGGAG ACAGCCGGCG TTGTGTCCAC CCCCCTCATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCGTTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTTGGGCT TGGCCTTATC ATCCGTCAAA GGAGTCGGAA AGGACCTCAA
 GGGCCTCCAC CAGCAGGGCT TCTGCACTGA *  
>DL;HLA:HLA06622
HLA:HLA06622 DQB1*05:03:01:02 810 bases
 ATGTCTTGGA AGAAGTCTTT GCGGATCCCC GGAGACCTTC GGGTAGCAAC TGTCACCTTG
 ATGCTGGCGA TCCTGAGCTC CTCACTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCCTGTG CTACTTCACC AACGGGACGG AGCGCGTGCG GGGTGTGACC
 AGACACATCT ATAACCGAGA GGAGTACGTG CGCTTCGACA GCGACGTGGG GGTGTATCGG
 GCGGTGACGC CGCAGGGGCG GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGGGGGCCC GGGCGTCGGT GGACAGAGTG TGCAGACACA ACTACGAGGT GGCGTACCGC
 GGGATCCTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GATCTGCTCG GTGACAGATT TCTATCCAAG CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA TCAGGAGGAG ACAGCCGGCG TTGTGTCCAC CCCCCTCATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCGTTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTTGGGCT TGGCCTTATC ATCCGTCAAA GGAGTCGGAA AGGACCTCAA
 GGGCCTCCAC CAGCAGGGCT TCTGCACTGA *  
>DL;HLA:HLA00641
HLA:HLA00641 DQB1*05:03:02 148 bases
 GACGGAGCGC GTGCGGGGTG TGACCAGACA CATCTATAAC CGAGAGGAGT ACGTGCGCTT
 CGACAGCGAC GTGGGGGTGT ATCGGGCGGT GACGCCGCAG GGGCGGCCTG ATGCCGAGTA
 CTGGAACAGC CAGAAGGAAG TCCTGGAG*   
>DL;HLA:HLA05769
HLA:HLA05769 DQB1*05:03:03 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC GGTGACAGAT TTCTATCCAA
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCTGGC GTTGTGTCCA
 CCCCCCTCAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA06120
HLA:HLA06120 DQB1*05:03:04 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC GGTGACAGAC TTCTATCCAA
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTCAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA06823
HLA:HLA06823 DQB1*05:03:05 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGGCAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC GGTGACAGAT TTCTATCCAA
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTCAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA00642
HLA:HLA00642 DQB1*05:04 223 bases
 TACCAGTTTA AGGGCCTGTG CTACTTCACC AACGGGACGG AGCGCGTGCG GGGTGTGACC
 AGATACATCT ATAACCGAGA AGAGTACGTG CGCTTCGACA GCGACGTGGG GGTGTACCGG
 GCGGTGACGC CGCAGGGGCG GCCTAGCGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGGAGGACC GGGCGTCGGT GGACAGGGTG TGCAGACACA ACT* 
>DL;HLA:HLA02689
HLA:HLA02689 DQB1*05:05 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTAGCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG *  
>DL;HLA:HLA05383
HLA:HLA05383 DQB1*05:06 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTGGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG *  
>DL;HLA:HLA05772
HLA:HLA05772 DQB1*05:07 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCACTTCGAC AGCGACGTGG
 GGGTGTACCG GGCAGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGGGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC GGTGACAGAT TTCTATCCAA
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTCAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA05775
HLA:HLA05775 DQB1*05:08 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC GGTGACAGAT TTCTATCCAA
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTCAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA06034
HLA:HLA06034 DQB1*05:09 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGGACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG *  
>DL;HLA:HLA06035
HLA:HLA06035 DQB1*05:10 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC GGTGACAGAT TTCTATCCAA
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTCAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGACCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA06287
HLA:HLA06287 DQB1*05:11 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCAGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGGGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG *  
>DL;HLA:HLA06670
HLA:HLA06670 DQB1*05:12 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCAGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGGTT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC GGTGACAGAT TTCTATCCAA
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTCAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA07091
HLA:HLA07091 DQB1*05:13 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TGTAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG *  
>DL;HLA:HLA07330
HLA:HLA07330 DQB1*05:14 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTAGCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC GGTGACAGAT TTCTATCCAA
 GCCACATCAA AGTCCGGTGG TTTCAGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTCAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA07929
HLA:HLA07929 DQB1*05:15 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAAACAC AACTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC GGTGACAGAT TTCTATCCAA
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTCAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA08292
HLA:HLA08292 DQB1*05:16 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGTCGG TGGACAGAGT GTGCAGACAC AGCTACGAGG
 TGGCGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGATCTGCTC GGTGACAGAT TTCTATCCAA
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTCAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA00643
HLA:HLA00643 DQB1*06:01:01 810 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCC GGAGGCCTTC GGGCACCAAC TGTGACCTTG
 ATGCTGGCGA TGCTGAGCAC CCCAGTGGCT GAGGGCAGAG ACCCTCCCGA GGATTTCGTG
 CTCCAGTTTA AGGCCATGTG CTACTTCACC AATGGGACGG AGCGCGTGCG TTATGTGACC
 AGATACATCT ATAACCGAGA GGAGGACGTG CGCTTCGACA GCGACGTGGG GGTGTATCGG
 GCGGTGACGC CGCAGGGGCG GCCTGACGCC GAGTACTGGA ACAGCCAGAA GGACATCCTG
 GAGAGGACCC GAGCGGAGTT GGACACGGTG TGCAGACACA ACTACGAGGT GGCGTTCCGC
 GGGATCTTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCG GTGACAGATT TCTATCCAGG CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA CCAGGAGGAG ACAGCTGGCG TTGTGTCCAC CCCCCTTATT
 AGGAACGGTG ACTGGACCTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCATGGA
 GACGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAACAAG ATGCTGAGTG GCATTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTCGGGCT GGGCCTTATC ATCCGTCAAA GGAGTCAGAA AGGACCTCAA
 GGGCCTCCAC CAGCAGGGCT TCTGCACTGA *  
>DL;HLA:HLA00644
HLA:HLA00644 DQB1*06:01:02 204 bases
 GCCATGTGCT ACTTCACCAA CGGGACGGAG CGCGTGCGTT ATGTGACCAG ATACATCTAT
 AACCGAGAGG AGGACGTGCG CTTCGACAGC GACGTGGGGG TGTATCGGGC GGTGACCCCG
 CAGGGGCGGC CTGACGCCGA GTACTGGAAC AGCCAGAAGG ACATCCTGGA GAGGACCCGA
 GCGGAGTTGG ACACGGTGTG CAGA*   
>DL;HLA:HLA00645
HLA:HLA00645 DQB1*06:01:03 676 bases
 AGAGACCCTC CCGAGGATTT CGTGCTCCAG TTTAAGGCCA TGTGCTACTT CACCAATGGG
 ACGGAGCGCG TGCGTTATGT GACCAGATAC ATCTATAACC GAGAGGAGGA CGTGCGCTTC
 GACAGCGACG TGGGGGTGTA TCGGGCGGTG ACGCCGCAGG GGCGGCCTGA CGCCGAGTAC
 TGGAACAGCC AGAAGGACAT CCTGGAGAGG ACCCGAGCGG AGTTGGACAC GGTGTGCAGA
 CACAACTACG AGGTGGCGTT CCGCGGGATC TTGCAGAGGA GAGTGGAGCC CACAGTGACC
 ATCTCCCCAT CCAGGACAGA GGCCCTCAAC CACCACAACC TGCTGGTCTG CTCGGTGACA
 GATTTCTATC CAGGCCAGAT CAAAGTCCGG TGGTTTCGGA ATGACCAGGA AGAGACAGCT
 GGCGTTGTGT CCACCCCCCT TATTAGGAAC GGTGACTGGA CCTTCCAGAT CCTGGTGATG
 CTGGAAATGA CTCCCCAGCA TGGAGACGTC TACACCTGCC ACGTGGAGCA CCCCAGCCTC
 CAGAGCCCCA TCACCGTGGA GTGGCGGGCT CAGTCTGAAT CTGCCCAGAA CAAGATGCTG
 AGTGGCATTG GAGGCTTCGT GCTGGGGCTG ATCTTCCTCG GGCTGGGCCT TATCATCCGT
 CAAAGGAGTC AGAAAG*    
>DL;HLA:HLA03307
HLA:HLA03307 DQB1*06:01:04 270 bases
 AGGATTTCGT GCTCCAGTTT AAGGCCATGT GCTACTTCAC CAATGGCACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGGACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGACC CGAGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA03991
HLA:HLA03991 DQB1*06:01:05 552 bases
 AGGATTTCGT GCTCCAGTTT AAGGCCATGT GCTACTTCAC CAATGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGGACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGACC CGAGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAGCTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA05776
HLA:HLA05776 DQB1*06:01:06 552 bases
 AGGATTTCGT GCTCCAGTTT AAGGCCATGT GCTACTTCAC CAATGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGGACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGACC CGAGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACGGAT TTCTATCCAG
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAGCTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA00646
HLA:HLA00646 DQB1*06:02:01 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCC GGAGACCTTC GGGTAGCAAC TGTCACCTTG
 ATGCTGGCGA TGCTGAGCTC CCTACTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TCTTGTGACC
 AGATACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA GCGACGTGGG GGTGTACCGC
 GCGGTGACGC CGCAGGGGCG GCCTGATGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGGGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACGAGGT GGCGTTCCGC
 GGGATCTTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCG GTGACAGATT TCTATCCAGG CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA TCAGGAGGAG ACAGCCGGCG TTGTGTCCAC CCCCCTTATT
 AGGAATGGTG ACTGGACTTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCGTTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTTGGGCT GGGCCTTATC ATCCGTCAAA GGAGTCAGAA AGGGCTTCTG
 CACTGA*     
>DL;HLA:HLA03156
HLA:HLA03156 DQB1*06:02:02 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA00647
HLA:HLA00647 DQB1*06:03:01 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCC GGAGACCTTC GGGTAGCAAC TGTCACCTTG
 ATGCTGGCGA TGCTGAGCTC CCTACTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TCTTGTAACC
 AGACACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA GCGACGTGGG GGTGTACCGC
 GCGGTGACGC CGCAGGGGCG GCCTGATGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGGGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACGAGGT GGCGTTCCGC
 GGGATCTTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCG GTGACAGATT TCTATCCAGG CCAGATCAAA
 GTCCGGTGGT TTCGGAATGA TCAGGAGGAG ACAGCCGGCG TTGTGTCCAC CCCCCTTATT
 AGGAATGGTG ACTGGACTTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCGTTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTTGGGCT GGGCCTTATC ATCCGTCAAA GGAGTCAGAA AGGGCTTCTG
 CACTGA*     
>DL;HLA:HLA02638
HLA:HLA02638 DQB1*06:03:02 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC ACGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA00648
HLA:HLA00648 DQB1*06:04:01 690 bases
 AGAGACTCTC CCGAGGATTT CGTGTACCAG TTTAAGGGCA TGTGCTACTT CACCAACGGG
 ACGGAGCGCG TGCGTCTTGT AACCAGACAC ATCTATAACC GAGAGGAGTA CGCGCGCTTC
 GACAGCGACG TGGGGGTGTA CCGGGCGGTG ACGCCGCAGG GGCGGCCTGT TGCCGAGTAC
 TGGAACAGCC AGAAGGAAGT CCTGGAGAGG ACCCGGGCGG AGTTGGACAC GGTGTGCAGA
 CACAACTACG AGGTGGGGTA CCGCGGGATC CTGCAGAGGA GAGTGGAGCC CACAGTGACC
 ATCTCCCCAT CCAGGACAGA GGCCCTCAAC CACCACAACC TGCTGGTCTG CTCGGTGACA
 GATTTCTATC CAGGCCAGAT CAAAGTCCAG TGGTTTCGGA ATGATCAGGA GGAGACAGCC
 GGCGTTGTGT CCACCCCCCT TATTAGGAAT GGTGACTGGA CTTTCCAGAT CCTGGTGATG
 CTGGAAATGA CTCCCCAGCG TGGAGATGTC TACACCTGCC ACGTGGAGCA CCCCAGCCTC
 CAGAGCCCCA TCACCGTGGA GTGGCGGGCT CAGTCTGAAT CTGCCCAGAG CAAGATGCTG
 AGTGGCGTTG GAGGCTTCGT GCTGGGGCTG ATCTTCCTTG GGCTGGGCCT TATCATCCGT
 CAAAGGAGTC AGAAAGGGCT TCTGCACTGA *  
>DL;HLA:HLA01005
HLA:HLA01005 DQB1*06:04:02 318 bases
 TCTCCCGAGG ATTTCGTGTA CCAGTTTAAG GGCATGTGCT ACTTCACCAA CGGGACGGAG
 CGCGTGCGTC TTGTAACCAG ACACATCTAT AACCGAGAGG AGTACGCGCG CTTCGACAGC
 GACGTGGGGG TGTACCGCGC GGTGACGCCG CAGGGGCGGC CTGTTGCCGA GTACTGGAAC
 AGCCAGAAGG AAGTCCTGGA GAGGACCCGG GCGGAGTTGG ACACGGTGTG CAGACACAAC
 TACGAGGTGG GGTACCGCGG GATCCTGCAG AGGAGAGTGG AGCCCACAGT GACCATCTCC
 CCATCCAGGA CAGAGGCC*    
>DL;HLA:HLA02602
HLA:HLA02602 DQB1*06:04:03 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACCGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG *  
>DL;HLA:HLA00649
HLA:HLA00649 DQB1*06:05:01 324 bases
 AGAGACTCTC CCGAGGATTT CGTGTACCAG TTTAAGGGCC TGTGCTACTT CACCAACGGG
 ACGGAGCGCG TGCGTCTTGT AACCAGATAC ATCTATAACC GAGAGGAGTA CGCGCGCTTC
 GACAGCGACG TGGGGGTGTA CCGGGCGGTG ACGCCGCAGG GGCGGCCTGT TGCCGAGTAC
 TGGAACAGCC AGAAGGAAGT CCTGGAGAGG ACCCGGGCGG AGTTGGACAC GGTGTGCAGA
 CACAACTACG AGGTGGGGTA CCGCGGGATC CTGCAGAGGA GAGTGGAGCC CACAGTGACC
 ATCTCCCCAT CCAGGACAGA GGCC*   
>DL;HLA:HLA00650
HLA:HLA00650 DQB1*06:05:02 173 bases
 GGACGGAGCG CGTGCGTCTT GTAACCAGAT ACATCTATAA CCGAGAGGAG TACGCGCGCT
 TCGACAGCGA CGTGGGGGTG TACCGGGCGG TGACGCCGCA GGGGCGGCCT GTCGCCGAGT
 ACTGGAACAG CCAGAAGGAA GTCCTGGAGA GGACCCGGGC GGAGTTGGAC ACG*
>DL;HLA:HLA00651
HLA:HLA00651 DQB1*06:06 176 bases
 GGACGGAGCG CGTGCGTCTT GTAACCAGAT ACATCTATAA CCGAGAGGAG TACGCGCGCT
 TCGACAGCGA CGTGGGGGTG TACCGGGCGG TGACGCCGCA GGGGCGGCCT GTTGCCGAGT
 ACTGGAACAG CCAGAAGGAA GTCCTGGAGA GGACCCGGGC GGCGGTGGAC AGGGTG*
>DL;HLA:HLA00652
HLA:HLA00652 DQB1*06:07:01 247 bases
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TCTTGTAACC
 AGACACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA GCGACGTGGG GGTGTACCGC
 GCGGTGACGC CGCAGGGGCG GCCTGATGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGAGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACGAGGT GGGGTACCGC
 GGGATCC*     
>DL;HLA:HLA05768
HLA:HLA05768 DQB1*06:07:02 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 GCCAGATCAA AGTCCAGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACTT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA00653
HLA:HLA00653 DQB1*06:08:01 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA02609
HLA:HLA02609 DQB1*06:08:02 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA00654
HLA:HLA00654 DQB1*06:09 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCC GGAGACCTTC GGGTAGCAAC TGTCACCTTG
 ATGCTGGCGA TGCTGAGCTC CCTACTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TCTTGTAACC
 AGATACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA GCGACGTGGG GGTGTACCGG
 GCGGTGACGC CGCAGGGGCG GCCTGTTGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGAGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACGAGGT GGGGTACCGC
 GGGATCCTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCG GTGACAGATT TCTATCCAGG CCAGATCAAA
 GTCCAGTGGT TTCGGAATGA TCAGGAGGAG ACAGCCGGCG TTGTGTCCAC CCCCCTTATT
 AGGAATGGTG ACTGGACTTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCGTTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTTGGGCT GGGCCTTATC ATCCGTCAAA GGAGTCAGAA AGGGCTTCTG
 CACTGA*     
>DL;HLA:HLA00655
HLA:HLA00655 DQB1*06:10 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTAGCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA00656
HLA:HLA00656 DQB1*06:11:01 257 bases
 TGTACCAGTT TAAGGGCATG TGCTACTTCA CCAACGGGAC GGAGCGCGTG CGTCTTGTGA
 CCAGATACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA CAGCGACGTG GGGGTGTACC
 GCGCGGTGAC GCCGCAGGGG CGGCCTGATG CCGAGTACTG GAACAGCCAG AAGGAAGTCC
 TGGAGGGGAC CCGGGCGGAG TTGGACACGG TGTGCAGACA CAACTACGAG GTGGCGTTCC
 GCGGGATCTT GCAGAGG*    
>DL;HLA:HLA00657
HLA:HLA00657 DQB1*06:11:02 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA00658
HLA:HLA00658 DQB1*06:12 786 bases
 ATGTCTTGGA AGAAGGCTTT GCGGATCCCC GGAGACCTTC GGGTAGCAAC TGTCACCTTG
 ATGCTGGCGA TGCTGAGCTC CCTACTGGCT GAGGGCAGAG ACTCTCCCGA GGATTTCGTG
 TACCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TCTTGTAACC
 AGATACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA GCGACGTGGG GGTGTACCGG
 GCGGTGACGC CGCAGGGGCG GCCTGTTGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGGGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACGAGGT GGGGTACCGC
 GGGATCCTGC AGAGGAGAGT GGAGCCCACA GTGACCATCT CCCCATCCAG GACAGAGGCC
 CTCAACCACC ACAACCTGCT GGTCTGCTCG GTGACAGATT TCTATCCAGG CCAGATCAAA
 GTCCAGTGGT TTCGGAATGA TCAGGAGGAG ACAGCCGGCG TTGTGTCCAC CCCCCTTATT
 AGGAATGGTG ACTGGACTTT CCAGATCCTG GTGATGCTGG AAATGACTCC CCAGCGTGGA
 GATGTCTACA CCTGCCACGT GGAGCACCCC AGCCTCCAGA GCCCCATCAC CGTGGAGTGG
 CGGGCTCAGT CTGAATCTGC CCAGAGCAAG ATGCTGAGTG GCGTTGGAGG CTTCGTGCTG
 GGGCTGATCT TCCTTGGGCT GGGCCTTATC ATCCGTCAAA GGAGTCAGAA AGGGCTTCTG
 CACTGA*     
>DL;HLA:HLA00659
HLA:HLA00659 DQB1*06:13 257 bases
 GAGGATTTCG TGTTCCAGTT TAAGGGCATG TGCTACTTCA CCAACGGGAC GGAGCGCGTG
 CGTCTTGTGA CCAGATACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA CAGCGACGTG
 GGGGTGTACC GCGCGGTGAC GCCGCAGGGG CGGCCTGTTG CCGAGTACTG GAACAGCCAG
 AAGGAAGTCC TGGAGGGGAC CCGGGCGGAG TTGGACACGG TGTGCAGACA CAACTACGAG
 GTGGCGTTCC GCGGGAT*    
>DL;HLA:HLA00660
HLA:HLA00660 DQB1*06:14:01 261 bases
 TGTTCCAGTT TAAGGGCATG TGCTACTTCA CCAACGGGAC GGAGCGCGTG CGTCTTGTAA
 CCAGACACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA CAGCGACGTG GGGGTGTACC
 GCGCGGTGAC GCCGCAGGGG CGGCCTGATG CCGAGTACTG GAACAGCCAG AAGGAAGTCC
 TGGAGGGGAC CCGGGCGGAG TTGGACACGG TGTGCAGACA CAACTACGAG GTGGCGTTCC
 GCGGGATCTT GCAGAGGAGA G*   
>DL;HLA:HLA03431
HLA:HLA03431 DQB1*06:14:02 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA00661
HLA:HLA00661 DQB1*06:15 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG *  
>DL;HLA:HLA01006
HLA:HLA01006 DQB1*06:16 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGAACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA01175
HLA:HLA01175 DQB1*06:17 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG *  
>DL;HLA:HLA01446
HLA:HLA01446 DQB1*06:18 259 bases
 TGTACCAGTT TAAGGGCATG TGCTACTTCA CCAACGGGAC GGAGCGCGTG CGTCTTGTAA
 CCAGATACAT CTATAACCGA GAGGAGTACG CGCGCTTCGA CAGCGACGTG GGGGTGTACC
 GGGCGGTGAC GCCGCAGGGG CGGCCTGTTG CCGAGTACTG GAACAGCCAG AAGGAAGTCC
 TGGAGAGGAC CCGGGCGGAG TTGGACACGG TGTGCAGACA CAACTACGAG GTGGCGTTCC
 GCGGGATCTT GCAGAGGAG*    
>DL;HLA:HLA01460
HLA:HLA01460 DQB1*06:19 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA01612
HLA:HLA01612 DQB1*06:20 240 bases
 TTCCAGTTTA AGGGCCTGTG CTACTTCACC AACGGGACGG AGCGCGTGCG TCTTGTGACC
 AGATACATCT ATAACCGAGA GGAGTACGCG CGCTTCGACA GCGACGTGGG GGTGTACCGC
 GCGGTGACGC CGCAGGGGCG GCCTGATGCC GAGTACTGGA ACAGCCAGAA GGAAGTCCTG
 GAGGGGACCC GGGCGGAGTT GGACACGGTG TGCAGACACA ACTACGAGGT GGCGTTCCGC
 *     
>DL;HLA:HLA01776
HLA:HLA01776 DQB1*06:21 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG *  
>DL;HLA:HLA01967
HLA:HLA01967 DQB1*06:22 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG *  
>DL;HLA:HLA02005
HLA:HLA02005 DQB1*06:23 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GGGGTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA02182
HLA:HLA02182 DQB1*06:24 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA02195
HLA:HLA02195 DQB1*06:25 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTAGCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG *  
>DL;HLA:HLA02221
HLA:HLA02221 DQB1*06:26N 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CTGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA02291
HLA:HLA02291 DQB1*06:27 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA02453
HLA:HLA02453 DQB1*06:28 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA02696
HLA:HLA02696 DQB1*06:29 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC CGCCTGCCGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA02740
HLA:HLA02740 DQB1*06:30 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA02917
HLA:HLA02917 DQB1*06:31 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA02950
HLA:HLA02950 DQB1*06:32 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA02970
HLA:HLA02970 DQB1*06:33 270 bases
 AGGATTTCGT GTTCCAGTTA AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA03114
HLA:HLA03114 DQB1*06:34 559 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 GCCAGATCAA AGTCCAGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACTT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GTGGGCTCA*    
>DL;HLA:HLA03809
HLA:HLA03809 DQB1*06:35 270 bases
 AGGATTTCGT GCTCCAGTTT AAGGCCATGT GCTACTTCAC CAATGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGGACGT GCGCTTCGAC AGCGACGTGG
 AGGTGTACCG GGCGGTGACG CCGCTGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGACC CGAGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA03979
HLA:HLA03979 DQB1*06:36 663 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 GCCAGATCAA AGTCCAGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACTT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGCGGAGTG GCGGGCTCAG TCTGAATCTG CCCAGAGCAA GATGCTGAGT GGCGTTGGAG
 GCTTCGTGCT GGGGCTGATC TTCCTTGGGC TGGGCCTTAT CATCCGTCAA AGGAGTCAGA
 AAG*     
>DL;HLA:HLA04119
HLA:HLA04119 DQB1*06:37 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AAGAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA04357
HLA:HLA04357 DQB1*06:38 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 GCCAGATCAA AGTCCAGTGG TTTCAGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACTT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA04358
HLA:HLA04358 DQB1*06:39 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACTT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA04737
HLA:HLA04737 DQB1*06:40 270 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACGTC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA06179
HLA:HLA06179 DQB1*06:41 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 GCCAGATCAA AGTCCAGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACTT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA06180
HLA:HLA06180 DQB1*06:42 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGGCC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 GCCAGATCAA AGTCCAGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACTT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA06272
HLA:HLA06272 DQB1*06:43 552 bases
 AGGATTTCGT GCTCCAGTTT AAGGCCATGT GCTACTTCAC CAATGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGGACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGACC CGAGTGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ACCAGGAGGA GACAGCTGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAACGGT GACTGGACCT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCATGG AGACGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA06518
HLA:HLA06518 DQB1*06:44 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACTT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCAAG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA06876
HLA:HLA06876 DQB1*06:45 267 bases
 AGGATTTCGT GTACCAGTTT AAGGGCCTGT GCTACTTCAC CAATGGGACG GAGCGCGTGC
 GTTATGTGAC CAGATACATC TATAACCGAG AGGAGGACGT GCGCTTCGAC AGCGACGTGG
 GGGTGTATCG GGCGGTGACG CCGCAGGGGC GGCCTGACGC CGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGAGGACC CGAGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGA*   
>DL;HLA:HLA06877
HLA:HLA06877 DQB1*06:46 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG *  
>DL;HLA:HLA07414
HLA:HLA07414 DQB1*06:47 552 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG TGGAGCCCAC AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 GCCAGATCAA AGTCCGGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACTT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCAAG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
>DL;HLA:HLA07539
HLA:HLA07539 DQB1*06:48 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA07820
HLA:HLA07820 DQB1*06:49 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGTCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA07922
HLA:HLA07922 DQB1*06:50 270 bases
 AGGATTTCGT GTTCCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTGAC CAGATACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG CGCGGTGACG CCGCAGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGGGGACC CGGGCGGAGT TGCACACGGT GTGCAGACAC AACTACGAGG
 TGGCGTTCCG CGGGATCTTG CAGAGGAGAG *  
>DL;HLA:HLA08082
HLA:HLA08082 DQB1*06:52 552 bases
 AGGATTTCGT GTACCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACG GAGCGCGTGC
 GTCTTGTAAC CAGACACATC TATAACCGAG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGTGTACCG GGCGGTGACG CCGCAGGGGC GGCCTGTTGC CGAGTACTGG AACAGCCAGA
 AGGAAGTCCT GGAGAGGACC CGGGCGGAGT TGGACACGGT GTGCAGACAC AACTACGAGG
 TGGGGTACCG CGGGATCCTG CAGAGGAGAG TGGAGCCCAT AGTGACCATC TCCCCATCCA
 GGACAGAGGC CCTCAACCAC CACAACCTGC TGGTCTGCTC GGTGACAGAT TTCTATCCAG
 GCCAGATCAA AGTCCAGTGG TTTCGGAATG ATCAGGAGGA GACAGCCGGC GTTGTGTCCA
 CCCCCCTTAT TAGGAATGGT GACTGGACTT TCCAGATCCT GGTGATGCTG GAAATGACTC
 CCCAGCGTGG AGATGTCTAC ACCTGCCACG TGGAGCACCC CAGCCTCCAG AGCCCCATCA
 CCGTGGAGTG GC*    
