>P1;HLA:HLA35619
HLA:HLA35619 DQB2*01:01:01:01 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA35620
HLA:HLA35620 DQB2*01:01:01:02 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA35623
HLA:HLA35623 DQB2*01:01:01:03 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA35626
HLA:HLA35626 DQB2*01:01:01:04 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA35920
HLA:HLA35920 DQB2*01:01:01:05 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA36328
HLA:HLA36328 DQB2*01:01:01:06 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA36413
HLA:HLA36413 DQB2*01:01:01:07 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA36550
HLA:HLA36550 DQB2*01:01:01:08 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA36595
HLA:HLA36595 DQB2*01:01:01:09 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA36533
HLA:HLA36533 DQB2*01:01:01:10 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA36378
HLA:HLA36378 DQB2*01:01:01:11 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA36367
HLA:HLA36367 DQB2*01:01:01:12 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA36580
HLA:HLA36580 DQB2*01:01:01:13 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA36371
HLA:HLA36371 DQB2*01:01:01:14 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA36527
HLA:HLA36527 DQB2*01:01:01:15 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA37367
HLA:HLA37367 DQB2*01:01:01:16 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA37216
HLA:HLA37216 DQB2*01:01:01:17 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA37233
HLA:HLA37233 DQB2*01:01:01:18 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA36320
HLA:HLA36320 DQB2*01:01:02 88 bases
 DFLVQFKGMC YFTNGTERVR GVARYIYNRE EYGRFDSDVG EFQAVTELGR SIEDWNNYKD
 FLEQERAAVD KVCRHNYEAE LRTTLQRQ   
>P1;HLA:HLA35735
HLA:HLA35735 DQB2*01:01:03 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA35621
HLA:HLA35621 DQB2*01:02:01:01 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVRWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLSGI GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA36383
HLA:HLA36383 DQB2*01:02:01:02 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVRWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLSGI GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA36419
HLA:HLA36419 DQB2*01:02:01:03 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVRWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLSGI GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA37275
HLA:HLA37275 DQB2*01:02:01:04 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVRWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLSGI GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA35622
HLA:HLA35622 DQB2*01:02:02:01 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVRWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLSGI GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA35800
HLA:HLA35800 DQB2*01:02:02:02 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVRWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLSGI GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA35933
HLA:HLA35933 DQB2*01:02:02:03 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVRWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLSGI GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA36330
HLA:HLA36330 DQB2*01:02:02:04 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVRWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLSGI GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA36365
HLA:HLA36365 DQB2*01:02:02:05 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVRWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLSGI GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA35625
HLA:HLA35625 DQB2*01:02:04 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVRWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLSGI GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA35627
HLA:HLA35627 DQB2*01:03 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNRGEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA35858
HLA:HLA35858 DQB2*01:04 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVQWFR NDQEETAGVV STSFIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLGGV GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA35803
HLA:HLA35803 DQB2*01:05 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV QWFRNDQEET AGVVSTSFIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LGGVGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA35799
HLA:HLA35799 DQB2*01:06 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHNN LLVCSVTDFY PAQIKVRWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLSGI GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA35760
HLA:HLA35760 DQB2*01:07:01:01 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVQWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLGGV GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA36562
HLA:HLA36562 DQB2*01:07:01:02 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVQWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLGGV GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA36372
HLA:HLA36372 DQB2*01:07:01:03 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVQWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLGGV GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA36374
HLA:HLA36374 DQB2*01:07:01:04 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVQWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLGGV GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA35624
HLA:HLA35624 DQB2*01:08 264 bases
 MALQIPGGFW AAAVTVMLVM LSTPVAEARD FPKDFLVQFK GMCYFTNGTE RVRGVARYIY
 NREEYGRFDS DVGEFQAVTE LGRSIEDWNN YKDFLEQERA AVDKVCRHNY EAELRTTLQR
 QVEPTVTISP SRTEALNHHN LLVCSVTDFY PAQIKVRWFR NDQEETAGVV STSLIRNGDW
 TFQILVMLEI TPQRGDIYTC QVEHPSLQSP ITVEWRAQSE SAQSKMLSGV GGFVLGLIFL
 GLGLIIRHRG QKGPRGPPPA GLLH   
>P1;HLA:HLA37184
HLA:HLA37184 DQB2*01:09 268 bases
 MSWKMALQIP GGFWAAAVTV MLVMLSTPVA EARDFPKDFL VQFKGMCYFT NGTERVRGVA
 RYIYNREEYG RFDSDVGEFQ AVTELGRSIE DWNNYKDFLE QERAAVDKVC RHNYEAELRT
 TLQRQVEPTV TISPSRTEAL NHHNLLVCSV TDFYPAQIKV RWFRNDQEET AGVVSTSLIR
 NGDWTFQILV MLEITPQRGD IYTCQVEHPS LQSPITVEWR AQSESAQSKM LSGIGGFVLG
 LIFLGLGLII RHRGQKGPRG PPPAGLLH   
>P1;HLA:HLA37276
HLA:HLA37276 DQB2*01:10N 3 bases
 MSX     
