>DL;HLA:HLA35619
HLA:HLA35619 DQB2*01:01:01:01 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35620
HLA:HLA35620 DQB2*01:01:01:02 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35623
HLA:HLA35623 DQB2*01:01:01:03 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35626
HLA:HLA35626 DQB2*01:01:01:04 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35920
HLA:HLA35920 DQB2*01:01:01:05 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36328
HLA:HLA36328 DQB2*01:01:01:06 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36413
HLA:HLA36413 DQB2*01:01:01:07 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36550
HLA:HLA36550 DQB2*01:01:01:08 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36595
HLA:HLA36595 DQB2*01:01:01:09 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36533
HLA:HLA36533 DQB2*01:01:01:10 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36378
HLA:HLA36378 DQB2*01:01:01:11 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36367
HLA:HLA36367 DQB2*01:01:01:12 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36580
HLA:HLA36580 DQB2*01:01:01:13 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36371
HLA:HLA36371 DQB2*01:01:01:14 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36527
HLA:HLA36527 DQB2*01:01:01:15 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA37367
HLA:HLA37367 DQB2*01:01:01:16 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA37216
HLA:HLA37216 DQB2*01:01:01:17 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA37233
HLA:HLA37233 DQB2*01:01:01:18 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36320
HLA:HLA36320 DQB2*01:01:02 267 bases
 AGGATTTCTT GGTTCAGTTT AAGGGCATGT GCTACTTCAC CAACGGGACA GAGCGCGTGC
 GCGGTGTGGC CAGATACATC TATAACCGCG AGGAGTACGG GCGCTTCGAC AGCGACGTTG
 GGGAGTTCCA GGCGGTGACC GAGCTGGGGC GGAGCATCGA GGACTGGAAC AACTATAAGG
 ACTTCTTGGA GCAGGAGCGG GCCGCGGTGG ACAAGGTGTG CAGACACAAC TACGAGGCGG
 AGCTGCGCAC GACCTTGCAG CGGCAAG   
>DL;HLA:HLA35735
HLA:HLA35735 DQB2*01:01:03 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG CGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35621
HLA:HLA35621 DQB2*01:02:01:01 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG CGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTGCGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCGGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCA TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36383
HLA:HLA36383 DQB2*01:02:01:02 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG CGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTGCGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCGGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCA TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36419
HLA:HLA36419 DQB2*01:02:01:03 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG CGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTGCGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCGGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCA TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA37275
HLA:HLA37275 DQB2*01:02:01:04 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG CGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTGCGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCGGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCA TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35622
HLA:HLA35622 DQB2*01:02:02:01 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG CGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTGCGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCA TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35800
HLA:HLA35800 DQB2*01:02:02:02 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG CGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTGCGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCA TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35933
HLA:HLA35933 DQB2*01:02:02:03 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG CGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTGCGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCA TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36330
HLA:HLA36330 DQB2*01:02:02:04 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG CGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTGCGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCA TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36365
HLA:HLA36365 DQB2*01:02:02:05 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG CGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTGCGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCA TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35625
HLA:HLA35625 DQB2*01:02:04 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCGGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCA TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35627
HLA:HLA35627 DQB2*01:03 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGG GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35858
HLA:HLA35858 DQB2*01:04 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CTTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35803
HLA:HLA35803 DQB2*01:05 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CTTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35799
HLA:HLA35799 DQB2*01:06 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG CGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTGCGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACAACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCA TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35760
HLA:HLA35760 DQB2*01:07:01:01 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36562
HLA:HLA36562 DQB2*01:07:01:02 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36372
HLA:HLA36372 DQB2*01:07:01:03 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA36374
HLA:HLA36374 DQB2*01:07:01:04 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
>DL;HLA:HLA35624
HLA:HLA35624 DQB2*01:08 807 bases
 ACGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA37184
HLA:HLA37184 DQB2*01:09 807 bases
 ATGTCTTGGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG CGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTGCGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCGGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CGGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGAGTGGCA TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCAG CAGGACTCCT GCACTGA   
>DL;HLA:HLA37276
HLA:HLA37276 DQB2*01:10N 807 bases
 ATGTCTTAGA AGATGGCTCT GCAGATCCCT GGAGGCTTTT GGGCAGCAGC TGTGACCGTG
 ATGCTGGTGA TGCTGAGCAC CCCAGTGGCT GAGGCCAGAG ACTTTCCCAA GGATTTCTTG
 GTCCAGTTTA AGGGCATGTG CTACTTCACC AACGGGACAG AGCGCGTGCG GGGTGTGGCC
 AGATACATCT ATAACCGCGA GGAGTACGGG CGCTTCGACA GCGACGTTGG GGAGTTCCAG
 GCGGTGACCG AGCTGGGGCG GAGCATCGAG GACTGGAACA ACTATAAGGA CTTCTTGGAG
 CAGGAGCGGG CCGCGGTGGA CAAGGTGTGC AGACACAACT ACGAGGCGGA GCTACGCACG
 ACCTTGCAGC GGCAAGTGGA GCCCACAGTG ACCATCTCCC CATCCAGGAC AGAGGCCCTC
 AACCACCACA ACCTGCTGGT CTGCTCAGTG ACAGATTTCT ATCCAGCCCA GATCAAAGTC
 CAGTGGTTTC GGAATGACCA GGAGGAGACA GCCGGTGTTG TGTCCACCTC CCTCATTAGG
 AATGGTGACT GGACCTTCCA GATTCTGGTG ATGCTGGAAA TAACTCCCCA GCGTGGAGAC
 ATCTACACCT GCCAAGTGGA GCACCCCAGC CTCCAGAGCC CCATCACCGT GGAGTGGCGG
 GCTCAGTCTG AATCTGCCCA GAGCAAGATG CTGGGTGGTG TTGGAGGCTT CGTGCTGGGG
 CTGATCTTCC TCGGGCTGGG CCTTATCATC CGTCACAGGG GTCAGAAAGG ACCTCGAGGG
 CCTCCACCTG CAGGACTCCT GCACTGA   
