>P1;HLA:HLA00662
HLA:HLA00662 DRA*01:01:01:01 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA06469
HLA:HLA06469 DRA*01:01:01:02 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA06470
HLA:HLA06470 DRA*01:01:01:03 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25698
HLA:HLA25698 DRA*01:01:01:04 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25564
HLA:HLA25564 DRA*01:01:01:05 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25902
HLA:HLA25902 DRA*01:01:01:06 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25847
HLA:HLA25847 DRA*01:01:01:07 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25839
HLA:HLA25839 DRA*01:01:01:08 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25752
HLA:HLA25752 DRA*01:01:01:09 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25773
HLA:HLA25773 DRA*01:01:01:10 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25785
HLA:HLA25785 DRA*01:01:01:11 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA26046
HLA:HLA26046 DRA*01:01:01:12 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA06468
HLA:HLA06468 DRA*01:01:02 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA00663
HLA:HLA00663 DRA*01:02:01 226 bases
 EHVIIQAEFY LNPDQSGEFM FDFDGDEIFH VDMAKKETVW RLEEFGRFAS FEAQGALANI
 AVDKANLEIM TKRSNYTPIT NVPPEVTVLT NSPVELREPN VLICFIDKFT PPVVNVTWLR
 NGKPVTTGVS ETVFLPREDH LFRKFHYLPF LPSTEDVYDC RVEHWGLDEP LLKHWEFDAP
 SPLPETTENV VCALGLTVGL VGIIIGTIFI IKGLRKSNAA ERRGPL 
>P1;HLA:HLA01593
HLA:HLA01593 DRA*01:02:02:01 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25972
HLA:HLA25972 DRA*01:02:02:02 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25840
HLA:HLA25840 DRA*01:02:02:03 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25662
HLA:HLA25662 DRA*01:02:02:04 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25877
HLA:HLA25877 DRA*01:02:02:05 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25830
HLA:HLA25830 DRA*01:02:02:06 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25754
HLA:HLA25754 DRA*01:02:02:07 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25612
HLA:HLA25612 DRA*01:02:02:08 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25897
HLA:HLA25897 DRA*01:02:02:09 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25731
HLA:HLA25731 DRA*01:02:02:10 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA26017
HLA:HLA26017 DRA*01:02:02:11 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25879
HLA:HLA25879 DRA*01:02:02:12 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25708
HLA:HLA25708 DRA*01:02:02:13 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25806
HLA:HLA25806 DRA*01:02:02:14 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA06454
HLA:HLA06454 DRA*01:02:03 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA31913
HLA:HLA31913 DRA*01:03 254 bases
 MAISGVPVLG FFIIALLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA31953
HLA:HLA31953 DRA*01:04 254 bases
 MAISGVPVLG FFITAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHRGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA32074
HLA:HLA32074 DRA*01:05 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHRGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
