>DL;HLA:HLA00662
HLA:HLA00662 DRA*01:01:01:01 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA06469
HLA:HLA06469 DRA*01:01:01:02 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA06470
HLA:HLA06470 DRA*01:01:01:03 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25698
HLA:HLA25698 DRA*01:01:01:04 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25564
HLA:HLA25564 DRA*01:01:01:05 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25902
HLA:HLA25902 DRA*01:01:01:06 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25847
HLA:HLA25847 DRA*01:01:01:07 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25839
HLA:HLA25839 DRA*01:01:01:08 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25752
HLA:HLA25752 DRA*01:01:01:09 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25773
HLA:HLA25773 DRA*01:01:01:10 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25785
HLA:HLA25785 DRA*01:01:01:11 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA26046
HLA:HLA26046 DRA*01:01:01:12 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA06468
HLA:HLA06468 DRA*01:01:02 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA TGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA00663
HLA:HLA00663 DRA*01:02:01 683 bases
 AAGAACATGT GATCATCCAG GCCGAGTTCT ATCTGAATCC TGACCAATCA GGCGAGTTTA
 TGTTTGACTT TGATGGTGAT GAGATTTTCC ATGTGGATAT GGCAAAGAAG GAGACGGTCT
 GGCGGCTTGA AGAATTTGGA CGATTTGCCA GCTTTGAGGC TCAAGGTGCA TTGGCCAACA
 TAGCTGTGGA CAAAGCCAAC CTGGAAATCA TGACAAAGCG CTCCAACTAT ACTCCGATCA
 CCAATGTACC TCCAGAGGTA ACTGTGCTCA CGAACAGCCC TGTGGAACTG AGAGAGCCCA
 ACGTCCTCAT CTGTTTCATC GACAAGTTCA CCCCACCAGT GGTCAATGTC ACGTGGCTTC
 GAAATGGAAA ACCTGTCACC ACAGGAGTGT CAGAGACAGT CTTCCTGCCC AGGGAAGACC
 ACCTTTTCCG CAAGTTCCAC TATCTCCCCT TCCTGCCCTC AACTGAGGAC GTTTACGACT
 GCAGGGTGGA GCACTGGGGC TTGGATGAGC CTCTTCTCAA GCACTGGGAG TTTGATGCTC
 CAAGCCCTCT CCCAGAGACT ACAGAGAACG TGGTGTGTGC CCTGGGCCTG ACTGTGGGTC
 TGGTGGGCAT CATTATTGGG ACCATCTTCA TCATCAAGGG ATTGCGCAAA AGCAATGCAG
 CAGAACGCAG GGGGCCTCTG TAA*   
>DL;HLA:HLA01593
HLA:HLA01593 DRA*01:02:02:01 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25972
HLA:HLA25972 DRA*01:02:02:02 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25840
HLA:HLA25840 DRA*01:02:02:03 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25662
HLA:HLA25662 DRA*01:02:02:04 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25877
HLA:HLA25877 DRA*01:02:02:05 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25830
HLA:HLA25830 DRA*01:02:02:06 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25754
HLA:HLA25754 DRA*01:02:02:07 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25612
HLA:HLA25612 DRA*01:02:02:08 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25897
HLA:HLA25897 DRA*01:02:02:09 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25731
HLA:HLA25731 DRA*01:02:02:10 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA26017
HLA:HLA26017 DRA*01:02:02:11 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25879
HLA:HLA25879 DRA*01:02:02:12 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25708
HLA:HLA25708 DRA*01:02:02:13 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA25806
HLA:HLA25806 DRA*01:02:02:14 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
>DL;HLA:HLA06454
HLA:HLA06454 DRA*01:02:03 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACAAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA* 
