>DL;HLA:HLA00662
HLA:HLA00662 DRA*01:01:01:01 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA06469
HLA:HLA06469 DRA*01:01:01:02 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA06470
HLA:HLA06470 DRA*01:01:01:03 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25698
HLA:HLA25698 DRA*01:01:01:04 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25564
HLA:HLA25564 DRA*01:01:01:05 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25902
HLA:HLA25902 DRA*01:01:01:06 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25847
HLA:HLA25847 DRA*01:01:01:07 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25839
HLA:HLA25839 DRA*01:01:01:08 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25752
HLA:HLA25752 DRA*01:01:01:09 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25773
HLA:HLA25773 DRA*01:01:01:10 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25785
HLA:HLA25785 DRA*01:01:01:11 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA26046
HLA:HLA26046 DRA*01:01:01:12 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA35746
HLA:HLA35746 DRA*01:01:01:13 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA35805
HLA:HLA35805 DRA*01:01:01:14 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA35895
HLA:HLA35895 DRA*01:01:01:15 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA35713
HLA:HLA35713 DRA*01:01:01:16 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA35653
HLA:HLA35653 DRA*01:01:01:17 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA36125
HLA:HLA36125 DRA*01:01:01:18 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA36592
HLA:HLA36592 DRA*01:01:01:19 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA36568
HLA:HLA36568 DRA*01:01:01:20 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38323
HLA:HLA38323 DRA*01:01:01:21 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38253
HLA:HLA38253 DRA*01:01:01:22 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38252
HLA:HLA38252 DRA*01:01:01:23 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38433
HLA:HLA38433 DRA*01:01:01:24 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38244
HLA:HLA38244 DRA*01:01:01:25 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38657
HLA:HLA38657 DRA*01:01:01:26 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA39225
HLA:HLA39225 DRA*01:01:01:27 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA39202
HLA:HLA39202 DRA*01:01:01:28 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA39387
HLA:HLA39387 DRA*01:01:01:29 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA39349
HLA:HLA39349 DRA*01:01:01:30 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA06468
HLA:HLA06468 DRA*01:01:02 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA TGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA36576
HLA:HLA36576 DRA*01:01:03 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCTCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38586
HLA:HLA38586 DRA*01:01:04 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTATGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38585
HLA:HLA38585 DRA*01:01:05 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGTGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38654
HLA:HLA38654 DRA*01:01:06 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG ACTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA39599
HLA:HLA39599 DRA*01:01:07 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTTGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA00663
HLA:HLA00663 DRA*01:02:01 683 bases
 AAGAACATGT GATCATCCAG GCCGAGTTCT ATCTGAATCC TGACCAATCA GGCGAGTTTA
 TGTTTGACTT TGATGGTGAT GAGATTTTCC ATGTGGATAT GGCAAAGAAG GAGACGGTCT
 GGCGGCTTGA AGAATTTGGA CGATTTGCCA GCTTTGAGGC TCAAGGTGCA TTGGCCAACA
 TAGCTGTGGA CAAAGCCAAC CTGGAAATCA TGACAAAGCG CTCCAACTAT ACTCCGATCA
 CCAATGTACC TCCAGAGGTA ACTGTGCTCA CGAACAGCCC TGTGGAACTG AGAGAGCCCA
 ACGTCCTCAT CTGTTTCATC GACAAGTTCA CCCCACCAGT GGTCAATGTC ACGTGGCTTC
 GAAATGGAAA ACCTGTCACC ACAGGAGTGT CAGAGACAGT CTTCCTGCCC AGGGAAGACC
 ACCTTTTCCG CAAGTTCCAC TATCTCCCCT TCCTGCCCTC AACTGAGGAC GTTTACGACT
 GCAGGGTGGA GCACTGGGGC TTGGATGAGC CTCTTCTCAA GCACTGGGAG TTTGATGCTC
 CAAGCCCTCT CCCAGAGACT ACAGAGAACG TGGTGTGTGC CCTGGGCCTG ACTGTGGGTC
 TGGTGGGCAT CATTATTGGG ACCATCTTCA TCATCAAGGG ATTGCGCAAA AGCAATGCAG
 CAGAACGCAG GGGGCCTCTG TAA   
>DL;HLA:HLA01593
HLA:HLA01593 DRA*01:02:02:01 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25972
HLA:HLA25972 DRA*01:02:02:02 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25840
HLA:HLA25840 DRA*01:02:02:03 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25662
HLA:HLA25662 DRA*01:02:02:04 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25877
HLA:HLA25877 DRA*01:02:02:05 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25830
HLA:HLA25830 DRA*01:02:02:06 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25754
HLA:HLA25754 DRA*01:02:02:07 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25612
HLA:HLA25612 DRA*01:02:02:08 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25897
HLA:HLA25897 DRA*01:02:02:09 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25731
HLA:HLA25731 DRA*01:02:02:10 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA26017
HLA:HLA26017 DRA*01:02:02:11 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25879
HLA:HLA25879 DRA*01:02:02:12 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25708
HLA:HLA25708 DRA*01:02:02:13 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA25806
HLA:HLA25806 DRA*01:02:02:14 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA35851
HLA:HLA35851 DRA*01:02:02:15 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA35832
HLA:HLA35832 DRA*01:02:02:16 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA35914
HLA:HLA35914 DRA*01:02:02:17 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA36157
HLA:HLA36157 DRA*01:02:02:19 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA39681
HLA:HLA39681 DRA*01:02:02:20 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA06454
HLA:HLA06454 DRA*01:02:03:01 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACAAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38207
HLA:HLA38207 DRA*01:02:03:02 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACAAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA31913
HLA:HLA31913 DRA*01:03 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTCTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA31953
HLA:HLA31953 DRA*01:04 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA CAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACCGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA32074
HLA:HLA32074 DRA*01:05 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACCGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38379
HLA:HLA38379 DRA*01:06 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCAAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38289
HLA:HLA38289 DRA*01:07 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCGGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38691
HLA:HLA38691 DRA*01:08 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACAAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CGCCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38622
HLA:HLA38622 DRA*01:09 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCCTCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACAAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38608
HLA:HLA38608 DRA*01:10 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TGTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38618
HLA:HLA38618 DRA*01:11 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAATGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38658
HLA:HLA38658 DRA*01:12 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCACA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38609
HLA:HLA38609 DRA*01:13 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACAA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38619
HLA:HLA38619 DRA*01:14 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCAAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA38770
HLA:HLA38770 DRA*01:15 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCGTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA39591
HLA:HLA39591 DRA*01:16 765 bases
 ATGACCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTCA TAGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGATTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
>DL;HLA:HLA39867
HLA:HLA39867 DRA*01:17 765 bases
 ATGGCCATAA GTGGAGTCCC TGTGCTAGGA TTTTTCATCA TAGCTGTGCT GATGAGCGCT
 CAGGAATCAT GGGCTATCAA AGAAGAACAT GTGATCATCC AGGCCGAGTT CTATCTGAAT
 CCTGACCAAT CAGGCGAGTT TATGTTTGAC TTTGATGGTG ATGAGATTTT CCATGTGGAT
 ATGGCAAAGA AGGAGACGGT CTGGCGGCTT GAAGAATTTG GACGATTTGC CAGCTTTGAG
 GCTCAAGGTG CATTGGCCAA CATAGCTGTG GACAAAGCCA ACCTGGAAAT CATGACAAAG
 CGCTCCAACT ATACTCCGAT CACCAATGTA CCTCCAGAGG TAACTGTGCT CACGAACAGC
 CCTGTGGAAC TGAGAGAGCC CAACGTCCTC ATCTGTTTAA TCGACAAGTT CACCCCACCA
 GTGGTCAATG TCACGTGGCT TCGAAATGGA AAACCTGTCA CCACAGGAGT GTCAGAGACA
 GTCTTCCTGC CCAGGGAAGA CCACCTTTTC CGCAAGTTCC ACTATCTCCC CTTCCTGCCC
 TCAACTGAGG ACGTTTACGA CTGCAGGGTG GAGCACTGGG GCTTGGATGA GCCTCTTCTC
 AAGCACTGGG AGTTTGATGC TCCAAGCCCT CTCCCAGAGA CTACAGAGAA CGTGGTGTGT
 GCCCTGGGCC TGACTGTGGG TCTGGTGGGC ATCATTATTG GGACCATCTT CATCATCAAG
 GGAGTGCGCA AAAGCAATGC AGCAGAACGC AGGGGGCCTC TGTAA 
