>P1;HLA:HLA00662
HLA:HLA00662 DRA*01:01:01:01 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA06469
HLA:HLA06469 DRA*01:01:01:02 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA06470
HLA:HLA06470 DRA*01:01:01:03 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25698
HLA:HLA25698 DRA*01:01:01:04 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25564
HLA:HLA25564 DRA*01:01:01:05 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25902
HLA:HLA25902 DRA*01:01:01:06 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25847
HLA:HLA25847 DRA*01:01:01:07 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25839
HLA:HLA25839 DRA*01:01:01:08 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25752
HLA:HLA25752 DRA*01:01:01:09 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25773
HLA:HLA25773 DRA*01:01:01:10 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA25785
HLA:HLA25785 DRA*01:01:01:11 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA26046
HLA:HLA26046 DRA*01:01:01:12 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA35746
HLA:HLA35746 DRA*01:01:01:13 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA35805
HLA:HLA35805 DRA*01:01:01:14 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA35895
HLA:HLA35895 DRA*01:01:01:15 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA35713
HLA:HLA35713 DRA*01:01:01:16 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA35653
HLA:HLA35653 DRA*01:01:01:17 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA36125
HLA:HLA36125 DRA*01:01:01:18 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA36592
HLA:HLA36592 DRA*01:01:01:19 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA36568
HLA:HLA36568 DRA*01:01:01:20 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA38323
HLA:HLA38323 DRA*01:01:01:21 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA38253
HLA:HLA38253 DRA*01:01:01:22 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA38252
HLA:HLA38252 DRA*01:01:01:23 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA38433
HLA:HLA38433 DRA*01:01:01:24 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA38244
HLA:HLA38244 DRA*01:01:01:25 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA38657
HLA:HLA38657 DRA*01:01:01:26 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA39225
HLA:HLA39225 DRA*01:01:01:27 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA39202
HLA:HLA39202 DRA*01:01:01:28 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA39387
HLA:HLA39387 DRA*01:01:01:29 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA39349
HLA:HLA39349 DRA*01:01:01:30 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA06468
HLA:HLA06468 DRA*01:01:02 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA36576
HLA:HLA36576 DRA*01:01:03 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA38586
HLA:HLA38586 DRA*01:01:04 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA38585
HLA:HLA38585 DRA*01:01:05 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA38654
HLA:HLA38654 DRA*01:01:06 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA39599
HLA:HLA39599 DRA*01:01:07 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA00663
HLA:HLA00663 DRA*01:02:01 226 bases
 EHVIIQAEFY LNPDQSGEFM FDFDGDEIFH VDMAKKETVW RLEEFGRFAS FEAQGALANI
 AVDKANLEIM TKRSNYTPIT NVPPEVTVLT NSPVELREPN VLICFIDKFT PPVVNVTWLR
 NGKPVTTGVS ETVFLPREDH LFRKFHYLPF LPSTEDVYDC RVEHWGLDEP LLKHWEFDAP
 SPLPETTENV VCALGLTVGL VGIIIGTIFI IKGLRKSNAA ERRGPL 
>P1;HLA:HLA01593
HLA:HLA01593 DRA*01:02:02:01 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25972
HLA:HLA25972 DRA*01:02:02:02 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25840
HLA:HLA25840 DRA*01:02:02:03 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25662
HLA:HLA25662 DRA*01:02:02:04 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25877
HLA:HLA25877 DRA*01:02:02:05 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25830
HLA:HLA25830 DRA*01:02:02:06 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25754
HLA:HLA25754 DRA*01:02:02:07 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25612
HLA:HLA25612 DRA*01:02:02:08 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25897
HLA:HLA25897 DRA*01:02:02:09 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25731
HLA:HLA25731 DRA*01:02:02:10 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA26017
HLA:HLA26017 DRA*01:02:02:11 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25879
HLA:HLA25879 DRA*01:02:02:12 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25708
HLA:HLA25708 DRA*01:02:02:13 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA25806
HLA:HLA25806 DRA*01:02:02:14 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA35851
HLA:HLA35851 DRA*01:02:02:15 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA35832
HLA:HLA35832 DRA*01:02:02:16 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA35914
HLA:HLA35914 DRA*01:02:02:17 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA36157
HLA:HLA36157 DRA*01:02:02:19 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA39681
HLA:HLA39681 DRA*01:02:02:20 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA06454
HLA:HLA06454 DRA*01:02:03:01 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA38207
HLA:HLA38207 DRA*01:02:03:02 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA31913
HLA:HLA31913 DRA*01:03 254 bases
 MAISGVPVLG FFIIALLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA31953
HLA:HLA31953 DRA*01:04 254 bases
 MAISGVPVLG FFITAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHRGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA32074
HLA:HLA32074 DRA*01:05 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHRGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA38379
HLA:HLA38379 DRA*01:06 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLQNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA38289
HLA:HLA38289 DRA*01:07 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPGEDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA38691
HLA:HLA38691 DRA*01:08 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFAPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA38622
HLA:HLA38622 DRA*01:09 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VILQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA38608
HLA:HLA38608 DRA*01:10 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD CDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA38618
HLA:HLA38618 DRA*01:11 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAEC RGPL    
>P1;HLA:HLA38658
HLA:HLA38658 DRA*01:12 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVHKSNAAER RGPL    
>P1;HLA:HLA38609
HLA:HLA38609 DRA*01:13 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYNCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA38619
HLA:HLA38619 DRA*01:14 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLQNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA38770
HLA:HLA38770 DRA*01:15 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFVP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
>P1;HLA:HLA39591
HLA:HLA39591 DRA*01:16 254 bases
 MTISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICFIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GLRKSNAAER RGPL    
>P1;HLA:HLA39867
HLA:HLA39867 DRA*01:17 254 bases
 MAISGVPVLG FFIIAVLMSA QESWAIKEEH VIIQAEFYLN PDQSGEFMFD FDGDEIFHVD
 MAKKETVWRL EEFGRFASFE AQGALANIAV DKANLEIMTK RSNYTPITNV PPEVTVLTNS
 PVELREPNVL ICLIDKFTPP VVNVTWLRNG KPVTTGVSET VFLPREDHLF RKFHYLPFLP
 STEDVYDCRV EHWGLDEPLL KHWEFDAPSP LPETTENVVC ALGLTVGLVG IIIGTIFIIK
 GVRKSNAAER RGPL    
