>DL;HLA:HLA00887
HLA:HLA00887 DRB3*01:01:02:01 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC AGCTTGGCAG CGTTGACAGT GACACTGATG
 GTGCTGAGCT CCCGACTGGC TTTCGCTGGG GACACCCGAC CACGTTTCTT GGAGCTGCGT
 AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC GGTACCTGGA CAGATACTTC
 CATAACCAGG AGGAGTTCCT GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG
 GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA AGGACCTCCT GGAGCAGAAG
 CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG TTGGTGAGAG CTTCACAGTG
 CAGCGGCGAG TCCATCCTCA GGTGACTGTG TATCCTGCAA AGACCCAGCC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAGTGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CGGGCCTGAT CCAGAATGGA
 GACTGGACCT TCCAGACCCT GGTGATGCTA GAAACAGTTC CTCGGAGTGG AGAGGTTTAC
 ACTTGCCAAG TGGAGCACCC AAGCGTAACG AGCGCTCTCA CAGTGGAATG GAGAGCACGG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGG CCGGGCTGTT CATCTACTTC AGGAATCAGA AAGGACACTC TGGACTTCAG
 CCAACAGGAT TCCTGAGCTG A*   
>DL;HLA:HLA01191
HLA:HLA01191 DRB3*01:01:02:02 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC AGCTTGGCAG CGTTGACAGT GACACTGATG
 GTGCTGAGCT CCCGACTGGC TTTCGCTGGG GACACCCGAC CACGTTTCTT GGAGCTGCGT
 AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC GGTACCTGGA CAGATACTTC
 CATAACCAGG AGGAGTTCCT GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG
 GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA AGGACCTCCT GGAGCAGAAG
 CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG TTGGTGAGAG CTTCACAGTG
 CAGCGGCGAG TCCATCCTCA GGTGACTGTG TATCCTGCAA AGACCCAGCC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAGTGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CGGGCCTGAT CCAGAATGGA
 GACTGGACCT TCCAGACCCT GGTGATGCTA GAAACAGTTC CTCGGAGTGG AGAGGTTTAC
 ACTTGCCAAG TGGAGCACCC AAGCGTAACG AGCGCTCTCA CAGTGGAATG GAGAGCACGG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGG CCGGGCTGTT CATCTACTTC AGGAATCAGA AAGGACACTC TGGACTTCAG
 CCAACAGGAT TCCTGAGCTG A*   
>DL;HLA:HLA00888
HLA:HLA00888 DRB3*01:01:03 264 bases
 GGGGACACCC GACCACGTTT CTTGGAGCTG CGTAAGTCTG AGTGTCATTT CTTCAATGGG
 ACGGAGCGGG TGCGGTACCT GGACAGATAC TTCCATAACC AGGAGGAGTT CCTGCGCTTC
 GACAGCGACG TGGGGGAGTA CCGGGCGGTG ACGGAGCTGG GGCGGCCTGT TGCCGAGTCC
 TGGAACAGCC AGAAGGACCT CCTGGAGCAG AAGCGGGGCC GGGTGGACAA TTACTGCAGA
 CACAACTACG GGGTTGGTGA GAGC*   
>DL;HLA:HLA00889
HLA:HLA00889 DRB3*01:01:04 246 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAACCAGG AGGAGTTCCT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGAG
 TTGGTG*     
>DL;HLA:HLA03432
HLA:HLA03432 DRB3*01:01:05 270 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA CAGATACTTT CATAACCAGG AGGAGTTCCT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA00890
HLA:HLA00890 DRB3*01:02 264 bases
 GGGGACACCC GACCACGTTT CTTGGAGCTG TGTAAGTCTG AGTGTCATTT CTTCAATGGG
 ACGGAGCGGG TGCGGTACCT GGACAGATAC TTCCATAACC AGGAGGAGTT CCTGCGCTTC
 GACAGCGACG TGGGGGAGTA CCGGGCGGTG ACGGAGCTGG GGCGGCCTGT CGCCGAGTCC
 TGGAACAGCC AGAAGGACCT CCTGGAGCAG AAGCGGGGCC GGGTGGACAA TTACTGCAGA
 CACAACTACG GGGTTGGTGA GAGC*   
>DL;HLA:HLA00891
HLA:HLA00891 DRB3*01:03 251 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA GAGATACTTC CATAACCAGG AGGAGTTCCT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG C*    
>DL;HLA:HLA00892
HLA:HLA00892 DRB3*01:04 257 bases
 CACGTTTCTC GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAACCAGG AGGAGTTCCT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACA*    
>DL;HLA:HLA00893
HLA:HLA00893 DRB3*01:05 268 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGAA CAGATACTTC CATAACCAGG AGGAGTTCCT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCG*   
>DL;HLA:HLA01092
HLA:HLA01092 DRB3*01:06 246 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAACCAGG AGGAGTTCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTG*     
>DL;HLA:HLA01093
HLA:HLA01093 DRB3*01:07 246 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTG*     
>DL;HLA:HLA01462
HLA:HLA01462 DRB3*01:08 266 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAACCAGG AGGAGAACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGG*   
>DL;HLA:HLA01505
HLA:HLA01505 DRB3*01:09 266 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGG*   
>DL;HLA:HLA01518
HLA:HLA01518 DRB3*01:10 246 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAACCAGG AGGAGTTCCT GAGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTG*     
>DL;HLA:HLA01818
HLA:HLA01818 DRB3*01:11 270 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA CATATACTTC CATAACCAGG AGGAGTTCCT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA03433
HLA:HLA03433 DRB3*01:12 270 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAACCAGG AGGAGTTCCT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACCGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA03434
HLA:HLA03434 DRB3*01:13 270 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAACCAGG AGGAGCTCCT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA04351
HLA:HLA04351 DRB3*01:14 270 bases
 CACGTTTCTT GGAGTACTCT ACGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAACCAGG AGGAGTTCCT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA06512
HLA:HLA06512 DRB3*01:15 270 bases
 CACGTTTCTT GGAGCTGCGT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTACCTGGA CAGATACTTC CATAACCAGG AGGAGTTCCT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA00894
HLA:HLA00894 DRB3*02:01 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC AGCTTGGCAG CGTTGACAGT GACACTGATG
 GTGCTGAGCT CCCGACTGGC TTTCGCTGGG GACACCCGAC CACGTTTCTT GGAGCTGCTT
 AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC GGTTCCTGGA GAGACACTTC
 CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGAGG
 GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAAG
 CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG TTGTGGAGAG CTTCACAGTG
 CAGCGGCGAG TCCATCCTCA GGTGACTGTG TATCCTGCAA AGACCCAGCC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAGTGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CGGGCCTGAT CCAGAATGGA
 GACTGGACCT TCCAGACCCT GGTGATGCTA GAAACATTTC CTCGGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGCGTAACG AGCCCTCTCA CAGTGGAATG GAGTGCACGG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTCGTGCT GGGCCTGCTC
 TTCCTTGGGG CCGGGCTGTT CATCTACTTC AGGAATCAGA AAGGACACTC TGGACTTCAG
 CCAACAGGAT TCCTGAGCTG A*   
>DL;HLA:HLA00895
HLA:HLA00895 DRB3*02:02:01:01 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC AGCTTGGCAG CGTTGACAGT GACACTGATG
 GTGCTGAGCT CCCGACTGGC TTTCGCTGGG GACACCCGAC CACGTTTCTT GGAGCTGCTT
 AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC GGTTCCTGGA GAGACACTTC
 CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGAGG
 GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAAG
 CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG TTGGTGAGAG CTTCACAGTG
 CAGCGGCGAG TCCATCCTCA GGTGACTGTG TATCCTGCAA AGACCCAGCC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAGTGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CGGGCCTGAT CCAGAATGGA
 GACTGGACCT TCCAGACCCT GGTGATGCTA GAAACAGTTC CTCGGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGCGTAACG AGCCCTCTCA CAGTGGAATG GAGTGCACGG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGG CCGGGCTGTT CATCTACTTC AGGAATCAGA AAGGACACTC TGGACTTCAG
 CCAACAGGAT TCCTGAGCTG A*   
>DL;HLA:HLA06593
HLA:HLA06593 DRB3*02:02:01:02 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC AGCTTGGCAG CGTTGACAGT GACACTGATG
 GTGCTGAGCT CCCGACTGGC TTTCGCTGGG GACACCCGAC CACGTTTCTT GGAGCTGCTT
 AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC GGTTCCTGGA GAGACACTTC
 CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGAGG
 GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAAG
 CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG TTGGTGAGAG CTTCACAGTG
 CAGCGGCGAG TCCATCCTCA GGTGACTGTG TATCCTGCAA AGACCCAGCC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAGTGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CGGGCCTGAT CCAGAATGGA
 GACTGGACCT TCCAGACCCT GGTGATGCTA GAAACAGTTC CTCGGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGCGTAACG AGCCCTCTCA CAGTGGAATG GAGTGCACGG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGG CCGGGCTGTT CATCTACTTC AGGAATCAGA AAGGACACTC TGGACTTCAG
 CCAACAGGAT TCCTGAGCTG A*   
>DL;HLA:HLA01094
HLA:HLA01094 DRB3*02:02:02 246 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAACTA CTGCAGACAC AACTACGGGG
 TTGGTG*     
>DL;HLA:HLA01160
HLA:HLA01160 DRB3*02:02:03 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGGCAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01608
HLA:HLA01608 DRB3*02:02:04 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC GGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA02637
HLA:HLA02637 DRB3*02:02:05 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GTGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA00896
HLA:HLA00896 DRB3*02:03 241 bases
 TTGGAGCTGC TTAAGTCTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT GCGGTTCCTG
 GAGAGACACT TCCATAACCA GGAGGAGTCC GTGCGCTTCG ACAGCGACGT GGGGGAGTAC
 CGGGCGGTGA GGGAGCTGGG GCGGCCTGAT GCCGAGTACT GGAACAGCCA GAAGGACCTC
 CTGGAGCAGA AGCGGGGCCA GGTGGACAAT TACTGCAGAC ACAACTACGG GGTTGGTGAG
 A*     
>DL;HLA:HLA00897
HLA:HLA00897 DRB3*02:04 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAACTA CTGCAGACAC AACTACGGGG
 TTGTGGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA00898
HLA:HLA00898 DRB3*02:05 261 bases
 CGTTTCTTGG AGCTGCTTAA GTCTGAGTGT CATTTCTTCA ATGGGACGGA GCGGGTGCGG
 TTCCTGGAGA GATACTTCCA TAACCAGGAG GAGTACGCGC GCTTCGACAG CGACGTGGGG
 GAGTACCGGG CGGTGAGGGA GCTGGGGCGG CCTGATGCCG AGTACTGGAA CAGCCAGAAG
 GACCTCCTGG AGCAGAAGCG GGGCCAGGTG GACAATTACT GCAGACACAA CTACGGGGTT
 GGTGAGAGCT TCACAGTGCA G*   
>DL;HLA:HLA00899
HLA:HLA00899 DRB3*02:06 246 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGAACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTG*     
>DL;HLA:HLA00900
HLA:HLA00900 DRB3*02:07 242 bases
 TTGGAGCTGC TTAAGTCTGA GTGTCATTTC TTCAATGGGA CGGAGCGGGT GCGGTTCCTG
 GAGAGACACT TCCATAACCA GGAGGAGTAC GCGCGCTTCG ACAGCGACGT GGGGGAGTAC
 CGGGCGGTGA GGGAGCTGGG GCGGCCTGTC GCCGAGTACT GGAACAGCCA GAAGGACCTC
 CTGGAGCAGA AGCGGGGCCA GGTGGACAAT TACTGCAGAC ACAACTACGG GGTTGGTGAG
 AG*     
>DL;HLA:HLA00901
HLA:HLA00901 DRB3*02:08 246 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTAGCGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTG*     
>DL;HLA:HLA01095
HLA:HLA01095 DRB3*02:09 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01157
HLA:HLA01157 DRB3*02:10 714 bases
 GGGGACACCC GACCACGTTT CTTGGAGCTG CTTAAGTCTG AGTGTCATTT CTTCAATGGG
 ACGGAGCGGG TGCGGTTCCT GGAGAGACAC TTCCATAACC AGGAGGAGTA CGCGCGCTTC
 GACAGCGACG TGGGGGAGTA CCGGGCGGTG ACGGAGCTGG GGCGGCCTGA TGCCGAGTAC
 TGGAACAGCC AGAAGGACCT CCTGGAGCAG AAGCGGGGCC AGGTGGACAA TTACTGCAGA
 CACAACTACG GGGTTGGTGA GAGCTTCACA GTGCAGCGGC GAGTCCATCC TCAGGTGACT
 GTGTATCCTG CAAAGACCCA GCCCCTGCAG CACCACAACC TCCTGGTCTG CTCTGTGAGT
 GGTTTCTATC CAGGCAGCAT TGAAGTCAGG TGGTTCCGGA ACGGCCAGGA AGAGAAGGCT
 GGGGTGGTGT CCACGGGCCT GATCCAGAAT GGAGACTGGA CCTTCCAGAC CCTGGTGATG
 CTAGAAACAG TTCCTCGGAG TGGAGAGGTT TACACCTGCC AAGTGGAGCA CCCAAGCGTA
 ACGAGCCCTC TCACAGTGGA ATGGAGTGCA CGGTCTGAAT CTGCACAGAG CAAGATGCTG
 AGTGGAGTCG GGGGCTTTGT GCTGGGCCTG CTCTTCCTTG GGGCCGGGCT GTTCATCTAC
 TTCAGGAATC AGAAAGGACA CTCTGGACTT CAGCCAACAG GATTCCTGAG CTGA*
>DL;HLA:HLA01165
HLA:HLA01165 DRB3*02:11 714 bases
 GGGGACACCC GACCACGTTT CTTGGAGCTG CTTAAGTCTG AGTGTCATTT CTTCAATGGG
 ACGGAGCGGG TGCGGTTCCT GGAGAGACAC TTCCATAACC AGGAGGAGTA CGCGCGCTTC
 GACAGCGACG TGGGGGAGTA CCGGGCGGTG AGGGAGCTGG GGCGGCCTGA TGCCGAGTAC
 TGGAACAGCC AGAAGGACAT CCTGGAGCAG AAGCGGGGCC AGGTGGACAA TTACTGCAGA
 CACAACTACG GGGTTGGTGA GAGCTTCACA GTGCAGCGGC GAGTCCATCC TCAGGTGACT
 GTGTATCCTG CAAAGACCCA GCCCCTGCAG CACCACAACC TCCTGGTCTG CTCTGTGAGT
 GGTTTCTATC CAGGCAGCAT TGAAGTCAGG TGGTTCCGGA ACGGCCAGGA AGAGAAGGCT
 GGGGTGGTGT CCACGGGCCT GATCCAGAAT GGAGACTGGA CCTTCCAGAC CCTGGTGATG
 CTAGAAACAG TTCCTCGGAG TGGAGAGGTT TACACCTGCC AAGTGGAGCA CCCAAGCGTA
 ACGAGCCCTC TCACAGTGGA ATGGAGTGCA CGGTCTGAAT CTGCACAGAG CAAGATGCTG
 AGTGGAGTCG GGGGCTTTGT GCTGGGCCTG CTCTTCCTTG GGGCCGGGCT GTTCATCTAC
 TTCAGGAATC AGAAAGGACA CTCTGGACTT CAGCCAACAG GATTCCTGAG CTGA*
>DL;HLA:HLA01185
HLA:HLA01185 DRB3*02:12 270 bases
 CACGTTTCTT GCAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01190
HLA:HLA01190 DRB3*02:13 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGCTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01444
HLA:HLA01444 DRB3*02:14 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGCTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01542
HLA:HLA01542 DRB3*02:15 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01560
HLA:HLA01560 DRB3*02:16 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGCTGC GGAGCACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01570
HLA:HLA01570 DRB3*02:17 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01769
HLA:HLA01769 DRB3*02:18 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGA GGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01870
HLA:HLA01870 DRB3*02:19 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA02151
HLA:HLA02151 DRB3*02:20 552 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGAACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG TCCATCCTCA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT TTCTATCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA
 CGGGCCTGAT CCAGAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTA GAAACAGTTC
 CTCGGAGTGG AGAGGTTTAC ACCTGCCAAG TGGAGCACCC AAGCGTAACG AGCCCTCTCA
 CAGTGGAATG GA*    
>DL;HLA:HLA02410
HLA:HLA02410 DRB3*02:21 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA02765
HLA:HLA02765 DRB3*02:22 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA03064
HLA:HLA03064 DRB3*02:23 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC TGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA03574
HLA:HLA03574 DRB3*02:24 552 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGTGGAGAG CTTCACAGTG CAGCGGCGAG TCCATCCTCA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT TTCTATCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA
 CGGGCCTGAT CCAGAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTA GAAACAGTTC
 CTCGGAGTGG AGAGGTTTAC ACCTGCCAAG TGGAGCACCC AAGCGTAACG AGCCCTCTCA
 CAGTGGAATG GA*    
>DL;HLA:HLA03989
HLA:HLA03989 DRB3*02:25 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA06515
HLA:HLA06515 DRB3*02:26 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAGG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA06517
HLA:HLA06517 DRB3*02:27 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA06671
HLA:HLA06671 DRB3*02:28 552 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTACGC GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGAGG GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG TCCATCCTCA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAGTGGT TTCTGTCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA
 CGGGCCTGAT CCAGAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTA GAAACAGTTC
 CTCGGAGTGG AGAGGTTTAC ACCTGCCAAG TGGAGCACCC AAGCGTAACG AGCCCTCTCA
 CAGTGGAATG GA*    
>DL;HLA:HLA00902
HLA:HLA00902 DRB3*03:01:01 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC AGCTTGGCAG CGTTGACAGT GACACTGATG
 GTGCTGAGCT CCCGACTGGC TTTCGCTGGG GACACCCGAC CACGTTTCTT GGAGCTGCTT
 AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC GGTTCCTGGA GAGATACTTC
 CATAACCAGG AGGAGTTCGT GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG
 GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA AGGACCTCCT GGAGCAGAAG
 CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG TTGTGGAGAG CTTCACAGTG
 CAGCGGCGAG TCCATCCTCA GGTGACTGTG TATCCTGCAA AGACCCAGCC CCTGCAGCAC
 CACAACCTCC TGGTCTGTTC TGTGAGTGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAATG GCCAGGAAGA GAAGACTGGG GTGGTGTCCA CAGGCCTGAT CCATAATGGA
 GACTGGACCT TCCAGACCCT GGTGATGCTA GAAACAGTTC CTCGGAGTGG AGAGGTTTAC
 ACTTGCCAAG TGGAGCACCC AAGCGTAACA AGCCCTCTCA CAGTGGAATG GAGAGCACGG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGG CCGGGCTGTT CATCTACTTC AGGAATCAGA AAGGACACTC TGGACTTCAG
 CCAACAGGAT TCCTGAGCTG A*   
>DL;HLA:HLA01233
HLA:HLA01233 DRB3*03:01:02 270 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGATACTTC CATAACCAGG AGGAGTTCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGCG
 TTGTGGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA03573
HLA:HLA03573 DRB3*03:01:03 552 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGATACTTC CATAACCAGG AGGAGTTCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGTGGAGAG CTTCACAGTG CAGCGGCGAG TCCATCCTCA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGTTC TGTGAGTGGT TTCTATCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAATG GCCAGGAAGA GAAGACTGGG GTGGTGTCCA
 CAGGCCTGAT CCATAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTA GAAACAGTTC
 CTCGGAGTGG AGAGGTTTAC ACTTGCCAAG TGGAGCACCC AAGCGTAACG AGCCCTCTCA
 CAGTGGAATG GA*    
>DL;HLA:HLA00903
HLA:HLA00903 DRB3*03:02 246 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGACACTTC CATAACCAGG AGGAGTTCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCAGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGTGG*     
>DL;HLA:HLA00904
HLA:HLA00904 DRB3*03:03 552 bases
 CACGTTTCTT GGAGCTGCTT AAGTCTGAGT GTCATTTCTT CAATGGGACG GAGCGGGTGC
 GGTTCCTGGA GAGATACTTC CATAACCAGG AGGAGTTCGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGTCGC CGAGTCCTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAAG CGGGGCCGGG TGGACAATTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG TCCATCCTCA GGTGACTGTG TATCCTGCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGTTC TGTGAGTGGT TTCTATCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAATG GCCAGGAAGA GAAGACTGGG GTGGTGTCCA
 CAGGCCTGAT CCATAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTA GAAACAGTTC
 CTCGGAGTGG AGAGGTTTAC ACTTGCCAAG TGGAGCACCC AAGCGTAACG AGCCCTCTCA
 CAGTGGAATG GA*    
>DL;HLA:HLA00905
HLA:HLA00905 DRB4*01:01:01:01 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGTATGGCAG CGCTGACAGT GACATTGACG
 GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCAAC CACGTTTCTT GGAGCAGGCT
 AAGTGTGAGT GTCATTTCCT CAATGGGACG GAGCGAGTGT GGAACCTGAT CAGATACATC
 TATAACCAAG AGGAGTACGC GCGCTACAAC AGTGACCTGG GGGAGTACCA GGCGGTGACG
 GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCGGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGATAC AACTACGGGG TTGTGGAGAG CTTCACAGTG
 CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTTCAA AGACCCAGCC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACA GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA
 GACTGGACCT TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCGGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCATCC AAGCATGATG AGCCCTCTCA CGGTGCAATG GAGTGCACGG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGA CAGGGCTGTT CATCTACTTC AGGAATCAGA AAGGACACTC TGGACTTCAG
 CCAACAGGAC TCTTGAGCTG A*   
>DL;HLA:HLA00907
HLA:HLA00907 DRB4*01:02 467 bases
 GAGCGAGTGT GGAACCTGAT CAGATACATC TATAACCAAG AGGAGTACGC GCGCTACAAC
 AGTGACCTGG GGGAGTACCA GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG
 AACAGCCAGA AGGACCTCCT GGAGCGGAGG CGGGCCGAGG TGGGCACCTA CTGCAGATAC
 AACTACGGGG TTGTGGAGAG CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG
 TATCCTTCAA AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGT
 TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA GAAGGCTGGG
 GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTG
 GAAACAGTTC CTCGGAGTGG AGAGGTTTAC ACCTGCCAAG TGGAGCA* 
>DL;HLA:HLA00908
HLA:HLA00908 DRB4*01:03:01:01 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGTATGGCAG CGCTGACAGT GACATTGACG
 GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCAAC CACGTTTCTT GGAGCAGGCT
 AAGTGTGAGT GTCATTTCCT CAATGGGACG GAGCGAGTGT GGAACCTGAT CAGATACATC
 TATAACCAAG AGGAGTACGC GCGCTACAAC AGTGACCTGG GGGAGTACCA GGCGGTGACG
 GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCGGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGATAC AACTACGGGG TTGTGGAGAG CTTCACAGTG
 CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTTCAA AGACCCAGCC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA
 GACTGGACCT TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCGGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCATCC AAGCATGATG AGCCCTCTCA CGGTGCAATG GAGTGCACGG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGA CAGGGCTGTT CATCTACTTC AGGAATCAGA AAGGACACTC TGGACTTCAG
 CCAACAGGAC TCTTGAGCTG A*   
>DL;HLA:HLA00909
HLA:HLA00909 DRB4*01:03:01:02N 489 bases
 CACGTTTCTT GGAGCAGGCT AAGTGTGAGT GTCATTTCCT CAATGGGACG GAGCGAGTGT
 GGAACCTGAT CAGATACATC TATAACCAAG AGGAGTACGC GCGCTACAAC AGTGACCTGG
 GGGAGTACCA GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCGGAGG CGGGCCGAGG TGGACACCTA CTGCAGATAC AACTACGGGG
 TTGTGGAGAG CTTCACAGTG CAGCGGCGAG AAAGACCCAG CCCCTGCAGC ACCACAACCT
 CCTGGTCTGC TCTGTGAATG GTTTCTATCC AGGCAGCATT GAAGTCAGGT GGTTCCGGAA
 CGGCCAGGAA GAGAAGGCTG GGGTGGTGTC CACAGGCCTG ATCCAGAATG GAGACTGGAC
 CTTCCAGACC CTGGTGATGC TGGAAACAGT TCCTCGGAGT GGAGAGGTTT ACACCTGCCA
 AGTGGAGCA*     
>DL;HLA:HLA06603
HLA:HLA06603 DRB4*01:03:01:03 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGTATGGCAG CGCTGACAGT GACATTGACG
 GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCAAC CACGTTTCTT GGAGCAGGCT
 AAGTGTGAGT GTCATTTCCT CAATGGGACG GAGCGAGTGT GGAACCTGAT CAGATACATC
 TATAACCAAG AGGAGTACGC GCGCTACAAC AGTGACCTGG GGGAGTACCA GGCGGTGACG
 GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCGGAGG
 CGGGCCGAGG TGGACACCTA CTGCAGATAC AACTACGGGG TTGTGGAGAG CTTCACAGTG
 CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTTCAA AGACCCAGCC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA
 GACTGGACCT TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCGGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCATCC AAGCATGATG AGCCCTCTCA CGGTGCAATG GAGTGCACGG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGA CAGGGCTGTT CATCTACTTC AGGAATCAGA AAGGACACTC TGGACTTCAG
 CCAACAGGAC TCTTGAGCTG A*   
>DL;HLA:HLA00910
HLA:HLA00910 DRB4*01:03:02 714 bases
 GGGGACACCC AACCACGTTT CTTGGAGCAG GCTAAGTGTG AGTGTCATTT CCTCAATGGG
 ACGGAGCGAG TGTGGAACCT GATCAGATAC ATCTATAACC AAGAGGAGTA CGCGCGCTAC
 AACAGTGACC TGGGGGAGTA CCAGGCGGTG ACGGAGCTGG GGCGGCCTGA CGCTGAGTAC
 TGGAACAGCC AGAAGGACCT CCTGGAGCGG AGGCGGGCCG AGGTGGACAC CTACTGCAGA
 TACAACTACG GGGTTGTGGA GAGCTTCACA GTGCAGCGGC GAGTCCAACC TAAGGTGACT
 GTGTATCCTT CAAAGACCCA GCCCCTGCAG CACCACAACC TCCTGGTCTG CTCTGTGAAT
 GGTTTCTATC CAGGCAGCAT TGAAGTCAGG TGGTTCCGGA ACGGCCAGGA AGAGAAGGCT
 GGGGTGGTGT CCACAGGCCT GATCCAGAAT GGAGACTGGA CCTTCCAGAC CCTGGTGATG
 CTGGAAACAG TTCCTCGGAG TGGAGAGGTT TACACCTGCC AAGTGGAGCA TCCAAGCATG
 ATGAGCCCTC TCACAGTGCA ATGGAGTGCA CGGTCTGAAT CTGCACAGAG CAAGATGCTG
 AGTGGAGTCG GGGGCTTTGT GCTGGGCCTG CTCTTCCTTG GGACAGGGCT GTTCATCTAC
 TTCAGGAATC AGAAAGGACA CTCTGGACTT CAGCCAACAG GACTCTTGAG CTGA*
>DL;HLA:HLA01225
HLA:HLA01225 DRB4*01:03:03 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGTATGGCAG CGCTGACAGT GACATTGACG
 GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCAAC CACGTTTCTT GGAGCAGGCT
 AAGTGTGAGT GTCATTTCCT CAATGGGACG GAGCGAGTGT GGAACCTGAT CAGATACATC
 TATAACCAAG AGGAGTACGC GCGCTACAAC AGTGACCTGG GGGAGTACCA GGCGGTGACG
 GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCGGAGG
 CGGGCCGAGG TGGACACCTA TTGCAGATAC AACTACGGGG TTGTGGAGAG CTTCACAGTG
 CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTTCAA AGACCCAGCC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA
 GACTGGACCT TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCGGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCATCC AAGCATGATG AGCCCTCTCA CGGTGCAATG GAGTGCACGG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGA CAGGGCTGTT CATCTACTTC AGGAATCAGA AAGGACACTC TGGACTTCAG
 CCAACAGGAC TCTTGAGCTG A*   
>DL;HLA:HLA01594
HLA:HLA01594 DRB4*01:03:04 509 bases
 CACGTTTCTT GGAGCAGGCT AAGTGTGAGT GTCATTTCCT CAATGGGACG GAGCGAGTGT
 GGAACCTGAT CAGATACATC TATAACCAAG AGGAGTACGC GCGCTACAAC AGTGATCTGG
 GGGAGTACCA GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCGGAGG CGGGCCGAGG TGGACACCTA CTGCAGATAC AACTACGGGG
 TTGTGGAGAG CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTTCAA
 AGACCCAGCC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA
 CAGGCCTGAT CCAGAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTG GAAACAGTTC
 CTCGGAGTGG AGAGGTTTAC ACCTGCCAA*   
>DL;HLA:HLA00911
HLA:HLA00911 DRB4*01:04 270 bases
 CACGTTTCTT GGAGCAGGCT AAGTGTGAGT GTCATTTCCT CAATGGGACG GAGCGAGTGT
 GGAACCTGAT CAGATACATC TATAACCAAG AGGAGTACGC GCGCTACAAC AGTGACCTGG
 GGGAGTACCA GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCGGAGG CGGGCCGAGG TGGACAACTA CTGCAGATAC AACTACGGGG
 TTGTGGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA00912
HLA:HLA00912 DRB4*01:05 242 bases
 TTGGAGCAGG CTAAGTGTGA GTGTCATTTC CTCAATGGGA CGGAGCGAGT GTGGAACCTG
 ATCAGATACA TCTATAACCA AGAGGAGTAC GCGCGCTACA ACAGTGACCT GGGGGAGTAC
 CAGGCGGTGA CGGAGCTGGG GCGGCCTGAC GCTGAGTACT GGAACAGCCA GAAGGACCTC
 CTGGAGCGGA GGCGGGCCGA GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGTGGAG
 AG*     
>DL;HLA:HLA01559
HLA:HLA01559 DRB4*01:06 543 bases
 CACGTTTCTT GGAGCAGGCT AAGTGTGAGT GTCATTTCCT CAATGGGACG GAGCGAGTGT
 GGAACCTGAT CAGATACATC TATAACCAAG AGGAGTACGC GCGCTACAAC AGTGACCTGG
 GGGAGTACCA GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCGGAGG CGGGCCGAGG TGGACACCTA CTGCAGATAC AACTACGGGG
 TTGTGGAGAG CTTCACAGTG CAGCGGCGAG TCCAACCTAA GGTGACTGTG TATCCTTCAA
 AGACCCAGCC CCTGCAGCAC TACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAACA GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA
 CAGGCCTGAT CCAGAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTG GAAACAGTTC
 CTCGGAGTGG AGAGGTTTAC ACCTGCCAAG TGGAGCATCC AAGCATGATG AGCCCTCTCA
 CGG*     
>DL;HLA:HLA01891
HLA:HLA01891 DRB4*01:07 276 bases
 GGGGACACCC AACCACGTTT CTTGGAGCAG GCTAAGTGTG AGTGTCATTT CCTCAATGGG
 ACGGAGCGAG TGTGGAACCT GATCAGATAC ATCTATAACC AAGAGGAGTA CGCGCGCTAC
 AACAGTGACC TGGGGGAGTA CCAGGCGGTG ACGGAGCTGG GGCGGCCTGA CGCTGAGTAC
 TGGAACAGCC AGAAGGACCT CCTGGAGCGG AGGCGGGCCG AGGTGGACAC CTACTGCAGA
 TACAACTACC GGGTTGTGGA GAGCTTCACA GTGCAG*  
>DL;HLA:HLA04572
HLA:HLA04572 DRB4*01:08 270 bases
 CACGTTTCTT GGAGCAGGCT AAGTGTGAGT GTCATTTCCT CAATGGGACG GAGCGAGTGT
 GGAACCTGAT CAGATACATC TATAACCAAG AGGAGTACGC GCGCTACAAC AGTGACCTGG
 GGGAGTACCA GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCGGAGG CGGGCCGAGG TGGACACCTA CTGCAGATAC AACTACGGGG
 TTGTGAAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA00913
HLA:HLA00913 DRB4*02:01N 547 bases
 GGTGCTGAGC TCCCCACTGG CTTTGGCTGG GGACACCCAA CCACGTTTCT TGGAGCAGGC
 TAAGTGTGAG TGTCATTTCC TCAATGGGAC GGAGCCTGAT CAGATACATC TATAACCAAG
 AGGAGTACGC GCGCTACAAC AGTGACCTGG GGGAGTACCA GGCGGTGACG GAGCTGGGGC
 GGCCTGACGC TGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCGGAGG CGGGCCGAGG
 TGGACACCTA CTGCAGATAC AACTACGGGG TTGTGGAGAG CTTCACAGTG CAGCGGCGAG
 TCCAACCTAA GGTGACTGTG TATCCTTCAA AGACCCAGCC CCTGCAGCAC CACAACCTCC
 TGGTCTGCTC TGTGAATGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACA
 GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCGGAGTGG AGAGGTTTAC ACCTGCCAAG
 TGGAGCA*     
>DL;HLA:HLA00914
HLA:HLA00914 DRB4*03:01N 247 bases
 TCCAACCTAA GGTGACTGTG TATCCTTCAA AGACCCAGCC CCTGCAGCAC CACAACCTCC
 TGGTCTGCTC TGTGAATGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG TTCCGGAACA
 GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA GACTGGACCT
 TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCGGAGTGG AGAGGTTTAC ACCTGCCAAG
 TGGAGCA*     
>DL;HLA:HLA00915
HLA:HLA00915 DRB5*01:01:01 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGTTCC TACATGGCAA AGCTGACAGT GACACTGATG
 GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC CACGTTTCTT GCAGCAGGAT
 AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC GGTTCCTGCA CAGAGACATC
 TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG
 GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA AGGACTTCCT GGAAGACAGG
 CGCGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TTGGTGAGAG CTTCACAGTG
 CAGCGGCGAG TTGAGCCTAA GGTGACTGTG TATCCTGCAA GGACCCAGAC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACA GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT TCAGAATGGA
 GACTGGACCT TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCGAAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGCGTGACG AGCCCTCTCA CAGTGGAATG GAGAGCACAG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGG CCGGGCTATT CATCTACTTC AAGAATCAGA AAGGGCACTC TGGACTTCAC
 CCAACAGGAC TCGTGAGCTG A*   
>DL;HLA:HLA00916
HLA:HLA00916 DRB5*01:01:02 257 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAGACAGG CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACA*    
>DL;HLA:HLA00917
HLA:HLA00917 DRB5*01:02 714 bases
 GGGGACACCC GACCACGTTT CTTGCAGCAG GATAAGTATG AGTGTCATTT CTTCAACGGG
 ACGGAGCGGG TGCGGTTCCT GCACAGAGGC ATCTATAACC AAGAGGAGAA CGTGCGCTTC
 GACAGCGACG TGGGGGAGTA CCGGGCGGTG ACGGAGCTGG GGCGGCCTGA CGCTGAGTAC
 TGGAACAGCC AGAAGGACTT CCTGGAAGAC AGGCGCGCCG CGGTGGACAC CTACTGCAGA
 CACAACTACG GGGTTGGTGA GAGCTTCACA GTGCAGCGGC GAGTTGAGCC TAAGGTGACT
 GTGTATCCTG CAAGGACCCA GACCCTGCAG CACCACAACC TCCTGGTCTG CTCTGTGAAT
 GGTTTCTATC CAGGCAGCAT TGAAGTCAGG TGGTTCCGGA ACAGCCAGGA AGAGAAGGCT
 GGGGTGGTGT CCACAGGCCT GATTCAGAAT GGAGACTGGA CCTTCCAGAC CCTGGTGATG
 CTGGAAACAG TTCCTCGAAG TGGAGAGGTT TACACCTGCC AAGTGGAGCA CCCAAGCGTG
 ACGAGCCCTC TCACAGTGGA ATGGAGAGCA CAGTCTGAAT CTGCACAGAG CAAGATGCTG
 AGTGGAGTCG GGGGCTTTGT GCTGGGCCTG CTCTTCCTTG GGGCCGGGCT ATTCATCTAC
 TTCAAGAATC AGAAAGGGCA CTCTGGACTT CACCCAACAG GACTCGTGAG CTGA*
>DL;HLA:HLA00918
HLA:HLA00918 DRB5*01:03 250 bases
 TTGCAGCAGG ATAAGTATGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT GCGGTTCCTG
 CACAGAGGCA TCTATAACCA AGAGGAGAAC GTGCGCTTCG ACAGCGACGT GGGGGAGTAC
 CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC GCTGAGTACT GGAACAGCCA GAAGGACTTC
 CTGGAAGACA CGCGCGCCGC GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGGTGAG
 AGCTTCACAG *    
>DL;HLA:HLA00919
HLA:HLA00919 DRB5*01:04 334 bases
 GGGGACACCC GACCACGTTT CTTGCAGCAG GATAAGTATG AGTGTCATTT CTTCAACGGG
 ACGGAGCGGG TGCGGTTCCT GCACAGAGAC ATCTATAACC AAGAGGAGGA CTTGCGCTTC
 GACAGCGACG TGGGGGAGTA CCGGGCGGTG ACGGAGCTGG GGCGGCCTGA CGCTGAGTAC
 TGGAACAGCC AGAAGGACTT CCTGGAAGAC AGGCGGGCCC TGGTGGACAC CTACTGCAGA
 CACAACTACG GGGTTGGTGA GAGCTTCACA GTGCAGCGGC GAGTTGAGCC TAAGGTGACT
 GTGTATCCTG CAAGGACCCA GACCCTGCAG CACC*  
>DL;HLA:HLA00920
HLA:HLA00920 DRB5*01:05 267 bases
 CCACGTTTCT TGCAGCAGGA TAAGTATGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG
 CGGTTCCTGC ACAGAGACAT CTATAACCAA GAGGAGGACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CTGAGTACTG GAACAGCCAG
 AAGGACTTCC TGGAAGACAG GCGCGCCGCG GTGGACACCT ACTGCAGACA CAACTACGGG
 GTTGGTGAGA GCTTCACAGT GCAGCGG*   
>DL;HLA:HLA00921
HLA:HLA00921 DRB5*01:06 269 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGCAGGCG CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 CTGTGGAGAG CTTCACAGTG CAGCGGCGA*   
>DL;HLA:HLA00922
HLA:HLA00922 DRB5*01:07 246 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAAGACAGG CGCGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTG*     
>DL;HLA:HLA00923
HLA:HLA00923 DRB5*01:08N 500 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGGCATC TATAACCAAG AGGAGAACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAGACAGG CGCGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG TTGAGCCTAA GGTGACTGTG TATCCTGCAA
 GGACCCAGAC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAACA GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA
 CAGGCCTGAT TCAGAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTG GAGAGGTTTA
 CACCTGCCAA GTGGAGCACC *   
>DL;HLA:HLA00924
HLA:HLA00924 DRB5*01:09 246 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAAACAGG CGCGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTG*     
>DL;HLA:HLA01012
HLA:HLA01012 DRB5*01:10N 268 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGGCATC TATAACCAAG AGGAGAACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAGACAGG CGCGCCGCGG TGGACACCTA CTGCACACAA CTACGGGGTT
 GGTGAGAGCT TCACAGTGCA GCGGCGAG*   
>DL;HLA:HLA01638
HLA:HLA01638 DRB5*01:11 270 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGCAGGCG CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01634
HLA:HLA01634 DRB5*01:12 270 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC CGAGTCCTGG AACAGCCAGA
 AGGACTTCCT GGAGCGGAGG CGGGCCGAGG TGGACACCGT GTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01871
HLA:HLA01871 DRB5*01:13 270 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGATGA GGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAGACAGG CGCGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA04132
HLA:HLA04132 DRB5*01:14 552 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAGACAGG CGCGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG TTGAGCCTAA GGTGACTGTG TATCCTGCAA
 GGACCCAGAC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAACA GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA
 CAGGCCTGAT TCAGAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTG GAAACAGTTC
 CTCGAAGTGG AGAGGTTTAC ACCTGCCAAG TGGAGCACCC AAGCGTGACG AGCCCTCTCA
 CAGTGGAATG GA*    
>DL;HLA:HLA00926
HLA:HLA00926 DRB5*02:02 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGTTCC TACATGGCAG TGCTGACAGT GACACTGATG
 GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC CATGTTTCTT GCAGCAGGAT
 AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC GGTTCCTGCA CAGAGGCATC
 TATAACCAAG AGGAGAACGT GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG
 GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCAGGCG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG CTGTGGAGAG CTTCACAGTG
 CAGCGGCGAG TTGAGCCTAA GGTGACTGTG TATCCTGCAA GGACCCAGAC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT TCAGAATGGA
 GACTGGACCT TCCAGATTCT GGTGATGCTG GAAACAGTTC CTCGGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGCGTGACG AGCCCTCTCA CAGTGGAATG GAGAGCACAG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAATCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGG CCGGGCTATT CATCTACTTC AAGAATCAGA AAGGGCACTC TGGACTTCAC
 CCAACAGGAC TCGTGAGCTG A*   
>DL;HLA:HLA00927
HLA:HLA00927 DRB5*02:03 262 bases
 TTTCTTGCAG CAGGATAAGT ATGAGTGTCA TTTCTTCAAC GGGACGGAGC GGGTGCGGTT
 CCTGCACAGA GGCATCTATA ACCAAGAGGA GAACGTGCGC TTCGACAGCG ACGTGGGGGA
 GTACCGGGCG GTGACGGAGC TGGGGCGGCC TGACGCTGAG TACTGGAACA GCCAGAAGGA
 CATCCTGGAG CAGGCGCGGG CCGCGGTGGA CACCTACTGC AGACACAACT ACGGGGTTGG
 TGAGAGCTTC ACAGTGCAGC GG*   
>DL;HLA:HLA00928
HLA:HLA00928 DRB5*02:04 257 bases
 CATGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGGCATC TATAACCAAG AGGAGAACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAGCAGGCG CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 CTGTGGAGAG CTTCACA*    
>DL;HLA:HLA01280
HLA:HLA01280 DRB5*02:05 270 bases
 CATGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGGCATC TATAACCAAG AGGAGAACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAGG CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 CTGTGGAGAG CTTCACAGTG CAGCGGCGAG *  
