>DL;HLA:HLA00664
HLA:HLA00664 DRB1*01:01:01 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGCTCC TGCATGACAG CGCTGACAGT GACACTGATG
 GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC CACGTTTCTT GTGGCAGCTT
 AAGTTTGAAT GTCATTTCTT CAATGGGACG GAGCGGGTGC GGTTGCTGGA AAGATGCATC
 TATAACCAAG AGGAGTCCGT GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG
 GAGCTGGGGC GGCCTGATGC CGAGTACTGG AACAGCCAGA AGGACCTCCT GGAGCAGAGG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TTGGTGAGAG CTTCACAGTG
 CAGCGGCGAG TTGAGCCTAA GGTGACTGTG TATCCTTCAA AGACCCAGCC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAGTGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT CCAGAATGGA
 GATTGGACCT TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCGGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGTGTGACG AGCCCTCTCA CAGTGGAATG GAGAGCACGG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTCGTGCT GGGCCTGCTC
 TTCCTTGGGG CCGGGCTGTT CATCTACTTC AGGAATCAGA AAGGACACTC TGGACTTCAG
 CCAACAGGAT TCCTGAGCTG A*   
>DL;HLA:HLA00915
HLA:HLA00915 DRB5*01:01:01 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGTTCC TACATGGCAA AGCTGACAGT GACACTGATG
 GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC CACGTTTCTT GCAGCAGGAT
 AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC GGTTCCTGCA CAGAGACATC
 TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG
 GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA AGGACTTCCT GGAAGACAGG
 CGCGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG TTGGTGAGAG CTTCACAGTG
 CAGCGGCGAG TTGAGCCTAA GGTGACTGTG TATCCTGCAA GGACCCAGAC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACA GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT TCAGAATGGA
 GACTGGACCT TCCAGACCCT GGTGATGCTG GAAACAGTTC CTCGAAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGCGTGACG AGCCCTCTCA CAGTGGAATG GAGAGCACAG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAGTCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGG CCGGGCTATT CATCTACTTC AAGAATCAGA AAGGGCACTC TGGACTTCAC
 CCAACAGGAC TCGTGAGCTG A*   
>DL;HLA:HLA00916
HLA:HLA00916 DRB5*01:01:02 257 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAGACAGG CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACA*    
>DL;HLA:HLA00917
HLA:HLA00917 DRB5*01:02 714 bases
 GGGGACACCC GACCACGTTT CTTGCAGCAG GATAAGTATG AGTGTCATTT CTTCAACGGG
 ACGGAGCGGG TGCGGTTCCT GCACAGAGGC ATCTATAACC AAGAGGAGAA CGTGCGCTTC
 GACAGCGACG TGGGGGAGTA CCGGGCGGTG ACGGAGCTGG GGCGGCCTGA CGCTGAGTAC
 TGGAACAGCC AGAAGGACTT CCTGGAAGAC AGGCGCGCCG CGGTGGACAC CTACTGCAGA
 CACAACTACG GGGTTGGTGA GAGCTTCACA GTGCAGCGGC GAGTTGAGCC TAAGGTGACT
 GTGTATCCTG CAAGGACCCA GACCCTGCAG CACCACAACC TCCTGGTCTG CTCTGTGAAT
 GGTTTCTATC CAGGCAGCAT TGAAGTCAGG TGGTTCCGGA ACAGCCAGGA AGAGAAGGCT
 GGGGTGGTGT CCACAGGCCT GATTCAGAAT GGAGACTGGA CCTTCCAGAC CCTGGTGATG
 CTGGAAACAG TTCCTCGAAG TGGAGAGGTT TACACCTGCC AAGTGGAGCA CCCAAGCGTG
 ACGAGCCCTC TCACAGTGGA ATGGAGAGCA CAGTCTGAAT CTGCACAGAG CAAGATGCTG
 AGTGGAGTCG GGGGCTTTGT GCTGGGCCTG CTCTTCCTTG GGGCCGGGCT ATTCATCTAC
 TTCAAGAATC AGAAAGGGCA CTCTGGACTT CACCCAACAG GACTCGTGAG CTGA*
>DL;HLA:HLA00918
HLA:HLA00918 DRB5*01:03 250 bases
 TTGCAGCAGG ATAAGTATGA GTGTCATTTC TTCAACGGGA CGGAGCGGGT GCGGTTCCTG
 CACAGAGGCA TCTATAACCA AGAGGAGAAC GTGCGCTTCG ACAGCGACGT GGGGGAGTAC
 CGGGCGGTGA CGGAGCTGGG GCGGCCTGAC GCTGAGTACT GGAACAGCCA GAAGGACTTC
 CTGGAAGACA CGCGCGCCGC GGTGGACACC TACTGCAGAC ACAACTACGG GGTTGGTGAG
 AGCTTCACAG *    
>DL;HLA:HLA00919
HLA:HLA00919 DRB5*01:04 334 bases
 GGGGACACCC GACCACGTTT CTTGCAGCAG GATAAGTATG AGTGTCATTT CTTCAACGGG
 ACGGAGCGGG TGCGGTTCCT GCACAGAGAC ATCTATAACC AAGAGGAGGA CTTGCGCTTC
 GACAGCGACG TGGGGGAGTA CCGGGCGGTG ACGGAGCTGG GGCGGCCTGA CGCTGAGTAC
 TGGAACAGCC AGAAGGACTT CCTGGAAGAC AGGCGGGCCC TGGTGGACAC CTACTGCAGA
 CACAACTACG GGGTTGGTGA GAGCTTCACA GTGCAGCGGC GAGTTGAGCC TAAGGTGACT
 GTGTATCCTG CAAGGACCCA GACCCTGCAG CACC*  
>DL;HLA:HLA00920
HLA:HLA00920 DRB5*01:05 267 bases
 CCACGTTTCT TGCAGCAGGA TAAGTATGAG TGTCATTTCT TCAACGGGAC GGAGCGGGTG
 CGGTTCCTGC ACAGAGACAT CTATAACCAA GAGGAGGACG TGCGCTTCGA CAGCGACGTG
 GGGGAGTACC GGGCGGTGAC GGAGCTGGGG CGGCCTGACG CTGAGTACTG GAACAGCCAG
 AAGGACTTCC TGGAAGACAG GCGCGCCGCG GTGGACACCT ACTGCAGACA CAACTACGGG
 GTTGGTGAGA GCTTCACAGT GCAGCGG*   
>DL;HLA:HLA00921
HLA:HLA00921 DRB5*01:06 269 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGCAGGCG CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 CTGTGGAGAG CTTCACAGTG CAGCGGCGA*   
>DL;HLA:HLA00922
HLA:HLA00922 DRB5*01:07 246 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAAGACAGG CGCGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTG*     
>DL;HLA:HLA00923
HLA:HLA00923 DRB5*01:08N 500 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGGCATC TATAACCAAG AGGAGAACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAGACAGG CGCGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG TTGAGCCTAA GGTGACTGTG TATCCTGCAA
 GGACCCAGAC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAACA GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA
 CAGGCCTGAT TCAGAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTG GAGAGGTTTA
 CACCTGCCAA GTGGAGCACC *   
>DL;HLA:HLA00924
HLA:HLA00924 DRB5*01:09 246 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAAACAGG CGCGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTG*     
>DL;HLA:HLA01012
HLA:HLA01012 DRB5*01:10N 268 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGGCATC TATAACCAAG AGGAGAACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAGACAGG CGCGCCGCGG TGGACACCTA CTGCACACAA CTACGGGGTT
 GGTGAGAGCT TCACAGTGCA GCGGCGAG*   
>DL;HLA:HLA01638
HLA:HLA01638 DRB5*01:11 270 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGCAGGCG CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01634
HLA:HLA01634 DRB5*01:12 270 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC CGAGTCCTGG AACAGCCAGA
 AGGACTTCCT GGAGCGGAGG CGGGCCGAGG TGGACACCGT GTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA01871
HLA:HLA01871 DRB5*01:13 270 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGATGA GGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAGACAGG CGCGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA04132
HLA:HLA04132 DRB5*01:14 552 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGTACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAGACAGG CGCGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG TTGAGCCTAA GGTGACTGTG TATCCTGCAA
 GGACCCAGAC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAACA GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA
 CAGGCCTGAT TCAGAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTG GAAACAGTTC
 CTCGAAGTGG AGAGGTTTAC ACCTGCCAAG TGGAGCACCC AAGCGTGACG AGCCCTCTCA
 CAGTGGAATG GA*    
>DL;HLA:HLA11771
HLA:HLA11771 DRB5*01:15 552 bases
 CACGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGACATC TATAACCAAG AGGAGGACTT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAAGACAGG CGCGCCGCGG TGGACACCGT GTGCAGACAC AACTACGGGG
 TTGGTGAGAG CTTCACAGTG CAGCGGCGAG TTGAGCCTAA GGTGACTGTG TATCCTGCAA
 GGACCCAGAC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAACA GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA
 CAGGCCTGAT TCAGAATGGA GACTGGACCT TCCAGACCCT GGTGATGCTG GAAACAGTTC
 CTCGAAGTGG AGAGGTTTAC ACCTGCCAAG TGGAGCACCC AAGCGTGACG AGCCCTCTCA
 CAGTGGAATG GA*    
>DL;HLA:HLA00926
HLA:HLA00926 DRB5*02:02 801 bases
 ATGGTGTGTC TGAAGCTCCC TGGAGGTTCC TACATGGCAG TGCTGACAGT GACACTGATG
 GTGCTGAGCT CCCCACTGGC TTTGGCTGGG GACACCCGAC CATGTTTCTT GCAGCAGGAT
 AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC GGTTCCTGCA CAGAGGCATC
 TATAACCAAG AGGAGAACGT GCGCTTCGAC AGCGACGTGG GGGAGTACCG GGCGGTGACG
 GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA AGGACATCCT GGAGCAGGCG
 CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG CTGTGGAGAG CTTCACAGTG
 CAGCGGCGAG TTGAGCCTAA GGTGACTGTG TATCCTGCAA GGACCCAGAC CCTGCAGCAC
 CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG GCAGCATTGA AGTCAGGTGG
 TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA CAGGCCTGAT TCAGAATGGA
 GACTGGACCT TCCAGATTCT GGTGATGCTG GAAACAGTTC CTCGGAGTGG AGAGGTTTAC
 ACCTGCCAAG TGGAGCACCC AAGCGTGACG AGCCCTCTCA CAGTGGAATG GAGAGCACAG
 TCTGAATCTG CACAGAGCAA GATGCTGAGT GGAATCGGGG GCTTTGTGCT GGGCCTGCTC
 TTCCTTGGGG CCGGGCTATT CATCTACTTC AAGAATCAGA AAGGGCACTC TGGACTTCAC
 CCAACAGGAC TCGTGAGCTG A*   
>DL;HLA:HLA00927
HLA:HLA00927 DRB5*02:03 262 bases
 TTTCTTGCAG CAGGATAAGT ATGAGTGTCA TTTCTTCAAC GGGACGGAGC GGGTGCGGTT
 CCTGCACAGA GGCATCTATA ACCAAGAGGA GAACGTGCGC TTCGACAGCG ACGTGGGGGA
 GTACCGGGCG GTGACGGAGC TGGGGCGGCC TGACGCTGAG TACTGGAACA GCCAGAAGGA
 CATCCTGGAG CAGGCGCGGG CCGCGGTGGA CACCTACTGC AGACACAACT ACGGGGTTGG
 TGAGAGCTTC ACAGTGCAGC GG*   
>DL;HLA:HLA00928
HLA:HLA00928 DRB5*02:04 257 bases
 CATGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGGCATC TATAACCAAG AGGAGAACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACTTCCT GGAGCAGGCG CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 CTGTGGAGAG CTTCACA*    
>DL;HLA:HLA01280
HLA:HLA01280 DRB5*02:05 270 bases
 CATGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGGCATC TATAACCAAG AGGAGAACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACCTCCT GGAGCAGAGG CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 CTGTGGAGAG CTTCACAGTG CAGCGGCGAG *  
>DL;HLA:HLA08085
HLA:HLA08085 DRB5*02:06 552 bases
 CATGTTTCTT GCAGCAGGAT AAGTATGAGT GTCATTTCTT CAACGGGACG GAGCGGGTGC
 GGTTCCTGCA CAGAGGCATC TATAACCAAG AGGAGAACGT GCGCTTCGAC AGCGACGTGG
 GGGAGTACCG GGCGGTGACG GAGCTGGGGC GGCCTGACGC TGAGTACTGG AACAGCCAGA
 AGGACATCCT GGAGCAGGCG CGGGCCGCGG TGGACACCTA CTGCAGACAC AACTACGGGG
 CTGTGGAGAG CTTCACAGTG CAGCGGCGAG TTGAGCCTGA GGTGACTGTG TATCCTGCAA
 GGACCCAGAC CCTGCAGCAC CACAACCTCC TGGTCTGCTC TGTGAATGGT TTCTATCCAG
 GCAGCATTGA AGTCAGGTGG TTCCGGAACG GCCAGGAAGA GAAGGCTGGG GTGGTGTCCA
 CAGGCCTGAT TCAGAATGGA GACTGGACCT TCCAGATTCT GGTGATGCTG GAAACAGTTC
 CTCGGAGTGG AGAGGTTTAC ACCTGCCAAG TGGAGCACCC AAGCGTGACG AGCCCTCTCA
 CAGTGGAATG GA*    
