>DL;HLA:HLA00934
HLA:HLA00934 E*01:01:01:01 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAACCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CAGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
>DL;HLA:HLA02225
HLA:HLA02225 E*01:01:01:02 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAACCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CAGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
>DL;HLA:HLA02450
HLA:HLA02450 E*01:01:01:03 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAACCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CAGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
>DL;HLA:HLA10665
HLA:HLA10665 E*01:01:02 546 bases
 GCTCCCACTC CTTGAAGTAT TTCCACACTT CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCTC TGTGGGCTAC GTGGACGACA CCCAGTTCGT GCGCTTCGAC AACGACGCCG
 CGAGTCCGAG GATGGTGCCG CGGGCGCCGT GGATGGAGCA GGAGGGGTCA GAGTATTGGG
 ACCGGGAGAC ACGGAGCGCC AGGGACACCG CACAGATTTT CCGAGTGAAT CTGCGGACGC
 TGCGCGGCTA CTACAATCAG AGCGAGGCCG GGTCTCACAC CCTGCAGTGG ATGCATGGCT
 GCGAGCTGGG GCCCGACAGG CGCTTCCTCC GCGGGTATGA ACAGTTCGCC TACGACGGCA
 AGGATTATCT CACCCTGAAT GAGGACCTGC GCTCCTGGAC CGCGGTGGAC ACGGCGGCTC
 AGATCTCCGA GCAAAAGTCA AATGATGCCT CTGAGGCGGA GCACCAGAGA GCCTACCTGG
 AAGACACATG CGTGGAGTGG CTCCACAAAT ACCTGGAGAA GGGGAAGGAG ACGCTGCTTC
 ACCTGG*     
>DL;HLA:HLA00936
HLA:HLA00936 E*01:03:01:01 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAACCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CGGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
>DL;HLA:HLA02226
HLA:HLA02226 E*01:03:01:02 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAACCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CGGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
>DL;HLA:HLA12602
HLA:HLA12602 E*01:03:01:03 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAACCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CGGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
>DL;HLA:HLA00937
HLA:HLA00937 E*01:03:02:01 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAATCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CGGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
>DL;HLA:HLA05913
HLA:HLA05913 E*01:03:02:02 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAATCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CGGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
>DL;HLA:HLA01339
HLA:HLA01339 E*01:03:03 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAATCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CGGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCTTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
>DL;HLA:HLA02224
HLA:HLA02224 E*01:03:04 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAATCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CGGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCAGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
>DL;HLA:HLA07813
HLA:HLA07813 E*01:03:05 886 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAACCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CGGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTC ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGA* 
>DL;HLA:HLA00938
HLA:HLA00938 E*01:04 275 bases
 GGTCTCACAC CCTGCAGTGG ATGCATGGCT GCGAGCTGGG GCCCGACGGG CGCTTCCTCC
 GCGGGTATGA ACAGTTCGCC TACGACGGCA AGGATTATCT CACCCTGAAT GAGGACCTGC
 GCTCCTGGAC CGCGGTGGAC ACGGCGGCTC AGATCTCCGA GCAAAAGTCA AATGATGCCT
 CTGAGGCGGA GCACCAGGGA GCCTACCTGG AAGACACATG CGTGGAGTGG CTCCACAAAT
 ACCTGGAGAA GGGGAAGGAG ACGCTGCTTC ACCTG*  
>DL;HLA:HLA09519
HLA:HLA09519 E*01:05 546 bases
 GCTCCCACTC CTTGAAGTAT TTCCACACTT CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCTC TGTGGGCTAC GTGGACGACA CCCAGTTCGT GCGCTTCGAC AACGACGCCG
 CGAGTCCGAG GATGGTGCCG CGGGCGCCGT GGATGGAGCA GGAGGGGTCA GAGTATTGGG
 ACCGGGAGAC ACGGAGCGCC AGGGACACCG CACAGATTTT CCGAGTGAAC CTGCGGACGC
 TGCGCGGCTA CTACAATCAG AGCAAGGCCG GGTCTCACAC CCTGCAGTGG ATGCATGGCT
 GCGAGCTGGG GCCCGACGGG CGCTTCCTCC GCGGGTATGA ACAGTTCGCC TACGACGGCA
 AGGATTATCT CACCCTGAAT GAGGACCTGC GCTCCTGGAC CGCGGTGGAC ACGGCGGCTC
 AGATCTCCGA GCAAAAGTCA AATGATGCCT CTGAGGCGGA GCACCAGAGA GCCTACCTGG
 AAGACACATG CGTGGAGTGG CTCCACAAAT ACCTGGAGAA GGGGAAGGAG ACGCTGCTTC
 ACCTGG*     
>DL;HLA:HLA09694
HLA:HLA09694 E*01:06 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAACCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CGGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ATCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
>DL;HLA:HLA10666
HLA:HLA10666 E*01:07 546 bases
 GCTCCCACTC CTTGAAGTAT TTCCACACTT CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCTC TGTGGGCTAC GTGGACGACA CCCAGTTCGT GCGCTTCGAC AACGACGCCG
 CGAGTCCGAG GATGGTGCCG CGGGCGCCGT GGATGGAGCA GGAGGGGTCA GAGTATTGGG
 ACCGGGAGAC ACGGAGCGCC AGGGACACCG CACAGATTTT CCGAGTGAAC CTGCGGACGC
 TGCGCGGCTA CTACAATCAG AGCGAGGCCG GGTCTCACAC CCTGCAGTGG ATGCATGGCT
 GCGAGCTGGG GCCCGACAGG CGCTTCCTCC GCGGGTATGA ACAGTTCGCC TACGACGGCA
 AGGATTATCT CACCCTGAAT GAGGACCTGC GCTCCTGGAC CGCGGTGGAC ACGGCGGCTC
 AGATCTCCGA GCAAAAGTCA AATGATGCCT CTGAGGCGGA GCACCAGAGA GTCTACCTGG
 AAGACACATG CGTGGAGTGG CTCCACAAAT ACCTGGAGAA GGGGAAGGAG ACGCTGCTTC
 ACCTGG*     
>DL;HLA:HLA12603
HLA:HLA12603 E*01:08N 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAACCTGCGG
 ACGCTGCGCG GCTAGTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CGGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCAGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
>DL;HLA:HLA13757
HLA:HLA13757 E*01:09 1077 bases
 ATGGTAGATG GAACCCTCCT TTTACTCCTC TCGGAGGCCC TGGCCCTTAC CCAGACCTGG
 GCGGGCTCCC ACTCCTTGAA GTATTTCCAC ACTTCCGTGT CCCGGCCCGG CCGCGGGGAG
 CCCCGCTTCA TCTCTGTGGG CTACGTGGAC GACACCCAGT TCGTGCGCTT CGACAACGAC
 GCCGCGAGTC CGAGGATGGT GCCGCGGGCG CCGTGGATGG AGCAGGAGGG GTCAGAGTAT
 TGGGACCGGG AGACACGGAG CGCCAGGGAC ACCGCACAGA TTTTCCGAGT GAACCTGCGG
 ACGCTGCGCG GCTACTACAA TCAGAGCGAG GCCGGGTCTC ACACCCTGCA GTGGATGCAT
 GGCTGCGAGC TGGGGCCCGA CAGGCGCTTC CTCCGCGGGT ATGAACAGTT CGCCTACGAC
 GGCAAGGATT ATCTCACCCT GAATGAGGAC CTGCGCTCCT GGACCGCGGT GGACACGGCG
 GCTCAGATCT CCGAGCAAAA GTCAAATGAT GCCTCTGAGG CGGAGCACCA GAGAGCCTAC
 CTGGAAGACA CATGCGTGGA GTGGCTCCAC AAATACCTGG AGAAGGGGAA GGAGACGCTG
 CTTCACCTGG AGCCCCCAAA GACACACGTG ACTCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACACTGAC CTGGCAGCAG
 GATGGGGAGG GCCATACCCA GGACACGGAG CTCGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAGCCGAG ATACACGTGC
 CATGTGCAGC ATGAGGGGCT ACCCGAGCCC GTCACCCTGA GATGGAAGCC GGCTTCCCAG
 CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGATC TGTGGTCTCT
 GGAGCTGTGG TTGCTGCTGT GATATGGAGG AAGAAGAGCT CAGGTGGAAA AGGAGGGAGC
 TACTCTAAGG CTGAGTGGAG CGACAGTGCC CAGGGGTCTG AGTCTCACAG CTTGTAA*
