>P1;HLA:HLA00934
HLA:HLA00934 E*01:01:01:01 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA02225
HLA:HLA02225 E*01:01:01:02 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA02450
HLA:HLA02450 E*01:01:01:03 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
<<<<<<< HEAD
=======
>P1;HLA:HLA14497
HLA:HLA14497 E*01:01:01:04 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA14499
HLA:HLA14499 E*01:01:01:05 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA10665
HLA:HLA10665 E*01:01:02 181 bases
 SHSLKYFHTS VSRPGRGEPR FISVGYVDDT QFVRFDNDAA SPRMVPRAPW MEQEGSEYWD
 RETRSARDTA QIFRVNLRTL RGYYNQSEAG SHTLQWMHGC ELGPDRRFLR GYEQFAYDGK
 DYLTLNEDLR SWTAVDTAAQ ISEQKSNDAS EAEHQRAYLE DTCVEWLHKY LEKGKETLLH
 L*     
>>>>>>> Latest
>P1;HLA:HLA00936
HLA:HLA00936 E*01:03:01:01 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA02226
HLA:HLA02226 E*01:03:01:02 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA00937
HLA:HLA00937 E*01:03:02 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA01339
HLA:HLA01339 E*01:03:03 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA02224
HLA:HLA02224 E*01:03:04 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA00938
HLA:HLA00938 E*01:04 91 bases
 SHTLQWMHGC ELGPDGRFLR GYEQFAYDGK DYLTLNEDLR SWTAVDTAAQ ISEQKSNDAS
 EAEHQGAYLE DTCVEWLHKY LEKGKETLLH L*  
<<<<<<< HEAD
=======
>P1;HLA:HLA09519
HLA:HLA09519 E*01:05 181 bases
 SHSLKYFHTS VSRPGRGEPR FISVGYVDDT QFVRFDNDAA SPRMVPRAPW MEQEGSEYWD
 RETRSARDTA QIFRVNLRTL RGYYNQSKAG SHTLQWMHGC ELGPDGRFLR GYEQFAYDGK
 DYLTLNEDLR SWTAVDTAAQ ISEQKSNDAS EAEHQRAYLE DTCVEWLHKY LEKGKETLLH
 L*     
>P1;HLA:HLA09694
HLA:HLA09694 E*01:06 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLSEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA10666
HLA:HLA10666 E*01:07 181 bases
 SHSLKYFHTS VSRPGRGEPR FISVGYVDDT QFVRFDNDAA SPRMVPRAPW MEQEGSEYWD
 RETRSARDTA QIFRVNLRTL RGYYNQSEAG SHTLQWMHGC ELGPDRRFLR GYEQFAYDGK
 DYLTLNEDLR SWTAVDTAAQ ISEQKSNDAS EAEHQRVYLE DTCVEWLHKY LEKGKETLLH
 L*     
>P1;HLA:HLA12603
HLA:HLA12603 E*01:08N 105 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGX* 
>P1;HLA:HLA13757
HLA:HLA13757 E*01:09 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEPRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA14498
HLA:HLA14498 E*01:10 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVIAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>>>>>>> Latest
