>P1;HLA:HLA00934
HLA:HLA00934 E*01:01:01:01 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA02225
HLA:HLA02225 E*01:01:01:02 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA02450
HLA:HLA02450 E*01:01:01:03 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA00936
HLA:HLA00936 E*01:03:01:01 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA02226
HLA:HLA02226 E*01:03:01:02 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA00937
HLA:HLA00937 E*01:03:02:01 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA05913
HLA:HLA05913 E*01:03:02:02 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA01339
HLA:HLA01339 E*01:03:03 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA02224
HLA:HLA02224 E*01:03:04 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA07813
HLA:HLA07813 E*01:03:05 295 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRW*
>P1;HLA:HLA00938
HLA:HLA00938 E*01:04 91 bases
 SHTLQWMHGC ELGPDGRFLR GYEQFAYDGK DYLTLNEDLR SWTAVDTAAQ ISEQKSNDAS
 EAEHQGAYLE DTCVEWLHKY LEKGKETLLH L*  
