>P1;HLA:HLA00934
HLA:HLA00934 E*01:01:01:01 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA02225
HLA:HLA02225 E*01:01:01:02 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA02450
HLA:HLA02450 E*01:01:01:03 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA14497
HLA:HLA14497 E*01:01:01:04 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA14499
HLA:HLA14499 E*01:01:01:05 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA15627
HLA:HLA15627 E*01:01:01:06 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA15628
HLA:HLA15628 E*01:01:01:07 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA16323
HLA:HLA16323 E*01:01:01:08 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA17337
HLA:HLA17337 E*01:01:01:09 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA18020
HLA:HLA18020 E*01:01:01:10 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA24287
HLA:HLA24287 E*01:01:01:11 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA24131
HLA:HLA24131 E*01:01:01:12 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26715
HLA:HLA26715 E*01:01:01:13 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26740
HLA:HLA26740 E*01:01:01:14 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26767
HLA:HLA26767 E*01:01:01:15 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26611
HLA:HLA26611 E*01:01:01:16 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26743
HLA:HLA26743 E*01:01:01:17 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26588
HLA:HLA26588 E*01:01:01:18 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26626
HLA:HLA26626 E*01:01:01:19 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26594
HLA:HLA26594 E*01:01:01:20 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26657
HLA:HLA26657 E*01:01:01:21 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26592
HLA:HLA26592 E*01:01:01:22 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26661
HLA:HLA26661 E*01:01:01:23 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26756
HLA:HLA26756 E*01:01:01:24 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26714
HLA:HLA26714 E*01:01:01:25 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26687
HLA:HLA26687 E*01:01:01:26 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26711
HLA:HLA26711 E*01:01:01:27 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26608
HLA:HLA26608 E*01:01:01:28 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26635
HLA:HLA26635 E*01:01:01:29 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA10665
HLA:HLA10665 E*01:01:02 181 bases
 SHSLKYFHTS VSRPGRGEPR FISVGYVDDT QFVRFDNDAA SPRMVPRAPW MEQEGSEYWD
 RETRSARDTA QIFRVNLRTL RGYYNQSEAG SHTLQWMHGC ELGPDRRFLR GYEQFAYDGK
 DYLTLNEDLR SWTAVDTAAQ ISEQKSNDAS EAEHQRAYLE DTCVEWLHKY LEKGKETLLH
 L*     
>P1;HLA:HLA26716
HLA:HLA26716 E*01:01:03 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26655
HLA:HLA26655 E*01:01:04 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26678
HLA:HLA26678 E*01:01:05 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26675
HLA:HLA26675 E*01:01:06 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA00936
HLA:HLA00936 E*01:03:01:01 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA02226
HLA:HLA02226 E*01:03:01:02 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA12602
HLA:HLA12602 E*01:03:01:03 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA16324
HLA:HLA16324 E*01:03:01:04 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA23915
HLA:HLA23915 E*01:03:01:05 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA23913
HLA:HLA23913 E*01:03:01:06 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA24825
HLA:HLA24825 E*01:03:01:07 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26731
HLA:HLA26731 E*01:03:01:08 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26724
HLA:HLA26724 E*01:03:01:09 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26649
HLA:HLA26649 E*01:03:01:10 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26610
HLA:HLA26610 E*01:03:01:11 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA00937
HLA:HLA00937 E*01:03:02:01 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA05913
HLA:HLA05913 E*01:03:02:02 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA22411
HLA:HLA22411 E*01:03:02:03 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA24045
HLA:HLA24045 E*01:03:02:04 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA23995
HLA:HLA23995 E*01:03:02:05 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA23888
HLA:HLA23888 E*01:03:02:06 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA24341
HLA:HLA24341 E*01:03:02:07 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA24031
HLA:HLA24031 E*01:03:02:08 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26587
HLA:HLA26587 E*01:03:02:09 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26670
HLA:HLA26670 E*01:03:02:10 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26719
HLA:HLA26719 E*01:03:02:11 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26660
HLA:HLA26660 E*01:03:02:12 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26758
HLA:HLA26758 E*01:03:02:13 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26703
HLA:HLA26703 E*01:03:02:14 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26730
HLA:HLA26730 E*01:03:02:15 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26606
HLA:HLA26606 E*01:03:02:16 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26676
HLA:HLA26676 E*01:03:02:17 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA01339
HLA:HLA01339 E*01:03:03 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA02224
HLA:HLA02224 E*01:03:04 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA07813
HLA:HLA07813 E*01:03:05:01 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26663
HLA:HLA26663 E*01:03:05:02 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA22323
HLA:HLA22323 E*01:03:06 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA24136
HLA:HLA24136 E*01:03:07 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA00938
HLA:HLA00938 E*01:04 91 bases
 SHTLQWMHGC ELGPDGRFLR GYEQFAYDGK DYLTLNEDLR SWTAVDTAAQ ISEQKSNDAS
 EAEHQGAYLE DTCVEWLHKY LEKGKETLLH L*  
>P1;HLA:HLA09519
HLA:HLA09519 E*01:05 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSK AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA09694
HLA:HLA09694 E*01:06 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLSEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA10666
HLA:HLA10666 E*01:07 181 bases
 SHSLKYFHTS VSRPGRGEPR FISVGYVDDT QFVRFDNDAA SPRMVPRAPW MEQEGSEYWD
 RETRSARDTA QIFRVNLRTL RGYYNQSEAG SHTLQWMHGC ELGPDRRFLR GYEQFAYDGK
 DYLTLNEDLR SWTAVDTAAQ ISEQKSNDAS EAEHQRVYLE DTCVEWLHKY LEKGKETLLH
 L*     
>P1;HLA:HLA12603
HLA:HLA12603 E*01:08N 105 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGX* 
>P1;HLA:HLA13757
HLA:HLA13757 E*01:09 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEPRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA14498
HLA:HLA14498 E*01:10:01:01 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVIAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26596
HLA:HLA26596 E*01:10:01:02 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVIAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA22421
HLA:HLA22421 E*01:11 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISNHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA23945
HLA:HLA23945 E*01:12:01:01 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKQASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA24163
HLA:HLA24163 E*01:12:01:02 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKQASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA23839
HLA:HLA23839 E*01:13 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGLEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA24640
HLA:HLA24640 E*01:14 358 bases
 MVDGTLLLLL SEALAVTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26673
HLA:HLA26673 E*01:15 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYLH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDRRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26747
HLA:HLA26747 E*01:16 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELRPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
>P1;HLA:HLA26737
HLA:HLA26737 E*01:17 358 bases
 MVDGTLLLLL SEALALTQTW AGSHSLKYFH TSVSRPGRGE PRFISVGYVD DTQFVRFDND
 AASPRMVPRA PWMEQEGSEY WDRETRSARD TAQIFRVNLR TLRGYYNQSE AGSHTLQWMH
 GCELGPDGRF LRGYEQFAYD GKDYLTLNED LRSWTAVDTA AQISEQKSND ASEAEHQRAY
 LEDTCVEWLH KYLEKGKETL LHLEPPKTHV THHPISDHEA TLRCWALGFY PAEITLTWQQ
 DGEGHTQDVE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP VTLRWKPASQ
 PTIPIVGIIA GLVLLGSVVS GAVVAAVIWR KKSSGGKGGS YSKAEWSDSA QGSESHSL*
