>DL;HLA:HLA01096
HLA:HLA01096 F*01:01:01:01 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02280
HLA:HLA02280 F*01:01:01:02 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02263
HLA:HLA02263 F*01:01:01:03 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02271
HLA:HLA02271 F*01:01:01:04 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02274
HLA:HLA02274 F*01:01:01:05 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02266
HLA:HLA02266 F*01:01:01:06 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02269
HLA:HLA02269 F*01:01:01:07 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02647
HLA:HLA02647 F*01:01:01:08 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02275
HLA:HLA02275 F*01:01:01:09 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02270
HLA:HLA02270 F*01:01:01:10 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02277
HLA:HLA02277 F*01:01:01:11 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02278
HLA:HLA02278 F*01:01:01:12 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA17164
HLA:HLA17164 F*01:01:01:13 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA17268
HLA:HLA17268 F*01:01:01:14 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA18019
HLA:HLA18019 F*01:01:01:15 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA18021
HLA:HLA18021 F*01:01:01:16 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA21228
HLA:HLA21228 F*01:01:01:17 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA21304
HLA:HLA21304 F*01:01:01:18 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA21360
HLA:HLA21360 F*01:01:01:19 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA01755
HLA:HLA01755 F*01:01:02:01 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCAGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02265
HLA:HLA02265 F*01:01:02:02 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCAGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02273
HLA:HLA02273 F*01:01:02:03 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCAGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02279
HLA:HLA02279 F*01:01:02:04 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCAGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02264
HLA:HLA02264 F*01:01:02:05 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCAGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA05914
HLA:HLA05914 F*01:01:02:06 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCAGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA17561
HLA:HLA17561 F*01:01:02:07 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCAGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA18055
HLA:HLA18055 F*01:01:02:08 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCAGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA21499
HLA:HLA21499 F*01:01:02:09 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCAGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA21300
HLA:HLA21300 F*01:01:02:10 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCAGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA21929
HLA:HLA21929 F*01:01:02:11 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCAGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02267
HLA:HLA02267 F*01:02 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGTCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02276
HLA:HLA02276 F*01:03:01:01 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTCCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02268
HLA:HLA02268 F*01:03:01:02 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTCCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA17982
HLA:HLA17982 F*01:03:01:03 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTCCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA21470
HLA:HLA21470 F*01:03:01:04 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTCCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA02272
HLA:HLA02272 F*01:04 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CAGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA17339
HLA:HLA17339 F*01:05 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTATTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCTCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
>DL;HLA:HLA19135
HLA:HLA19135 F*01:06 1041 bases
 ATGGCGCCCC GAAGCCTCCT CCTGCTGCTC TCAGGGGCCC TGGCCCTGAC CGATACTTGG
 GCGGGCTCCC ACTCCTTGAG GTTTTTCAGC ACCGCTGTGT CGCGGCCCGG CCGCGGGGAG
 CCCCGCTACA TCGCCGTGGA GTACGTAGAC GACACGCAAT TCCTGCGGTT CGACAGCGAC
 GCCGCGATTC CGAGGATGGA GCCGCGGGAG CCGTGGGTGG AGCAAGAGGG GCCGCAGTAT
 TGGGAGTGGA CCACAGGGTA CGCCAAGGCC AACGCACAGA CTGACCGAGT GGCCCTGAGG
 AACCTGCTCC GCCGCTACAA CCAGAGCGAG GCTGGGTCTC ACACCCTCCA GGGAATGAAT
 GGCTGCGACA TGGGGCCCGA CGGACGCCTC CTCCGCGGGT ATCACCAGCA CGCGTACGAC
 GGCAAGGATT ACATCTCCCT GAACGAGGAC CTGCGCTCCT GGACCGCGGC GGACACCGTG
 GCTCAGATCA CCCAGCGCTT CTATGAGGCA GAGGAATATG CAGAGGAGTT CAGGACCTAC
 CTGGAGGGCG AGTGCCTGGA GTTGCTCCGC AGATACTTGG AGAATGGGAA GGAGACGCTA
 CAGCGCGCAG ATCCTCCAAA GGCACACGTT GCCCACCACC CCATCTCTGA CCATGAGGCC
 ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGCGGAGA TCACGCTGAC CTGGCAGCGG
 GATGGGGAGG AACAGACCCA GGACACAGAG CTTGTGGAGA CCAGGCCTGC AGGGGATGGA
 ACCTTCCAGA AGTGGGCCGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG ATACACATGC
 CATGTGCAGC ACGAGGGGCT GCCCCAGCCC CTCATCCTGA GATGGGAGCA GTCTCCCCAG
 CCCACCATCC CCATCGTGGG CATCGTTGCT GGCCTTGTTG TCCTTGGAGC TGTGGTCACT
 GGAGCTGTGG TCGCTGCTGT GATGTGGAGG AAGAAGAGCT CAGATAGAAA CAGAGGGAGC
 TACTCTCAGG CTGCAGTGTG A*   
