>P1;HLA:HLA01096
HLA:HLA01096 F*01:01:01:01 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02280
HLA:HLA02280 F*01:01:01:02 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02263
HLA:HLA02263 F*01:01:01:03 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02271
HLA:HLA02271 F*01:01:01:04 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02274
HLA:HLA02274 F*01:01:01:05 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02266
HLA:HLA02266 F*01:01:01:06 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02269
HLA:HLA02269 F*01:01:01:07 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02647
HLA:HLA02647 F*01:01:01:08 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02275
HLA:HLA02275 F*01:01:01:09 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02270
HLA:HLA02270 F*01:01:01:10 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02277
HLA:HLA02277 F*01:01:01:11 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02278
HLA:HLA02278 F*01:01:01:12 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA17164
HLA:HLA17164 F*01:01:01:13 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA17268
HLA:HLA17268 F*01:01:01:14 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA18019
HLA:HLA18019 F*01:01:01:15 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA18021
HLA:HLA18021 F*01:01:01:16 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA21228
HLA:HLA21228 F*01:01:01:17 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA21304
HLA:HLA21304 F*01:01:01:18 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA21360
HLA:HLA21360 F*01:01:01:19 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA22256
HLA:HLA22256 F*01:01:01:20 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA22478
HLA:HLA22478 F*01:01:01:21 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA29008
HLA:HLA29008 F*01:01:01:22 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA35825
HLA:HLA35825 F*01:01:01:23 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38199
HLA:HLA38199 F*01:01:01:24 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38266
HLA:HLA38266 F*01:01:01:25 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38276
HLA:HLA38276 F*01:01:01:26 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38330
HLA:HLA38330 F*01:01:01:27 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38377
HLA:HLA38377 F*01:01:01:28 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38304
HLA:HLA38304 F*01:01:01:29 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38305
HLA:HLA38305 F*01:01:01:30 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38485
HLA:HLA38485 F*01:01:01:31 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38422
HLA:HLA38422 F*01:01:01:32 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38469
HLA:HLA38469 F*01:01:01:33 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38183
HLA:HLA38183 F*01:01:01:34 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38486
HLA:HLA38486 F*01:01:01:35 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38443
HLA:HLA38443 F*01:01:01:36 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38408
HLA:HLA38408 F*01:01:01:37 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38518
HLA:HLA38518 F*01:01:01:38 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38428
HLA:HLA38428 F*01:01:01:39 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38216
HLA:HLA38216 F*01:01:01:40 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38302
HLA:HLA38302 F*01:01:01:41 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38419
HLA:HLA38419 F*01:01:01:42 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38474
HLA:HLA38474 F*01:01:01:43 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA40728
HLA:HLA40728 F*01:01:01:44 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA41225
HLA:HLA41225 F*01:01:01:45 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA41280
HLA:HLA41280 F*01:01:01:46 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA41457
HLA:HLA41457 F*01:01:01:47 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA41717
HLA:HLA41717 F*01:01:01:48 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA41734
HLA:HLA41734 F*01:01:01:49 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA41751
HLA:HLA41751 F*01:01:01:50 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA41724
HLA:HLA41724 F*01:01:01:51 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA41589
HLA:HLA41589 F*01:01:01:52 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA41646
HLA:HLA41646 F*01:01:01:53 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA41675
HLA:HLA41675 F*01:01:01:54 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA01755
HLA:HLA01755 F*01:01:02:01 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02265
HLA:HLA02265 F*01:01:02:02 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02273
HLA:HLA02273 F*01:01:02:03 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02279
HLA:HLA02279 F*01:01:02:04 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02264
HLA:HLA02264 F*01:01:02:05 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA05914
HLA:HLA05914 F*01:01:02:06 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA17561
HLA:HLA17561 F*01:01:02:07 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA18055
HLA:HLA18055 F*01:01:02:08 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA21499
HLA:HLA21499 F*01:01:02:09 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA21300
HLA:HLA21300 F*01:01:02:10 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA21929
HLA:HLA21929 F*01:01:02:11 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA22339
HLA:HLA22339 F*01:01:02:12 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA35867
HLA:HLA35867 F*01:01:02:13 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38514
HLA:HLA38514 F*01:01:02:14 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA41691
HLA:HLA41691 F*01:01:02:15 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA22431
HLA:HLA22431 F*01:01:04 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA22750
HLA:HLA22750 F*01:01:05 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA32356
HLA:HLA32356 F*01:01:06 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA32453
HLA:HLA32453 F*01:01:07 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA33857
HLA:HLA33857 F*01:01:08 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA35225
HLA:HLA35225 F*01:01:09 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38267
HLA:HLA38267 F*01:01:10 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38147
HLA:HLA38147 F*01:01:11 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02267
HLA:HLA02267 F*01:02:01:01 346 bases
 MAPRSLLLLL SGVLALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA35880
HLA:HLA35880 F*01:02:01:02 346 bases
 MAPRSLLLLL SGVLALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02276
HLA:HLA02276 F*01:03:01:01 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PPGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02268
HLA:HLA02268 F*01:03:01:02 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PPGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA17982
HLA:HLA17982 F*01:03:01:03 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PPGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA21470
HLA:HLA21470 F*01:03:01:04 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PPGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA34439
HLA:HLA34439 F*01:03:01:05 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PPGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38288
HLA:HLA38288 F*01:03:01:06 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PPGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA34956
HLA:HLA34956 F*01:03:02 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PPGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA02272
HLA:HLA02272 F*01:04:01:01 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE QWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA22420
HLA:HLA22420 F*01:04:01:02 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE QWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA17339
HLA:HLA17339 F*01:05:01:01 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSLQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA41709
HLA:HLA41709 F*01:05:01:02 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSLQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA19135
HLA:HLA19135 F*01:06 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRFFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA33592
HLA:HLA33592 F*01:07 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGKEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA35014
HLA:HLA35014 F*01:08 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRTAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA34858
HLA:HLA34858 F*01:09 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRANPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PPGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA34883
HLA:HLA34883 F*01:10 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETP QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA34948
HLA:HLA34948 F*01:11 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVTAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA37646
HLA:HLA37646 F*01:12 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAFD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38210
HLA:HLA38210 F*01:13N 48 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEX 
>P1;HLA:HLA38138
HLA:HLA38138 F*01:14N 139 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAX    
>P1;HLA:HLA38107
HLA:HLA38107 F*01:15 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRAALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38339
HLA:HLA38339 F*01:16 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYY GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PPGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38197
HLA:HLA38197 F*01:17 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIARMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38130
HLA:HLA38130 F*01:18 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRCYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA38437
HLA:HLA38437 F*01:19 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTL AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA40310
HLA:HLA40310 F*01:20 346 bases
 MAPRSLLLLL SGALALTDTW AGCHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
>P1;HLA:HLA40729
HLA:HLA40729 F*01:21 346 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPPE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAV 
