>P1;HLA:HLA01096
HLA:HLA01096 F*01:01:01:01 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02280
HLA:HLA02280 F*01:01:01:02 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02263
HLA:HLA02263 F*01:01:01:03 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02271
HLA:HLA02271 F*01:01:01:04 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02274
HLA:HLA02274 F*01:01:01:05 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02266
HLA:HLA02266 F*01:01:01:06 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02269
HLA:HLA02269 F*01:01:01:07 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02647
HLA:HLA02647 F*01:01:01:08 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA01755
HLA:HLA01755 F*01:01:02:01 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02265
HLA:HLA02265 F*01:01:02:02 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02273
HLA:HLA02273 F*01:01:02:03 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02279
HLA:HLA02279 F*01:01:02:04 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02264
HLA:HLA02264 F*01:01:02:05 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02275
HLA:HLA02275 F*01:01:03:01 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02270
HLA:HLA02270 F*01:01:03:02 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02277
HLA:HLA02277 F*01:01:03:03 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02278
HLA:HLA02278 F*01:01:03:04 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02267
HLA:HLA02267 F*01:02 362 bases
 MAPRSLLLLL SGVLALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02276
HLA:HLA02276 F*01:03:01:01 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PPGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02268
HLA:HLA02268 F*01:03:01:02 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE PWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PPGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
>P1;HLA:HLA02272
HLA:HLA02272 F*01:04 362 bases
 MAPRSLLLLL SGALALTDTW AGSHSLRYFS TAVSRPGRGE PRYIAVEYVD DTQFLRFDSD
 AAIPRMEPRE QWVEQEGPQY WEWTTGYAKA NAQTDRVALR NLLRRYNQSE AGSHTLQGMN
 GCDMGPDGRL LRGYHQHAYD GKDYISLNED LRSWTAADTV AQITQRFYEA EEYAEEFRTY
 LEGECLELLR RYLENGKETL QRADPPKAHV AHHPISDHEA TLRCWALGFY PAEITLTWQR
 DGEEQTQDTE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPQP LILRWEQSPQ
 PTIPIVGIVA GLVVLGAVVT GAVVAAVMWR KKSSDRNRGS YSQAAVTDSA QGSGVSLTAN
 KV*     
