>DL;HLA:HLA00939
HLA:HLA00939 G*01:01:01:01 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA02283
HLA:HLA02283 G*01:01:01:02 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA02288
HLA:HLA02288 G*01:01:01:03 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA02281
HLA:HLA02281 G*01:01:01:04 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA02282
HLA:HLA02282 G*01:01:01:05 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA03588
HLA:HLA03588 G*01:01:01:06 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA17057
HLA:HLA17057 G*01:01:01:07 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA17163
HLA:HLA17163 G*01:01:01:08 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA22340
HLA:HLA22340 G*01:01:01:09 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA22635
HLA:HLA22635 G*01:01:01:10 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA22787
HLA:HLA22787 G*01:01:01:11 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA26876
HLA:HLA26876 G*01:01:01:12 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA26791
HLA:HLA26791 G*01:01:01:13 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA27878
HLA:HLA27878 G*01:01:01:14Q 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA00940
HLA:HLA00940 G*01:01:02:01 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GTCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA02285
HLA:HLA02285 G*01:01:02:02 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GTCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA22996
HLA:HLA22996 G*01:01:02:03 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GTCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA26990
HLA:HLA26990 G*01:01:02:04 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GTCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA00941
HLA:HLA00941 G*01:01:03:01 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGTCGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA03807
HLA:HLA03807 G*01:01:03:02 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGTCGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA07532
HLA:HLA07532 G*01:01:03:03 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGTCGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA18110
HLA:HLA18110 G*01:01:03:04 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGTCGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA00942
HLA:HLA00942 G*01:01:04 545 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCG GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCTCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCG*     
>DL;HLA:HLA00943
HLA:HLA00943 G*01:01:05 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGTCGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA00944
HLA:HLA00944 G*01:01:06 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACATGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA00945
HLA:HLA00945 G*01:01:07 821 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGT CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG G* 
>DL;HLA:HLA00946
HLA:HLA00946 G*01:01:08 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA02284
HLA:HLA02284 G*01:01:09 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAAGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA02954
HLA:HLA02954 G*01:01:11 895 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCGTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGA*
>DL;HLA:HLA02972
HLA:HLA02972 G*01:01:12 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCTTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA02973
HLA:HLA02973 G*01:01:13 546 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCATAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGG*     
>DL;HLA:HLA03159
HLA:HLA03159 G*01:01:14 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGATTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA03553
HLA:HLA03553 G*01:01:15 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAAGGGCCG GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA03552
HLA:HLA03552 G*01:01:16 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CGGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA03556
HLA:HLA03556 G*01:01:17 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGTT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA03557
HLA:HLA03557 G*01:01:18 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CAGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA03558
HLA:HLA03558 G*01:01:19 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACATGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA04419
HLA:HLA04419 G*01:01:20 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GTCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA07536
HLA:HLA07536 G*01:01:21 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTCTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA17338
HLA:HLA17338 G*01:01:22:01 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA22484
HLA:HLA22484 G*01:01:22:02 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA22571
HLA:HLA22571 G*01:01:22:03 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA22351
HLA:HLA22351 G*01:01:23 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCAGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA26786
HLA:HLA26786 G*01:01:24 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTATAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA27277
HLA:HLA27277 G*01:01:25 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACTT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGAA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA00947
HLA:HLA00947 G*01:02 944 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCG GGAGGGGCCG GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCCGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GAAGCAGTCT TCCCTGCCCA
 CCATCCCCAT CATGGGTATC GTTGCTGGCC TGGTTGTCCT TGCAGCTGTA GTCACTGGAG
 CTGCGGTCGC TGCTGTGCTG TGGAGAAAGA AGAGCTCAGA TTGA* 
>DL;HLA:HLA00948
HLA:HLA00948 G*01:03:01:01 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACTCGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACATGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA06452
HLA:HLA06452 G*01:03:01:02 1017 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACTCGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACATGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA00949
HLA:HLA00949 G*01:04:01:01 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCA TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA18022
HLA:HLA18022 G*01:04:01:02 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCA TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA22243
HLA:HLA22243 G*01:04:01:03 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCA TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA27538
HLA:HLA27538 G*01:04:01:04Q 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCA TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA00950
HLA:HLA00950 G*01:04:02 821 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCC GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCATCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CATGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG G* 
>DL;HLA:HLA00951
HLA:HLA00951 G*01:04:03 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCA TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA02287
HLA:HLA02287 G*01:04:04 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCA TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCAGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA03555
HLA:HLA03555 G*01:04:05 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAATTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCATCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA18826
HLA:HLA18826 G*01:04:06 939 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCATCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACATG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GAAGCAGTCT TCCCTGCCCA
 CCATCCCCAT CATGGGTATC GTTGCTGGCC TGGTTGTCCT TGCAGCTGTA GTCACTGGAG
 CTGCGGTCGC TGCTGTGCTG TGGAGAAAGA AGAGCTCAG*  
>DL;HLA:HLA00952
HLA:HLA00952 G*01:05N 1016 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACT GCGCTCCTGG ACCGCAGCGG
 ACACTGCGGC TCAGATCTCC AAGCGCAAGT GTGAGGCGGC CAATGTGGCT GAACAAAGGA
 GAGCCTACCT GGAGGGCACG TGCGTGGAGT GGCTCCACAG ATACCTGGAG AACGGGAAGG
 AGATGCTGCA GCGCGCGGAC CCCCCCAAGA CACACGTGAC CCACCACCCT GTCTTTGACT
 ATGAGGCCAC CCTGAGGTGC TGGGCCCTGG GCTTCTACCC TGCGGAGATC ATACTGACCT
 GGCAGCGGGA TGGGGAGGAC CAGACCCAGG ACGTGGAGCT CGTGGAGACC AGGCCTGCAG
 GGGATGGAAC CTTCCAGAAG TGGGCAGCTG TGGTGGTGCC TTCTGGAGAG GAGCAGAGAT
 ACACGTGCCA TGTGCAGCAT GAGGGGCTGC CGGAGCCCCT CATGCTGAGA TGGAAGCAGT
 CTTCCCTGCC CACCATCCCC ATCATGGGTA TCGTTGCTGG TCTGGTTGTC CTTGCAGCTG
 TAGTCACTGG AGCTGCGGTC GCTGCTGTGC TGTGGAGGAA GAAGAGCTCA GATTGA*
>DL;HLA:HLA01357
HLA:HLA01357 G*01:06:01:01 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACATGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GTCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA27242
HLA:HLA27242 G*01:06:01:02 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACATGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GTCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA02286
HLA:HLA02286 G*01:07 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTT CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCA TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA02876
HLA:HLA02876 G*01:08:01 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGTGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA14680
HLA:HLA14680 G*01:08:02 895 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GTTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGTGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGA*
>DL;HLA:HLA02969
HLA:HLA02969 G*01:09 546 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCCACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGG*     
>DL;HLA:HLA03192
HLA:HLA03192 G*01:10 546 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA TGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCG GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGG*     
>DL;HLA:HLA03193
HLA:HLA03193 G*01:11 546 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA TGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCATCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGG*     
>DL;HLA:HLA03396
HLA:HLA03396 G*01:12 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCCAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA03397
HLA:HLA03397 G*01:13N 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGTA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA03398
HLA:HLA03398 G*01:14 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGACT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCAGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ATGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA03399
HLA:HLA03399 G*01:15 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGT GTCCGACGGA CGCCTCATCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA03400
HLA:HLA03400 G*01:16 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTGCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ATGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA04000
HLA:HLA04000 G*01:17 546 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCGCAGAC ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGG*     
>DL;HLA:HLA08306
HLA:HLA08306 G*01:18 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CGCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA13776
HLA:HLA13776 G*01:19 822 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCCT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCATCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GA* 
>DL;HLA:HLA14685
HLA:HLA14685 G*01:20 546 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGT CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC
 GCGCGG*     
>DL;HLA:HLA17755
HLA:HLA17755 G*01:21N 821 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 TGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCACAC CCTCCAGTGG ATGATTGGCT
 GCGACCTGGG GTCCGACGGA CGCCTCATCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGCGGGATG
 GGGAGGACCA GACCTAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG G* 
>DL;HLA:HLA18538
HLA:HLA18538 G*01:22 939 bases
 GCTCCCACTC CATGAGGTAT TTCAGCGCCG CCGTGTCCCG GCCCGGCCGC GGGGAGCCCC
 GCTTCATCGC CATGGGCTAC GTGGACGACA CGCAGTTCGT GCGGTTCGAC AGCGACTCGG
 CGTGTCCGAG GATGGAGCCG CGGGCGCCGT GGGTGGAGCA GGAGGGGCCA GAGTATTGGG
 AAGAGGAGAC ACGGAACACC AAGGCCCACG CACAGACTGA CAGAATGAAC CTGCAGACCC
 CGCGCGGCTA CTACAACCAG AGCGAGGCCA GTTCTCATAC CCTCCAGTGG ATGATTGGTT
 GCGACCTGGG GTCCGACGGA CGCCTCCTCC GCGGGTATGA ACAGTATGCC TACGATGGCA
 AGGATTACCT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCAGCGGAC ACTGCGGCTC
 AGATCTCCAA GCGCAAGTGT GAGGCGGCCA ATGTGGCTGA ACAAAGGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCACAGAT ACCTGGAGAA CGGGAAGGAG ATGCTGCAGC
 GCGCGGACCC CCCCAAGACA CACGTGACCC ACCACCCTGT CTTTGACTAT GAGGCCACCC
 TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAT ACTGACCTGG CAGTGGGATG
 GGGAGGACCA GACCCAGGAC GTGGAGCTCG TGGAGACCAG GCCTGCAGGG GATGGAACCT
 TCCAGAAGTG GGCAGCTGTG GTGGTGCCTT CTGGAGAGGA GCAGAGATAC ACGTGCCATG
 TGCAGCATGA GGGGCTGCCG GAGCCCCTCA TGCTGAGATG GGAGCAGTCT TCCCTGCCCA
 CCATCCCCAT CATGGGTATC GTTGCTGGCC TGGTTGTCCT TGCAGCTGTA GTCACTGGAG
 CTGCGGTCGC TGCTGTGCTG TGGAGGAAGA AGAGCTCAG*  
>DL;HLA:HLA26781
HLA:HLA26781 G*01:23 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTATTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCA TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GCCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CGCTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA27226
HLA:HLA27226 G*01:24 1017 bases
 ATGGTGGTCA TGGCACCCCG AACCCTCTTC CTGCTACTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCAGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA TACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCTCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCAGCG
 GACACTGCGG CTCAGATCTC CAAGCGCAAG TGTGAGGCGG CCAATGTGGC TGAACAAAGG
 AGAGCCTACC TGGAGGGCAC GTGCGTGGAG TGGCTCCACA GATACCTGGA GAACGGGAAG
 GAGATGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTTTGAC
 TATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CATACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACGTGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACGTGCC ATGTGCAGCA TGAGGGGCTG CCGGAGCCCC TCATGCTGAG ATGGAAGCAG
 TCTTCCCTGC CCACCATCCC CATCATGGGT ATCGTTGCTG GTCTGGTTGT CCTTGCAGCT
 GTAGTCACTG GAGCTGCGGT CACTGCTGTG CTGTGGAGGA AGAAGAGCTC AGATTGA*
>DL;HLA:HLA27282
HLA:HLA27282 G*01:25N 1015 bases
 ATGGTGGTCA TGGCGCCCCG AACCCTCTTC CTGCTGCTCT CGGGGGCCCT GACCCTGACC
 GAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCAGCG CCGCCGTGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CGCCATGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACT CGGCGTGTCC GAGGATGGAG CCGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CCGGAGTATT GGGAAGAGGA GACACGGAAC ACCAAGGCCC ACGCACAGAC TGACAGAATG
 AACCTGCAGA CCCTGCGCGG CTACTACAAC CAGAGCGAGG CCAGTTCTCA CACCCTCCAG
 TGGATGATTG GCTGCGACCT GGGGTCCGAC GGACGCCTCC TCCGCGGGTA TGAACAGTAT
 GCCTACGATG GCAAGGATTA CCGCCCTGAA CGAGGACCTG CGCTCCTGGA CCGCAGCGGA
 CACTGCGGCT CAGATCTCCA AGCGCAAGTG TGAGGCGGCC AATGTGGCTG AACAAAGGAG
 AGCCTACCTG GAGGGCACGT GCGTGGAGTG GCTCCACAGA TACCTGGAGA ACGGGAAGGA
 GATGCTGCAG CGCGCGGACC CCCCCAAGAC ACACGTGACC CACCACCCTG TCTTTGACTA
 TGAGGCCACC CTGAGGTGCT GGGCCCTGGG CTTCTACCCT GCGGAGATCA TACTGACCTG
 GCAGCGGGAT GGGGAGGACC AGACCCAGGA CGTGGAGCTC GTGGAGACCA GGCCTGCAGG
 GGATGGAACC TTCCAGAAGT GGGCAGCTGT GGTGGTGCCT TCTGGAGAGG AGCAGAGATA
 CACGTGCCAT GTGCAGCATG AGGGGCTGCC GGAGCCCCTC ATGCTGAGAT GGAAGCAGTC
 TTCCCTGCCC ACCATCCCCA TCATGGGTAT CGTTGCTGGC CTGGTTGTCC TTGCAGCTGT
 AGTCACTGGA GCTGCGGTCG CTGCTGTGCT GTGGAGAAAG AAGAGCTCAG ATTGA*
