>P1;HLA:HLA00939
HLA:HLA00939 G*01:01:01:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA02283
HLA:HLA02283 G*01:01:01:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA02288
HLA:HLA02288 G*01:01:01:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA02281
HLA:HLA02281 G*01:01:01:04 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA02282
HLA:HLA02282 G*01:01:01:05 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA03588
HLA:HLA03588 G*01:01:01:06 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA17057
HLA:HLA17057 G*01:01:01:07 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA17163
HLA:HLA17163 G*01:01:01:08 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA22340
HLA:HLA22340 G*01:01:01:09 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA22635
HLA:HLA22635 G*01:01:01:10 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA22787
HLA:HLA22787 G*01:01:01:11 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA26876
HLA:HLA26876 G*01:01:01:12 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA26791
HLA:HLA26791 G*01:01:01:13 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA27878
HLA:HLA27878 G*01:01:01:14Q 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA34610
HLA:HLA34610 G*01:01:01:15 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA35937
HLA:HLA35937 G*01:01:01:16 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA36910
HLA:HLA36910 G*01:01:01:17 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA36798
HLA:HLA36798 G*01:01:01:18 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38319
HLA:HLA38319 G*01:01:01:19 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38263
HLA:HLA38263 G*01:01:01:20 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38221
HLA:HLA38221 G*01:01:01:21 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38333
HLA:HLA38333 G*01:01:01:22 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38484
HLA:HLA38484 G*01:01:01:23 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38100
HLA:HLA38100 G*01:01:01:24 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38270
HLA:HLA38270 G*01:01:01:25 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38269
HLA:HLA38269 G*01:01:01:26 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38326
HLA:HLA38326 G*01:01:01:27 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38355
HLA:HLA38355 G*01:01:01:28 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38120
HLA:HLA38120 G*01:01:01:29 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38286
HLA:HLA38286 G*01:01:01:30 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38369
HLA:HLA38369 G*01:01:01:31 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38257
HLA:HLA38257 G*01:01:01:32 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38373
HLA:HLA38373 G*01:01:01:33 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA40730
HLA:HLA40730 G*01:01:01:34 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA40731
HLA:HLA40731 G*01:01:01:35 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA40829
HLA:HLA40829 G*01:01:01:36 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA40817
HLA:HLA40817 G*01:01:01:37 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA00940
HLA:HLA00940 G*01:01:02:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA02285
HLA:HLA02285 G*01:01:02:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA22996
HLA:HLA22996 G*01:01:02:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA26990
HLA:HLA26990 G*01:01:02:04 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA34776
HLA:HLA34776 G*01:01:02:05Q 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA36812
HLA:HLA36812 G*01:01:02:06 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA37634
HLA:HLA37634 G*01:01:02:07 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38362
HLA:HLA38362 G*01:01:02:08 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38429
HLA:HLA38429 G*01:01:02:09 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38396
HLA:HLA38396 G*01:01:02:10 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38188
HLA:HLA38188 G*01:01:02:11 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38363
HLA:HLA38363 G*01:01:02:12 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA40732
HLA:HLA40732 G*01:01:02:13 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA40851
HLA:HLA40851 G*01:01:02:14 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA00941
HLA:HLA00941 G*01:01:03:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA03807
HLA:HLA03807 G*01:01:03:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA07532
HLA:HLA07532 G*01:01:03:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA18110
HLA:HLA18110 G*01:01:03:04 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38366
HLA:HLA38366 G*01:01:03:05 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA00942
HLA:HLA00942 G*01:01:04 181 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 A     
>P1;HLA:HLA00943
HLA:HLA00943 G*01:01:05 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA00944
HLA:HLA00944 G*01:01:06 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA00945
HLA:HLA00945 G*01:01:07 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW  
>P1;HLA:HLA00946
HLA:HLA00946 G*01:01:08 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA02284
HLA:HLA02284 G*01:01:09 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA02954
HLA:HLA02954 G*01:01:11 298 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRW
>P1;HLA:HLA02972
HLA:HLA02972 G*01:01:12 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA02973
HLA:HLA02973 G*01:01:13 181 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 A     
>P1;HLA:HLA03159
HLA:HLA03159 G*01:01:14 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA03553
HLA:HLA03553 G*01:01:15 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA03552
HLA:HLA03552 G*01:01:16 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA03556
HLA:HLA03556 G*01:01:17 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA03557
HLA:HLA03557 G*01:01:18 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW  
>P1;HLA:HLA03558
HLA:HLA03558 G*01:01:19 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA04419
HLA:HLA04419 G*01:01:20 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA07536
HLA:HLA07536 G*01:01:21 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA17338
HLA:HLA17338 G*01:01:22:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA22484
HLA:HLA22484 G*01:01:22:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA22571
HLA:HLA22571 G*01:01:22:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA28767
HLA:HLA28767 G*01:01:22:04 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38410
HLA:HLA38410 G*01:01:22:05 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38187
HLA:HLA38187 G*01:01:22:06 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA22351
HLA:HLA22351 G*01:01:23 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA26786
HLA:HLA26786 G*01:01:24 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA27277
HLA:HLA27277 G*01:01:25 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA30865
HLA:HLA30865 G*01:01:26 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA34382
HLA:HLA34382 G*01:01:27 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA34359
HLA:HLA34359 G*01:01:28 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA35718
HLA:HLA35718 G*01:01:29 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA35806
HLA:HLA35806 G*01:01:30:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA35687
HLA:HLA35687 G*01:01:30:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38480
HLA:HLA38480 G*01:01:31 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA00947
HLA:HLA00947 G*01:02 313 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEREGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRWKQSSLPT IPIMGIVAGL VVLAAVVTGA
 AVAAVLWRKK SSD    
>P1;HLA:HLA00948
HLA:HLA00948 G*01:03:01:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDSQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA06452
HLA:HLA06452 G*01:03:01:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDSQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA00949
HLA:HLA00949 G*01:04:01:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA18022
HLA:HLA18022 G*01:04:01:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA22243
HLA:HLA22243 G*01:04:01:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA27538
HLA:HLA27538 G*01:04:01:04Q 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA32227
HLA:HLA32227 G*01:04:01:05 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA36799
HLA:HLA36799 G*01:04:01:06 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA36814
HLA:HLA36814 G*01:04:01:07 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38327
HLA:HLA38327 G*01:04:01:08 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38301
HLA:HLA38301 G*01:04:01:09 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA40273
HLA:HLA40273 G*01:04:01:10 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA00950
HLA:HLA00950 G*01:04:02 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLIR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW  
>P1;HLA:HLA00951
HLA:HLA00951 G*01:04:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA02287
HLA:HLA02287 G*01:04:04:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38356
HLA:HLA38356 G*01:04:04:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA03555
HLA:HLA03555 G*01:04:05 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA18826
HLA:HLA18826 G*01:04:06 312 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLIR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRWKQSSLPT IPIMGIVAGL VVLAAVVTGA
 AVAAVLWRKK SS    
>P1;HLA:HLA32219
HLA:HLA32219 G*01:04:07 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38134
HLA:HLA38134 G*01:04:08 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38890
HLA:HLA38890 G*01:04:09 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA40841
HLA:HLA40841 G*01:04:10 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA00952
HLA:HLA00952 G*01:05:01N 213 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDCAPGPQR TLRLRSPSAS VRRPMWLNKG
 EPTWRARAWS GSTDTWRTGR RCCSARTPPR HTX  
>P1;HLA:HLA35882
HLA:HLA35882 G*01:05:02N 213 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDCAPGPQR TLRLRSPSAS VRRPMWLNKG
 EPTWRARAWS GSTDTWRTGR RCCSARTPPR HTX  
>P1;HLA:HLA01357
HLA:HLA01357 G*01:06:01:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YMCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA27242
HLA:HLA27242 G*01:06:01:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YMCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38265
HLA:HLA38265 G*01:06:01:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YMCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA33886
HLA:HLA33886 G*01:06:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YMCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA02286
HLA:HLA02286 G*01:07 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVFRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA02876
HLA:HLA02876 G*01:08:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQWDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA14680
HLA:HLA14680 G*01:08:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQWDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA02969
HLA:HLA02969 G*01:09 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAHLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YMCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA03192
HLA:HLA03192 G*01:10 181 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDM QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 A     
>P1;HLA:HLA03193
HLA:HLA03193 G*01:11 337 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDMQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSS  
>P1;HLA:HLA03396
HLA:HLA03396 G*01:12 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGHVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW  
>P1;HLA:HLA03397
HLA:HLA03397 G*01:13N 53 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEX
>P1;HLA:HLA03398
HLA:HLA03398 G*01:14 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIDC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQQDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYMCHV QHEGLPEPLM LRW  
>P1;HLA:HLA03399
HLA:HLA03399 G*01:15 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLVSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA03400
HLA:HLA03400 G*01:16 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGCDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYMCHV QHEGLPEPLM LRW  
>P1;HLA:HLA04000
HLA:HLA04000 G*01:17 181 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLRRH LENGKEMLQR
 A     
>P1;HLA:HLA08306
HLA:HLA08306 G*01:18 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPAKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW  
>P1;HLA:HLA13776
HLA:HLA13776 G*01:19 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFLRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLIR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW  
>P1;HLA:HLA14685
HLA:HLA14685 G*01:20 181 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKETLQR
 A     
>P1;HLA:HLA17755
HLA:HLA17755 G*01:21N 250 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTX     
>P1;HLA:HLA18538
HLA:HLA18538 G*01:22 312 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTP RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQWDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRWEQSSLPT IPIMGIVAGL VVLAAVVTGA
 AVAAVLWRKK SS    
>P1;HLA:HLA26781
HLA:HLA26781 G*01:23 338 bases
 MVVMAPRTLF LLFSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA27226
HLA:HLA27226 G*01:24 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVTAV LWRKKSSD  
>P1;HLA:HLA27282
HLA:HLA27282 G*01:25N 171 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYRPE RGPALLDRSG HCGSDLQAQV X
>P1;HLA:HLA28771
HLA:HLA28771 G*01:26 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKTSD  
>P1;HLA:HLA31323
HLA:HLA31323 G*01:27 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TMAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YMCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA31010
HLA:HLA31010 G*01:28N 137 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGX    
>P1;HLA:HLA31330
HLA:HLA31330 G*01:29 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YLSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA31028
HLA:HLA31028 G*01:30 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPCFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA31436
HLA:HLA31436 G*01:31 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFVAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA32598
HLA:HLA32598 G*01:32 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NQDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA32596
HLA:HLA32596 G*01:33 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTEAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA33686
HLA:HLA33686 G*01:34 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSH GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA33635
HLA:HLA33635 G*01:35 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME ARAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA34252
HLA:HLA34252 G*01:36Q 333 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GYEQYAYDGK DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE
 GTCVEWLHRY LENGKEMLQR ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG
 EDQTQDVELV ETRPAGDGTF QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRWKQSSLPT
 IPIMGIVAGL VVLAAVVTGA AVAAVLWRKK SSD  
>P1;HLA:HLA34272
HLA:HLA34272 G*01:37 338 bases
 MVVMAPRTIF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA34275
HLA:HLA34275 G*01:38Q 335 bases
 MAPRTLFLLL SGALTLTETW AGSHSMRYFS AAVSRPGRGE PRFIAMGYVD DTQFVRFDSD
 SACPRMEPRA PWVEQEGPEY WEEETRNTKA HAQTDRMNLQ TLRGYYNQSE ASSHTLQWMI
 GCDLGSDGRL LRGYEQYAYD GKDYLALNED LRSWTAADTA AQISKRKCEA ANVAEQRRAY
 LEGTCVEWLH RYLENGKEML QRADPPKTHV THHPVFDYEA TLRCWALGFY PAEIILTWQR
 DGEDQTQDVE LVETRPAGDG TFQKWAAVVV PSGEEQRYTC HVQHEGLPEP LMLRWKQSSL
 PTIPIMGIVA GLVVLAAVVT GAAVAAVLWR KKSSD  
>P1;HLA:HLA34318
HLA:HLA34318 G*01:39 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PESLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA34291
HLA:HLA34291 G*01:40 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMFGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA35819
HLA:HLA35819 G*01:41 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIATG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA36655
HLA:HLA36655 G*01:42 337 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSE GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSS  
>P1;HLA:HLA36821
HLA:HLA36821 G*01:43 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSTAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA37438
HLA:HLA37438 G*01:44 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELMETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA37415
HLA:HLA37415 G*01:45 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKR
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA37528
HLA:HLA37528 G*01:46 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAATVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38361
HLA:HLA38361 G*01:47 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL LEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38086
HLA:HLA38086 G*01:48 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKPK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38460
HLA:HLA38460 G*01:49 338 bases
 MVVMAPRTLF LLLSGALTLT ETWTGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38338
HLA:HLA38338 G*01:50Q 349 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLGS CSHWSCGRCC AVEKEELRLK RRELLSGCK 
>P1;HLA:HLA38393
HLA:HLA38393 G*01:51 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ VVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38208
HLA:HLA38208 G*01:52 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YMCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVILAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA38171
HLA:HLA38171 G*01:53 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAYAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA39676
HLA:HLA39676 G*01:54 338 bases
 MVVMAPRTLF LLLSGSLTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA39754
HLA:HLA39754 G*01:55 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLILRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
>P1;HLA:HLA40888
HLA:HLA40888 G*01:56 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKGHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD  
