>P1;HLA:HLA00939
HLA:HLA00939 G*01:01:01:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA02283
HLA:HLA02283 G*01:01:01:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA02288
HLA:HLA02288 G*01:01:01:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA02281
HLA:HLA02281 G*01:01:01:04 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA02282
HLA:HLA02282 G*01:01:01:05 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA03588
HLA:HLA03588 G*01:01:01:06 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA17057
HLA:HLA17057 G*01:01:01:07 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA17163
HLA:HLA17163 G*01:01:01:08 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA22340
HLA:HLA22340 G*01:01:01:09 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA22635
HLA:HLA22635 G*01:01:01:10 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA22787
HLA:HLA22787 G*01:01:01:11 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA26876
HLA:HLA26876 G*01:01:01:12 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA26791
HLA:HLA26791 G*01:01:01:13 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA27878
HLA:HLA27878 G*01:01:01:14Q 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA00940
HLA:HLA00940 G*01:01:02:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA02285
HLA:HLA02285 G*01:01:02:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA22996
HLA:HLA22996 G*01:01:02:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA26990
HLA:HLA26990 G*01:01:02:04 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA00941
HLA:HLA00941 G*01:01:03:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA03807
HLA:HLA03807 G*01:01:03:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA07532
HLA:HLA07532 G*01:01:03:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA18110
HLA:HLA18110 G*01:01:03:04 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA00942
HLA:HLA00942 G*01:01:04 181 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 A*     
>P1;HLA:HLA00943
HLA:HLA00943 G*01:01:05 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA00944
HLA:HLA00944 G*01:01:06 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA00945
HLA:HLA00945 G*01:01:07 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA00946
HLA:HLA00946 G*01:01:08 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA02284
HLA:HLA02284 G*01:01:09 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA02954
HLA:HLA02954 G*01:01:11 298 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRW*
>P1;HLA:HLA02972
HLA:HLA02972 G*01:01:12 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA02973
HLA:HLA02973 G*01:01:13 181 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 A*     
>P1;HLA:HLA03159
HLA:HLA03159 G*01:01:14 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA03553
HLA:HLA03553 G*01:01:15 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA03552
HLA:HLA03552 G*01:01:16 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA03556
HLA:HLA03556 G*01:01:17 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA03557
HLA:HLA03557 G*01:01:18 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA03558
HLA:HLA03558 G*01:01:19 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA04419
HLA:HLA04419 G*01:01:20 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA07536
HLA:HLA07536 G*01:01:21 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA17338
HLA:HLA17338 G*01:01:22:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA22484
HLA:HLA22484 G*01:01:22:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA22571
HLA:HLA22571 G*01:01:22:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA22351
HLA:HLA22351 G*01:01:23 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA26786
HLA:HLA26786 G*01:01:24 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA27277
HLA:HLA27277 G*01:01:25 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA00947
HLA:HLA00947 G*01:02 313 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEREGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRWKQSSLPT IPIMGIVAGL VVLAAVVTGA
 AVAAVLWRKK SSD*    
>P1;HLA:HLA00948
HLA:HLA00948 G*01:03:01:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDSQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA06452
HLA:HLA06452 G*01:03:01:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDSQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA00949
HLA:HLA00949 G*01:04:01:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA18022
HLA:HLA18022 G*01:04:01:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA22243
HLA:HLA22243 G*01:04:01:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA27538
HLA:HLA27538 G*01:04:01:04Q 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA00950
HLA:HLA00950 G*01:04:02 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLIR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA00951
HLA:HLA00951 G*01:04:03 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA02287
HLA:HLA02287 G*01:04:04 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA03555
HLA:HLA03555 G*01:04:05 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLIR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA18826
HLA:HLA18826 G*01:04:06 312 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLIR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRWKQSSLPT IPIMGIVAGL VVLAAVVTGA
 AVAAVLWRKK SS*    
>P1;HLA:HLA00952
HLA:HLA00952 G*01:05N 213 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDCAPGPQR TLRLRSPSAS VRRPMWLNKG
 EPTWRARAWS GSTDTWRTGR RCCSARTPPR HTX*  
>P1;HLA:HLA01357
HLA:HLA01357 G*01:06:01:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YMCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA27242
HLA:HLA27242 G*01:06:01:02 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YMCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA02286
HLA:HLA02286 G*01:07 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVFRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA02876
HLA:HLA02876 G*01:08:01 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQWDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA14680
HLA:HLA14680 G*01:08:02 298 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQWDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRW*
>P1;HLA:HLA02969
HLA:HLA02969 G*01:09 181 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAHLE GTCVEWLHRY LENGKEMLQR
 A*     
>P1;HLA:HLA03192
HLA:HLA03192 G*01:10 181 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDM QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 A*     
>P1;HLA:HLA03193
HLA:HLA03193 G*01:11 181 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDM QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLIR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 A*     
>P1;HLA:HLA03396
HLA:HLA03396 G*01:12 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGHVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA03397
HLA:HLA03397 G*01:13N 53 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEX*
>P1;HLA:HLA03398
HLA:HLA03398 G*01:14 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIDC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQQDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYMCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA03399
HLA:HLA03399 G*01:15 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLVSDGRLIR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA03400
HLA:HLA03400 G*01:16 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGCDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYMCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA04000
HLA:HLA04000 G*01:17 181 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLRRH LENGKEMLQR
 A*     
>P1;HLA:HLA08306
HLA:HLA08306 G*01:18 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPAKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA13776
HLA:HLA13776 G*01:19 273 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFLRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLIR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRW*  
>P1;HLA:HLA14685
HLA:HLA14685 G*01:20 181 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKETLQR
 A*     
>P1;HLA:HLA17755
HLA:HLA17755 G*01:21N 225 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTL RGYYNQSEAS SHTLQWMIGC DLGSDGRLIR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQRDG EDQTX* 
>P1;HLA:HLA18538
HLA:HLA18538 G*01:22 312 bases
 SHSMRYFSAA VSRPGRGEPR FIAMGYVDDT QFVRFDSDSA CPRMEPRAPW VEQEGPEYWE
 EETRNTKAHA QTDRMNLQTP RGYYNQSEAS SHTLQWMIGC DLGSDGRLLR GYEQYAYDGK
 DYLALNEDLR SWTAADTAAQ ISKRKCEAAN VAEQRRAYLE GTCVEWLHRY LENGKEMLQR
 ADPPKTHVTH HPVFDYEATL RCWALGFYPA EIILTWQWDG EDQTQDVELV ETRPAGDGTF
 QKWAAVVVPS GEEQRYTCHV QHEGLPEPLM LRWEQSSLPT IPIMGIVAGL VVLAAVVTGA
 AVAAVLWRKK SS*    
>P1;HLA:HLA26781
HLA:HLA26781 G*01:23 338 bases
 MVVMAPRTLF LLFSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLIRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVAAV LWRKKSSD*  
>P1;HLA:HLA27226
HLA:HLA27226 G*01:24 338 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYLAL NEDLRSWTAA DTAAQISKRK CEAANVAEQR
 RAYLEGTCVE WLHRYLENGK EMLQRADPPK THVTHHPVFD YEATLRCWAL GFYPAEIILT
 WQRDGEDQTQ DVELVETRPA GDGTFQKWAA VVVPSGEEQR YTCHVQHEGL PEPLMLRWKQ
 SSLPTIPIMG IVAGLVVLAA VVTGAAVTAV LWRKKSSD*  
>P1;HLA:HLA27282
HLA:HLA27282 G*01:25N 171 bases
 MVVMAPRTLF LLLSGALTLT ETWAGSHSMR YFSAAVSRPG RGEPRFIAMG YVDDTQFVRF
 DSDSACPRME PRAPWVEQEG PEYWEEETRN TKAHAQTDRM NLQTLRGYYN QSEASSHTLQ
 WMIGCDLGSD GRLLRGYEQY AYDGKDYRPE RGPALLDRSG HCGSDLQAQV X*
