>DL;HLA:HLA02546
HLA:HLA02546 H*01:01:01:01 1096 bases
 ATGGTGCTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT GGCCCTGACC
 CAGACCTGGG CGCGCTCCCA CTCCATGAGG TATTTCTACA CCACCATGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CTCCGTCGGC TACGTGGACG ATACGCAGTT CGTGCGGTTC
 GACAGCGACG CCGCGAGCCA GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCGGGAGGGG
 CCGGAGTATT GGGACCGGAA CACACAGATC TGCAAGGCCC AGGCACAGAC TGAACGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG GCGGTTCTCA CACCATGCAG
 GTGATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCTTCC TCCGCGGGTA TGAACAGCAC
 GCCTACGACA GCAAGGATTA CATCGCTCTG AACGAGGACC TGCGCTCCTG GACCGCGGCG
 GACATGGCAG CTCAGATCAC CAAGCGCAAG TGGGAGGCGG CCCGTCAGGC GGAGCAGCTG
 AGAGCCTACC TGGAGGGCGA GTTCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACACATATGA CCCACCACCC CATCTCTGAC
 CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAC ACACGGAGCT CATGGAGACC AGGCCTGCAG
 GGGATGGAAC CTTCCAGAAG TGGGCGGCTG TGGTGGTGCC TTCTGGAGAG GAGCAGAGAT
 ACACCTGCCA TGTGCAGCAT GAGGGTCTGC CAGAGCCCCT CACCCTGAGA TGGGAGCCAT
 CTTCCCAGCC CACCATCCCC ATCGTGGGCA TCGTTGCTGG CCTGGTTCTA CTTGTAGCTG
 TGGTCACTGG AGCTGTGGTC GCTGCTGTAA TGTGGAGGAA GAAGAGCTCA GATAGAAAAG
 GAGGGAGCTA CTCTCAGGCT GCAAGCGGCA ACAGTGCCCA GGGCTCTGAT GTGTCTCTCA
 CGGCGTGAAA GTGTGA*    
>DL;HLA:HLA02557
HLA:HLA02557 H*01:01:01:02 1096 bases
 ATGGTGCTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT GGCCCTGACC
 CAGACCTGGG CGCGCTCCCA CTCCATGAGG TATTTCTACA CCACCATGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CTCCGTCGGC TACGTGGACG ATACGCAGTT CGTGCGGTTC
 GACAGCGACG CCGCGAGCCA GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCGGGAGGGG
 CCGGAGTATT GGGACCGGAA CACACAGATC TGCAAGGCCC AGGCACAGAC TGAACGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG GCGGTTCTCA CACCATGCAG
 GTGATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCTTCC TCCGCGGGTA TGAACAGCAC
 GCCTACGACA GCAAGGATTA CATCGCTCTG AACGAGGACC TGCGCTCCTG GACCGCGGCG
 GACATGGCAG CTCAGATCAC CAAGCGCAAG TGGGAGGCGG CCCGTCAGGC GGAGCAGCTG
 AGAGCCTACC TGGAGGGCGA GTTCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACACATATGA CCCACCACCC CATCTCTGAC
 CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAC ACACGGAGCT CATGGAGACC AGGCCTGCAG
 GGGATGGAAC CTTCCAGAAG TGGGCGGCTG TGGTGGTGCC TTCTGGAGAG GAGCAGAGAT
 ACACCTGCCA TGTGCAGCAT GAGGGTCTGC CAGAGCCCCT CACCCTGAGA TGGGAGCCAT
 CTTCCCAGCC CACCATCCCC ATCGTGGGCA TCGTTGCTGG CCTGGTTCTA CTTGTAGCTG
 TGGTCACTGG AGCTGTGGTC GCTGCTGTAA TGTGGAGGAA GAAGAGCTCA GATAGAAAAG
 GAGGGAGCTA CTCTCAGGCT GCAAGCGGCA ACAGTGCCCA GGGCTCTGAT GTGTCTCTCA
 CGGCGTGAAA GTGTGA*    
>DL;HLA:HLA02548
HLA:HLA02548 H*01:01:01:03 1096 bases
 ATGGTGCTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT GGCCCTGACC
 CAGACCTGGG CGCGCTCCCA CTCCATGAGG TATTTCTACA CCACCATGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CTCCGTCGGC TACGTGGACG ATACGCAGTT CGTGCGGTTC
 GACAGCGACG CCGCGAGCCA GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCGGGAGGGG
 CCGGAGTATT GGGACCGGAA CACACAGATC TGCAAGGCCC AGGCACAGAC TGAACGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG GCGGTTCTCA CACCATGCAG
 GTGATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCTTCC TCCGCGGGTA TGAACAGCAC
 GCCTACGACA GCAAGGATTA CATCGCTCTG AACGAGGACC TGCGCTCCTG GACCGCGGCG
 GACATGGCAG CTCAGATCAC CAAGCGCAAG TGGGAGGCGG CCCGTCAGGC GGAGCAGCTG
 AGAGCCTACC TGGAGGGCGA GTTCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACACATATGA CCCACCACCC CATCTCTGAC
 CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAC ACACGGAGCT CATGGAGACC AGGCCTGCAG
 GGGATGGAAC CTTCCAGAAG TGGGCGGCTG TGGTGGTGCC TTCTGGAGAG GAGCAGAGAT
 ACACCTGCCA TGTGCAGCAT GAGGGTCTGC CAGAGCCCCT CACCCTGAGA TGGGAGCCAT
 CTTCCCAGCC CACCATCCCC ATCGTGGGCA TCGTTGCTGG CCTGGTTCTA CTTGTAGCTG
 TGGTCACTGG AGCTGTGGTC GCTGCTGTAA TGTGGAGGAA GAAGAGCTCA GATAGAAAAG
 GAGGGAGCTA CTCTCAGGCT GCAAGCGGCA ACAGTGCCCA GGGCTCTGAT GTGTCTCTCA
 CGGCGTGAAA GTGTGA*    
>DL;HLA:HLA02551
HLA:HLA02551 H*01:02 1096 bases
 ATGGTGCTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT GGCCCTGACC
 CAGACCTGGG CGCGCTCCCA CTCCATGAGG TATTTCTACA CCACCATGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CTCCGTCGGC TACGTGGACG ATACGCAGTT CGTGCGGTTC
 GACAGCGACG CCGCGAGCCA GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCGGGAGGGG
 CCGGAGTATT GGGACCGGAA CACACAGATC TGCAAGGCCC AGGCACAGAC TGAACGAGAG
 AACCTGCGGA TCGCGCTCCT CTACTACAAC CAGAGCGAGG GCGGTTCTCA CACCATGCAG
 GTGATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCTTCC TCCGCGGGTA TGAACAGCAC
 GCCTACGACG GCAAGGATTA CATCGCTCTG AACGAGGACC TGCGCTCCTG GACCGCGGCG
 GACATGGCAG CTCAGATCAC CAAGCGCAAG TGGGAGGCGG CCCGTCGGGC GGAGCAGCTG
 AGAGCCTACC TGGAGGGCGA GTTCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACACATATGA CCCACCACCC CATCTCTGAC
 CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAC ACACGGAGCT CGTGGAGACC AGGCCTGCAG
 GGGATGGAAC CTTCCAGAAG TGGGCGGCTG TGGTGGTGCC TTCTGGAGAG GAGCAGAGAT
 ACACCTGCCA TGTGCAGCAT GAGGGTCTGC CAGAGCCCCT CACCCTGAGA TGGGAGCCAT
 CTTCCCAGCC CACCATCCCC ATCGTGGGCA TCGTTGCTGG CCTGGTTCTA CTTGTAGCTG
 TGGTCACTGG AGCTGTGGTC GCTGCTGTAA TGTGGAGGAA GAAGAGCTCA GATAGAAAAG
 GAGGGAGCTA CTCTCAGGCT GCAAGCGGCA ACAGTGCCCA GGGCTCTGAT GTGTCTCTCA
 CGGCGTGAAA GTGTGA*    
>DL;HLA:HLA02547
HLA:HLA02547 H*02:01:01:01 1096 bases
 ATGGTGCTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT GGCCCTGACC
 CAGACCTGGG CGCGCTCCCA CTCCATGAGG TATTTCTACA CCACCATGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CTCCGTCGGC TACGTGGACG ATACGCAGTT CGTGCGGTTC
 GACAGCGACG ACGCGAGTCC GAGAGAGGAG CCGCGGGCGC CGTGGATGGA GCGGGAGGGG
 CCGGAGTATT GGGACCGGAA CACACAGATC TGCAAGGCCC AAGCACGGAC TGAACGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG GCGGTTCTCA CACCATGCAG
 GTGATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCTTCC TCTGCGGGTA TGAACAGCAC
 GCCTACGACG GCAAGGATTA CATCGCTCTG AACGAGGACC TGCGCTCCTG GACCGCGGCG
 GACATGGCAG CTCAGATCAC CAAGCGCAAG TGGGAGGCGG CCCGTCGGGC GGAGCAGCGG
 AGAGTCTACC TGGAGGGCGA GTTCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACACATATGA CCCACCACCC CATCTCTGAC
 CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAC ACACGGAGCT CGTGGAGACC AGGCCTGCAG
 GGGATGGAAC CTTCCAGAAG TGGGCGGCTG TGGTGGTGCC TTCTGGAGAG GAGCAGAGAT
 ACACCTGCCA TGTGCAGCAT GAGGGTCTGC CAGAGCCCCT CACCCTGAGA TGGGAGCCAT
 CTTCCCAGCC CACCATCCCC ATCGTGGGCA TCGTTGCTGG CCTGGTTCTA CTTGTAGCTG
 TGGTCACTGG AGCTGTGGTC GCTGCTGTAA TGTGGAGGAA GAAGAGCTCA GATAGAAAAG
 GAGGGAGCTA CTCTCAGGCT GCAAGCGGCA ACAGTGCCCA GGGCTCTGAT GTGTCTCTCA
 CAGCGTGAAA GTGTGA*    
>DL;HLA:HLA02549
HLA:HLA02549 H*02:01:01:02 1096 bases
 ATGGTGCTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT GGCCCTGACC
 CAGACCTGGG CGCGCTCCCA CTCCATGAGG TATTTCTACA CCACCATGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CTCCGTCGGC TACGTGGACG ATACGCAGTT CGTGCGGTTC
 GACAGCGACG ACGCGAGTCC GAGAGAGGAG CCGCGGGCGC CGTGGATGGA GCGGGAGGGG
 CCGGAGTATT GGGACCGGAA CACACAGATC TGCAAGGCCC AAGCACGGAC TGAACGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG GCGGTTCTCA CACCATGCAG
 GTGATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCTTCC TCTGCGGGTA TGAACAGCAC
 GCCTACGACG GCAAGGATTA CATCGCTCTG AACGAGGACC TGCGCTCCTG GACCGCGGCG
 GACATGGCAG CTCAGATCAC CAAGCGCAAG TGGGAGGCGG CCCGTCGGGC GGAGCAGCGG
 AGAGTCTACC TGGAGGGCGA GTTCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACACATATGA CCCACCACCC CATCTCTGAC
 CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAC ACACGGAGCT CGTGGAGACC AGGCCTGCAG
 GGGATGGAAC CTTCCAGAAG TGGGCGGCTG TGGTGGTGCC TTCTGGAGAG GAGCAGAGAT
 ACACCTGCCA TGTGCAGCAT GAGGGTCTGC CAGAGCCCCT CACCCTGAGA TGGGAGCCAT
 CTTCCCAGCC CACCATCCCC ATCGTGGGCA TCGTTGCTGG CCTGGTTCTA CTTGTAGCTG
 TGGTCACTGG AGCTGTGGTC GCTGCTGTAA TGTGGAGGAA GAAGAGCTCA GATAGAAAAG
 GAGGGAGCTA CTCTCAGGCT GCAAGCGGCA ACAGTGCCCA GGGCTCTGAT GTGTCTCTCA
 CAGCGTGAAA GTGTGA*    
>DL;HLA:HLA02556
HLA:HLA02556 H*02:02 1090 bases
 ATGGTGCTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT GACCCAGACC
 TGGGCGCGCT CCCACTCCAT GAGGTATTTC TACACCACCA TGTCCCGGCC CGGCCGCGGG
 GAGCCCCGCT TCATCTCCGT CGGCTACGTG GACTATACGC AGTTCGTGCG GTTCGACAGC
 GACGACGCGA GTCCGAGAGA GGAGCCGCGG GCGCCGTGGA TGGAGCGGGA GGGGCCGGAG
 TATTGGGACC GGAACACACA GATCTGCAAG GCCCAAGCAC GGACTGAACG AGAGAACCTG
 CGGATCGCGC TCCGCTACTA CAACCAGAGC GAGGGCGGTT CCCACACCAT GCAGGTGATG
 TATGGCTGCG ACGTGGGGCC CGACGGGCGC TTCCTCCGCG GGTATGAACA GCACGCCTAC
 GACGGCAAGG ATTACATCGC TCTGAACGAG GACCTGCGCT CCTGGACCGC GGCGGACATG
 GCAGCTCAGA TCACCAAGCG CAAGTGGGAG GCGGCCCGTG TGGCGGAGCA GCTGAGAGCC
 TACCTGGAGG GCGAGTTCGT GGAGTGGCTC CGCAGATACC TGGAGAACGG GAAGGAGACG
 CTGCAGCGCG CGGACCCCCC CAAGACACAT ATGACCCACT ACCCCATCTC TGACCATGAG
 GCCACCCTGA GGTGCTGGGC CCTGGGCTTC TACCCTGCGG AGATCACACT GACCTGGCAG
 CGGGATGGGG AGGACCAGAC CCACACACGG AGCTCGTGGA GACCAGGCCT GCAGGGGATG
 GAACCTTCCA GAAGTGGGCG GCTGTGGTGG TGCCTTCTGG AGAGGAGCAG AGATACACCT
 GCCATGTGCA GCATGAGGGT CTGCCCGAGC CCCTCACCCT GAGATGGGAG CCATCTTCCC
 AGCCCACCAT CCCCATCGTG GGCATCATTG CTGGCCTGGT TCTACTTGTA GCTGTGGTCA
 CTGGAGCTGT GGTCACTGCT GTAATGTGGA GGAAGAAGAG CTCAGATAGA AAAGGAGGGA
 GCTACTCTCA GGCTGCAAGC GGCAACAGTG CCCAGGGCTC TGATGTGTCT CTCACGGCGT
 GAAAGTGTGA *    
>DL;HLA:HLA02550
HLA:HLA02550 H*02:03 1090 bases
 ATGGTGCTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT GACCCAGACC
 TGGGCGCGCT CCCACTCCAT GAGGTATTTC TACACCACCA TGTCCCGGCC CGGCCGCGGG
 GAGCCCCGCT TCATCTCCGT CGGCTACGTG GACGATACGC AGTTCGTGCG GTTCGACAGC
 GACGACGCGA GTCCGAGAGA GGAGCCGCGG GCGCCGTGGA TGGAGCGGGA GGGGCCGGAG
 TATTGGGACC GGAACACACA GATCTGCAAG GCCCAAGCAC GGACTGAACG AGAGAACCTG
 CGGATCGCGC TCCGCTACTA CAACCAGAGC GAGGGCGGTT CTCACACCAT GCAGGTGATG
 TATGGCTGCG ACGTGGGGCC CGACGGGCGC TTCCTCCGCG GGTATGAACA GCACGCCTAC
 GACGGCAAGG ATTACATCGC TCTGAACGAG GACCTGCGCT CCTGGACCGC GGCGGACATG
 GCAGCTCAGA TCACCAAGCG CAAGTGGGAG GCGGCCCGTC GGGCGGAGCA GCTGAGAGCC
 TACCTGGAGG GCGAGTTCGT GGAGTGGCTC CGCAGATACC TGGAGAACGG GAAGGAGACG
 CTGCAGCGCG CGGACCCCCC CAAGACACAT ATGACCCACT ACCCCATCTC TGACCATGAG
 GCCACCCTGA GGTGCTGGGC CCTGGGCTTC TACCCTGCGG AGATCACACT GACCTGGCAG
 CGGGATGGGG AGGACCAGAC CCACACACGG AGCTCGTGGA GACCAGGCCT GCAGGGGATG
 GAACCTTCCA GAAGTGGGCG GCTGTGGTGG TGCCTTCTGG AGAGGAGCAG AGATACACCT
 GCCATGTGCA GCATGAGGGT CTGCCCGAGC CCCTCACCCT GAGATGGGAG CCATCTTCCC
 AGCCCACCAT CCCCATCGTG GGCATCATTG CTGGCCTGGT TCTACTTGTA GCTGTGGTCA
 CTGGAGCTGT GGTCACTGCT GTAATGTGGA GGAAGAAGAG CTCAGATTGA AAAGGAGGGA
 GCTACTCTCA GGCTGCAAGC GGCAACAGTG CCCAGGGCTC TGATGTGTCT CTCACGGCGT
 GAAAGTGTGA *    
>DL;HLA:HLA02552
HLA:HLA02552 H*02:04 1104 bases
 ATGGTGCTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT GGCCCTGACC
 CTGACCCAGA CCTGGGCGCG CTCCCACTCC ATGAGGTATT TCTACACCAC CATGTCCCGG
 CCCGGCCGCG GGGAGCCCCG CTTCATCTCC GTCGGCTACG TGGACGATAC GCAGTTCGTG
 CGGTTCGACA GCGACGACGC GAGTCCGAGA GAGGAGCCGC GGGCGCCGTG GATGGAGCGG
 GAGGGGCCAG AGTATTGGGA CCGGAACACA CAGATCTGCA AGGCCCAGGC ACAGACTGAA
 CGAGAGAACC TGCGGATCGC GCTCCGCTAC TACAACCAGA GCGAGGGCGG TTCTCACACC
 ATGCAGGTGA TGTATGGCTG CGACGTGGGG CCCGACGGGC GCTTCCTCCG CGGGTATGAA
 CAGCACGCCT ACGACGGCAA GGATTACATC GCCCTGAACG AGGACCTGCG CTCCTGGACC
 GCGGCGGACA TGGCAGCTCA GATCACCAAG CGCAAGTGGG AGGCGGCCCG TCGGGCGGAG
 CAGCTGAGAG CCTACCTGGA GGGCGAGTTC GTGGAGTGGC TCCGCAGATA CCTGGAGAAC
 GGGAAGGAGA CGCTGCAGCG CGCGGACCCC CCCCAAGACA CATATGACCC ACCACCCCAT
 CTCTGACCAT GAGGCCACCC TGAGGTGCTG GGCCCTGGGC TTCTACCCTG CGGAGATCAC
 ACTGACCTGG CAGCGGGATG GGGAGGACCA GACCCAGGAC ACGGAGCTCG TGGAGACCAG
 GCCTGCAGGG GATGGAACCT TCCAGAAGTG GGCGGCTGTG GTGGTGCCTT CTGGAGAGGA
 GCAGAGATAC ACCTGCCATG TGCAGCATGA GGGTCTGCCC GAGCCCCTCA CCCTGAGATG
 GGAGCCATCT TCCCAGCCCA ACGTCCCCAT CGTGGGCATC GTTGCTGGCC TGGTTCTACT
 TGTAGCTGTG GTCACTGGAG CTGTGGTCGC TGCTGTAATG TGGAGGAAGA AGAGCTCAGA
 TAGAAAAGGA GGGAGCTACT CTCAGGCTGC AAGCAGCAAC AGTGCCCAGG GCTCTGATGT
 GTCTCTCACG GCTTGAAAGT GTGA*   
>DL;HLA:HLA02554
HLA:HLA02554 H*02:05 1096 bases
 ATGGTGCTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT GGCCCTGACC
 CAGACCTGGG CGCGCTCCCA CTCCATGAGG TATTTCTACA CCACCATGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CTCCGTCGGC TACGTGGACG ATACGCAGTT CGTGCGGTTC
 GACAGCGACG ACGCGAGTCC GAGAGAGGAG CCGCGGGCGC CGTGGATGGA GCGGGAGGGG
 CCGGAGTATT GGGACCGGAA CACACAGATC TGCAAGGCCC AAGCACGGAC TGAACGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG GCGGTTCTCA CACCATGCAG
 GTGATGTATG GCTGCGACTT GGGGCCCGAC GGGCGCTTCC TCCGCGGGTA TGAACAGCAC
 GCCTACGACG GCAAGGATTA CATCGCTCTG AACGAGGACC TGCGCTCCTG GACCGCGGCG
 GACATGGCAG CTCAGATCAC CAAGCGCAAG TGGGAGGCGG CCCGTCGGGC GGAGCAGCGG
 AGAGTCTACC TGGAGGGCGA GTTCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACACATATGA CCCACCACCC CATCTCTGAC
 CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAC ACACGGAGCT CGTGGAGACC AGGCCTGCAG
 GGGATGGAAC CTTCCAGAAG TGGGCGGCTG TGGTGGTGCC TTCTGGAGAG GAGCAGAGAT
 ACACCTGCCA TGTGCAGCAT GAGGGTCTGC CAGAGCCCCT CACCCTGAGA TGGGAGCCAT
 CTTCCCAGCC CACCATCCCC ATCGTGGGCA TCGTTGCTGG CCTGGTTCTA CTTGTAGCTG
 TGGTCACTGG AGCTGTGGTC GCTGCTGTAA TGTGGAGGAA GAAGAGCTCA GATAGAAAAG
 GAGGGAGCTA CTCTCAGGCT GCAAGCGGCA ACAGTGCCCA GGGCTCTGAT GTGTCTCTCA
 CGGCGTGAAA GTGTGA*    
>DL;HLA:HLA02555
HLA:HLA02555 H*02:06 1097 bases
 ATGGTGCTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT GGCCCTGACC
 CAGACCTGGG CGCGTTCCCA CTCCATGAGG TATTTCTACA CCACCATGTC CCGGCCCGGC
 GCCGGGGAGC CCCGCTTCAT CTCCGTCGGC TACGTGGACG ATACGCAGTT CGTGCGGTTC
 GACAGCGACG ACGCGAGTCC GAGAGAGGAG CCGCGGGCGC CGTGGATGGA GCGGGAGGGG
 CCAAAGTATT GGGACCGGAA CACACAGATC TGCAAGGCCC AGGCACAGAC TGAACGAGAG
 AACCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG GCGGTTCTCA CACCATGCAG
 GTGATGTATG GCTGCGACGT GGGGCCCGAC GGGCCTTTCC TCCGCGGGTA TGAACAGCAC
 GCCTACGACG GCAAGGATTA CATCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCGGCG
 GACATGGCAG CTCAGATCAC CAAGCGCAAG TGGGAGGCGG CCCGTCGGGC GGAGCAGCGG
 AGAGTCTACT TGGAGGGCGA GTTCGTGGAG TGGCTCCGCA GATACTTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACACATATGA CCCACCACCC CATCTCTGAC
 CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACACGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCGGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACCTGCC ATGTGCAGCA TGAGGGTCTG CCCGAGCCCC TCACCCTGAG ATGGGAGCCA
 TCTTCCCAGC CCACCGTCCC CATCGTGGGC ATCGTTGCTG GCTTGGTTCT ACTTGTAGCT
 GTGGTCACTG GAGCTGTGGT CGCTGCTGTA ATGTGGAGGA AGAAGAGCTC AGATAGAAAA
 GGAGGGAGCT ACTCTCAGGC TGCAAGCAGC AACAGTGCCC AGGGCTCTGA TGTGTCTCTC
 ACGGCTTGAA ACTGTGA*    
>DL;HLA:HLA02553
HLA:HLA02553 H*03:01 1096 bases
 ATGGTGCTCA TGGCGCCCCG AACCCTCCTC CTGCTGCTCT CAGGGGCCCT GGCCCTGACC
 CAGACCTGGG CGCGCTCCCA CTCCATGAGG TATTTCTACA CCACCATGTC CCGGCCCGGC
 CGCGGGGAGC CCCGCTTCAT CTCCGTCGGC TACGTGGACG ATACGCAGTT CGTGCGGTTC
 GACAGCGACG CCGCGAGCCA GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCGGGAGGGG
 CCGGAGTATT GGGACCGGAA CACACAGATC TGCAAGGCCC AGGCACAGAC TGAACGAGAG
 AACCTGGGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG GCGGTTCTCA CACCATCGAC
 GTGATGTATG GCTGCGACGT GGGGCCCGAC GGGCGCTTCC TCCGCGGGTA TGAACAGTAC
 GCCTACGACA GCAAGGATTA CATCGCTCTG ACCGAGGACC TGCGCTCCTG GACCGCGGCG
 GACATGGCAG CTCAGATCAC CAAGCGCAAG TGGGAGGCGG CCCGTCAGGC GGAGCAGCTG
 AGAGCCTACC TGGAGGGCGA GTTCGTGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CGCCCCCAAG ACACATATGA CCCACCACCC CATCTCTGAC
 CATGAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAC ACACGGAGCT CGTGGAGACC AGGCCTGCAG
 GGGATGGAAC CTTCCAGAAG TGGGCGGCTG TGGTGGTGCC TTCTGGAGAG GAGCAGAGAT
 ACACCTGCCA TGTGCAGCAT GAGGGTCTGC CAGAGCCCCT CACCCTGAGA TGGGAGCCAT
 CTTCCCAGCC CACCATCCCC ATCGTGGGCA TCGTTGCTGG CCTGGTTCTA CTTGTAGCTG
 TGGTCACTGG AGCTGTGGTC GCTGCTGTAA TGTGGAGGAA GAAGAGCTCA GATAGAAAAG
 GAGGGAGCTA CTCTCAGGCT GCAAGCGGCA ACAGTGCCCA GGGCTCTGAT GTGTCTCTCA
 CGGCGTGAAA GTGTGA*    
>DL;HLA:HLA14067
HLA:HLA14067 HFE*001:01:01 1047 bases
 ATGGGCCCGC GAGCCAGGCC GGCGCTTCTC CTCCTGATGC TTTTGCAGAC CGCGGTCCTG
 CAGGGGCGCT TGCTGCGTTC ACACTCTCTG CACTACCTCT TCATGGGTGC CTCAGAGCAG
 GACCTTGGTC TTTCCTTGTT TGAAGCTTTG GGCTACGTGG ATGACCAGCT GTTCGTGTTC
 TATGATCATG AGAGTCGCCG TGTGGAGCCC CGAACTCCAT GGGTTTCCAG TAGAATTTCA
 AGCCAGATGT GGCTGCAGCT GAGTCAGAGT CTGAAAGGGT GGGATCACAT GTTCACTGTT
 GACTTCTGGA CTATTATGGA AAATCACAAC CACAGCAAGG AGTCCCACAC CCTGCAGGTC
 ATCCTGGGCT GTGAAATGCA AGAAGACAAC AGTACCGAGG GCTACTGGAA GTACGGGTAT
 GATGGGCAGG ACCACCTTGA ATTCTGCCCT GACACACTGG ATTGGAGAGC AGCAGAACCC
 AGGGCCTGGC CCACCAAGCT GGAGTGGGAA AGGCACAAGA TTCGGGCCAG GCAGAACAGG
 GCCTACCTGG AGAGGGACTG CCCTGCACAG CTGCAGCAGT TGCTGGAGCT GGGGAGAGGT
 GTTTTGGACC AACAAGTGCC TCCTTTGGTG AAGGTGACAC ATCATGTGAC CTCTTCAGTG
 ACCACTCTAC GGTGTCGGGC CTTGAACTAC TACCCCCAGA ACATCACCAT GAAGTGGCTG
 AAGGATAAGC AGCCAATGGA TGCCAAGGAG TTCGAACCTA AAGACGTATT GCCCAATGGG
 GATGGGACCT ACCAGGGCTG GATAACCTTG GCTGTACCCC CTGGGGAAGA GCAGAGATAT
 ACGTGCCAGG TGGAGCACCC AGGCCTGGAT CAGCCCCTCA TTGTGATCTG GGAGCCCTCA
 CCGTCTGGCA CCCTAGTCAT TGGAGTCATC AGTGGAATTG CTGTTTTTGT CGTCATCTTG
 TTCATTGGAA TTTTGTTCAT AATATTAAGG AAGAGGCAGG GTTCAAGAGG AGCCATGGGG
 CACTACGTCT TAGCTGAACG TGAGTGA*   
>DL;HLA:HLA14071
HLA:HLA14071 HFE*001:01:02 1047 bases
 ATGGGCCCGC GAGCCAGGCC GGCGCTTCTC CTCCTGATGC TTTTGCAGAC CGCGGTCCTG
 CAGGGGCGCT TGCTGCGTTC ACACTCTCTG CACTACCTCT TCATGGGTGC CTCAGAGCAG
 GACCTTGGTC TTTCCTTGTT TGAAGCTTTG GGCTACGTGG ATGACCAGCT GTTCGTGTTC
 TATGATCATG AGAGTCGCCG TGTGGAGCCC CGAACTCCAT GGGTTTCCAG TAGAATTTCA
 AGCCAGATGT GGCTGCAGCT GAGTCAGAGT CTGAAAGGGT GGGATCACAT GTTCACTGTT
 GACTTCTGGA CTATTATGGA AAATCACAAC CACAGCAAGG AGTCCCACAC CCTGCAGGTC
 ATCCTGGGCT GTGAAATGCA AGAAGACAAC AGTACCGAGG GCTACTGGAA GTACGGGTAT
 GATGGGCAGG ACCACCTTGA ATTCTGCCCT GACACACTGG ATTGGAGAGC AGCAGAACCC
 AGGGCCTGGC CCACCAAGCT GGAGTGGGAA AGGCACAAGA TTCGGGCCAG GCAGAACAGG
 GCCTACCTGG AGAGGGACTG CCCTGCACAG CTGCAGCAGT TGCTGGAGCT GGGGAGAGGT
 GTTTTGGACC AACAAGTGCC TCCTTTGGTG AAGGTGACAC ATCATGTGAC CTCTTCAGTG
 ACCACTCTAC GGTGTCGGGC CTTGAACTAC TACCCCCAGA ACATCACCAT GAAGTGGCTG
 AAGGATAAGC AGCCAATGGA TGCCAAGGAG TTCGAACCTA AAGACGTATT GCCCAATGGG
 GATGGGACCT ACCAGGGCTG GATAACCTTG GCTGTACCCC CTGGGGAAGA GCAGAGATAT
 ACGTGCCAGG TGGAGCACCC AGGCCTGGAT CAGCCCCTCA TTGTGATCTG GGAGCCCTCA
 CCGTCTGGCA CCCTAGTCAT TGGAGTCATC AGTGGAATTG CTGTTTTTGT CGTCATCTTG
 TTCATTGGAA TTTTGTTCAT AATATTAAGG AAGAGGCAGG GTTCAAGAGG AGCCATGGGG
 CACTACGTCT TAGCTGAACG TGAGTGA*   
>DL;HLA:HLA14072
HLA:HLA14072 HFE*001:01:03 1047 bases
 ATGGGCCCGC GAGCCAGGCC GGCGCTTCTC CTCCTGATGC TTTTGCAGAC CGCGGTCCTG
 CAGGGGCGCT TGCTGCGTTC ACACTCTCTG CACTACCTCT TCATGGGTGC CTCAGAGCAG
 GACCTTGGTC TTTCCTTGTT TGAAGCTTTG GGCTACGTGG ATGACCAGCT GTTCGTGTTC
 TATGATCATG AGAGTCGCCG TGTGGAGCCC CGAACTCCAT GGGTTTCCAG TAGAATTTCA
 AGCCAGATGT GGCTGCAGCT GAGTCAGAGT CTGAAAGGGT GGGATCACAT GTTCACTGTT
 GACTTCTGGA CTATTATGGA AAATCACAAC CACAGCAAGG AGTCCCACAC CCTGCAGGTC
 ATCCTGGGCT GTGAAATGCA AGAAGACAAC AGTACCGAGG GCTACTGGAA GTACGGGTAT
 GATGGGCAGG ACCACCTTGA ATTCTGCCCT GACACACTGG ATTGGAGAGC AGCAGAACCC
 AGGGCCTGGC CCACCAAGCT GGAGTGGGAA AGGCACAAGA TTCGGGCCAG GCAGAACAGG
 GCCTACCTGG AGAGGGACTG CCCTGCACAG CTGCAGCAGT TGCTGGAGCT GGGGAGAGGT
 GTTTTGGACC AACAAGTGCC TCCTTTGGTG AAGGTGACAC ATCATGTGAC CTCTTCAGTG
 ACCACTCTAC GGTGTCGGGC CTTGAACTAC TACCCCCAGA ACATCACCAT GAAGTGGCTG
 AAGGATAAGC AGCCAATGGA TGCCAAGGAG TTCGAACCTA AAGACGTATT GCCCAATGGG
 GATGGGACCT ACCAGGGCTG GATAACCTTG GCTGTACCCC CTGGGGAAGA GCAGAGATAT
 ACGTGCCAGG TGGAGCACCC AGGCCTGGAT CAGCCCCTCA TTGTGATCTG GGAGCCCTCA
 CCGTCTGGCA CCCTAGTCAT TGGAGTCATC AGTGGAATTG CTGTTTTTGT CGTCATCTTG
 TTCATTGGAA TTTTGTTCAT AATATTAAGG AAGAGGCAGG GTTCAAGAGG AGCCATGGGG
 CACTACGTCT TAGCTGAACG TGAGTGA*   
>DL;HLA:HLA14070
HLA:HLA14070 HFE*002 930 bases
 GTTCACACTC TCTGCACTAC CTCTTCATGG GTGCCTCAGA GCAGGACCTT GGTCTTTCCT
 TGTTTGAAGC TTTGGGCTAC GTGGATGACC AGCTGTTCGT GTTCTATGAT CATGAGAGTC
 GCCGTGTGGA GCCCCGAACT CCATGGGTTT CCAGTAGAAT TTCAAGCCAG ATGTGGCTGC
 AGCTGAGTCA GAGTCTGAAA GGGTGGGATC ACATGTTCAC TGTTGACTTC TGGACTATTA
 TGGAAAATCA CAACCACAGC AAGGAGTCCC ACACCCTGCA GGTCATCCTG GGCTGTGAAA
 TGCAAGAAGA CAACAGTACC GAGGGCTACT GGAAGTACGG GTATGATGGG CAGGACCACC
 TTGAATTCTG CCCTGACACA CTGGATTGGA GAGCAGCAGA ACCCAGGGCC TGGCCCACCA
 AGCTGGAGTG GGAAAGGCAC AAGATTCGGG CCAGGCAGAA CAGGGCCTAC CTGGAGAGGG
 ACTGCCCTGC ACAGCTGCAG CAGTTGCTGG AGCTGGGGAG AGGTGTTTTG GACCAACAAG
 TGCCTCCTTT GGTGAAGGTG ACACATCATG TGACCTCTTC AGTGACCACT CTACGGTGTC
 GGGCCTTGAA CTACTACCCC CAGAACATCA CCATGAAGTG GCTGAAGGAT AAGCAGCCAA
 TGGATGCCAA GGAGTTCGAA CCTAAAGACG TATTGCCCAA TGGGGATGGG ACCTACCAGG
 GCTGGATAAC CTTGGCTGTA CCCCCTGGGG AAGAGCAGAG ATATACGTAC CAGGTGGAGC
 ACCCAGGCCT GGATCAGCCC CTCATTGTGA TCTGGGAGCC CTCACCGTCT GGCACCCTAG
 TCATTGGAGT CATCAGTGGA ATTGCTGTTT TTGTCGTCAT CTTGTTCATT GGAATTTTGT
 TCATAATATT AAGGAAGAGG CAGGGTTCAA *  
>DL;HLA:HLA14069
HLA:HLA14069 HFE*003 930 bases
 GTTCACACTC TCTGCACTAC CTCTTCATGG GTGCCTCAGA GCAGGACCTT GGTCTTTCCT
 TGTTTGAAGC TTTGGGCTAC GTGGATGACC AGCTGTTCGT GTTCTATGAT GATGAGAGTC
 GCCGTGTGGA GCCCCGAACT CCATGGGTTT CCAGTAGAAT TTCAAGCCAG ATGTGGCTGC
 AGCTGAGTCA GAGTCTGAAA GGGTGGGATC ACATGTTCAC TGTTGACTTC TGGACTATTA
 TGGAAAATCA CAACCACAGC AAGGAGTCCC ACACCCTGCA GGTCATCCTG GGCTGTGAAA
 TGCAAGAAGA CAACAGTACC GAGGGCTACT GGAAGTACGG GTATGATGGG CAGGACCACC
 TTGAATTCTG CCCTGACACA CTGGATTGGA GAGCAGCAGA ACCCAGGGCC TGGCCCACCA
 AGCTGGAGTG GGAAAGGCAC AAGATTCGGG CCAGGCAGAA CAGGGCCTAC CTGGAGAGGG
 ACTGCCCTGC ACAGCTGCAG CAGTTGCTGG AGCTGGGGAG AGGTGTTTTG GACCAACAAG
 TGCCTCCTTT GGTGAAGGTG ACACATCATG TGACCTCTTC AGTGACCACT CTACGGTGTC
 GGGCCTTGAA CTACTACCCC CAGAACATCA CCATGAAGTG GCTGAAGGAT AAGCAGCCAA
 TGGATGCCAA GGAGTTCGAA CCTAAAGACG TATTGCCCAA TGGGGATGGG ACCTACCAGG
 GCTGGATAAC CTTGGCTGTA CCCCCTGGGG AAGAGCAGAG ATATACGTGC CAGGTGGAGC
 ACCCAGGCCT GGATCAGCCC CTCATTGTGA TCTGGGAGCC CTCACCGTCT GGCACCCTAG
 TCATTGGAGT CATCAGTGGA ATTGCTGTTT TTGTCGTCAT CTTGTTCATT GGAATTTTGT
 TCATAATATT AAGGAAGAGG CAGGGTTCAA *  
>DL;HLA:HLA14068
HLA:HLA14068 HFE*004 930 bases
 GTTCACACTC TCTGCACTAC CTCTTCATGG GTGCCTCAGA GCAGGACCTT GGTCTTTCCT
 TGTTTGAAGC TTTGGGCTAC GTGGATGACC AGCTGTTCGT GTTCTATGAT TATGAGAGTC
 GCCGTGTGGA GCCCCGAACT CCATGGGTTT CCAGTAGAAT TTCAAGCCAG ATGTGGCTGC
 AGCTGAGTCA GAGTCTGAAA GGGTGGGATC ACATGTTCAC TGTTGACTTC TGGACTATTA
 TGGAAAATCA CAACCACAGC AAGGAGTCCC ACACCCTGCA GGTCATCCTG GGCTGTGAAA
 TGCAAGAAGA CAACAGTACC GAGGGCTACT GGAAGTACGG GTATGATGGG CAGGACCACC
 TTGAATTCTG CCCTGACACA CTGGATTGGA GAGCAGCAGA ACCCAGGGCC TGGCCCACCA
 AGCTGGAGTG GGAAAGGCAC AAGATTCGGG CCAGGCAGAA CAGGGCCTAC CTGGAGAGGG
 ACTGCCCTGC ACAGCTGCAG CAGTTGCTGG AGCTGGGGAG AGGTGTTTTG GACCAACAAG
 TGCCTCCTTT GGTGAAGGTG ACACATCATG TGACCTCTTC AGTGACCACT CTACGGTGTC
 GGGCCTTGAA CTACTACCCC CAGAACATCA CCATGAAGTG GCTGAAGGAT AAGCAGCCAA
 TGGATGCCAA GGAGTTCGAA CCTAAAGACG TATTGCCCAA TGGGGATGGG ACCTACCAGG
 GCTGGATAAC CTTGGCTGTA CCCCCTGGGG AAGAGCAGAG ATATACGTGC CAGGTGGAGC
 ACCCAGGCCT GGATCAGCCC CTCATTGTGA TCTGGGAGCC CTCACCGTCT GGCACCCTAG
 TCATTGGAGT CATCAGTGGA ATTGCTGTTT TTGTCGTCAT CTTGTTCATT GGAATTTTGT
 TCATAATATT AAGGAAGAGG CAGGGTTCAA *  
