>P1;HLA:HLA14067
HLA:HLA14067 HFE*001:01:01 348 bases
 MGPRARPALL LLMLLQTAVL QGRLLRSHSL HYLFMGASEQ DLGLSLFEAL GYVDDQLFVF
 YDHESRRVEP RTPWVSSRIS SQMWLQLSQS LKGWDHMFTV DFWTIMENHN HSKESHTLQV
 ILGCEMQEDN STEGYWKYGY DGQDHLEFCP DTLDWRAAEP RAWPTKLEWE RHKIRARQNR
 AYLERDCPAQ LQQLLELGRG VLDQQVPPLV KVTHHVTSSV TTLRCRALNY YPQNITMKWL
 KDKQPMDAKE FEPKDVLPNG DGTYQGWITL AVPPGEEQRY TCQVEHPGLD QPLIVIWEPS
 PSGTLVIGVI SGIAVFVVIL FIGILFIILR KRQGSRGAMG HYVLAERE* 
>P1;HLA:HLA14071
HLA:HLA14071 HFE*001:01:02 348 bases
 MGPRARPALL LLMLLQTAVL QGRLLRSHSL HYLFMGASEQ DLGLSLFEAL GYVDDQLFVF
 YDHESRRVEP RTPWVSSRIS SQMWLQLSQS LKGWDHMFTV DFWTIMENHN HSKESHTLQV
 ILGCEMQEDN STEGYWKYGY DGQDHLEFCP DTLDWRAAEP RAWPTKLEWE RHKIRARQNR
 AYLERDCPAQ LQQLLELGRG VLDQQVPPLV KVTHHVTSSV TTLRCRALNY YPQNITMKWL
 KDKQPMDAKE FEPKDVLPNG DGTYQGWITL AVPPGEEQRY TCQVEHPGLD QPLIVIWEPS
 PSGTLVIGVI SGIAVFVVIL FIGILFIILR KRQGSRGAMG HYVLAERE* 
>P1;HLA:HLA14072
HLA:HLA14072 HFE*001:01:03 348 bases
 MGPRARPALL LLMLLQTAVL QGRLLRSHSL HYLFMGASEQ DLGLSLFEAL GYVDDQLFVF
 YDHESRRVEP RTPWVSSRIS SQMWLQLSQS LKGWDHMFTV DFWTIMENHN HSKESHTLQV
 ILGCEMQEDN STEGYWKYGY DGQDHLEFCP DTLDWRAAEP RAWPTKLEWE RHKIRARQNR
 AYLERDCPAQ LQQLLELGRG VLDQQVPPLV KVTHHVTSSV TTLRCRALNY YPQNITMKWL
 KDKQPMDAKE FEPKDVLPNG DGTYQGWITL AVPPGEEQRY TCQVEHPGLD QPLIVIWEPS
 PSGTLVIGVI SGIAVFVVIL FIGILFIILR KRQGSRGAMG HYVLAERE* 
>P1;HLA:HLA14070
HLA:HLA14070 HFE*002 309 bases
 SHSLHYLFMG ASEQDLGLSL FEALGYVDDQ LFVFYDHESR RVEPRTPWVS SRISSQMWLQ
 LSQSLKGWDH MFTVDFWTIM ENHNHSKESH TLQVILGCEM QEDNSTEGYW KYGYDGQDHL
 EFCPDTLDWR AAEPRAWPTK LEWERHKIRA RQNRAYLERD CPAQLQQLLE LGRGVLDQQV
 PPLVKVTHHV TSSVTTLRCR ALNYYPQNIT MKWLKDKQPM DAKEFEPKDV LPNGDGTYQG
 WITLAVPPGE EQRYTYQVEH PGLDQPLIVI WEPSPSGTLV IGVISGIAVF VVILFIGILF
 IILRKRQGS*     
>P1;HLA:HLA14069
HLA:HLA14069 HFE*003 309 bases
 SHSLHYLFMG ASEQDLGLSL FEALGYVDDQ LFVFYDDESR RVEPRTPWVS SRISSQMWLQ
 LSQSLKGWDH MFTVDFWTIM ENHNHSKESH TLQVILGCEM QEDNSTEGYW KYGYDGQDHL
 EFCPDTLDWR AAEPRAWPTK LEWERHKIRA RQNRAYLERD CPAQLQQLLE LGRGVLDQQV
 PPLVKVTHHV TSSVTTLRCR ALNYYPQNIT MKWLKDKQPM DAKEFEPKDV LPNGDGTYQG
 WITLAVPPGE EQRYTCQVEH PGLDQPLIVI WEPSPSGTLV IGVISGIAVF VVILFIGILF
 IILRKRQGS*     
>P1;HLA:HLA14068
HLA:HLA14068 HFE*004 309 bases
 SHSLHYLFMG ASEQDLGLSL FEALGYVDDQ LFVFYDYESR RVEPRTPWVS SRISSQMWLQ
 LSQSLKGWDH MFTVDFWTIM ENHNHSKESH TLQVILGCEM QEDNSTEGYW KYGYDGQDHL
 EFCPDTLDWR AAEPRAWPTK LEWERHKIRA RQNRAYLERD CPAQLQQLLE LGRGVLDQQV
 PPLVKVTHHV TSSVTTLRCR ALNYYPQNIT MKWLKDKQPM DAKEFEPKDV LPNGDGTYQG
 WITLAVPPGE EQRYTCQVEH PGLDQPLIVI WEPSPSGTLV IGVISGIAVF VVILFIGILF
 IILRKRQGS*     
