>DL;HLA:HLA14067
HLA:HLA14067 HFE*001:01:01 1047 bases
 ATGGGCCCGC GAGCCAGGCC GGCGCTTCTC CTCCTGATGC TTTTGCAGAC CGCGGTCCTG
 CAGGGGCGCT TGCTGCGTTC ACACTCTCTG CACTACCTCT TCATGGGTGC CTCAGAGCAG
 GACCTTGGTC TTTCCTTGTT TGAAGCTTTG GGCTACGTGG ATGACCAGCT GTTCGTGTTC
 TATGATCATG AGAGTCGCCG TGTGGAGCCC CGAACTCCAT GGGTTTCCAG TAGAATTTCA
 AGCCAGATGT GGCTGCAGCT GAGTCAGAGT CTGAAAGGGT GGGATCACAT GTTCACTGTT
 GACTTCTGGA CTATTATGGA AAATCACAAC CACAGCAAGG AGTCCCACAC CCTGCAGGTC
 ATCCTGGGCT GTGAAATGCA AGAAGACAAC AGTACCGAGG GCTACTGGAA GTACGGGTAT
 GATGGGCAGG ACCACCTTGA ATTCTGCCCT GACACACTGG ATTGGAGAGC AGCAGAACCC
 AGGGCCTGGC CCACCAAGCT GGAGTGGGAA AGGCACAAGA TTCGGGCCAG GCAGAACAGG
 GCCTACCTGG AGAGGGACTG CCCTGCACAG CTGCAGCAGT TGCTGGAGCT GGGGAGAGGT
 GTTTTGGACC AACAAGTGCC TCCTTTGGTG AAGGTGACAC ATCATGTGAC CTCTTCAGTG
 ACCACTCTAC GGTGTCGGGC CTTGAACTAC TACCCCCAGA ACATCACCAT GAAGTGGCTG
 AAGGATAAGC AGCCAATGGA TGCCAAGGAG TTCGAACCTA AAGACGTATT GCCCAATGGG
 GATGGGACCT ACCAGGGCTG GATAACCTTG GCTGTACCCC CTGGGGAAGA GCAGAGATAT
 ACGTGCCAGG TGGAGCACCC AGGCCTGGAT CAGCCCCTCA TTGTGATCTG GGAGCCCTCA
 CCGTCTGGCA CCCTAGTCAT TGGAGTCATC AGTGGAATTG CTGTTTTTGT CGTCATCTTG
 TTCATTGGAA TTTTGTTCAT AATATTAAGG AAGAGGCAGG GTTCAAGAGG AGCCATGGGG
 CACTACGTCT TAGCTGAACG TGAGTGA*   
>DL;HLA:HLA14071
HLA:HLA14071 HFE*001:01:02 1047 bases
 ATGGGCCCGC GAGCCAGGCC GGCGCTTCTC CTCCTGATGC TTTTGCAGAC CGCGGTCCTG
 CAGGGGCGCT TGCTGCGTTC ACACTCTCTG CACTACCTCT TCATGGGTGC CTCAGAGCAG
 GACCTTGGTC TTTCCTTGTT TGAAGCTTTG GGCTACGTGG ATGACCAGCT GTTCGTGTTC
 TATGATCATG AGAGTCGCCG TGTGGAGCCC CGAACTCCAT GGGTTTCCAG TAGAATTTCA
 AGCCAGATGT GGCTGCAGCT GAGTCAGAGT CTGAAAGGGT GGGATCACAT GTTCACTGTT
 GACTTCTGGA CTATTATGGA AAATCACAAC CACAGCAAGG AGTCCCACAC CCTGCAGGTC
 ATCCTGGGCT GTGAAATGCA AGAAGACAAC AGTACCGAGG GCTACTGGAA GTACGGGTAT
 GATGGGCAGG ACCACCTTGA ATTCTGCCCT GACACACTGG ATTGGAGAGC AGCAGAACCC
 AGGGCCTGGC CCACCAAGCT GGAGTGGGAA AGGCACAAGA TTCGGGCCAG GCAGAACAGG
 GCCTACCTGG AGAGGGACTG CCCTGCACAG CTGCAGCAGT TGCTGGAGCT GGGGAGAGGT
 GTTTTGGACC AACAAGTGCC TCCTTTGGTG AAGGTGACAC ATCATGTGAC CTCTTCAGTG
 ACCACTCTAC GGTGTCGGGC CTTGAACTAC TACCCCCAGA ACATCACCAT GAAGTGGCTG
 AAGGATAAGC AGCCAATGGA TGCCAAGGAG TTCGAACCTA AAGACGTATT GCCCAATGGG
 GATGGGACCT ACCAGGGCTG GATAACCTTG GCTGTACCCC CTGGGGAAGA GCAGAGATAT
 ACGTGCCAGG TGGAGCACCC AGGCCTGGAT CAGCCCCTCA TTGTGATCTG GGAGCCCTCA
 CCGTCTGGCA CCCTAGTCAT TGGAGTCATC AGTGGAATTG CTGTTTTTGT CGTCATCTTG
 TTCATTGGAA TTTTGTTCAT AATATTAAGG AAGAGGCAGG GTTCAAGAGG AGCCATGGGG
 CACTACGTCT TAGCTGAACG TGAGTGA*   
>DL;HLA:HLA14072
HLA:HLA14072 HFE*001:01:03 1047 bases
 ATGGGCCCGC GAGCCAGGCC GGCGCTTCTC CTCCTGATGC TTTTGCAGAC CGCGGTCCTG
 CAGGGGCGCT TGCTGCGTTC ACACTCTCTG CACTACCTCT TCATGGGTGC CTCAGAGCAG
 GACCTTGGTC TTTCCTTGTT TGAAGCTTTG GGCTACGTGG ATGACCAGCT GTTCGTGTTC
 TATGATCATG AGAGTCGCCG TGTGGAGCCC CGAACTCCAT GGGTTTCCAG TAGAATTTCA
 AGCCAGATGT GGCTGCAGCT GAGTCAGAGT CTGAAAGGGT GGGATCACAT GTTCACTGTT
 GACTTCTGGA CTATTATGGA AAATCACAAC CACAGCAAGG AGTCCCACAC CCTGCAGGTC
 ATCCTGGGCT GTGAAATGCA AGAAGACAAC AGTACCGAGG GCTACTGGAA GTACGGGTAT
 GATGGGCAGG ACCACCTTGA ATTCTGCCCT GACACACTGG ATTGGAGAGC AGCAGAACCC
 AGGGCCTGGC CCACCAAGCT GGAGTGGGAA AGGCACAAGA TTCGGGCCAG GCAGAACAGG
 GCCTACCTGG AGAGGGACTG CCCTGCACAG CTGCAGCAGT TGCTGGAGCT GGGGAGAGGT
 GTTTTGGACC AACAAGTGCC TCCTTTGGTG AAGGTGACAC ATCATGTGAC CTCTTCAGTG
 ACCACTCTAC GGTGTCGGGC CTTGAACTAC TACCCCCAGA ACATCACCAT GAAGTGGCTG
 AAGGATAAGC AGCCAATGGA TGCCAAGGAG TTCGAACCTA AAGACGTATT GCCCAATGGG
 GATGGGACCT ACCAGGGCTG GATAACCTTG GCTGTACCCC CTGGGGAAGA GCAGAGATAT
 ACGTGCCAGG TGGAGCACCC AGGCCTGGAT CAGCCCCTCA TTGTGATCTG GGAGCCCTCA
 CCGTCTGGCA CCCTAGTCAT TGGAGTCATC AGTGGAATTG CTGTTTTTGT CGTCATCTTG
 TTCATTGGAA TTTTGTTCAT AATATTAAGG AAGAGGCAGG GTTCAAGAGG AGCCATGGGG
 CACTACGTCT TAGCTGAACG TGAGTGA*   
>DL;HLA:HLA14070
HLA:HLA14070 HFE*002 930 bases
 GTTCACACTC TCTGCACTAC CTCTTCATGG GTGCCTCAGA GCAGGACCTT GGTCTTTCCT
 TGTTTGAAGC TTTGGGCTAC GTGGATGACC AGCTGTTCGT GTTCTATGAT CATGAGAGTC
 GCCGTGTGGA GCCCCGAACT CCATGGGTTT CCAGTAGAAT TTCAAGCCAG ATGTGGCTGC
 AGCTGAGTCA GAGTCTGAAA GGGTGGGATC ACATGTTCAC TGTTGACTTC TGGACTATTA
 TGGAAAATCA CAACCACAGC AAGGAGTCCC ACACCCTGCA GGTCATCCTG GGCTGTGAAA
 TGCAAGAAGA CAACAGTACC GAGGGCTACT GGAAGTACGG GTATGATGGG CAGGACCACC
 TTGAATTCTG CCCTGACACA CTGGATTGGA GAGCAGCAGA ACCCAGGGCC TGGCCCACCA
 AGCTGGAGTG GGAAAGGCAC AAGATTCGGG CCAGGCAGAA CAGGGCCTAC CTGGAGAGGG
 ACTGCCCTGC ACAGCTGCAG CAGTTGCTGG AGCTGGGGAG AGGTGTTTTG GACCAACAAG
 TGCCTCCTTT GGTGAAGGTG ACACATCATG TGACCTCTTC AGTGACCACT CTACGGTGTC
 GGGCCTTGAA CTACTACCCC CAGAACATCA CCATGAAGTG GCTGAAGGAT AAGCAGCCAA
 TGGATGCCAA GGAGTTCGAA CCTAAAGACG TATTGCCCAA TGGGGATGGG ACCTACCAGG
 GCTGGATAAC CTTGGCTGTA CCCCCTGGGG AAGAGCAGAG ATATACGTAC CAGGTGGAGC
 ACCCAGGCCT GGATCAGCCC CTCATTGTGA TCTGGGAGCC CTCACCGTCT GGCACCCTAG
 TCATTGGAGT CATCAGTGGA ATTGCTGTTT TTGTCGTCAT CTTGTTCATT GGAATTTTGT
 TCATAATATT AAGGAAGAGG CAGGGTTCAA *  
>DL;HLA:HLA14069
HLA:HLA14069 HFE*003 930 bases
 GTTCACACTC TCTGCACTAC CTCTTCATGG GTGCCTCAGA GCAGGACCTT GGTCTTTCCT
 TGTTTGAAGC TTTGGGCTAC GTGGATGACC AGCTGTTCGT GTTCTATGAT GATGAGAGTC
 GCCGTGTGGA GCCCCGAACT CCATGGGTTT CCAGTAGAAT TTCAAGCCAG ATGTGGCTGC
 AGCTGAGTCA GAGTCTGAAA GGGTGGGATC ACATGTTCAC TGTTGACTTC TGGACTATTA
 TGGAAAATCA CAACCACAGC AAGGAGTCCC ACACCCTGCA GGTCATCCTG GGCTGTGAAA
 TGCAAGAAGA CAACAGTACC GAGGGCTACT GGAAGTACGG GTATGATGGG CAGGACCACC
 TTGAATTCTG CCCTGACACA CTGGATTGGA GAGCAGCAGA ACCCAGGGCC TGGCCCACCA
 AGCTGGAGTG GGAAAGGCAC AAGATTCGGG CCAGGCAGAA CAGGGCCTAC CTGGAGAGGG
 ACTGCCCTGC ACAGCTGCAG CAGTTGCTGG AGCTGGGGAG AGGTGTTTTG GACCAACAAG
 TGCCTCCTTT GGTGAAGGTG ACACATCATG TGACCTCTTC AGTGACCACT CTACGGTGTC
 GGGCCTTGAA CTACTACCCC CAGAACATCA CCATGAAGTG GCTGAAGGAT AAGCAGCCAA
 TGGATGCCAA GGAGTTCGAA CCTAAAGACG TATTGCCCAA TGGGGATGGG ACCTACCAGG
 GCTGGATAAC CTTGGCTGTA CCCCCTGGGG AAGAGCAGAG ATATACGTGC CAGGTGGAGC
 ACCCAGGCCT GGATCAGCCC CTCATTGTGA TCTGGGAGCC CTCACCGTCT GGCACCCTAG
 TCATTGGAGT CATCAGTGGA ATTGCTGTTT TTGTCGTCAT CTTGTTCATT GGAATTTTGT
 TCATAATATT AAGGAAGAGG CAGGGTTCAA *  
>DL;HLA:HLA14068
HLA:HLA14068 HFE*004 930 bases
 GTTCACACTC TCTGCACTAC CTCTTCATGG GTGCCTCAGA GCAGGACCTT GGTCTTTCCT
 TGTTTGAAGC TTTGGGCTAC GTGGATGACC AGCTGTTCGT GTTCTATGAT TATGAGAGTC
 GCCGTGTGGA GCCCCGAACT CCATGGGTTT CCAGTAGAAT TTCAAGCCAG ATGTGGCTGC
 AGCTGAGTCA GAGTCTGAAA GGGTGGGATC ACATGTTCAC TGTTGACTTC TGGACTATTA
 TGGAAAATCA CAACCACAGC AAGGAGTCCC ACACCCTGCA GGTCATCCTG GGCTGTGAAA
 TGCAAGAAGA CAACAGTACC GAGGGCTACT GGAAGTACGG GTATGATGGG CAGGACCACC
 TTGAATTCTG CCCTGACACA CTGGATTGGA GAGCAGCAGA ACCCAGGGCC TGGCCCACCA
 AGCTGGAGTG GGAAAGGCAC AAGATTCGGG CCAGGCAGAA CAGGGCCTAC CTGGAGAGGG
 ACTGCCCTGC ACAGCTGCAG CAGTTGCTGG AGCTGGGGAG AGGTGTTTTG GACCAACAAG
 TGCCTCCTTT GGTGAAGGTG ACACATCATG TGACCTCTTC AGTGACCACT CTACGGTGTC
 GGGCCTTGAA CTACTACCCC CAGAACATCA CCATGAAGTG GCTGAAGGAT AAGCAGCCAA
 TGGATGCCAA GGAGTTCGAA CCTAAAGACG TATTGCCCAA TGGGGATGGG ACCTACCAGG
 GCTGGATAAC CTTGGCTGTA CCCCCTGGGG AAGAGCAGAG ATATACGTGC CAGGTGGAGC
 ACCCAGGCCT GGATCAGCCC CTCATTGTGA TCTGGGAGCC CTCACCGTCT GGCACCCTAG
 TCATTGGAGT CATCAGTGGA ATTGCTGTTT TTGTCGTCAT CTTGTTCATT GGAATTTTGT
 TCATAATATT AAGGAAGAGG CAGGGTTCAA *  
