>DL;HLA:HLA02626
HLA:HLA02626 J*01:01:01:01 1095 bases
 ATGGGGTCAT GGCGCCCCGA ACCCTCCTCC TGCTGCTCTC GGGGACCCTG GCCCTGGCCG
 AGACCTGGGC GGGCTCCCAC TCCATGAGGT ATTTCAGCAC CGCCGTTTCC TGGCCGGGCC
 GCGGGGAGCC CAGCTTCATT GCCGTGGGCT ACGTGGACGA CACGCAGTTC GTGCGGGTCG
 ACAGTGACGC CGTGAGTCTG AGGATGAAGA CGCGGGCGCG GTGGGTGGAG CAGGAGGGGC
 CGGAGTATTG GGACCTACAG ACACTGGGCG CCAAGGCCCA GGCACAGACT GACCGAGTGA
 ACCTGCGGAC CCTGCTCCGC TACTACAACC AGAGCGAGGC GGGGTATCAC ATCCTCCAGG
 GAATGTTTGG CTGCGACCTG GGGCCCGACG GGCGTCTCCT CCGCGGGTAT GAGCAGTATG
 CCTACGACGG CAAGGATTAC ATCGCCCTGA ACGAGGACCT GCGCTCCTGG ACCGCCGCGG
 ATACCGCGGC TCAGATTACC CAGCGCAAGT ATGAGGCGGC CAATGTGGCT GAGCAAAGGA
 GAGCCTACCT GGAGGGCACC TGCATGGAGT GGCTCCGCAG ACACCTGGAG AACGGGAAGG
 AGACGCTGCA GCGCGCGGAC CCCCCCCAAG ACACACGTGA CCCACCCCCC TCTCTGAACA
 TGAGGCATAA CGAGGTCCTG GGTTCTGGGC TTCTACCCTG CGGAGATCAC ATTGACCTGG
 CAGCGGGATG GGGAGGACCA GACCCAGGAC ATGGAGCTCG TGGAGACCAG GCCCACAGGG
 GATGGAACCT TCCAGAAGTG GGCGGTTGTG GTAGTGCCTT CTGGAGAGGA ACAGAGATAC
 ACATGCCATG TGCAGCACAA GGGGCTGCCC AAGCCCCTCA TCCTGAGATG GGAGCCCTCT
 CCCCAGCCCA CCATCCCCAT TGTGGGTATC ATTGCTGGCC TGGTTCTCCT TGGAGCTGTG
 GTCACTGGAG CTGTGGTCAC TGCTGTGATG TGGAGGAAGA AGAGCTCAGA TAGAAAAGGA
 GGGAGCTACT CTCAGGCTGC AAGCAGCCAA AGTGCCCAGG GCTCTGATGT GTCTCTCACG
 GCTTGTAAAG TGTGA*    
>DL;HLA:HLA02629
HLA:HLA02629 J*01:01:01:02 1095 bases
 ATGGGGTCAT GGCGCCCCGA ACCCTCCTCC TGCTGCTCTC GGGGACCCTG GCCCTGGCCG
 AGACCTGGGC GGGCTCCCAC TCCATGAGGT ATTTCAGCAC CGCCGTTTCC TGGCCGGGCC
 GCGGGGAGCC CAGCTTCATT GCCGTGGGCT ACGTGGACGA CACGCAGTTC GTGCGGGTCG
 ACAGTGACGC CGTGAGTCTG AGGATGAAGA CGCGGGCGCG GTGGGTGGAG CAGGAGGGGC
 CGGAGTATTG GGACCTACAG ACACTGGGCG CCAAGGCCCA GGCACAGACT GACCGAGTGA
 ACCTGCGGAC CCTGCTCCGC TACTACAACC AGAGCGAGGC GGGGTATCAC ATCCTCCAGG
 GAATGTTTGG CTGCGACCTG GGGCCCGACG GGCGTCTCCT CCGCGGGTAT GAGCAGTATG
 CCTACGACGG CAAGGATTAC ATCGCCCTGA ACGAGGACCT GCGCTCCTGG ACCGCCGCGG
 ATACCGCGGC TCAGATTACC CAGCGCAAGT ATGAGGCGGC CAATGTGGCT GAGCAAAGGA
 GAGCCTACCT GGAGGGCACC TGCATGGAGT GGCTCCGCAG ACACCTGGAG AACGGGAAGG
 AGACGCTGCA GCGCGCGGAC CCCCCCCAAG ACACACGTGA CCCACCCCCC TCTCTGAACA
 TGAGGCATAA CGAGGTCCTG GGTTCTGGGC TTCTACCCTG CGGAGATCAC ATTGACCTGG
 CAGCGGGATG GGGAGGACCA GACCCAGGAC ATGGAGCTCG TGGAGACCAG GCCCACAGGG
 GATGGAACCT TCCAGAAGTG GGCGGTTGTG GTAGTGCCTT CTGGAGAGGA ACAGAGATAC
 ACATGCCATG TGCAGCACAA GGGGCTGCCC AAGCCCCTCA TCCTGAGATG GGAGCCCTCT
 CCCCAGCCCA CCATCCCCAT TGTGGGTATC ATTGCTGGCC TGGTTCTCCT TGGAGCTGTG
 GTCACTGGAG CTGTGGTCAC TGCTGTGATG TGGAGGAAGA AGAGCTCAGA TAGAAAAGGA
 GGGAGCTACT CTCAGGCTGC AAGCAGCCAA AGTGCCCAGG GCTCTGATGT GTCTCTCACG
 GCTTGTAAAG TGTGA*    
>DL;HLA:HLA02653
HLA:HLA02653 J*01:01:01:03 1095 bases
 ATGGGGTCAT GGCGCCCCGA ACCCTCCTCC TGCTGCTCTC GGGGACCCTG GCCCTGGCCG
 AGACCTGGGC GGGCTCCCAC TCCATGAGGT ATTTCAGCAC CGCCGTTTCC TGGCCGGGCC
 GCGGGGAGCC CAGCTTCATT GCCGTGGGCT ACGTGGACGA CACGCAGTTC GTGCGGGTCG
 ACAGTGACGC CGTGAGTCTG AGGATGAAGA CGCGGGCGCG GTGGGTGGAG CAGGAGGGGC
 CGGAGTATTG GGACCTACAG ACACTGGGCG CCAAGGCCCA GGCACAGACT GACCGAGTGA
 ACCTGCGGAC CCTGCTCCGC TACTACAACC AGAGCGAGGC GGGGTATCAC ATCCTCCAGG
 GAATGTTTGG CTGCGACCTG GGGCCCGACG GGCGTCTCCT CCGCGGGTAT GAGCAGTATG
 CCTACGACGG CAAGGATTAC ATCGCCCTGA ACGAGGACCT GCGCTCCTGG ACCGCCGCGG
 ATACCGCGGC TCAGATTACC CAGCGCAAGT ATGAGGCGGC CAATGTGGCT GAGCAAAGGA
 GAGCCTACCT GGAGGGCACC TGCATGGAGT GGCTCCGCAG ACACCTGGAG AACGGGAAGG
 AGACGCTGCA GCGCGCGGAC CCCCCCCAAG ACACACGTGA CCCACCCCCC TCTCTGAACA
 TGAGGCATAA CGAGGTCCTG GGTTCTGGGC TTCTACCCTG CGGAGATCAC ATTGACCTGG
 CAGCGGGATG GGGAGGACCA GACCCAGGAC ATGGAGCTCG TGGAGACCAG GCCCACAGGG
 GATGGAACCT TCCAGAAGTG GGCGGTTGTG GTAGTGCCTT CTGGAGAGGA ACAGAGATAC
 ACATGCCATG TGCAGCACAA GGGGCTGCCC AAGCCCCTCA TCCTGAGATG GGAGCCCTCT
 CCCCAGCCCA CCATCCCCAT TGTGGGTATC ATTGCTGGCC TGGTTCTCCT TGGAGCTGTG
 GTCACTGGAG CTGTGGTCAC TGCTGTGATG TGGAGGAAGA AGAGCTCAGA TAGAAAAGGA
 GGGAGCTACT CTCAGGCTGC AAGCAGCCAA AGTGCCCAGG GCTCTGATGT GTCTCTCACG
 GCTTGTAAAG TGTGA*    
>DL;HLA:HLA02630
HLA:HLA02630 J*01:01:01:04 1095 bases
 ATGGGGTCAT GGCGCCCCGA ACCCTCCTCC TGCTGCTCTC GGGGACCCTG GCCCTGGCCG
 AGACCTGGGC GGGCTCCCAC TCCATGAGGT ATTTCAGCAC CGCCGTTTCC TGGCCGGGCC
 GCGGGGAGCC CAGCTTCATT GCCGTGGGCT ACGTGGACGA CACGCAGTTC GTGCGGGTCG
 ACAGTGACGC CGTGAGTCTG AGGATGAAGA CGCGGGCGCG GTGGGTGGAG CAGGAGGGGC
 CGGAGTATTG GGACCTACAG ACACTGGGCG CCAAGGCCCA GGCACAGACT GACCGAGTGA
 ACCTGCGGAC CCTGCTCCGC TACTACAACC AGAGCGAGGC GGGGTATCAC ATCCTCCAGG
 GAATGTTTGG CTGCGACCTG GGGCCCGACG GGCGTCTCCT CCGCGGGTAT GAGCAGTATG
 CCTACGACGG CAAGGATTAC ATCGCCCTGA ACGAGGACCT GCGCTCCTGG ACCGCCGCGG
 ATACCGCGGC TCAGATTACC CAGCGCAAGT ATGAGGCGGC CAATGTGGCT GAGCAAAGGA
 GAGCCTACCT GGAGGGCACC TGCATGGAGT GGCTCCGCAG ACACCTGGAG AACGGGAAGG
 AGACGCTGCA GCGCGCGGAC CCCCCCCAAG ACACACGTGA CCCACCCCCC TCTCTGAACA
 TGAGGCATAA CGAGGTCCTG GGTTCTGGGC TTCTACCCTG CGGAGATCAC ATTGACCTGG
 CAGCGGGATG GGGAGGACCA GACCCAGGAC ATGGAGCTCG TGGAGACCAG GCCCACAGGG
 GATGGAACCT TCCAGAAGTG GGCGGTTGTG GTAGTGCCTT CTGGAGAGGA ACAGAGATAC
 ACATGCCATG TGCAGCACAA GGGGCTGCCC AAGCCCCTCA TCCTGAGATG GGAGCCCTCT
 CCCCAGCCCA CCATCCCCAT TGTGGGTATC ATTGCTGGCC TGGTTCTCCT TGGAGCTGTG
 GTCACTGGAG CTGTGGTCAC TGCTGTGATG TGGAGGAAGA AGAGCTCAGA TAGAAAAGGA
 GGGAGCTACT CTCAGGCTGC AAGCAGCCAA AGTGCCCAGG GCTCTGATGT GTCTCTCACG
 GCTTGTAAAG TGTGA*    
>DL;HLA:HLA02634
HLA:HLA02634 J*01:01:01:05 1095 bases
 ATGGGGTCAT GGCGCCCCGA ACCCTCCTCC TGCTGCTCTC GGGGACCCTG GCCCTGGCCG
 AGACCTGGGC GGGCTCCCAC TCCATGAGGT ATTTCAGCAC CGCCGTTTCC TGGCCGGGCC
 GCGGGGAGCC CAGCTTCATT GCCGTGGGCT ACGTGGACGA CACGCAGTTC GTGCGGGTCG
 ACAGTGACGC CGTGAGTCTG AGGATGAAGA CGCGGGCGCG GTGGGTGGAG CAGGAGGGGC
 CGGAGTATTG GGACCTACAG ACACTGGGCG CCAAGGCCCA GGCACAGACT GACCGAGTGA
 ACCTGCGGAC CCTGCTCCGC TACTACAACC AGAGCGAGGC GGGGTATCAC ATCCTCCAGG
 GAATGTTTGG CTGCGACCTG GGGCCCGACG GGCGTCTCCT CCGCGGGTAT GAGCAGTATG
 CCTACGACGG CAAGGATTAC ATCGCCCTGA ACGAGGACCT GCGCTCCTGG ACCGCCGCGG
 ATACCGCGGC TCAGATTACC CAGCGCAAGT ATGAGGCGGC CAATGTGGCT GAGCAAAGGA
 GAGCCTACCT GGAGGGCACC TGCATGGAGT GGCTCCGCAG ACACCTGGAG AACGGGAAGG
 AGACGCTGCA GCGCGCGGAC CCCCCCCAAG ACACACGTGA CCCACCCCCC TCTCTGAACA
 TGAGGCATAA CGAGGTCCTG GGTTCTGGGC TTCTACCCTG CGGAGATCAC ATTGACCTGG
 CAGCGGGATG GGGAGGACCA GACCCAGGAC ATGGAGCTCG TGGAGACCAG GCCCACAGGG
 GATGGAACCT TCCAGAAGTG GGCGGTTGTG GTAGTGCCTT CTGGAGAGGA ACAGAGATAC
 ACATGCCATG TGCAGCACAA GGGGCTGCCC AAGCCCCTCA TCCTGAGATG GGAGCCCTCT
 CCCCAGCCCA CCATCCCCAT TGTGGGTATC ATTGCTGGCC TGGTTCTCCT TGGAGCTGTG
 GTCACTGGAG CTGTGGTCAC TGCTGTGATG TGGAGGAAGA AGAGCTCAGA TAGAAAAGGA
 GGGAGCTACT CTCAGGCTGC AAGCAGCCAA AGTGCCCAGG GCTCTGATGT GTCTCTCACG
 GCTTGTAAAG TGTGA*    
>DL;HLA:HLA02632
HLA:HLA02632 J*01:01:01:06 1095 bases
 ATGGGGTCAT GGCGCCCCGA ACCCTCCTCC TGCTGCTCTC GGGGACCCTG GCCCTGGCCG
 AGACCTGGGC GGGCTCCCAC TCCATGAGGT ATTTCAGCAC CGCCGTTTCC TGGCCGGGCC
 GCGGGGAGCC CAGCTTCATT GCCGTGGGCT ACGTGGACGA CACGCAGTTC ATGCGGGTCG
 ACAGTGACGC CGTGAGTCTG AGGATGAAGA CGCGGGCGCG GTGGGTGGAG CAGGAGGGGC
 CGGAGTATTG GGACCTACAG ACACTGGGCG CCAAGGCCCA GGCACAGACT GACCGAGTGA
 ACCTGCGGAC CCTGCTCCGC TACTACAACC AGAGCGAGGC GGGGTATCAC ATCCTCCAGG
 GAATGTTTGG CTGCGACCTG GGGCCCGACG GGCGTCTCCT CCGCGGGTAT GAGCAGTATG
 CCTACGACGG CAAGGATTAC ATCGCCCTGA ACGAGGACCT GCGCTCCTGG ACCGCCGCGG
 ATACCGCGGC TCAGATTACC CAGCGCAAGT ATGAGGCGGC CAATGTGGCT GAGCAAAGGA
 GAGCCTACCT GGAGGGCACC TGCATGGAGT GGCTCCGCAG ACACCTGGAG AACGGGAAGG
 AGACGCTGCA GCGCGCGGAC CCCCCCCAAG ACACACGTGA CCCACCCCCC TCTCTGAACA
 TGAGGCATAA CGAGGTCCTG GGTTCTGGGC TTCTACCCTG CGGAGATCAC ATTGACCTGG
 CAGCGGGATG GGGAGGACCA GACCCAGGAC ATGGAGCTCG TGGAGACCAG GCCCACAGGG
 GATGGAACCT TCCAGAAGTG GGCGGTTGTG GTAGTGCCTT CTGGAGAGGA ACAGAGATAC
 ACATGCCATG TGCAGCACAA GGGGCTGCCC AAGCCCCTCA TCCTGAGATG GGAGCCCTCT
 CCCCAGCCCA CCATCCCCAT TGTGGGTATC ATTGCTGGCC TGGTTCTCCT TGGAGCTGTG
 GTCACTGGAG CTGTGGTCAC TGCTGTGATG TGGAGGAAGA AGAGCTCAGA TAGAAAAGGA
 GGGAGCTACT CTCAGGCTGC AAGCAGCCAA AGTGCCCAGG GCTCTGATGT GTCTCTCACG
 GCTTGTAAAG TGTGA*    
>DL;HLA:HLA02628
HLA:HLA02628 J*01:01:01:07 1082 bases
 ATGGGGTCAT GGCGCCCCGA ACCCTCCTCC TGCTGCTCTC GGGGACCCTG GCCCTGGCCG
 AGACCTGGGC GGGCTCCCAC TCCATGAGGT ATTTCAGCAC CGCGGTTTCC TGGCCGGGCC
 GCGGGGAGCC CAGCTTCATT GCCGTGGGCT ACGTGGACGA CACGCAGGTC GTGCGGGTCG
 ACAGTGACGC CGTGAGTCTG AGGATGAAGA CGCGGGCGCG GTGGGTGGAG CCAGGAGGGG
 CCGGAGTATT GGGACCTACA GACACTGGGC GCCAAGGCCC AGGCACAGAC TGACCGAGTG
 AACCTGCGGA CCCTGCTCCG CTACTACAAC CAGAGCGAGG CGGCGTATCA CATCCTCCAG
 GGAATGTTTG GCTGCGACCT GGGGCCCGAC GGGCGTCTCC TCCGCGGGTA TGAGCAGTAT
 GCCTACGACG GCAAGGATTA CATCGCCCTG AACGAGGACC TGCGCTCCTG GACCGCCGCG
 GATACCGCGG CTCAGATTAC CCAGCGCAAG TATGAGGCGG CCAATGTGGC TGAGCAAAGG
 AGAGCCTACC TGGAGGGCAC CTGCATGGAG TGGCTCCGCA GACACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCGCGGA CCCCCCCAAG ACACACGTGA CCCACCACCC TGTCTCTGAA
 CATGAGGCAT AACGAGGTGC TGGGTTCTGG GCTTCTACCC TGCGGAGATC ACATTGACCT
 GGCAGCGGGA TGGGGAGGAC CAGACCCAGG ACATGGAGCT CGTGGAGACC AGGCCCACAG
 GGGATGGAAC CTTCCAGAAG TGGGCGGTTG TGGTAGTGCC TTCTGGAGAG GAACAGAGAT
 ACACATGCCA TGTGCAGCAC AAGGGGCTGC CCAAGCCCCT CATCCTGAGA TGGGAGCCCT
 CTCCCCAGCC CACCATCCCC ATTGTGGGTA TCATTGCTGG CCTGGTTCTC CTTGGAGCTG
 TGGTCACTGC TGTGATGTGG AGGAAGAAGA GCTCAGATAG AAAAGGAGGG AGCTACTCTC
 AGGCTGCAAG CAGCCAAAGT GCCCAGGGCT CTGATGTGTC TCTCACGGCT TGTAAAGTGT
 GA*     
>DL;HLA:HLA02631
HLA:HLA02631 J*01:01:01:08 1081 bases
 ATGGGGTCAT GGCGCCCCGA ACCCTCCTCC TGCTGCTCTC GGGGACCCTG GCCCTGGCCG
 AGACCTGGGC GGGCTCCCAC TCCATGAGGT ATTTCAGCAC CGCGGTTTCC TGGCCGGGCC
 GCGGGGAGCC CAGCTTCATT GCCGTGGGCT ACGTGGACGA CACGCAGGTC GTGCGGGTCG
 ACAGTGACGC CGTGAGTCTG AGGATGAAGA CGCGGGCGCG GTGGGTGGAG CAGGAGGGGC
 CGGAGTATTG GGACCTACAG ACACTGGGCG CCAAGGCCCA GGCACAGACT GACCGAGTGA
 ACCTGCGGAC CCTGCTCCGC TACTACAACC AGAGCGAGGC GGCGTATCAC ATCCTCCAGG
 GAATGTTTGG CTGCGACCTG GGGCCCGACG GGCGTCTCCT CCGCGGGTAT GAGCAGTATG
 CCTACGACGG CAAGGATTAC ATCGCCCTGA ACGAGGACCT GCGCTCCTGG ACCGCCGCGG
 ATACCGCGGC TCAGATTACC CAGCGCAAGT ATGAGGCGGC CAATGTGGCT GAGCAAAGGA
 GAGCCTACCT GGAGGGCACC TGCATGGAGT GGCTCCGCAG ACACCTGGAG AACGGGAAGG
 AGACGCTGCA GCGCGCGGAC CCCCCCAAGA CACACGTGAC CCACCACCCT GTCTCTGAAC
 ATGAGGCATA ACGAGGTGCT GGGTTCTGGG CTTCTACCCT GCGGAGATCA CATTGACCTG
 GCAGCGGGAT GGGGAGGACC AGACCCAGGA CATGGAGCTC GTGGAGACCA GGCCCACAGG
 GGATGGAACC TTCCAGAAGT GGGCGGTTGT GGTAGTGCCT TCTGGAGAGG AACAGAGATA
 CACATGCCAT GTGCAGCACA AGGGGCTGCC CAAGCCCCTC ATCCTGAGAT GGGAGCCCTC
 TCCCCAGCCC ACCATCCCCA TTGTGGGTAT CATTGCTGGC CTGGTTCTCC TTGGAGCTGT
 GGTCACTGCT GTGATGTGGA GGAAGAAGAG CTCAGATAGA AAAGGAGGGA GCTACTCTCA
 GGCTGCAAGC AGCCAAAGTG CCCAGGGCTC TGATGTGTCT CTCACGGCTT GTAAAGTGTG
 A*     
>DL;HLA:HLA02627
HLA:HLA02627 J*02:01 1094 bases
 ATGGGGTCAT GGCGCCCCGA ACCCTCCTCC TGCTGCTCTC GGGACCCTGC CCTGGCCGAG
 ACCTGGGCGG GCTCCCACTC CATGAGGTAT TTCAGCACCG CCGTTTCCTG GCCGGGCCGC
 GGGGAGCCCA GCTTCATTGC CGTGGGCTAC GTGGACGACA CGCAGTTCGT GCGGGTCGAC
 AGTGACGCCG TGAGTCTGAG GATGAAGACG CGGGCGCGGT GGGTGGAGCA GGAGGGGCCG
 GAGTATTGGG ACCTACAGAC ACTGGGCGCC AAGGCCCAGG CACAGACTGA CCGAGTGAAC
 CTGCGGACCC TGCTCCGCTA CTACAACCAG AGCGAGGCGG GGTATCACAT CCTCCAGGGA
 ATGTTTGGCT GCGACCTGGG GCCCGACGGG CGTCTCCTCC GCGGGTATGA GCAGTATGCC
 TACGACGGCA AGGATTACAT CGCCCTGAAC GAGGACCTGC GCTCCTGGAC CGCCGCGGAT
 ACCGCGGCTC AGATTACCCA GCGCAAGTAT GAGGCGGCCA ATGTGGCTGA GCAAAGGAGA
 GCCTACCTGG AGGGCACCTG CATGGAGTGG CTCCGCAGAC ACCTGGAGAA CGGGAAGGAG
 ACGCTGCAGC GCGCGGACCC CCCCCAAGAC ACACGTGACC CACCCCCCTC TCTGAACATG
 AGGCATAACG AGGTCCTGGG TTCTGGGCTT CTACCCTGCG GAGATCACAT TGACCTGGCA
 GCGGGATGGG GAGGACCAGA CCCAGGACAT GGAGCTCGTG GAGACCAGGC CCACAGGGGA
 TGGAACCTTC CAGAAGTGGG CGGTTGTGGT AGTGCCTTCT GGAGAGGAAC AGAGATACAC
 ATGCCATGTG CAGCACAAGG GGCCTGCCCA AGCCCCTCAT CCTGAGATGG GAGCCCTCTC
 CCCAGCCCAC CATCCCCATT GTGGGTATCA TTGCTGGCCT GGTTCTCCTT GGAGCTGTGG
 TCACTGGAGC TGTGGTCACT GCTGTGATGT GGAGGAAGAA GAGCTCAGAT AGAAAAGGAG
 GGAGCTACTC TCAGGCTGCA AGCAGCCAAA GTGCCCAGGG CTCTGATGTG TCTCTCACGG
 CTTGTAAAGT GTGA*    
