>DL;HLA:HLA02654
HLA:HLA02654 K*01:01:01:01 1092 bases
 ATGGGGTCAT GGCGTCCCGA ACCCTCCTCC TGCTGCTCTT GGGGGCCCTG GCCCTGACCG
 AGACCTGGGC GGGTACCCAC TCCATAAGGT ATTTCAGCAC CGCCGTGTCC CGGCCGGGTC
 GCGGGGAGCC CCGGTACATC GCAGTGGGCT ACGTGGACGA CACGCAGTTC GTGCGGTTCG
 ACAGCGACGC GGCGACTCCG AGGATGTAGC CGCAGTCGCC GTGGTTGGAG CAGGAGGGAC
 CGGAGTATTG GGACCGGAGC ACACGGAACA TCAGGCCCGC GCACAGACTG ACAAGAGTGA
 ACCTGCCCAT GCCGCGCCGC TACTACCACC AGAGCTAGGC CGGGTCTAAC ACCCTCCAGA
 TAATGTATGG CTGCGACTTG GGGCTGGAAG GGCGCCTCCT CCGCGGGTAT GAACAGCACG
 CCAACGATGG CAAGGATTAC ATAGCCCGGA ACTAGGACCT GCGCTCCTGG ACCGCGGCGG
 ACATGGCGGC TCAGATCACC AAGCGCAAGT GGGAGGCAGA AGAATTTGCA GAGCAGATCA
 GGGCCTACCT GGAGGGCACG TGCGTGGAGA GGCTCGCAGA CACCTGGAGA ACGGGAAGGA
 GACGCTGCAG CTCACGGACC TCTCCCCCAG ACACATATGA TCCACCATTC CGTCTCTGAC
 TATAAGGCCA CCCTGAGGTG CTGGGCCCTG GGCTTCTACC CTGTGGAGAT CACACTGGCC
 TGGCAGCAGG ATGGAGAGGA CCAGACTCGG GACATGGAGC TTCTAGAGAC CAGGCCTGCA
 GGGGATGGAA CCTTCCAGAA GTGGGCAGCT GTGGTGGTGC CTTCTGGAGA GGAACAGAGA
 TACCCGTGCC ATGTGCAGCA TGAGGGGTTG CCCAAGCCCC TCACCCTGAG ATGGGAGCAG
 TCTTCTCAGC CCACCATCCC CATCGTGGGT ATCGTTGCTG GCCTGGTTCT CCTTGGAGCT
 GTAGTCACTG GAGCTGTGGT TTCTGCTGTG ATGTGCAGGA AGAAGAACTC AGATAGAGTG
 AGCTACTCTG AAGCTGCAAG CAGCGACCAT GCGCAGGGTT CTGATGTGTC TCTCACGGCT
 TGTAAAGTGT GA    
>DL;HLA:HLA02658
HLA:HLA02658 K*01:01:01:02 1093 bases
 ATGGGGTCAT GGCGTCCCGA ACCCTCCTCC TGCTGCTCTT GGGGGCCCTG GCCCTGACCG
 AGACCTGGGC GGGTACCCAC TCCATAAGGT ATTTCAGCAC CGCCGTGTCC CGGCCGGGTC
 GCGGGGAGCC CCGGTACATC GCAGTGGGCT ACGTGGACGA CACGCAGTTC GTGCGGTTCG
 ACAGCGACGC GGCGACTCCG AGGATGTAGC CGCAGGCGCA GTGGTTGGAG CAGGATGGAC
 CGGAGTATTG GGACCGGAGC ACACGGAACA TCAGGCCCGC GCACAGACTG ACAAGAGTGA
 ACCTGCCCAT GCCGCGCCGC TACTACCACC AGAGCTAGGC CGGGTCTAAC ACCCTCCAGA
 TAATGTATGG CTGCGACTTG GGGCTGGAAG GGCGCCTCCT CCGCGGGTAT GAACAGCACC
 CCAACGATGG CAAGGATTAC ATAGCCCGGA ACTAGGACCT GCGCTCCTGG ACCGCGGCGG
 ACATGGAGGC TCAGATCACC AAGCGCAAGT GGGAGGCAGA AGAATTTGCA GAGCAGATCA
 GGGCCTACCT GGAGGGCACG TGCGTGGAGA GGCTCGCAGA CACCTGGAGA ACGGGAAGGA
 GATGCTGCAG CTCACGGACC CCCCCACCAA GACACATATG ATCCACCATT CCATCTCTGA
 CTATAAGGCC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGTGGAGA TCACACTGAC
 CTGGCAGCAG GATGGAGAGG ACCAGACTCG GGACATGGAG CTTGTAGAGA CCAGGCCTGC
 AGGGGATGGA AACTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG
 ATACATGTGC CATGTGCAGC ATGAGGGGTT GCCCAAGCCC CTCACCCTGA GATGGAAGCA
 GTCTTCTCAG CCCACCATCC CCATCGTGGG TATCGTTGCT GGCCTGGTTC TCCTTGGAGC
 TGTAGTCACT GGAGCTGTGG TTTCTGCTGT GATGTGCAGG AAGAAGAACT CAGATAGAGT
 GAGCTACTCT GAAGCTGCAA GCAGTGACCA TGCGCAGGGT TCTGATGTGT CTCTCATGGC
 TTGTAAAGTG TGA    
>DL;HLA:HLA02657
HLA:HLA02657 K*01:01:01:03 1093 bases
 ATGGGGTCAT GGCGTCCCGA ACCCTCCTCC TGCTGCTCTT GGGGGCCCTG GCCCTGACCG
 AGACCTGGGC GGGTTCCCAC TCCATAAGGT AGTTCAGCAC CGCCGTGTCC CGGCCGGGTC
 GCGGGGAGCC CCGGTACATC GCAGTGGGCT ACGTGGACGA CACGCAGTTC GTGCGGTTCG
 ACAGCGACGC GGCGACTCCG AGGACGTAGC CGCAGTCGCC GTGGTTGGAG CAGGAGGGAC
 CGGAGTATTG GGACCGGAGC ACACGGAACA TCAGGCCCGC GCACAGACTG ACAAGAGTGA
 ACCTGCCCAT GCCGCGCCGC TACTACCACC AGAGCTAGGC CGGGTCTAAC ACCCTCCAGA
 TAATGTATGG CTGCGACTTG GGGCTGGAAG GGCGCCTCCT CCGCGGGTAT GAACAGCACG
 CCAACGATGG CAAGGATTAC ATAGCCCGGA ACTAGGACCT GCGCTCCTGG ACCGCGGCGG
 ACATGGCGGC TCAGATCATC AAGCGCAAGT GGGAGGCAGA AGAATTTGCA GAGCAGATCA
 GGGCCTACCT GGAGGGCACG TGCGTGGAGA GGCTCGCAGA CACCTGGAGA ACGGGAAGGA
 GACGCTGCAG CTCACTGACC CCCGCCCCCA GACACATATG ATCCACCATT CCGTCTCTGA
 CTATAAGGCC ACCCTGAGGT GCTGGGCCCT GGGCTTCTAC CCTGTGGAGA TCACACTGAC
 CTGGCAGCAG GATGGAGAGG ACCAGACTAG GGACATGGAG CTTGTAGAGA CCAGGCCTGC
 AGGGGATGGA ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG CCTTCTGGAG AGGAACAGAG
 ATACCCGTGC CATGTGCAGC ATGAGGGGTT GCCCAAGCCC CTCACCCTGA GATGGGAGCA
 GTCTTCTCAG CCCACCATCC CCATCGTGGG CATCATTGCT GGCCTGGTTC TCCTTGGAGC
 TGTAGTCACT GGAGCTGTGG TTTCTGCTGT GATGTGCAGG AAGAAGAACT CAGATAGAGT
 GAGCTACTCT GAAGCTGCAA GCAGCGACCA TGCGCAGGGT TCTGATGTGT CTCTCACGGC
 TTGTAAAGTG TGA    
>DL;HLA:HLA02659
HLA:HLA02659 K*01:01:01:04 1094 bases
 ATGGGGTCAT GGCGTCCCGA ACCCTCCTCC TGCTGCTCTT GGGGGCCCTG GCCCTGACCG
 AGACCTGGGC GGGTTCCCAC TCCATAAGGT AGTTCAGCAC CGCCGTGTCC CGGCCGGGTC
 GCGGGGAGCC CCGGTACATC GCAGTGGGCT ACGTGGACGA CACGCAGTTC GTGCGGTTCG
 ACAGCGACGC GGCGACTCCG AGGATGTAGC CGCAGGCGCC GTGGTTGGAG CAGGAGGGAC
 CGGAGTATTG GGACCGGAGC ACACGGAACA TCAGGCCCGC GCACAGACTG ACAAGAGTGA
 ACCTGCCCAT GCCGCGCCGC TACTACCACC AGAGCTAGGC CGGGTCTAAC AACCTCCAGA
 TAATGTATGG CTGCGACTTG GGGCTGGAAG GGCGCCTCCT CCGCGGGTAT GAACAGCACG
 CCAACGATGG CAAGGATTAC ATAGCCCGGA ACTAGGACCT GCGCTCCTGG ACCGCGGCGG
 ACATGGCGGC TCAGATCACC AAGCGCAAGT GGGAGGCAGA AGAATTTGCA GAGCAGATCA
 GGGCCTACCT GGAGGGCACG TGCGTGGAGA GGCTCGCAGA CACCTGGAGA ACGGGAAGGA
 GATGCTGCAG CTCACGGACA CCCCCCTCCA AGACACATAT GATCCACCAT TCCATCTCTG
 ACTATAAGGC CACCCTGAGG TGCTGGGCCC TGGGCTTCTA CCCTGTGGAG ATCACACTGA
 GCTGGCAGCA AGATGGAGAG GACCAGACTC GGGACATGGA GCTTGTAGAG ACCAGGCCTG
 CAGGGGATGG AACCTTCCAG AAGTGGGCAG CTGTGGTGGT GCCTTCTGGA GAGGAACAGA
 GATACATGTG CCATGTGCAG CATGAGGGGT TGCCCGAGCC CCTCACCCTG AGATGGGAGC
 AGTCTTCTCA GCCCACCATC CCCATCGTGG GCATCGTTAC TGGCCTGGTT CTCCTTGGAG
 CTGTAGTCAC TGGAGCTGTG GTTTCTGCTG TGATGTGCAG GAAGAAGAAC TCAGATAGAG
 TGAGCTACTC TGAAGCTGCA AGCAGCGACC ATGCGCAGGG TTCTGATGTG TCTCTCACGG
 CTTGTAAAGT GTGA    
>DL;HLA:HLA02656
HLA:HLA02656 K*01:02 1093 bases
 ATGGGGTTAT GGCGTCCCGA ACCCTCCTCC TGCTGCTCTT GGGGGCCCTG GCCCTGACCG
 AGACCTGGGC GGGTTCCCAC TCCATAAGGT AGTTCAGCAC CGCCGTGTCC CGGCCGGGTC
 GCGGGGAGCC CCGGTACATC GCAGTGGGCT ACGTGGACGA CACGCAGTTC GTGCGGTTCG
 ACAGCGACGC GGCGACTCCG AGGATGTAGC CGCAGGCGCC GTGGTTGGAG CAGGAGGGAC
 CGGAGTATTG GGACCGGAGC ACACGGAACA TCAGGCCCGC GCACAGACTG ACAAGAGTGA
 ACCTGCCCAT GCCGCGCCGC TACTACCACC AGAGCTAGGC CGGGTCTAAC ACCCTCCAGA
 TAATGTATGG CTGCGACTCG GGGCTGGAAC GGCGCCTCCT CCGCGGGTAT GAACAGCACG
 CCAACGATGG CAAGGATTAC ATAGCCCGGA ACTAGGACCT GCGCTCCTGG ACCGCGGCGG
 ACATGGCGGC TCAGATCACC AAGCGCAAGT GGGAGGCAGA AGAATTTGCA GAGCAGATCA
 GGGCCTACCT GGAGGGCACG TGCGTGGAGA GGCTCGCAGA CACCTGGAGA ACGGGAAGGA
 GATGCTGCAG CTCACGGACA CCCCCCCCGC AAGACACATA TGATCCACCA TTCCATCTCT
 GACTATAAGG CCACCCTGAG GTGCTGGGCC CTGGGCTTCT ACCCTATGGA GATCACACTG
 AGCTGGCAGC AGGATGAAGA GGACCAGACT CGGGACATGG AGCTTGTAGA GACCAGGCCT
 GCAGGGGATG GAACCTTCCA GAAGTGGGCA GCTGTGGTGG TGCCTTCTGG AGAGGAACAG
 ATACATGTGC CATGTGCAGC ATGAGGGGTT GCCCGAGCCC CTCACCCTGA GATGGGAGCA
 GTCTTCTCAG CCCACCATCC CCATCGTGGG CATCGTTACT GGCCTGGTTC TCCTTGGAGC
 TGTAGTCACT GGAGCTGTGG TTTCTGCTGT GATGTGCAGG AAGAAGAACT CAGATAGAGT
 GAGCTACTCT GAAGCTGCAA GCAGCGACCA TGCGCAGGGT TCTGATGTGT CTCTCACGGC
 TTGTAAAGTG TGA    
>DL;HLA:HLA02660
HLA:HLA02660 K*01:03 1091 bases
 ATGGGGTCAT GGCGTCCCAA ACCCTCCTCC TGCTGCTCTT GGGGGCCCTG GCCCTGACCG
 AGACCTGGGC GGGTACCCAC TCCATAAGGT ATTTCAGCAC CGCCGTGTCC CGGCCGGGTC
 GCGGGGAGCC CCGGTACATC GCAGTGGGCT ACGTGGACGA CACGCAGTTC GTGCGGTTCG
 ACAGCGACGC GGCGACTCCG AGGATGTAGC CGCAGGCGCC GTGGTTGGAG CAGGAGGGAC
 CGGAGTATTG GGACCGGAGC ACACCGAACA TCAGGCCCGC GCACAGACTG ACAAGAGTGA
 ACCTGCCCAT GCCGCGCCGC TACTACCACC AGAGCTAGGC CGGGTCTAAC ACCCTCCAGA
 TAATGTATGG CTGCGACTTG GGGCTGGAAG GGCGCCTCCT CCGCGGGTAT GAACAGCACG
 CCAACGATGG CAAGGATTAC ATAGCCCGGA ACTAGGACCT GCGCTCCTGG ACCGCGGCGG
 ACATGGCGGC TCAGATCACC AAGCGCAAGT GGGAGGCAGA AGAATTTGCA GAGCAGATCA
 GGGCCTACCT GGAGGGCACG TGCGTGGAGA GGCTCGCAGA CACCTGGAGA ACGGGAAGGA
 GACGCTGCAG CTCACGGACC CCCCCCCCCA AGACACATAT GATCCACCAT TCCGTCTCTG
 ACTATAAGGC CACCCTGAGA TGCTGGGCCC TGGGCTTCTA CCCTGTGGAG ATCACACTGA
 CCTGGCAGCA GGATGGAGAG GACCAGACTC AGGACATGGA GCTTGTAGAG ACCAGGCCTG
 CAGGGGATGG AAACTTCCAG AAGTGGGCAG CTGTGGTGGT GCCTTCTGGA GAGGAACAGA
 GATACATGTG CCATGTGCAG CATGAGGGGT TGCCCAAGCC CCTCACCCTG AGATGGAAGC
 AGTCTTCTCA GCCCACCATC CCCATCGTGG GTATCGTTGC TGGCCTGGTT CTCCTTGGAG
 CTGTAGTCAC TGGAGCTGTG GTTTCTGCTG TGATGTGCAG GAAGAACTCA GATAGAGTGA
 GCTACTCTGA AGCTGCAAGC AGCAACCATG CGCAGGGTTC TGATGTGTCT CTCACGGCTT
 GTAAAGTGTG A    
