>DL;HLA:HLA02655
HLA:HLA02655 L*01:01:01:01 1096 bases
 ATGGGGGTCA TGGCTCCCCG AACCCTCCTC CTGCTGCTCT TGGGGGCCCT GGCCCTGACC
 GAGACCTGGG CCGGCTCCCA CTCCTTGAGG TATTTCAGCA CCGCAGTGTC CCAGCCCGGC
 CGCGGGGAGC CCCGGTTCAT CGCCGTGGGC TACGTGGACG ACACAGAGTT CGTGCGGTTC
 GACAGCGACT CCGTGAGTCC GAGGATGGAG CGGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CTGGAGTATT GGGACCAGGA GACACGGAAC GCCAAGGGCC ACGCGCAGAT TTACCGAGTG
 AACCTGCGGA CCCTGCTCCG CTATTACAAC CAGAGCGAGG CCGGTTCTCA CACCATCCAG
 AGGAAGCATG GCTGCGACGT GGGCCCGACA GGCGCCTCCT CCGCAGGTAT GAACAGTTCG
 CCTACGATGG CAAGGATTAC ATCGCCCTGA ACGAGGACCT GCACTCCTGG ACCGCCGCGA
 ACACAGCGGC TCAGATCTCC CAGCACAAGT GGGAAGCGGA CAAATACTCA GAGCAGGTCA
 GGGCCTACCT GAGGGCAAGT GCATGGAGTG GCTCCGCAGA CACCTGGAGA ACGGGAAGGA
 GACGCTGCAG CACGCGGATC CCCCAAAGGC ACATGTGACC CAGCACCCCA TCTCTGACCA
 TGAGGCCACC CTGAGGTGCT GGGCCCTGGG CCTCTACCCT GCGGAGATCA CACTGACCTG
 GCAGCAGGAT GGGGAGGACC AGACCCAGGA CACGGAGCTT GTGGAGACCA GGCCTGCAGG
 GGACGGAACC TTCCAGAAGT GGGTGGCTGT AGTGGTGCCT TCCGGAGAGG AGCAGAGATA
 CATGTGCCAT GTGCAGCATG AGGGGCTGCC AGAGCCCCTC ACCCTGAGAT GGGAGCCGTC
 TTCTCAGCCC ACCATCCCCA TCGTGGGCAT CGTTGCTGGC CTGTTTCTCC TTGGAGCTGT
 GGTCACTGGA GCTGTGGTTG CTGCTGCGAT GTGGAGGAAG AAAAGCTCAG ATAGAACAAG
 GAGGAGCTAT GCTCGGGCTG CCTGCAGCAA TTGTGCTCAG TACTCTGATG CATCTCATGA
 TACTTGTAAA GCTTGA    
>DL;HLA:HLA02662
HLA:HLA02662 L*01:01:01:02 1096 bases
 ATGGGGGTCA TGGCTCCCCG AACCCTCCTC CTGCTGCTCT TGGGGGCCCT GGCCCTGACC
 GAGACCTGGG CCGGCTCCCA CTCCTTGAGG TATTTCAGCA CCGCAGTGTC CCAGCCCGGC
 CGCGGGGAGC CCCGGTTCAT CGCCGTGGGC TACGTGGACG ACACAGAGTT CGTGCGGTTC
 GACAGCGACT CCGTGAGTCC GAGGATGGAG CGGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CTGGAGTATT GGGACCAGGA GACACGGAAC GCCAAGGGCC ACGCGCAGAT TTACCGAGTG
 AACCTGCGGA CCCTGCTCCG CTATTACAAC CAGAGCGAGG CCGGTTCTCA CACCATCCAG
 AGGAAGCATG GCTGCGACGT GGGCCCGACA GGCGCCTCCT CCGCAGGTAT GAACAGTTCG
 CCTACGATGG CAAGGATTAC ATCGCCCTGA ACGAGGACCT GCACTCCTGG ACCGCCGCGA
 ACACAGCGGC TCAGATCTCC CAGCACAAGT GGGAAGCGGA CAAATACTCA GAGCAGGTCA
 GGGCCTACCT GAGGGCAAGT GCATGGAGTG GCTCCGCAGA CACCTGGAGA ACGGGAAGGA
 GACGCTGCAG CACGCGGATC CCCCAAAGGC ACATGTGACC CAGCACCCCA TCTCTGACCA
 TGAGGCCACC CTGAGGTGCT GGGCCCTGGG CCTCTACCCT GCGGAGATCA CACTGACCTG
 GCAGCAGGAT GGGGAGGACC AGACCCAGGA CACGGAGCTT GTGGAGACCA GGCCTGCAGG
 GGACGGAACC TTCCAGAAGT GGGTGGCTGT AGTGGTGCCT TCCGGAGAGG AGCAGAGATA
 CATGTGCCAT GTGCAGCATG AGGGGCTGCC AGAGCCCCTC ACCCTGAGAT GGGAGCCGTC
 TTCTCAGCCC ACCATCCCCA TCGTGGGCAT CGTTGCTGGC CTGTTTCTCC TTGGAGCTGT
 GGTCACTGGA GCTGTGGTTG CTGCTGCGAT GTGGAGGAAG AAAAGCTCAG ATAGAACAAG
 GAGGAGCTAT GCTCGGGCTG CCTGCAGCAA TTGTGCTCAG TACTCTGATG CATCTCATGA
 TACTTGTAAA GCTTGA    
>DL;HLA:HLA02663
HLA:HLA02663 L*01:01:01:03 1096 bases
 ATGGGGGTCA TGGCTCCCCG AACCCTCCTC CTGCTGCTCT TGGGGGCCCT GGCCCTGACC
 GAGACCTGGG CCGGCTCCCA CTCCTTGAGG TATTTCAGCA CCGCAGTGTC CCAGCCCGGC
 CGCGGGGAGC CCCGGTTCAT CGCCGTGGGC TACGTGGACG ACACAGAGTT CGTGCGGTTC
 GACAGCGACT CCGTGAGTCC GAGGATGGAG CGGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CTGGAGTATT GGGACCAGGA GACACGGAAC GCCAAGGGCC ACGCGCAGAT TTACCGAGTG
 AACCTGCGGA CCCTGCTCCG CTATTACAAC CAGAGCGAGG CCGGTTCTCA CACCATCCAG
 AGGAAGCATG GCTGCGACGT GGGCCCGACA GGCGCCTCCT CCGCAGGTAT GAACAGTTCG
 CCTACGATGG CAAGGATTAC ATCGCCCTGA ACGAGGACCT GCACTCCTGG ACCGCCGCGA
 ACACAGCGGC TCAGATCTCC CAGCACAAGT GGGAAGCGGA CAAATACTCA GAGCAGGTCA
 GGGCCTACCT GAGGGCAAGT GCATGGAGTG GCTCCGCAGA CACCTGGAGA ACGGGAAGGA
 GACGCTGCAG CACGCGGATC CCCCAAAGGC ACATGTGACC CAGCACCCCA TCTCTGACCA
 TGAGGCCACC CTGAGGTGCT GGGCCCTGGG CCTCTACCCT GCGGAGATCA CACTGACCTG
 GCAGCAGGAT GGGGAGGACC AGACCCAGGA CACGGAGCTT GTGGAGACCA GGCCTGCAGG
 GGACGGAACC TTCCAGAAGT GGGTGGCTGT AGTGGTGCCT TCCGGAGAGG AGCAGAGATA
 CATGTGCCAT GTGCAGCATG AGGGGCTGCC AGAGCCCCTC ACCCTGAGAT GGGAGCCGTC
 TTCTCAGCCC ACCATCCCCA TCGTGGGCAT CGTTGCTGGC CTGTTTCTCC TTGGAGCTGT
 GGTCACTGGA GCTGTGGTTG CTGCTGCGAT GTGGAGGAAG AAAAGCTCAG ATAGAACAAG
 GAGGAGCTAT GCTCGGGCTG CCTGCAGCAA TTGTGCTCAG TACTCTGATG CATCTCATGA
 TACTTGTAAA GCTTGA    
>DL;HLA:HLA02661
HLA:HLA02661 L*01:01:02 1096 bases
 ATGGGGGTCA TGGCTCCCCG AACGCTCCTC CTGCTGCTCT TGGGGGCCCT GGCCCTGACC
 GAGACCTGGG CCGGCTCCCA CTCCTTGAGG TATTTCAGCA CCGCAGTGTC CCAGCCCGGC
 CGCGGGGAGC CCCGGTTCAT CGCCGTGGGC TACGTGGACG ACACAGAGTT CGTGCGGTTC
 GACAGCGACT CCGTGAGTCC GAGGATGGAG CGGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CTGGAGTATT GGGACCAGGA GACACGGAAC GCCAAGGGCC ACGCGCAGAT TTACCGAGTG
 AACCTGCGGA CCCTGCTCCG CTATTACAAC CAGAGCGAGG CCGGTTCTCA CACCATCCAG
 AGGAAGCATG GCTGCGACGT GGGCCCGACA GGCGCCTCCT CCGCAGGTAT GAACAGTTCG
 CCTACGATGG CAAGGATTAC ATCGCCCTGA ACGAGGACCT GCACTCCTGG ACCGCCGCGA
 ACACAGCGGC TCAGATCTCC CAGCACAAGT GGGAAGCGGA CAAATACTCA GAGCAGGTCA
 GGGCCTACCT GAGGGCAAGT GCATGGAGTG GCTCCGCAGA CACCTGGAGA ACGGGAAGGA
 GACGCTGCAG CACGCGGATC CCCCAAAGGC ACATGTGACC CAGCACCCCA TCTCTGACCA
 TGAGGCCACC CTGAGGTGCT GGGCCCTGGG CCTCTACCCT GCGGAGATCA CACTGACCTG
 GCAGCAGGAT GGGGAGGACC AGACCCAGGA CACGGAGCTT GTGGAGACCA GGCCTGCAGG
 GGACGGAACC TTCCAGAAGT GGGTGGCTGT AGTGGTGCCT TCCGGAGAGG AGCAGAGATA
 CATGTGCCAT GTGCAGCATG AGGGGCTGCC AGAGCCCCTC ACCCTGAGAT GGGAGCCGTC
 TTCTCAGCCC ACCATCCCCA TCGTGGGCAT CGTTGCTGGC CTGTTTCTCC TTGGAGCTGT
 GGTCACTGGA GCTGTGGTTG CTGCTGCGAT GTGGAGGAAG AAAAGCTCAG ATAGAACAAG
 GAGGAGCTAT GCTCGGGCTG CCTGCAGCAA TTGTGCTCAG TACTCTGATG CATCTCATGA
 TACTTGTAAA GCTTGA    
>DL;HLA:HLA02664
HLA:HLA02664 L*01:02 1094 bases
 ATGGGGGTCA TGGCTCCCCG AACCCTCCTC CTGCTGCTCT TGGGGGCCCT GGCCCTGACC
 GAGACCTGGG CCGGCTCCCA CTCCTTGAGG TATTTCAGCA CCGCAGTGTC CCAGCCCGGC
 CGCGGGGAGC CCCGGTTCAT CGCCGTGGGC TACGTGGACG ACACAGAGTT CGTGCGGTTC
 GACAGCGACT CCGTGAGTCC GAGGATGGAG CGGCGGGCGC CGTGGGTGGA GCAGGAGGGG
 CTGGAGTATT GGGACCAGGA GACACGGAAC GCCAAGGGCC ACGCGCAGAT TTACCGAGTG
 AACCTGCGGA CCCTGCTCCG CTATTACAAC CAGAGCGAGG CCGGTTCTCA CACCATCCAG
 AGGAAGCATG ACTGCGACGT GGGCCCGACA GGCGCCTCCT CCGCAGGTAT GAACAGTTCG
 CCTACGATGG CAAGGATTAC ATCGCCCTGA ACGAGGACCT GCCCTCCTGG ACCGCCGCGA
 ACACAGCGGC TCAGATCTCC CAGCACAAGT GGGAAGCGGA CAAATACTCA GAGCAGGTCA
 GGGCCTACCT GAGGGCAAGT GCATGGAGTG GCTCCGCAGA CACCTGGAGA ACGGGAAGGA
 GACGCTGCAG CGCGCGGATC CCCCAAAGGC ACATGTGACC CAGCACCCCG TCTCTGACCA
 TGAGGCCACC CTTGAGGTGC TGGGCCCTGG GCCTCTACCC TGCGGAGATC ACACTGACCT
 GGCAGCAGGA TGGGGAGGAC CAGACCCAGG ACACGGAGCT TGTGGAGACC AGGCCTGCAG
 GGGACGGAAC CTTCCAGAAG TGGGTGGCTG TAGTGGTGCC TTCCGGAGAG GAGCAGAGAT
 ACATGTGCCA TGTGCAGCAT GAGGGGCTGC CAGAGCCCCT CACCCTGAGA TGGGAGCCGT
 CTTCTCAGCC CACCATCCCC ATCGTGGGCA TCGTTGCTGG CCTGTTTCTC CTTGGAGCTG
 TGGTCACTGG AGCTGTGGTT GCTGCTGTGA TGTAGAGGAA GAAAAGCTCA GATGGAACAA
 GGAGCTATGC TCGGGCTGCC TGCAGCAATT GTGCCCAGTA CTCTGATGCA TCTCATGATA
 CTTGTAAAGC TTGA    
