>P1;HLA:HLA01013
HLA:HLA01013 MICA*001 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETKEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA01014
HLA:HLA01014 MICA*002:01 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA01381
HLA:HLA01381 MICA*002:02 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA03752
HLA:HLA03752 MICA*002:03 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA05867
HLA:HLA05867 MICA*002:04 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA01015
HLA:HLA01015 MICA*004 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRRVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA01016
HLA:HLA01016 MICA*005 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01017
HLA:HLA01017 MICA*006 361 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSIVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVRCCK KKTSAAEGPE LVSLQVLDQH PVGTSDHRDA TQLGFQPLMS ALGSTGSTEG
 A*     
>P1;HLA:HLA01018
HLA:HLA01018 MICA*007:01 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA01382
HLA:HLA01382 MICA*007:02 274 bases
 EPHSLRYNLT VLSWDGSVQS GFLAEVHLDG QPFLRCDRQK CRAKPQGQWA EDVLGNKTWD
 RETRDLTGNG KDLRMTLAHI KDQKEGLHSL QEIRVCEIHE DNSTRSSQHF YYDGELFLSQ
 NLETEEWTMP QSSRAQTLAM NVRNFLKEDA MKTKTHYHAM HADCLQELRR YLKSGVVLRR
 TVPPMVNVTR SEASEGNITV TCRASGFYPW NITLSWRQDG VSLSHDTQQW GDVLPDGNGT
 YQTWVATRIC QGEEQRFTCY MEHSGNHSTH PVPS*  
>P1;HLA:HLA02147
HLA:HLA02147 MICA*007:03 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA07097
HLA:HLA07097 MICA*007:04 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA08958
HLA:HLA08958 MICA*007:05 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA08961
HLA:HLA08961 MICA*007:06 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA01019
HLA:HLA01019 MICA*008:01:01 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA06643
HLA:HLA06643 MICA*008:01:02 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA01363
HLA:HLA01363 MICA*008:02 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA01402
HLA:HLA01402 MICA*008:03 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA02488
HLA:HLA02488 MICA*008:04 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA08919
HLA:HLA08919 MICA*008:05 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA01020
HLA:HLA01020 MICA*009:01 361 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVRCCK KKTSAAEGPE LVSLQVLDQH PVGTSDHRDA TQLGFQPLMS ALGSTGSTEG
 A*     
>P1;HLA:HLA01397
HLA:HLA01397 MICA*009:02 361 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVRCCK KKTSAAEGPE LVSLQVLDQH PVGTSDHRDA TQLGFQPLMS ALGSTGSTEG
 A*     
>P1;HLA:HLA01021
HLA:HLA01021 MICA*010:01 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA06451
HLA:HLA06451 MICA*010:02 360 bases
 PHSLPYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGPEL VSLQVLDQHP VGTSDHRDAT QLGFQPLMSA LGSTGSTEGA
 *     
>P1;HLA:HLA01022
HLA:HLA01022 MICA*011 361 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAV KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHA VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVCCCK KKTSAAEGPE LVSLQVLDQH PVGTSDHRDA TQLGFQPLMS ALGSAGSTEG
 A*     
>P1;HLA:HLA01023
HLA:HLA01023 MICA*012:01 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTLY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA01401
HLA:HLA01401 MICA*012:02 273 bases
 PHSLRYNLTV LSWDGSVQSG FLTEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTLYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA03110
HLA:HLA03110 MICA*012:03 274 bases
 EPHSLRYNLT VLSWDGSVQS GFLTEVHLDG QPFLRCDRQK CRAKPQGQWA EDVLGNKTWD
 RETRDLTGNG KDLRMTLAHI KDQKEGLHSL QEIRVCEIHE DNSTRSSQHF YYDGELFLSQ
 NLETEEWTMP QSSRAQTLAM NVRNFLKEDA MKTKTLYHAM HADCLQELRR YLKSGVVLRR
 TVPPMVNVTR SEASEGNITV TCRASGFYPW NITLSWRQDG VSLSHDTQQW GDVLPDGNGT
 YQTWVATRIC QGEEQRFTCY MEHSGNHSTH PVPS*  
>P1;HLA:HLA10241
HLA:HLA10241 MICA*012:04 317 bases
 PHSLRYNLTV LSWDGSVQSG FLTEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTLYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA14483
HLA:HLA14483 MICA*012:05 273 bases
 PHSLRYNLTV LSWDGSVQSG FLTEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTLYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01024
HLA:HLA01024 MICA*013 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01025
HLA:HLA01025 MICA*014 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDRELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRR
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01026
HLA:HLA01026 MICA*015 325 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDRELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKCWCFR VIGRHSMFLL LLLLLLLLLL
 FLLLLFSTSV VVRRKHQLQR VQSSX*   
>P1;HLA:HLA01027
HLA:HLA01027 MICA*016 360 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGL SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGPEL VSLQVLDQHP VGTSDHRDAT QLGFQPLMSA LGSTGSTEGA
 *     
>P1;HLA:HLA01335
HLA:HLA01335 MICA*017 349 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLREIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKC
 WCFRVIGRHS MFLLLLLLLL LLLLFLLLLF STSVVVRRKH QLQRVQSSX* 
>P1;HLA:HLA01336
HLA:HLA01336 MICA*018:01 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
>P1;HLA:HLA02034
HLA:HLA02034 MICA*018:02 318 bases
 EPHSLRYNLT VLSWDGSVQS GFLTEVHLDG QPFLRCDRQK CRAKPQGQWA EDVLGNKTWD
 RETRDLTGNG KDLRMTLAHI KDQKEGLHSL QEIRVCEIHE DNSTRSSQHF YYDGELFLSQ
 NLETEEWTMP QSSRAQTLAM NVRNFLKEDA MKTKTHYHAM HADCLQELRR YLKSGVVLRR
 TVPPMVNVTR SEASEGNITV TCRASGFYPW NITLSWRQDG VSLSHDTQQW GDVLPDGNGT
 YQTWVATRIC QGEEQRFTCY MEHSGNHSTH PVPSGKVLVL QSHWQTFHVS AVAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA01334
HLA:HLA01334 MICA*019:01 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA13376
HLA:HLA13376 MICA*019:02 318 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA01370
HLA:HLA01370 MICA*020 323 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 AIFVIIIFYV CCCKKKTSAA EGP*   
>P1;HLA:HLA01394
HLA:HLA01394 MICA*022 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01396
HLA:HLA01396 MICA*023 309 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA01391
HLA:HLA01391 MICA*024 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01392
HLA:HLA01392 MICA*025 273 bases
 PHSLPYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01393
HLA:HLA01393 MICA*026 319 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVRCCK KKTSAAEGP*    
>P1;HLA:HLA01371
HLA:HLA01371 MICA*027 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA01398
HLA:HLA01398 MICA*028 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA01365
HLA:HLA01365 MICA*029 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN IRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA01333
HLA:HLA01333 MICA*030 319 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHA VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVCCCK KKTSAAEGP*    
>P1;HLA:HLA01383
HLA:HLA01383 MICA*031 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETKEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01386
HLA:HLA01386 MICA*032 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTLYHAMH ADCLQELRRY LKSSVVLRRR
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01366
HLA:HLA01366 MICA*033 318 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LESEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA01395
HLA:HLA01395 MICA*034 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAV KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01384
HLA:HLA01384 MICA*035 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01387
HLA:HLA01387 MICA*036 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTKSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01388
HLA:HLA01388 MICA*037 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01389
HLA:HLA01389 MICA*038 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01390
HLA:HLA01390 MICA*039 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGL SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01385
HLA:HLA01385 MICA*040 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETKEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01367
HLA:HLA01367 MICA*041 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEGHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA01399
HLA:HLA01399 MICA*042 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01368
HLA:HLA01368 MICA*043 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTRYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQSFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVCCCKKK TSAAEGP*    
>P1;HLA:HLA01400
HLA:HLA01400 MICA*044 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRR
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01369
HLA:HLA01369 MICA*045 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICEGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA01372
HLA:HLA01372 MICA*046 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFCPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA01410
HLA:HLA01410 MICA*047 319 bases
 PHSLRYNLTV LSGDGSVQSG FLAEGHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHA VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVCCCK KKTSAAEGP*    
>P1;HLA:HLA01420
HLA:HLA01420 MICA*048 360 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAADGPEL VSLQVLDQHP VGTSDHRDAT QLGFQPLMSA LGSTGSTEGA
 *     
>P1;HLA:HLA01498
HLA:HLA01498 MICA*049 361 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVRCCK KKTSAAEGPE LVSLQVLDQH PVGMSDHRDA TQLGFQPLMS ALGSTGSTEG
 A*     
>P1;HLA:HLA01710
HLA:HLA01710 MICA*050 320 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSFQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAIF
 VIIIFYVCCC KKKTSAAEGP *   
>P1;HLA:HLA01761
HLA:HLA01761 MICA*051 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA02333
HLA:HLA02333 MICA*052 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYIC CCKKKTSAAE GP*   
>P1;HLA:HLA02334
HLA:HLA02334 MICA*053 310 bases
 EPHSLRYNLT VLSGDGSVQS GFLAEVHLDG QPFLRCDRQK CRAKPQGQWA EDVLGNKTWD
 RETRDLTGNG KDLRMTLAHI KDQKEGLHSL QEIRVCEIHE DNSTRSSQHF YYDGELFLSQ
 NLETEEWTVP QSSRAQTLAM NVRNFLKEDA MKTKTHYHAM HADCLQELRR YLESGVVLRR
 TVPPMVNVTR SEASEGNITV TCRASSFYPR NIILTWRQDG VSLSHDTQQW GDVLPDGNGT
 YQTWVATRIC RGEEQRFTCY MEHSGNHSTH PVPSGKVLVL QSHWQTFHVS AVAAGCCYFC
 YYYFLCPLLX *    
>P1;HLA:HLA03157
HLA:HLA03157 MICA*054 318 bases
 PHSLPYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHGTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA03189
HLA:HLA03189 MICA*055 318 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAI
 FVIIIFYVCC CKKKTSAA*    
>P1;HLA:HLA03255
HLA:HLA03255 MICA*056 318 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQSG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA03484
HLA:HLA03484 MICA*057 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA03751
HLA:HLA03751 MICA*058 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSRNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA04350
HLA:HLA04350 MICA*059 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEGHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICE GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA04853
HLA:HLA04853 MICA*060 273 bases
 PHSLRYNLTV LSWDGSVQSG FLTEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTLYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSRNHSTHP VPS*  
>P1;HLA:HLA05137
HLA:HLA05137 MICA*061 317 bases
 PHSLRYNLTV LSWDGSVQSG FLTEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTLYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GKEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA05377
HLA:HLA05377 MICA*062 273 bases
 PHSLPYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSRNHSTHP VPS*  
>P1;HLA:HLA05919
HLA:HLA05919 MICA*063N 38 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRX*  
>P1;HLA:HLA06453
HLA:HLA06453 MICA*064N 243 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTX*     
>P1;HLA:HLA07086
HLA:HLA07086 MICA*065 318 bases
 PHSLPYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTCS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA07107
HLA:HLA07107 MICA*066 318 bases
 PHSLPYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEAQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA07329
HLA:HLA07329 MICA*067 319 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED SSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRR
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVRCCK KKTSAAEGP*    
>P1;HLA:HLA07420
HLA:HLA07420 MICA*068 325 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKCWCFR VIGRHSMFLL LLLLLLLLLL
 FLLLLFSTSV VVRRKHQLQR VQSSX*   
>P1;HLA:HLA07546
HLA:HLA07546 MICA*069 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSDLGSTGS TEGA*   
>P1;HLA:HLA07761
HLA:HLA07761 MICA*070 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 SQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA08898
HLA:HLA08898 MICA*072 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA08956
HLA:HLA08956 MICA*073 309 bases
 PHSLRYNLTV LSRDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA08959
HLA:HLA08959 MICA*074 319 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EMRVCEIHED NSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVRCCK KKTSAAEGP*    
>P1;HLA:HLA09082
HLA:HLA09082 MICA*075 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQKFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA09117
HLA:HLA09117 MICA*076 318 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA10268
HLA:HLA10268 MICA*077 319 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRR
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHGTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVRCCK KKTSAAEGP*    
>P1;HLA:HLA10648
HLA:HLA10648 MICA*078 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN IRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA10934
HLA:HLA10934 MICA*079 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA11070
HLA:HLA11070 MICA*080 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSIHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA11072
HLA:HLA11072 MICA*081 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWAATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA11073
HLA:HLA11073 MICA*082 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELWRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA11472
HLA:HLA11472 MICA*083 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLR EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA11481
HLA:HLA11481 MICA*084 322 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLR EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA13078
HLA:HLA13078 MICA*085 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA13970
HLA:HLA13970 MICA*086 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMSQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA14463
HLA:HLA14463 MICA*087 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCLLLX*     
