>DL;HLA:HLA01013
HLA:HLA01013 MICA*001 1152 bases
 ATGGGGCTGG GCCCGGTCTT CCTGCTTCTG GCTGGCATCT TCCCTTTTGC ACCTCCGGGA
 GCTGCTGCTG AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT
 GTGCAGTCAG GGTTTCTCAC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC
 AGGCAGAAAT GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG
 ACATGGGACA GAGAGACCAG AGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG
 GCTCATATCA AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TAAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCCATGA ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CACGCTATGC ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC
 CTGAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC
 ATTACCGTGA CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG
 CTGGTGCTTC AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTATT
 TTTGTTATTA TTATTTTCTA TGTCCGTTGT TGTAAGAAGA AAACATCAGC TGCAGAGGGT
 CCAGAGCTCG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACGAG TGACCACAGG
 GATGCCACAC AGCTCGGATT TCAGCCTCTG ATGTCAGATC TTGGGTCCAC TGGCTCCACT
 GAGGGCGCCT AG*    
>DL;HLA:HLA01014
HLA:HLA01014 MICA*002:01 1097 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTGCTGCTG
 CTATTTTTGT TATTATTATT TTCTACGTCT GTTGTTGTAA GAAGAAAACA TCAGCTGCAG
 AGGGTCCAGA GCTCGTGAGC CTGCAGGTCC TGGATCAACA CCCAGTTGGG ACGAGTGACC
 ACAGGGATGC CACACAGCTC GGATTTCAGC CTCTGATGTC AGATCTTGGG TCCACTGGCT
 CCACTGAGGG CGCCTAG*    
>DL;HLA:HLA01381
HLA:HLA01381 MICA*002:02 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GTGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA03752
HLA:HLA03752 MICA*002:03 969 bases
 AGCCCCACAG TCTTCGCTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTGCTGCTG
 CTATTTTTGT TATTATTATT TTCTACGTCT GTTGTTGTAA GAAGAAAACA TCAGCTGCAG
 AGGGTCCAG*     
>DL;HLA:HLA01015
HLA:HLA01015 MICA*004 1158 bases
 ATGGGGCTGG GCCCGGTCTT CCTGCTTCTG GCTGGCATCT TCCCTTTTGC ACCTCCGGGA
 GCTGCTGCTG AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT
 GTGCAGTCAG GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAT GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG
 ACATGGGACA GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG
 GCTCATATCA AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACGTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCCATGA ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CACGCTATGC ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC
 CTGAGGAGAA GAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG
 CTGGTGCTTC AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT
 GCTATTTTTG TTATTATTAT TTTCTATGTC CGTTGTTGTA AGAAGAAAAC ATCAGCTGCA
 GAGGGTCCAG AGCTCGTGAG CCTGCAGGTC CTGGATCAAC ACCCAGTTGG GACGAGTGAC
 CACAGGGATG CCACACAGCT CGGATTTCAG CCTCTGATGT CAGCTCTTGG GTCCACTGGC
 TCCACTGAGG GCGCCTAG*    
>DL;HLA:HLA01016
HLA:HLA01016 MICA*005 821 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC T* 
>DL;HLA:HLA01017
HLA:HLA01017 MICA*006 1088 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACGTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCATAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTATTTTTG
 TTATTATTAT TTTCTATGTC CGTTGTTGTA AGAAGAAAAC ATCAGCTGCA GAGGGTCCAG
 AGCTCGTGAG CCTGCAGGTC CTGGATCAAC ACCCAGTTGG GACGAGTGAC CACAGGGATG
 CCACACAGCT CGGATTTCAG CCTCTGATGT CAGCTCTTGG GTCCACTGGC TCCACTGAGG
 GCGCCTAG*     
>DL;HLA:HLA01018
HLA:HLA01018 MICA*007:01 954 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GTGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTATT TTTGTTATTA
 TTATTTTCTA TGTCCGTTGT TGTAAGAAGA AAACATCAGC TGCAGAGGGT CCAG*
>DL;HLA:HLA01382
HLA:HLA01382 MICA*007:02 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA02147
HLA:HLA02147 MICA*007:03 954 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTATGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GTGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTATT TTTGTTATTA
 TTATTTTCTA TGTCCGTTGT TGTAAGAAGA AAACATCAGC TGCAGAGGGT CCAG*
>DL;HLA:HLA01019
HLA:HLA01019 MICA*008:01 1156 bases
 ATGGGGCTGG GCCCGGTCTT CCTGCTTCTG GCTGGCATCT TCCCTTTTGC ACCTCCGGGA
 GCTGCTGCTG AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT
 GTGCAGTCAG GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAT GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG
 ACATGGGACA GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG
 GCTCATATCA AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCCATGA ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CACGCTATGC ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CGGCGTAGTC
 CTGAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG
 CTGGTGCTTC AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGGCTGCTGC
 TATTTTTGTT ATTATTATTT TCTATGTCCG TTGTTGTAAG AAGAAAACAT CAGCTGCAGA
 GGGTCCAGAG CTCGTGAGCC TGCAGGTCCT GGATCAACAC CCAGTTGGGA CGAGTGACCA
 CAGGGATGCC ACACAGCTCG GATTTCAGCC TCTGATGTCA GCTCTTGGGT CCACTGGCTC
 CACTGAGGGC ACCTAG*    
>DL;HLA:HLA01363
HLA:HLA01363 MICA*008:02 958 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACT AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGGCTGCTGC TATTTTTGTT
 ATTATTATTT TCTATGTCCG TTGTTGTAAG AAGAAAACAT CAGCTGCAGA GGGTCCAG*
>DL;HLA:HLA01402
HLA:HLA01402 MICA*008:03 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCATC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA02488
HLA:HLA02488 MICA*008:04 1156 bases
 ATGGGGCTGG GCCCGGTCTT TCTGCTTCTG GCTGGCATCT TCCCTTTTGC ACCTCCGGGA
 GCTGCTGCTG AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT
 GTGCAGTCAG GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAT GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG
 ACATGGGACA GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG
 GCTCATATCA AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCCATGA ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CACGCTATGC ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CGGCGTAGTC
 CTGAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG
 CTGGTGCTTC AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGGCTGCTGC
 TATTTTTGTT ATTATTATTT TCTATGTCCG TTGTTGTAAG AAGAAAACAT CAGCTGCAGA
 GGGTCCAGAG CTCGTGAGCC TGCAGGTCCT GGATCAACAC CCAGTTGGGA CGAGTGACCA
 CAGGGATGCC ACACAGCTCG GATTTCAGCC TCTGATGTCA GCTCTTGGGT CCACTGGCTC
 CACTGAGGGC ACCTAG*    
>DL;HLA:HLA01020
HLA:HLA01020 MICA*009:01 1088 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACGTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTATTTTTG
 TTATTATTAT TTTCTATGTC CGTTGTTGTA AGAAGAAAAC ATCAGCTGCA GAGGGTCCAG
 AGCTCGTGAG CCTGCAGGTC CTGGATCAAC ACCCAGTTGG GACGAGTGAC CACAGGGATG
 CCACACAGCT CGGATTTCAG CCTCTGATGT CAGCTCTTGG GTCCACTGGC TCCACTGAGG
 GCGCCTAG*     
>DL;HLA:HLA01397
HLA:HLA01397 MICA*009:02 1088 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTATGATGG GGAGCTCTTC CTCTCCCAAA
 ACGTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTATTTTTG
 TTATTATTAT TTTCTATGTC CGTTGTTGTA AGAAGAAAAC ATCAGCTGCA GAGGGTCCAG
 AGCTCGTGAG CCTGCAGGTC CTGGATCAAC ACCCAGTTGG GACGAGTGAC CACAGGGATG
 CCACACAGCT CGGATTTCAG CCTCTGATGT CAGCTCTTGG GTCCACTGGC TCCACTGAGG
 GCGCCTAG*     
>DL;HLA:HLA01021
HLA:HLA01021 MICA*010 1084 bases
 AGCCCCACAG TCTTCCTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT ATTTTTGTTA
 TTATTATTTT CTATGTCCGT TGTTGTAAGA AGAAAACATC AGCTGCAGAG GGTCCAGAGC
 TCGTGAGCCT GCAGGTCCTG GATCAACACC CAGTTGGGAC GAGTGACCAC AGGGATGCCA
 CACAGCTCGG ATTTCAGCCT CTGATGTCAG CTCTTGGGTC CACTGGCTCC ACTGAGGGCG
 CCTA*     
>DL;HLA:HLA01022
HLA:HLA01022 MICA*011 1088 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCG TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACG CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTATTTTTG
 TTATTATTAT TTTCTATGTC TGTTGTTGTA AGAAGAAAAC ATCAGCTGCA GAGGGTCCAG
 AGCTCGTGAG CCTGCAGGTC CTGGATCAAC ACCCAGTTGG GACGAGTGAC CACAGGGATG
 CCACACAGCT CGGATTTCAG CCTCTGATGT CAGCTCTTGG GTCCGCTGGC TCCACTGAGG
 GTGCCTAG*     
>DL;HLA:HLA01023
HLA:HLA01023 MICA*012:01 1082 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCAC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG AGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACTCTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTATT TTTGTTATTA
 TTATTTTCTA TGTCCGTTGT TGTAAGAAGA AAACATCAGC TGCAGAGGGT CCAGAGCTCG
 TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACGAG TGACCACAGG GATGCCACAC
 AGCTCGGATT TCAGCCTCTG ATGTCAGATC TTGGGTCCAC TGGCTCCACT GAGGGCGCCT
 AG*     
>DL;HLA:HLA01401
HLA:HLA01401 MICA*012:02 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCAC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG AGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACTCTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAAAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA03110
HLA:HLA03110 MICA*012:03 823 bases
 GAGCCCCACA GTCTTCGTTA TAACCTCACG GTGCTGTCCT GGGATGGATC TGTGCAGTCA
 GGGTTTCTCA CTGAGGTACA TCTGGATGGT CAGCCCTTCC TGCGCTGTGA CAGGCAGAAA
 TGCAGGGCAA AGCCCCAGGG ACAGTGGGCA GAAGATGTCC TGGGAAACAA GACATGGGAC
 AGAGAGACCA GAGACTTGAC AGGGAACGGA AAGGACCTCA GGATGACCCT GGCTCATATC
 AAGGACCAGA AAGAAGGCTT GCATTCCCTC CAGGAGATTA GGGTCTGTGA GATCCATGAA
 GACAACAGCA CCAGGAGCTC CCAGCATTTC TACTACGATG GGGAGCTCTT CCTCTCCCAA
 AACCTGGAGA CTGAGGAATG GACAATGCCC CAGTCCTCCA GAGCTCAGAC CTTGGCCATG
 AACGTCAGGA ATTTCTTGAA GGAAGATGCC ATGAAGACCA AGACACTCTA TCACGCTATG
 CATGCAGACT GCCTGCAGGA ACTACGGCGA TATCTAAAAT CCGGCGTAGT CCTGAGGAGA
 ACAGTGCCCC CCATGGTGAA TGTCACCCGC AGCGAGGCCT CAGAGGGCAA CATTACCGTG
 ACATGCAGGG CTTCTGGCTT CTATCCCTGG AATATCACAC TGAGCTGGCG TCAGGATGGG
 GTATCTTTGA GCCACGACAC CCAGCAGTGG GGGGATGTCC TGCCTGATGG GAATGGAACC
 TACCAGACCT GGGTGGCCAC CAGGATTTGC CAAGGAGAGG AGCAGAGGTT CACCTGCTAC
 ATGGAACACA GCGGGAATCA CAGCACTCAC CCTGTGCCCT CTG* 
>DL;HLA:HLA01024
HLA:HLA01024 MICA*013 821 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC T* 
>DL;HLA:HLA01025
HLA:HLA01025 MICA*014 821 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATAG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CGGCGTAGTC CTGAGGAGAA
 GAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC T* 
>DL;HLA:HLA01026
HLA:HLA01026 MICA*015 978 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATAG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGAAAGTGC TGGTGCTTCA
 GAGTCATTGG CAGACATTCC ATGTTTCTGC TGTTGCTGCT GCTGCTGCTG CTGCTGCTGC
 TATTTTTGTT ATTATTATTT TCTACGTCTG TTGTTGTAAG AAGAAAACAT CAGCTGCAGA
 GGGTCCAGGG CTCGTGAG*    
>DL;HLA:HLA01027
HLA:HLA01027 MICA*016 1085 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGC
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT ATTTTTGTTA
 TTATTATTTT CTATGTCCGT TGTTGTAAGA AGAAAACATC AGCTGCAGAG GGTCCAGAGC
 TCGTGAGCCT GCAGGTCCTG GATCAACACC CAGTTGGGAC GAGTGACCAC AGGGATGCCA
 CACAGCTCGG ATTTCAGCCT CTGATGTCAG CTCTTGGGTC CACTGGCTCC ACTGAGGGCG
 CCTAG*     
>DL;HLA:HLA01335
HLA:HLA01335 MICA*017 978 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC GGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGAAAGTGC TGGTGCTTCA
 GAGTCATTGG CAGACATTCC ATGTTTCTGC TGTTGCTGCT GCTGCTGCTG CTGCTGCTGC
 TATTTTTGTT ATTATTATTT TCTACGTCTG TTGTTGTAAG AAGAAAACAT CAGCTGCAGA
 GGGTCCAGGG CTCGTGAG*    
>DL;HLA:HLA01336
HLA:HLA01336 MICA*018:01 1152 bases
 ATGGGGCTGG GCCCGGTCTT CCTGCTTCTG GCTGGCATCT TCCCTTTTGC ACCTCCGGGA
 GCTGCTGCTG AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT
 GTGCAGTCAG GGTTTCTCAC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC
 AGGCAGAAAT GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG
 ACATGGGACA GAGAGACCAG AGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG
 GCTCATATCA AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCCATGA ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CACGCTATGC ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC
 CTGAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC
 ATTACCGTGA CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG
 CTGGTGCTTC AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTATT
 TTTGTTATTA TTATTTTCTA TGTCCGTTGT TGTAAGAAGA AAACATCAGC TGCAGAGGGT
 CCAGAGCTCG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACGAG TGACCACAGG
 GATGCCACAC AGCTCGGATT TCAGCCTCTG ATGTCAGATC TTGGGTCCAC TGGCTCCACT
 GAGGGCACCT AG*    
>DL;HLA:HLA02034
HLA:HLA02034 MICA*018:02 954 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCAC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG AGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GTGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTATT TTTGTTATTA
 TTATTTTCTA TGTCCGTTGT TGTAAGAAGA AAACATCAGC TGCAGAGGGT CCAG*
>DL;HLA:HLA01334
HLA:HLA01334 MICA*019 1085 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT ATTTTTGTTA
 TTATTATTTT CTATGTCCGT TGTTGTAAGA AGAAAACATC AGCTGCAGAG GGTCCAGAGC
 TCGTGAGCCT GCAGGTCCTG GATCAACACC CAGTTGGGAC GAGTGACCAC AGGGATGCCA
 CACAGCTCGG ATTTCAGCCT CTGATGTCAG CTCTTGGGTC CACTGGCTCC ACTGAGGGCG
 CCTAG*     
>DL;HLA:HLA01370
HLA:HLA01370 MICA*020 972 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTGCTGCTG
 CTGCTATTTT TGTTATTATT ATTTTCTACG TCTGTTGTTG TAAGAAGAAA ACATCAGCTG
 CAGAGGGTCC AG*    
>DL;HLA:HLA01394
HLA:HLA01394 MICA*022 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01396
HLA:HLA01396 MICA*023 929 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGGCTGCTGC TATTTTTGTT
 ATTATTATTT TCTATGTCCG TTGTTGTAA*   
>DL;HLA:HLA01391
HLA:HLA01391 MICA*024 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01392
HLA:HLA01392 MICA*025 822 bases
 AGCCCCACAG TCTTCCTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01393
HLA:HLA01393 MICA*026 960 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GTGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTATTTTTG
 TTATTATTAT TTTCTATGTC CGTTGTTGTA AGAAGAAAAC ATCAGCTGCA GAGGGTCCAG
 *     
>DL;HLA:HLA01371
HLA:HLA01371 MICA*027 957 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT ATTTTTGTTA
 TTATTATTTT CTATGTCCGT TGTTGTAAGA AGAAAACATC AGCTGCAGAG GGTCCAG*
>DL;HLA:HLA01398
HLA:HLA01398 MICA*028 929 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGGCTGCTGC TATTTTTGTT
 ATTATTATTT TCTATGTCCG TTGTTGTAA*   
>DL;HLA:HLA01365
HLA:HLA01365 MICA*029 954 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACATCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTATT TTTGTTATTA
 TTATTTTCTA TGTCCGTTGT TGTAAGAAGA AAACATCAGC TGCAGAGGGT CCAG*
>DL;HLA:HLA01333
HLA:HLA01333 MICA*030 960 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACG CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTATTTTTG
 TTATTATTAT TTTCTATGTC TGTTGTTGTA AGAAGAAAAC ATCAGCTGCA GAGGGTCCAG
 *     
>DL;HLA:HLA01383
HLA:HLA01383 MICA*031 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TAAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01386
HLA:HLA01386 MICA*032 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACTCTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CAGCGTAGTC CTGAGGAGAA
 GAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01366
HLA:HLA01366 MICA*033 957 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGTC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT ATTTTTGTTA
 TTATTATTTT CTATGTCCGT TGTTGTAAGA AGAAAACATC AGCTGCAGAG GGTCCAG*
>DL;HLA:HLA01395
HLA:HLA01395 MICA*034 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCG TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01384
HLA:HLA01384 MICA*035 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01387
HLA:HLA01387 MICA*036 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAAGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01388
HLA:HLA01388 MICA*037 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01389
HLA:HLA01389 MICA*038 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01390
HLA:HLA01390 MICA*039 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGC
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01385
HLA:HLA01385 MICA*040 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TAAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01367
HLA:HLA01367 MICA*041 969 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTGCTGCTG
 CTATTTTTGT TATTATTATT TTCTACGTCT GTTGTTGTAA GAAGAAAACA TCAGCTGCAG
 AGGGTCCAG*     
>DL;HLA:HLA01399
HLA:HLA01399 MICA*042 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACT AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01368
HLA:HLA01368 MICA*043 954 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACGCTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGTTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTATT TTTGTTATTA
 TTATTTTCTA TGTCTGTTGT TGTAAGAAGA AAACATCAGC TGCAGAGGGT CCAG*
>DL;HLA:HLA01400
HLA:HLA01400 MICA*044 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACGTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 GAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA01369
HLA:HLA01369 MICA*045 954 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GTGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCG AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTATT TTTGTTATTA
 TTATTTTCTA TGTCCGTTGT TGTAAGAAGA AAACATCAGC TGCAGAGGGT CCAG*
>DL;HLA:HLA01372
HLA:HLA01372 MICA*046 969 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TGTCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTGCTGCTG
 CTATTTTTGT TATTATTATT TTCTACGTCT GTTGTTGTAA GAAGAAAACA TCAGCTGCAG
 AGGGTCCAG*     
>DL;HLA:HLA01410
HLA:HLA01410 MICA*047 960 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACG CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTATTTTTG
 TTATTATTAT TTTCTATGTC TGTTGTTGTA AGAAGAAAAC ATCAGCTGCA GAGGGTCCAG
 *     
>DL;HLA:HLA01420
HLA:HLA01420 MICA*048 1085 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT ATTTTTGTTA
 TTATTATTTT CTATGTCCGT TGTTGTAAGA AGAAAACATC AGCTGCAGAT GGTCCAGAGC
 TCGTGAGCCT GCAGGTCCTG GATCAACACC CAGTTGGGAC GAGTGACCAC AGGGATGCCA
 CACAGCTCGG ATTTCAGCCT CTGATGTCAG CTCTTGGGTC CACTGGCTCC ACTGAGGGCG
 CCTAG*     
>DL;HLA:HLA01498
HLA:HLA01498 MICA*049 1088 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACGTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTATTTTTG
 TTATTATTAT TTTCTATGTC CGTTGTTGTA AGAAGAAAAC ATCAGCTGCA GAGGGTCCAG
 AGCTCGTGAG CCTGCAGGTC CTGGATCAAC ACCCAGTTGG GATGAGTGAC CACAGGGATG
 CCACACAGCT CGGATTTCAG CCTCTGATGT CAGCTCTTGG GTCCACTGGC TCCACTGAGG
 GCGCCTAG*     
>DL;HLA:HLA01710
HLA:HLA01710 MICA*050 963 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCTTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTGCTATTT
 TTGTTATTAT TATTTTCTAC GTCTGTTGTT GTAAGAAGAA AACATCAGCT GCAGAGGGTC
 CAG*     
>DL;HLA:HLA01761
HLA:HLA01761 MICA*051 954 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GTGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTATT TTTGTTATTA
 TTATTTTCTA TGTCCGTTGT TGTAAGAAGA AAACATCAGC TGCAGAGGGT CCAG*
>DL;HLA:HLA02333
HLA:HLA02333 MICA*052 969 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTGCTGCTG
 CTATTTTTGT TATTATTATT TTCTACATCT GTTGTTGTAA GAAGAAAACA TCAGCTGCAG
 AGGGTCCAG*     
>DL;HLA:HLA02334
HLA:HLA02334 MICA*053 958 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGGCTGCTGC TATTTTTGTT
 ATTATTATTT TCTATGTCCG TTGTTGTAAG AAGAAAACAT CAGCTGCAGA GGGTCCAG*
>DL;HLA:HLA03157
HLA:HLA03157 MICA*054 957 bases
 AGCCCCACAG TCTTCCTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT ATTTTTGTTA
 TTATTATTTT CTATGTCCGT TGTTGTAAGA AGAAAACATC AGCTGCAGAG GGTCCAG*
>DL;HLA:HLA03189
HLA:HLA03189 MICA*055 956 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCGG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT GCTGCTGCTA
 TTTTTGTTAT TATTATTTTC TACGTCTGTT GTTGTAAGAA GAAAACATCA GCTGCA*
>DL;HLA:HLA03255
HLA:HLA03255 MICA*056 957 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTCGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTGCT ATTTTTGTTA
 TTATTATTTT CTATGTCCGT TGTTGTAAGA AGAAAACATC AGCTGCAGAG GGTCCAG*
>DL;HLA:HLA03484
HLA:HLA03484 MICA*057 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA03751
HLA:HLA03751 MICA*058 958 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CAGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGGCTGCTGC TATTTTTGTT
 ATTATTATTT TCTATGTCCG TTGTTGTAAG AAGAAAACAT CAGCTGCAGA GGGTCCAG*
>DL;HLA:HLA04350
HLA:HLA04350 MICA*059 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GTGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCG AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA04853
HLA:HLA04853 MICA*060 822 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCAC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG AGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACTCTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CAGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA05137
HLA:HLA05137 MICA*061 954 bases
 AGCCCCACAG TCTTCGTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTCAC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTGTGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG AGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAATGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACTCTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAAAATC CGGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATTACCGTGA
 CATGCAGGGC TTCTGGCTTC TATCCCTGGA ATATCACACT GAGCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC AAGGAAAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAAGTG CTGGTGCTTC
 AGAGTCATTG GCAGACATTC CATGTTTCTG CTGTTGCTGC TGCTGCTATT TTTGTTATTA
 TTATTTTCTA TGTCCGTTGT TGTAAGAAGA AAACATCAGC TGCAGAGGGT CCAG*
>DL;HLA:HLA05377
HLA:HLA05377 MICA*062 822 bases
 AGCCCCACAG TCTTCCTTAT AACCTCACGG TGCTGTCCTG GGATGGATCT GTGCAGTCAG
 GGTTTCTTGC TGAGGTACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAT
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAAATAAG ACATGGGACA
 GAGAGACCAG GGACTTGACA GGGAACGGAA AGGACCTCAG GATGACCCTG GCTCATATCA
 AGGACCAGAA AGAAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAACAGCAC CAGGAGCTCC CAGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TGAGGAATGG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCCATGA
 ACGTCAGGAA TTTCTTGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CACGCTATGC
 ATGCAGACTG CCTGCAGGAA CTACGGCGAT ATCTAGAATC CAGCGTAGTC CTGAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCCGCA GCGAGGCCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCATACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACGACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTTGCC GAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CAGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
