>P1;HLA:HLA01013
HLA:HLA01013 MICA*001 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETKEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA01014
HLA:HLA01014 MICA*002:01:01 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26233
HLA:HLA26233 MICA*002:01:02 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26254
HLA:HLA26254 MICA*002:01:03 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26318
HLA:HLA26318 MICA*002:01:04 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26333
HLA:HLA26333 MICA*002:01:05 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26266
HLA:HLA26266 MICA*002:01:06 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26215
HLA:HLA26215 MICA*002:01:07 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26896
HLA:HLA26896 MICA*002:01:08 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26937
HLA:HLA26937 MICA*002:01:09 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA27206
HLA:HLA27206 MICA*002:01:10 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA01381
HLA:HLA01381 MICA*002:02 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA03752
HLA:HLA03752 MICA*002:03 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA05867
HLA:HLA05867 MICA*002:04 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA01015
HLA:HLA01015 MICA*004:01:01 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRRVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26574
HLA:HLA26574 MICA*004:01:02 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRRVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26521
HLA:HLA26521 MICA*004:01:03 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRRVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26914
HLA:HLA26914 MICA*004:01:04 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRRVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26928
HLA:HLA26928 MICA*004:01:05 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRRVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26939
HLA:HLA26939 MICA*004:01:06 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRRVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA27243
HLA:HLA27243 MICA*004:01:07 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRRVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA27233
HLA:HLA27233 MICA*004:01:08 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRRVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA01016
HLA:HLA01016 MICA*005 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01017
HLA:HLA01017 MICA*006 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSIV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA01018
HLA:HLA01018 MICA*007:01:01 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA26294
HLA:HLA26294 MICA*007:01:02 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA26904
HLA:HLA26904 MICA*007:01:03 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA26936
HLA:HLA26936 MICA*007:01:04 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA27204
HLA:HLA27204 MICA*007:01:05 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA27205
HLA:HLA27205 MICA*007:01:06 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA02147
HLA:HLA02147 MICA*007:03 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA08958
HLA:HLA08958 MICA*007:05 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA08961
HLA:HLA08961 MICA*007:06:01 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA26927
HLA:HLA26927 MICA*007:06:02 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA15415
HLA:HLA15415 MICA*007:07 341 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG P* 
>P1;HLA:HLA01019
HLA:HLA01019 MICA*008:01:01 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA06643
HLA:HLA06643 MICA*008:01:02 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26248
HLA:HLA26248 MICA*008:01:03 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26219
HLA:HLA26219 MICA*008:01:04 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26382
HLA:HLA26382 MICA*008:01:05 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26232
HLA:HLA26232 MICA*008:01:06 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26265
HLA:HLA26265 MICA*008:01:07 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA27245
HLA:HLA27245 MICA*008:01:08 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA27265
HLA:HLA27265 MICA*008:01:09 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA01363
HLA:HLA01363 MICA*008:02 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA01402
HLA:HLA01402 MICA*008:03 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA02488
HLA:HLA02488 MICA*008:04:01 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26436
HLA:HLA26436 MICA*008:04:02 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26443
HLA:HLA26443 MICA*008:04:03 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26940
HLA:HLA26940 MICA*008:04:04 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA27228
HLA:HLA27228 MICA*008:04:05 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA08919
HLA:HLA08919 MICA*008:05 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26330
HLA:HLA26330 MICA*008:06 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26364
HLA:HLA26364 MICA*008:07 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26290
HLA:HLA26290 MICA*008:08 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26245
HLA:HLA26245 MICA*008:09 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26250
HLA:HLA26250 MICA*008:10 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26572
HLA:HLA26572 MICA*008:11 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26812
HLA:HLA26812 MICA*008:12 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA27319
HLA:HLA27319 MICA*008:13 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA01020
HLA:HLA01020 MICA*009:01:01 361 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVRCCK KKTSAAEGPE LVSLQVLDQH PVGTSDHRDA TQLGFQPLMS ALGSTGSTEG
 A*     
>P1;HLA:HLA26898
HLA:HLA26898 MICA*009:01:02 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26900
HLA:HLA26900 MICA*009:01:03 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26901
HLA:HLA26901 MICA*009:01:04 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26902
HLA:HLA26902 MICA*009:01:05 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26972
HLA:HLA26972 MICA*009:01:06 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA01397
HLA:HLA01397 MICA*009:02:01 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA17992
HLA:HLA17992 MICA*009:02:02 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26385
HLA:HLA26385 MICA*009:02:03 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26938
HLA:HLA26938 MICA*009:03 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA01021
HLA:HLA01021 MICA*010:01:01 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26544
HLA:HLA26544 MICA*010:01:02 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26424
HLA:HLA26424 MICA*010:01:03 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26517
HLA:HLA26517 MICA*010:01:04 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26405
HLA:HLA26405 MICA*010:01:05 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26929
HLA:HLA26929 MICA*010:01:06 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA06451
HLA:HLA06451 MICA*010:02:01 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26934
HLA:HLA26934 MICA*010:02:02 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26304
HLA:HLA26304 MICA*010:03 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA01022
HLA:HLA01022 MICA*011:01:01 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAVKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHAVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV CCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSAG STEGA*   
>P1;HLA:HLA26918
HLA:HLA26918 MICA*011:01:02 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAVKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHAVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV CCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSAG STEGA*   
>P1;HLA:HLA26919
HLA:HLA26919 MICA*011:01:03 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAVKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHAVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV CCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSAG STEGA*   
>P1;HLA:HLA26921
HLA:HLA26921 MICA*011:01:04 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAVKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHAVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV CCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSAG STEGA*   
>P1;HLA:HLA26933
HLA:HLA26933 MICA*011:01:05 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAVKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHAVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV CCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSAG STEGA*   
>P1;HLA:HLA26920
HLA:HLA26920 MICA*011:01:06 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAVKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHAVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV CCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSAG STEGA*   
>P1;HLA:HLA01023
HLA:HLA01023 MICA*012:01:01 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTLY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA26297
HLA:HLA26297 MICA*012:01:02 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTLY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA26973
HLA:HLA26973 MICA*012:01:03 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTLY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA01401
HLA:HLA01401 MICA*012:02 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTLY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA03110
HLA:HLA03110 MICA*012:03 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTLY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA10241
HLA:HLA10241 MICA*012:04 317 bases
 PHSLRYNLTV LSWDGSVQSG FLTEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTLYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA14483
HLA:HLA14483 MICA*012:05 273 bases
 PHSLRYNLTV LSWDGSVQSG FLTEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTLYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01024
HLA:HLA01024 MICA*013 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01025
HLA:HLA01025 MICA*014 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDRELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRR
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01026
HLA:HLA01026 MICA*015 349 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDRELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKC
 WCFRVIGRHS MFLLLLLLLL LLLLFLLLLF STSVVVRRKH QLQRVQSSX* 
>P1;HLA:HLA01027
HLA:HLA01027 MICA*016 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGLSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA01335
HLA:HLA01335 MICA*017 349 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLREIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKC
 WCFRVIGRHS MFLLLLLLLL LLLLFLLLLF STSVVVRRKH QLQRVQSSX* 
>P1;HLA:HLA01336
HLA:HLA01336 MICA*018:01:01 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
>P1;HLA:HLA26895
HLA:HLA26895 MICA*018:01:02 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
>P1;HLA:HLA26905
HLA:HLA26905 MICA*018:01:03 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
>P1;HLA:HLA26906
HLA:HLA26906 MICA*018:01:04 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
>P1;HLA:HLA26907
HLA:HLA26907 MICA*018:01:05 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
>P1;HLA:HLA26909
HLA:HLA26909 MICA*018:01:06 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
>P1;HLA:HLA26930
HLA:HLA26930 MICA*018:01:07 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
>P1;HLA:HLA02034
HLA:HLA02034 MICA*018:02 317 bases
 PHSLRYNLTV LSWDGSVQSG FLTEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA01334
HLA:HLA01334 MICA*019:01:01 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26435
HLA:HLA26435 MICA*019:01:02 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA13376
HLA:HLA13376 MICA*019:02 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA01370
HLA:HLA01370 MICA*020 323 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 AIFVIIIFYV CCCKKKTSAA EGP*   
>P1;HLA:HLA01394
HLA:HLA01394 MICA*022:01:01 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26894
HLA:HLA26894 MICA*022:01:02 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA01396
HLA:HLA01396 MICA*023 309 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA01391
HLA:HLA01391 MICA*024 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA01392
HLA:HLA01392 MICA*025 273 bases
 PHSLPYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01393
HLA:HLA01393 MICA*026 319 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVRCCK KKTSAAEGP*    
>P1;HLA:HLA01371
HLA:HLA01371 MICA*027:01:01 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26892
HLA:HLA26892 MICA*027:01:02 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA01398
HLA:HLA01398 MICA*028 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA01365
HLA:HLA01365 MICA*029:01:01 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNIRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA26910
HLA:HLA26910 MICA*029:01:02 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNIRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA22462
HLA:HLA22462 MICA*029:02 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN IRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA01333
HLA:HLA01333 MICA*030 319 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHA VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVCCCK KKTSAAEGP*    
>P1;HLA:HLA01383
HLA:HLA01383 MICA*031 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETKEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01386
HLA:HLA01386 MICA*032 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTLYHAMH ADCLQELRRY LKSSVVLRRR
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01366
HLA:HLA01366 MICA*033 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLESEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA01395
HLA:HLA01395 MICA*034 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAV KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01384
HLA:HLA01384 MICA*035 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01387
HLA:HLA01387 MICA*036 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTKSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01388
HLA:HLA01388 MICA*037 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01389
HLA:HLA01389 MICA*038 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01390
HLA:HLA01390 MICA*039 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGL SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01385
HLA:HLA01385 MICA*040 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETKEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01367
HLA:HLA01367 MICA*041 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEGHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA01399
HLA:HLA01399 MICA*042 273 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01368
HLA:HLA01368 MICA*043 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTRY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQSF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVCC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA01400
HLA:HLA01400 MICA*044 273 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRR
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA01369
HLA:HLA01369 MICA*045:01:01 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICEGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA26931
HLA:HLA26931 MICA*045:01:02 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICEGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA01372
HLA:HLA01372 MICA*046 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFCPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA01410
HLA:HLA01410 MICA*047 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEGH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHAVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV CCCKKKTSAA EGPELLSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSAG STEGA*   
>P1;HLA:HLA01420
HLA:HLA01420 MICA*048 360 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAADGPEL VSLQVLDQHP VGTSDHRDAT QLGFQPLMSA LGSTGSTEGA
 *     
>P1;HLA:HLA01498
HLA:HLA01498 MICA*049:01:01 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGMSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26903
HLA:HLA26903 MICA*049:01:02 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGMSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA01710
HLA:HLA01710 MICA*050 320 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSFQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAIF
 VIIIFYVCCC KKKTSAAEGP *   
>P1;HLA:HLA01761
HLA:HLA01761 MICA*051 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA02333
HLA:HLA02333 MICA*052 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYIC CCKKKTSAAE GP*   
>P1;HLA:HLA02334
HLA:HLA02334 MICA*053:01:01 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26519
HLA:HLA26519 MICA*053:01:02 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26529
HLA:HLA26529 MICA*053:01:03 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26570
HLA:HLA26570 MICA*053:01:04 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26512
HLA:HLA26512 MICA*053:01:05 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA03157
HLA:HLA03157 MICA*054 318 bases
 PHSLPYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHGTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA03189
HLA:HLA03189 MICA*055 318 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAI
 FVIIIFYVCC CKKKTSAA*    
>P1;HLA:HLA03255
HLA:HLA03255 MICA*056 318 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQSG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA03484
HLA:HLA03484 MICA*057:01:01 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26583
HLA:HLA26583 MICA*057:01:02 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26439
HLA:HLA26439 MICA*057:01:03 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26578
HLA:HLA26578 MICA*057:01:04 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA03751
HLA:HLA03751 MICA*058 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSRNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA04350
HLA:HLA04350 MICA*059 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEGH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICEGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA04853
HLA:HLA04853 MICA*060 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLTEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTLY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSRNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA05137
HLA:HLA05137 MICA*061 317 bases
 PHSLRYNLTV LSWDGSVQSG FLTEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTLYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GKEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA05377
HLA:HLA05377 MICA*062:01:01 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSRNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26941
HLA:HLA26941 MICA*062:01:02 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSRNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA05919
HLA:HLA05919 MICA*063N 38 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRX*  
>P1;HLA:HLA06453
HLA:HLA06453 MICA*064N 243 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTX*     
>P1;HLA:HLA07086
HLA:HLA07086 MICA*065 318 bases
 PHSLPYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTCS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA07107
HLA:HLA07107 MICA*066 318 bases
 PHSLPYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEAQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA07329
HLA:HLA07329 MICA*067 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDSSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRRVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA07420
HLA:HLA07420 MICA*068:01:01 349 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKC
 WCFRVIGRHS MFLLLLLLLL LLLLFLLLLF STSVVVRRKH QLQRVQSSX* 
>P1;HLA:HLA26911
HLA:HLA26911 MICA*068:01:02 349 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKC
 WCFRVIGRHS MFLLLLLLLL LLLLFLLLLF STSVVVRRKH QLQRVQSSX* 
>P1;HLA:HLA07546
HLA:HLA07546 MICA*069 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSDLGSTGS TEGA*   
>P1;HLA:HLA07761
HLA:HLA07761 MICA*070 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 SQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA08898
HLA:HLA08898 MICA*072:01:01 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSSVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26912
HLA:HLA26912 MICA*072:01:02 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSSVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26913
HLA:HLA26913 MICA*072:01:03 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSSVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA08956
HLA:HLA08956 MICA*073 309 bases
 PHSLRYNLTV LSRDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA08959
HLA:HLA08959 MICA*074 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEMRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA09082
HLA:HLA09082 MICA*075 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQKFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA09117
HLA:HLA09117 MICA*076 318 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAIFVI
 IIFYVRCCKK KTSAAEGP*    
>P1;HLA:HLA10268
HLA:HLA10268 MICA*077 319 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 VETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESSVVLRRR
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHGTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAIFV
 IIIFYVRCCK KKTSAAEGP*    
>P1;HLA:HLA10648
HLA:HLA10648 MICA*078 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN IRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA10934
HLA:HLA10934 MICA*079 317 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAIFVII
 IFYVRCCKKK TSAAEGP*    
>P1;HLA:HLA11070
HLA:HLA11070 MICA*080 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSIHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA11072
HLA:HLA11072 MICA*081 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWAATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA11073
HLA:HLA11073 MICA*082 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELWRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA11472
HLA:HLA11472 MICA*083 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLR EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKCWCFR VIGRHSMFLL LLLLLLLLLL
 FLLLLFSTSV VVRRKHQLQR VQ*   
>P1;HLA:HLA11481
HLA:HLA11481 MICA*084 322 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLR EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKCWCFR VIGRHSMFLL LLLLLLLLLL
 FLLLLFSTSV VVRRKHQLQR VQ*   
>P1;HLA:HLA13078
HLA:HLA13078 MICA*085 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN ITLTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCPLLX*     
>P1;HLA:HLA13970
HLA:HLA13970 MICA*086 322 bases
 PHSLRYNLTV LSGDGSVQSG FLAEVHLDGQ PFLRCDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTMSQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LKSGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASGFYPWN ITLSWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAAAAAAAA
 IFVIIIFYVC CCKKKTSAAE GP*   
>P1;HLA:HLA14463
HLA:HLA14463 MICA*087 309 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQQWG DVLPDGNGTY
 QTWVATRICR GEEQRFTCYM EHSGNHSTHP VPSGKVLVLQ SHWQTFHVSA VAAGCCYFCY
 YYFLCLLLX*     
>P1;HLA:HLA22544
HLA:HLA22544 MICA*088N 228 bases
 PHSLRYNLTV LSWDGSVQSG FLAEVHLDGQ PFLRYDRQKC RAKPQGQWAE DVLGNKTWDR
 ETRDLTGNGK DLRMTLAHIK DQKEGLHSLQ EIRVCEIHED NSTRSSQHFY YDGELFLSQN
 LETEEWTVPQ SSRAQTLAMN VRNFLKEDAM KTKTHYHAMH ADCLQELRRY LESGVVLRRT
 VPPMVNVTRS EASEGNITVT CRASSFYPRN IILTWRQDGV SLSHDTQX* 
>P1;HLA:HLA26343
HLA:HLA26343 MICA*089 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV CCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSDLGSTG STEGA*   
>P1;HLA:HLA26351
HLA:HLA26351 MICA*090 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAAAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26237
HLA:HLA26237 MICA*091 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAVAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26530
HLA:HLA26530 MICA*092 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVVAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26514
HLA:HLA26514 MICA*093 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF LVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26447
HLA:HLA26447 MICA*094 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26431
HLA:HLA26431 MICA*095 346 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLREIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKC
 WCFRVIGRHS MFLLLLLLLL LFLLLLFSTS VVVRRKHQLQ RVQSSX* 
>P1;HLA:HLA26582
HLA:HLA26582 MICA*096N 30 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPQSSLX *  
>P1;HLA:HLA26459
HLA:HLA26459 MICA*097 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26565
HLA:HLA26565 MICA*098:01 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26449
HLA:HLA26449 MICA*098:02 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26508
HLA:HLA26508 MICA*099:01:01 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26438
HLA:HLA26438 MICA*099:01:02 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLPY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26871
HLA:HLA26871 MICA*100 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHGQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGA*   
>P1;HLA:HLA26922
HLA:HLA26922 MICA*101 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEGH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHAVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV CCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSAG STEGA*   
>P1;HLA:HLA26890
HLA:HLA26890 MICA*102 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26891
HLA:HLA26891 MICA*103 333 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HASAVAAGCC YFCYYYFLCP LLX*  
>P1;HLA:HLA26893
HLA:HLA26893 MICA*104 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNIILTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICRGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA IFVIIIFYVG CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26899
HLA:HLA26899 MICA*105Q 384 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRTVPPMVNV TRSEASEGNI TVTCRASSFY PRNITLTWRQ
 DGVSLSHDTQ QWGDVLPDGN GTYQTWVATR ICQGEEQRFT CYMEHSGNHS THPVPSGKVL
 VLQSHWQTFH VSAVAAAAAA IFVIIIFYVR CCKKKTSAAE GPELVSLQVL DQHPVGTSDH
 RDATQLGFQP LMSALGSTGS TEGA*   
>P1;HLA:HLA26908
HLA:HLA26908 MICA*106 349 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKGRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLREIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKC
 WCFRVIGRHS MFLLLLLLLL LLLLFLLLLF STSVVVRRKH QLQRVQSSX* 
>P1;HLA:HLA26923
HLA:HLA26923 MICA*107N 59 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEAS GWSALPALX*
>P1;HLA:HLA26932
HLA:HLA26932 MICA*108 385 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESGVV LRRRVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AIFVIIIFYV RCCKKKTSAA EGPELVSLQV LDQHPVGTSD
 HRDATQLGFQ PLMSALGSTG STEGA*   
>P1;HLA:HLA26935
HLA:HLA26935 MICA*109 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNVETEEW TVPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLESSVV LRRTVPPMVN VTRSEASEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSALGSTGST EGA*   
>P1;HLA:HLA27258
HLA:HLA27258 MICA*110 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSGDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSALG STGSTEGT*   
>P1;HLA:HLA26888
HLA:HLA26888 MICA*111:01 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA26889
HLA:HLA26889 MICA*111:02 388 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAA AAAAIFVIII FYVCCCKKKT SAAEGPELVS LQVLDQHPVG
 TSDHRDATQL GFQPLMSDLG STGSTEGA*   
>P1;HLA:HLA07097
HLA:HLA07097 MICA*112:01:01 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
>P1;HLA:HLA26924
HLA:HLA26924 MICA*112:01:02 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
>P1;HLA:HLA26925
HLA:HLA26925 MICA*112:01:03 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
>P1;HLA:HLA26926
HLA:HLA26926 MICA*112:01:04 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
>P1;HLA:HLA26897
HLA:HLA26897 MICA*112:01:05 383 bases
 MGLGPVFLLL AGIFPFAPPG AAAEPHSLRY NLTVLSWDGS VQSGFLAEVH LDGQPFLRCD
 RQKCRAKPQG QWAEDVLGNK TWDRETRDLT GNGKDLRMTL AHIKDQKEGL HSLQEIRVCE
 IHEDNSTRSS QHFYYDGELF LSQNLETEEW TMPQSSRAQT LAMNVRNFLK EDAMKTKTHY
 HAMHADCLQE LRRYLKSGVV LRRTVPPMVN VTRSEASEGN ITVTCRASGF YPWNITLSWR
 QDGVSLSHDT QQWGDVLPDG NGTYQTWVAT RICQGEEQRF TCYMEHSGNH STHPVPSGKV
 LVLQSHWQTF HVSAVAAAAI FVIIIFYVRC CKKKTSAAEG PELVSLQVLD QHPVGTSDHR
 DATQLGFQPL MSDLGSTGST EGT*   
