>P1;HLA:HLA02033
HLA:HLA02033 MICB*001 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDES VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKV
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02059
HLA:HLA02059 MICB*002:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02749
HLA:HLA02749 MICB*002:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26091
HLA:HLA26091 MICB*002:01:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26141
HLA:HLA26141 MICB*002:01:04 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26199
HLA:HLA26199 MICB*002:01:05 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26167
HLA:HLA26167 MICB*002:01:06 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26151
HLA:HLA26151 MICB*002:01:07 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26136
HLA:HLA26136 MICB*002:01:08 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26754
HLA:HLA26754 MICB*002:01:09 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26729
HLA:HLA26729 MICB*002:01:10 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26621
HLA:HLA26621 MICB*002:01:11 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26688
HLA:HLA26688 MICB*002:01:12 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26615
HLA:HLA26615 MICB*002:01:13 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26639
HLA:HLA26639 MICB*002:01:14 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26645
HLA:HLA26645 MICB*002:01:15 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26701
HLA:HLA26701 MICB*002:01:16 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27300
HLA:HLA27300 MICB*002:01:17 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27305
HLA:HLA27305 MICB*002:01:18 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA28236
HLA:HLA28236 MICB*002:01:19 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA28237
HLA:HLA28237 MICB*002:01:20 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA18243
HLA:HLA18243 MICB*002:02:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26195
HLA:HLA26195 MICB*002:02:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA18553
HLA:HLA18553 MICB*002:03 273 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAETWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YNGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPS*  
>P1;HLA:HLA02060
HLA:HLA02060 MICB*003:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VICSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA27310
HLA:HLA27310 MICB*003:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VICSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA27317
HLA:HLA27317 MICB*003:01:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VICSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA02064
HLA:HLA02064 MICB*004:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA02750
HLA:HLA02750 MICB*004:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA27296
HLA:HLA27296 MICB*004:01:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA27297
HLA:HLA27297 MICB*004:01:04 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA27299
HLA:HLA27299 MICB*004:01:05 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA27309
HLA:HLA27309 MICB*004:01:06 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA28235
HLA:HLA28235 MICB*004:01:07 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA02062
HLA:HLA02062 MICB*005:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26086
HLA:HLA26086 MICB*005:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02061
HLA:HLA02061 MICB*005:02:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02747
HLA:HLA02747 MICB*005:02:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02748
HLA:HLA02748 MICB*005:02:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02746
HLA:HLA02746 MICB*005:02:04 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27301
HLA:HLA27301 MICB*005:02:05 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27302
HLA:HLA27302 MICB*005:02:06 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27307
HLA:HLA27307 MICB*005:02:07 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27308
HLA:HLA27308 MICB*005:02:08 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27312
HLA:HLA27312 MICB*005:02:09 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27313
HLA:HLA27313 MICB*005:02:10 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27315
HLA:HLA27315 MICB*005:02:11 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02067
HLA:HLA02067 MICB*005:03:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26161
HLA:HLA26161 MICB*005:03:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26128
HLA:HLA26128 MICB*005:03:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26201
HLA:HLA26201 MICB*005:03:04 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26142
HLA:HLA26142 MICB*005:03:05 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02068
HLA:HLA02068 MICB*005:04 317 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGP*    
>P1;HLA:HLA03111
HLA:HLA03111 MICB*005:05 273 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPS*  
>P1;HLA:HLA07364
HLA:HLA07364 MICB*005:06:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26093
HLA:HLA26093 MICB*005:06:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA08420
HLA:HLA08420 MICB*005:07:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26144
HLA:HLA26144 MICB*005:07:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA08423
HLA:HLA08423 MICB*005:08 359 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGPELV SLQVLDQHPV GTGDHRDAAQ LGFQPLMSAT GSTGSTEGA*
>P1;HLA:HLA18964
HLA:HLA18964 MICB*005:09 359 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGPELV SLQVLDQHPV GTGDHRDAAQ LGFQPLMSAT GSTGSTEGA*
>P1;HLA:HLA27885
HLA:HLA27885 MICB*005:10 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27890
HLA:HLA27890 MICB*005:11 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02063
HLA:HLA02063 MICB*006 317 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS KVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGP*    
>P1;HLA:HLA02069
HLA:HLA02069 MICB*007 317 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAETWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YNGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQKFTCYM EHSGNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGP*    
>P1;HLA:HLA02065
HLA:HLA02065 MICB*008:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26647
HLA:HLA26647 MICB*008:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26625
HLA:HLA26625 MICB*008:01:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26721
HLA:HLA26721 MICB*008:01:04 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26665
HLA:HLA26665 MICB*008:01:05 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26629
HLA:HLA26629 MICB*008:01:06 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26599
HLA:HLA26599 MICB*008:01:07 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26604
HLA:HLA26604 MICB*008:01:08 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26709
HLA:HLA26709 MICB*008:01:09 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26696
HLA:HLA26696 MICB*008:01:10 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26734
HLA:HLA26734 MICB*008:01:11 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02066
HLA:HLA02066 MICB*009N 169 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQX* 
>P1;HLA:HLA02070
HLA:HLA02070 MICB*010 359 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGPELV SLQVLDQHPV GTGDHRDAAQ LGFQPLMSAT GSTGSTEGT*
>P1;HLA:HLA02071
HLA:HLA02071 MICB*011 359 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKHQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGPELV SLQVLDQHPV GTGDHRDAAQ LGFQPLMSAT GSTGSTEGT*
>P1;HLA:HLA02072
HLA:HLA02072 MICB*012 359 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK GQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGPELV SLQVLDQHPV GTGDHRDAAQ LGFQPLMSAT GSTGSTEGA*
>P1;HLA:HLA02074
HLA:HLA02074 MICB*013:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH STHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26691
HLA:HLA26691 MICB*013:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH STHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26646
HLA:HLA26646 MICB*013:01:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH STHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26619
HLA:HLA26619 MICB*013:01:04 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH STHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26672
HLA:HLA26672 MICB*013:01:05 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH STHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02073
HLA:HLA02073 MICB*014:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH STHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26685
HLA:HLA26685 MICB*014:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH STHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26662
HLA:HLA26662 MICB*014:01:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH STHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26605
HLA:HLA26605 MICB*014:01:04 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH STHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26668
HLA:HLA26668 MICB*014:01:05 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH STHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26650
HLA:HLA26650 MICB*014:01:06 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH STHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02075
HLA:HLA02075 MICB*015 318 bases
 EPHSLRYNLM VLSQDGSVQS GFLAEGHLDG QPFLRYDRQK RRAKPQGQWA EDVLGAETWD
 TETEDLTENG QDLRRTLTHI KDQKGGLHSL QEIRVCEIHE DSSTRGSRHF YYNGELFLSQ
 NLETQESTVP QSSRAQTLAM NVTNFWKEDA MKTKTHYRAM QADCLQKLQR YLKSGVAIRR
 TVPPMVNVTC SKVSEGNITV TCRASSFYPR NITLTWRQDG VSLSHNTQQW GDVLPDGNGT
 YQTWVATRIR QGEEQRFTCY MEHSGNHSTH PVPSGKALVL QSQRTDFPYV SAAMPCFVII
 IILCVPCCKK KTSAAEGP*    
>P1;HLA:HLA02188
HLA:HLA02188 MICB*016 273 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAETWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHSTHP VPS*  
>P1;HLA:HLA02190
HLA:HLA02190 MICB*018:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26637
HLA:HLA26637 MICB*018:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27304
HLA:HLA27304 MICB*018:01:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02191
HLA:HLA02191 MICB*019:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26598
HLA:HLA26598 MICB*019:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26686
HLA:HLA26686 MICB*019:01:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26707
HLA:HLA26707 MICB*019:01:04 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26748
HLA:HLA26748 MICB*019:01:05 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26742
HLA:HLA26742 MICB*019:01:06 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26630
HLA:HLA26630 MICB*019:01:07 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26699
HLA:HLA26699 MICB*019:01:08 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA02192
HLA:HLA02192 MICB*020:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA26718
HLA:HLA26718 MICB*020:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA27298
HLA:HLA27298 MICB*020:01:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA02186
HLA:HLA02186 MICB*021:01:01N 89 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPRD SGQKMSWELR PGTQRPRTX*   
>P1;HLA:HLA27311
HLA:HLA27311 MICB*021:01:02N 89 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPRD SGQKMSWELR PGTQRPRTX*   
>P1;HLA:HLA27316
HLA:HLA27316 MICB*021:01:03N 89 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPRD SGQKMSWELR PGTQRPRTX*   
>P1;HLA:HLA02187
HLA:HLA02187 MICB*022 273 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAETWDT
 ETEGLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YNGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPS*  
>P1;HLA:HLA05831
HLA:HLA05831 MICB*023 359 bases
 PHSLHYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGPELV SLQVLDQHPV GTGDHRDAAQ LGFQPLMSAT GSTGSTEGA*
>P1;HLA:HLA07084
HLA:HLA07084 MICB*024:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQSFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA26705
HLA:HLA26705 MICB*024:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQSFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA26723
HLA:HLA26723 MICB*024:01:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQSFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA07085
HLA:HLA07085 MICB*025:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWE EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA26762
HLA:HLA26762 MICB*025:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWE EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA27303
HLA:HLA27303 MICB*025:01:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWE EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA27314
HLA:HLA27314 MICB*025:01:04 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWE EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA07379
HLA:HLA07379 MICB*026 359 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE NVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GKEQRFTCYM EHSGNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGPELV SLQVLDQHPV GTGDHRDAAQ LGFQPLMSAT GSTGSTEGT*
>P1;HLA:HLA08422
HLA:HLA08422 MICB*027 359 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSRNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGPELV SLQVLDQHPV GTGDHRDAAQ LGFQPLMSAT GSTGSTEGA*
>P1;HLA:HLA08424
HLA:HLA08424 MICB*028 359 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE NVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGPELV SLQVLDQHPV GTGDHRDAAQ LGFQPLMSAT GSTGSTEGA*
>P1;HLA:HLA08425
HLA:HLA08425 MICB*029 359 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAETWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YNGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGL SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPSGKALVLQ SQRTDFPYVS AAMPCFVIII
 ILCVPCCKKK TSAAEGPELV SLQVLDQHPV GTGDHRDAAQ LGFQPLMSAT GSTGSTEGA*
>P1;HLA:HLA12914
HLA:HLA12914 MICB*030 273 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED RSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPS*  
>P1;HLA:HLA13777
HLA:HLA13777 MICB*031:01:01 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26753
HLA:HLA26753 MICB*031:01:02 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26689
HLA:HLA26689 MICB*031:01:03 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26698
HLA:HLA26698 MICB*031:01:04 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26617
HLA:HLA26617 MICB*031:01:05 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27306
HLA:HLA27306 MICB*031:01:06 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKCRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA18237
HLA:HLA18237 MICB*032 273 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLDGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRICQ GEEQRFTCYM EHSGNHGTHP VPS*  
>P1;HLA:HLA18965
HLA:HLA18965 MICB*033 273 bases
 PHSLRYNLMV LSQDGSVQSG FLAEGHLAGQ PFLRYDRQKR RAKPQGQWAE DVLGAKTWDT
 ETEDLTENGQ DLRRTLTHIK DQKGGLHSLQ EIRVCEIHED SSTRGSRHFY YDGELFLSQN
 LETQESTVPQ SSRAQTLAMN VTNFWKEDAM KTKTHYRAMQ ADCLQKLQRY LKSGVAIRRT
 VPPMVNVTCS EVSEGNITVT CRASSFYPRN ITLTWRQDGV SLSHNTQQWG DVLPDGNGTY
 QTWVATRIRQ GEEQRFTCYM EHSGNHGTHP VPS*  
>P1;HLA:HLA26135
HLA:HLA26135 MICB*034 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAENVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKV
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA26211
HLA:HLA26211 MICB*035 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIIICVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26634
HLA:HLA26634 MICB*036 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQQTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26628
HLA:HLA26628 MICB*037 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 MHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAVPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA26766
HLA:HLA26766 MICB*038 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGT*   
>P1;HLA:HLA27886
HLA:HLA27886 MICB*039 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAK TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYDGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPQNITLTWR
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
>P1;HLA:HLA27889
HLA:HLA27889 MICB*040 383 bases
 MGLGRVLLFL AVAFPFAPPA AAAEPHSLRY NLMVLSQDGS VQSGFLAEGH LDGQPFLRYD
 RQKRRAKPQG QWAEDVLGAE TWDTETEDLT ENGQDLRRTL THIKDQKGGL HSLQEIRVCE
 IHEDSSTRGS RHFYYNGELF LSQNLETQES TVPQSSRAQT LAMNVTNFWK EDAMKTKTHY
 RAMQADCLQK LQRYLKSGVA IRRTVPPMVN VTCSEVSEGN ITVTCRASSF YPRNITLTWH
 QDGVSLSHNT QQWGDVLPDG NGTYQTWVAT RIRQGEEQRF TCYMEHSGNH GTHPVPSGKA
 LVLQSQRTDF PYVSAAMPCF VIIIILCVPC CKKKTSAAEG PELVSLQVLD QHPVGTGDHR
 DAAQLGFQPL MSATGSTGST EGA*   
