>DL;HLA:HLA02033
HLA:HLA02033 MICB*001 1152 bases
 ATGGGGCTGG GCCGGGTCCT GCTGTTTCTG GCCGTCGCCT TCCCTTTTGC ACCCCCGGCA
 GCCGCCGCTG AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGAATCT
 GTGCAGTCAG GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAC GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG
 ACCTGGGACA CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG
 ACTCATATCA AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCTATGA ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CGCGCTATGC AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC
 ATCAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGTG
 CTGGTGCTTC AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT
 GTTATTATTA TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT
 CCAGAGCTTG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG
 GATGCAGCAC AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT
 GAGGGCGCCT AG*    
>DL;HLA:HLA02059
HLA:HLA02059 MICB*002:01:01 1152 bases
 ATGGGGCTGG GCCGGGTCCT GCTGTTTCTG GCCGTCGCCT TCCCTTTTGC ACCCCCGGCA
 GCCGCCGCTG AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT
 GTGCAGTCAG GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAC GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTGAG
 ACCTGGGACA CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG
 ACTCATATCA AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACAATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCTATGA ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CGCGCTATGC AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC
 ATCAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG
 CTGGTGCTTC AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT
 GTTATTATTA TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT
 CCAGAGCTTG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG
 GATGCAGCAC AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT
 GAGGGCGCCT AG*    
>DL;HLA:HLA02749
HLA:HLA02749 MICB*002:01:02 1152 bases
 ATGGGGCTGG GCCGGGTCCT GCTGTTTCTG GCCGTCGCCT TCCCTTTTGC ACCCCCGGCA
 GCCGCCGCTG AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT
 GTGCAGTCAG GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAC GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTGAG
 ACCTGGGACA CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG
 ACTCATATCA AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACAATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCTATGA ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CGCGCTATGC AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC
 ATCAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG
 CTGGTGCTTC AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT
 GTTATTATTA TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT
 CCAGAGCTTG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG
 GATGCAGCAC AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT
 GAGGGCGCCT AG*    
>DL;HLA:HLA02060
HLA:HLA02060 MICB*003 1152 bases
 ATGGGGCTGG GCCGGGTCCT GCTGTTTCTG GCCGTCGCCT TCCCTTTTGC ACCCCCGGCA
 GCCGCCGCTG AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT
 GTGCAGTCAG GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAC GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG
 ACCTGGGACA CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG
 ACTCATATCA AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCTATGA ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CGCGCTATGC AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC
 ATCAGGAGAA CAGTGCCCCC CATGGTGAAT GTCATCTGCA GCGAGGTCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG
 CTGGTGCTTC AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT
 GTTATTATTA TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT
 CCAGAGCTTG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG
 GATGCAGCAC AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT
 GAGGGCACCT AG*    
>DL;HLA:HLA02064
HLA:HLA02064 MICB*004:01:01 1152 bases
 ATGGGGCTGG GCCGGGTCCT GCTGTTTCTG GCCGTCGCCT TCCCTTTTGC ACCCCCGGCA
 GCCGCCGCTG AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT
 GTGCAGTCAG GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAC GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAAATGTCCT GGGAGCTAAG
 ACCTGGGACA CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG
 ACTCATATCA AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCTATGA ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CGCGCTATGC AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC
 ATCAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG
 CTGGTGCTTC AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT
 GTTATTATTA TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT
 CCAGAGCTTG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG
 GATGCAGCAC AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT
 GAGGGCACCT AG*    
>DL;HLA:HLA02750
HLA:HLA02750 MICB*004:01:02 1152 bases
 ATGGGGCTGG GCCGGGTCCT GCTGTTTCTG GCCGTCGCCT TCCCTTTTGC ACCCCCGGCA
 GCCGCCGCTG AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT
 GTGCAGTCAG GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAC GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAAATGTCCT GGGAGCTAAG
 ACCTGGGACA CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG
 ACTCATATCA AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCTATGA ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CGCGCTATGC AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC
 ATCAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG
 CTGGTGCTTC AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT
 GTTATTATTA TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT
 CCAGAGCTTG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG
 GATGCAGCAC AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT
 GAGGGCACCT AG*    
>DL;HLA:HLA02062
HLA:HLA02062 MICB*005:01 953 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAT GGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCA*
>DL;HLA:HLA02061
HLA:HLA02061 MICB*005:02:01 1152 bases
 ATGGGGCTGG GCCGGGTCCT GCTGTTTCTG GCCGTCGCCT TCCCTTTTGC ACCCCCGGCA
 GCCGCCGCTG AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT
 GTGCAGTCAG GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAC GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG
 ACCTGGGACA CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG
 ACTCATATCA AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCTATGA ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CGCGCTATGC AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC
 ATCAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG
 CTGGTGCTTC AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT
 GTTATTATTA TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT
 CCAGAGCTTG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG
 GATGCAGCAC AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT
 GAGGGCGCCT AG*    
>DL;HLA:HLA02747
HLA:HLA02747 MICB*005:02:02 1152 bases
 ATGGGGCTGG GCCGGGTCCT GCTGTTTCTG GCCGTCGCCT TCCCTTTTGC ACCCCCGGCA
 GCCGCCGCTG AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT
 GTGCAGTCAG GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAC GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG
 ACCTGGGACA CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG
 ACTCATATCA AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCTATGA ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CGCGCTATGC AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC
 ATCAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG
 CTGGTGCTTC AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT
 GTTATTATTA TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT
 CCAGAGCTTG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG
 GATGCAGCAC AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT
 GAGGGCGCCT AG*    
>DL;HLA:HLA02748
HLA:HLA02748 MICB*005:02:03 1152 bases
 ATGGGGCTGG GCCGGGTCCT GCTGTTTCTG GCCGTCGCCT TCCCTTTTGC ACCCCCGGCA
 GCCGCCGCTG AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT
 GTGCAGTCAG GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAC GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG
 ACCTGGGACA CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG
 ACTCATATCA AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCTATGA ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CGCGCTATGC AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC
 ATCAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG
 CTGGTGCTTC AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT
 GTTATTATTA TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT
 CCAGAGCTTG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG
 GATGCAGCAC AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT
 GAGGGCGCCT AG*    
>DL;HLA:HLA02746
HLA:HLA02746 MICB*005:02:04 1152 bases
 ATGGGGCTGG GCCGGGTCCT GCTGTTTCTG GCCGTCGCCT TCCCTTTTGC ACCCCCGGCA
 GCCGCCGCTG AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT
 GTGCAGTCAG GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAC GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG
 ACCTGGGACA CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG
 ACTCATATCA AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATCCATGAAG ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCTATGA ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CGCGCTATGC AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC
 ATCAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG
 CTGGTGCTTC AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT
 GTTATTATTA TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT
 CCAGAGCTTG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG
 GATGCAGCAC AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT
 GAGGGCGCCT AG*    
>DL;HLA:HLA02067
HLA:HLA02067 MICB*005:03 1082 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGAA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCAGAGCTTG
 TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG GATGCAGCAC
 AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT GAGGGCGCCT
 AG*     
>DL;HLA:HLA02068
HLA:HLA02068 MICB*005:04 954 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACGTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCAG*
>DL;HLA:HLA03111
HLA:HLA03111 MICB*005:05 822 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACCCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA07364
HLA:HLA07364 MICB*005:06 1082 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GTGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCAGAGCTTG
 TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG GATGCAGCAC
 AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT GAGGGCGCCT
 AG*     
>DL;HLA:HLA02063
HLA:HLA02063 MICB*006 953 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCAAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCA*
>DL;HLA:HLA02069
HLA:HLA02069 MICB*007 954 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTGAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACAATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAAGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCAG*
>DL;HLA:HLA02065
HLA:HLA02065 MICB*008 1152 bases
 ATGGGGCTGG GCCGGGTCCT GCTGTTTCTG GCCGTCGCCT TCCCTTTTGC ACCCCCGGCA
 GCCGCCGCTG AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT
 GTGCAGTCAG GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC
 AGGCAGAAAC GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTGAG
 ACCTGGGACA CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG
 ACTCATATCA AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG
 ATGCATGAAG ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACAATGG GGAGCTCTTC
 CTCTCCCAAA ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC
 TTGGCTATGA ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT
 CGCGCTATGC AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC
 ATCAGGAGAA CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC
 ATCACCGTGA CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT
 CAGGATGGGG TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG
 AATGGAACCT ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC
 ACCTGCTACA TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG
 CTGGTGCTTC AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT
 GTTATTATTA TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT
 CCAGAGCTTG TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG
 GATGCAGCAC AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT
 GAGGGCGCCT AG*    
>DL;HLA:HLA02066
HLA:HLA02066 MICB*009N 954 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGTGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCATCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCAG*
>DL;HLA:HLA02070
HLA:HLA02070 MICB*010 1082 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCAGAGCTTG
 TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG GATGCAGCAC
 AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT GAGGGCACCT
 AG*     
>DL;HLA:HLA02071
HLA:HLA02071 MICB*011 1082 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCACCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCAGAGCTTG
 TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG GATGCAGCAC
 AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT GAGGGCACCT
 AG*     
>DL;HLA:HLA02072
HLA:HLA02072 MICB*012 1082 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGGCCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCAGAGCTTG
 TGAGCCTGCA GGTCCTGGAT CAACACCCAG TTGGGACAGG AGACCACAGG GATGCAGCAC
 AGCTGGGATT TCAGCCTCTG ATGTCAGCTA CTGGGTCCAC TGGTTCCACT GAGGGCGCCT
 AG*     
>DL;HLA:HLA02074
HLA:HLA02074 MICB*013 954 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGAA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCAG*
>DL;HLA:HLA02073
HLA:HLA02073 MICB*014 954 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTGAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACAATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCAG*
>DL;HLA:HLA02075
HLA:HLA02075 MICB*015 953 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTGAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACAATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCAAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCA*
>DL;HLA:HLA02188
HLA:HLA02188 MICB*016 822 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTGAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGAA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC AGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA02190
HLA:HLA02190 MICB*018 822 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACAATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA02191
HLA:HLA02191 MICB*019 822 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTGAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA02192
HLA:HLA02192 MICB*020 822 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAAATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACAATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA02186
HLA:HLA02186 MICB*021N 821 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCAGGGAC AGTGGGCAGA AGATGTCCTG GGAGCTAAGA CCTGGGACAC
 AGAGACCGAG GACTTGACAG AGAATGGGCA AGACCTCAGG AGGACCCTGA CTCATATCAA
 GGACCAGAAA GGAGGCTTGC ATTCCCTCCA GGAGATTAGG GTCTGTGAGA TCCATGAAGA
 CAGCAGCACC AGGGGCTCCC GGCATTTCTA CTACGATGGG GAGCTCTTCC TCTCCCAAAA
 CCTGGAGACT CAAGAATCGA CAGTGCCCCA GTCCTCCAGA GCTCAGACCT TGGCTATGAA
 CGTCACAAAT TTCTGGAAGG AAGATGCCAT GAAGACCAAG ACACACTATC GCGCTATGCA
 GGCAGACTGC CTGCAGAAAC TACAGCGATA TCTGAAATCC GGGGTGGCCA TCAGGAGAAC
 AGTGCCCCCC ATGGTGAATG TCACCTGCAG CGAGGTCTCA GAGGGCAACA TCACCGTGAC
 ATGCAGGGCT TCCAGCTTCT ATCCCCGGAA TATCACACTG ACCTGGCGTC AGGATGGGGT
 ATCTTTGAGC CACAACACCC AGCAGTGGGG GGATGTCCTG CCTGATGGGA ATGGAACCTA
 CCAGACCTGG GTGGCCACCA GGATTCGCCA AGGAGAGGAG CAGAGGTTCA CCTGCTACAT
 GGAACACAGC GGGAATCACG GCACTCACCC TGTGCCCTCT G* 
>DL;HLA:HLA02187
HLA:HLA02187 MICB*022 822 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTGAG ACCTGGGACA
 CAGAGACCGA GGGCTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACAATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA05831
HLA:HLA05831 MICB*023 954 bases
 AGCCCCACAG TCTTCATTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAGATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCAG*
>DL;HLA:HLA07084
HLA:HLA07084 MICB*024 822 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGTCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAAATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA07085
HLA:HLA07085 MICB*025 822 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAAATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGGAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAGAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TG* 
>DL;HLA:HLA07379
HLA:HLA07379 MICB*026 954 bases
 AGCCCCACAG TCTTCGTTAC AACCTCATGG TGCTGTCCCA GGATGGATCT GTGCAGTCAG
 GGTTTCTCGC TGAGGGACAT CTGGATGGTC AGCCCTTCCT GCGCTATGAC AGGCAGAAAC
 GCAGGGCAAA GCCCCAGGGA CAGTGGGCAG AAAATGTCCT GGGAGCTAAG ACCTGGGACA
 CAGAGACCGA GGACTTGACA GAGAATGGGC AAGACCTCAG GAGGACCCTG ACTCATATCA
 AGGACCAGAA AGGAGGCTTG CATTCCCTCC AGGAGATTAG GGTCTGTGAG ATCCATGAAG
 ACAGCAGCAC CAGGGGCTCC CGGCATTTCT ACTACGATGG GGAGCTCTTC CTCTCCCAAA
 ACCTGGAGAC TCAAGAATCG ACAGTGCCCC AGTCCTCCAG AGCTCAGACC TTGGCTATGA
 ACGTCACAAA TTTCTGGAAG GAAGATGCCA TGAAGACCAA GACACACTAT CGCGCTATGC
 AGGCAGACTG CCTGCAGAAA CTACAGCGAT ATCTGAAATC CGGGGTGGCC ATCAGGAGAA
 CAGTGCCCCC CATGGTGAAT GTCACCTGCA GCGAGGTCTC AGAGGGCAAC ATCACCGTGA
 CATGCAGGGC TTCCAGCTTC TATCCCCGGA ATATCACACT GACCTGGCGT CAGGATGGGG
 TATCTTTGAG CCACAACACC CAGCAGTGGG GGGATGTCCT GCCTGATGGG AATGGAACCT
 ACCAGACCTG GGTGGCCACC AGGATTCGCC AAGGAAAGGA GCAGAGGTTC ACCTGCTACA
 TGGAACACAG CGGGAATCAC GGCACTCACC CTGTGCCCTC TGGGAAGGCG CTGGTGCTTC
 AGAGTCAACG GACAGACTTT CCATATGTTT CTGCTGCTAT GCCATGTTTT GTTATTATTA
 TTATTCTCTG TGTCCCTTGT TGCAAGAAGA AAACATCAGC GGCAGAGGGT CCAG*
