>DL;HLA:HLA18596
HLA:HLA18596 N*01:01:01:01 635 bases
 AATTAGGACC CCCTCACCTC CTTTCAGACC TGGTGCCTCC AACTATATCC TGCCTCACTC
 TGCTTTGAAA CAGGAAAGTG TTCCCCCTGG ACTCTTAGAG TAGATGTGGG TATCTGAGTT
 TCTCTTCCTA AAATCCTTTC CTTCTTAGAG CGATCAATGA GCCCTGTTGA ATGGCCTATG
 GAAGGGAAAT GAATGTTCTA AATTTCCTCT GACCCTTTTC TTCGGACCCC CAAAGGCATT
 CCCCACCAGC ACCCACTATG ACCCCATCTC TGACTGTAAT ACCACCCTGA GGTGCTGGGC
 CCTGGGCTTC CACCCTGAAG AGATCACATT GATCTGGCAG CAGGATGGGG AGGACTATAC
 CTAGGACATG GAGCTTGCAG AGACCATTTT ATCTTTTTGA CAACTTTTTT TTTTTTTTTT
 TTTTTTGAGA CAGAGTCTCA CTCTTGCCCA AGCTGGAGTG CAGTGGCGCG ATCTTGGCTC
 ACTGCAAGCT CCGCCTCCCA GGTTGATGCC ATTCTCCTGC CTCAGCCTCC TGAATAGCTG
 GGACTACAGG CACCCGCCAC CATGCCCGGC TAATTTTTTG TATTTTTAGT AGAGACGGGG
 TTTCACCGTG TTAACCAGGA TGGGCTCGAT CTCCT  
>DL;HLA:HLA18599
HLA:HLA18599 N*01:01:01:02 634 bases
 AATTAGGACC CCCTCACCTC CTTTCAGACC TGGTGCCTCC AACTATATCC TGCCTCACTC
 TGCTTTGAAA CAGGAAAGTG TTCCCCCTGG ACTCTTAGAG TAGATGTGGG TATCTGAGTT
 TCTCTTCCTA AAATCCTTTC CTTCTTAGAG CGATCAATGA GCCCTGTTGA ATGGCCTATG
 GAAGGGAAAT GAATGTTCTA AATTTCCTCT GACCCTTTTC TTCGGACCCC CAAAGGCATT
 CCCCACCAGC ACCCACTATG ACCCCATCTC TGACTGTAAT ACCACCCTGA GGTGCTGGGC
 CCTGGGCTTC CACCCTGAAG AGATCACATT GATCTGGCAG CAGGATGGGG AGGACTATAC
 CTAGGACATG GAGCTTGCAG AGACCATTTT ATCTTTTTGA CAACTTTTTT TTTTTTTTTT
 TTTTTTGAGA CAGAGTCTAC TCTTGCCCAA GCTGGAGTGC AGTGGCGCGA TCTTGGCTCA
 CTGCAACGTC CGCCTCCCAG GTTGATGCCA TTCTCCTGCC TCAGCCTCCT GAATAGCTGG
 GACTACAGGC ACCCGCCACC ATGCCCGGCT AATTTTTTGT ATTTTTAGTA GAGACGGGGT
 TTCACCGTGT TAACCAGGAT GGGCTCGATC TCCT  
>DL;HLA:HLA18597
HLA:HLA18597 N*01:01:01:03 635 bases
 AATTAGGACC CCCTCACCTC CTTTCAGACC TGGTGCCTCC AACTATATCC TGCCTCACTC
 TGCTTTGAAA CAGGAAAGTG TTCCCCCTGG ACTCTTAGAG TAGATGTGGG TATCTGAGTT
 TCTCTTCCTA AAATCCTTTC CTTCTTAGAG CGATCAATGA GCCCTGTTGA ATGGCCTATG
 GAAGGGAAAT GAATGTTCTA AATTTCCTCT GACCCTTTTC TTCGGACCCC CAAAGGCATT
 CCCCACCAGC ACCCACTATG ACCCCATCTC TGACTGTAAT ACCACCCTGA GGTGCTGGGC
 CCTGGGCTTC CACCCTGAAG AGATCACATT GATCTGGCAG CAGGATGGGG AGGACTATAC
 CTAGGACATG GAGCTTGCAG AGACCATTTT ATCTTTTTGA CAACTTTTTT TTTTTTTTTT
 TTTTTTTGAG ACAGAGTCTC ACTCTTGCCC AAGCTGGAGT GCAGTGGCGC GATCTTGGCT
 CACTGCAAGC TCCGCCTCCC AGGTTGATGC CATTCTCCTG CCTCAGCCTC CTGAATAGCT
 GGGACTACAG GCACCCGCCA CCATGCCCGG CTAATTTTTT GTATTTTTAG TAGAGACGGG
 GTTTCACCGT GTTAACCAGG ATGGGCTCGA TCTCC  
>DL;HLA:HLA18598
HLA:HLA18598 N*01:01:01:04 339 bases
 GGTATCTGAG TTTCTCTTCC TAAAATCCTT TCCTTCTTAG AGCGATCAAT GAGCCCTGTT
 GAATGGCCTA TGGAAGGGAA ATGAATGTTC TAAATTTCCT CTGTCCCTTT TCTTCGGACC
 CCCAAAGGCA TTCCCCACCA GCACCCACTA TGACCCCATC TCTGACTGTA ATACCACCCT
 GAGGTGCTGG GCCCTGGGCT TCCACCCTGA AGAGATCACA TTGATCTGGC AGCAGGATGG
 GGAGGACTAT ACCTAGGACA TGGAGCTTGC AGAGACCATT TTATCTTTTT GACAACTTTT
 TTTTTTTTTT TTTTTTTTGA GACAGAGTCT CACTCTTGC  
>DL;HLA:HLA18600
HLA:HLA18600 N*01:01:01:05 635 bases
 AATTAGGACC CCCTCACCTC CTTTCAGACC TGGTGCCTCC AACTATATCC TGCCTCACTC
 TGCTTTGAAA CAGGAAAGTG TTCCCCCTGG ACTCTTAGAG TAGATGTGGG TATCTGAGTT
 TCTCTTCCTA AAATCCTTTC CTTCTTAGAG CGATCAATGA GCCCTGTTGA ATGGCCTATG
 GAAGGGAAAT GAATGTTCTA AATTTCCTCT GACCCTTTTC TTCGGACCCC CAAAGGCATT
 CCCCACCAGC ACCCACTATG ACCCCATCTC TGACTGTAAT ACCACCCTGA GGTGCTGGGC
 CCTGGGCTTC CACCCTGAAG AGATCACATT GATCTGGCAG CAGGATGGGG AGGACTATAC
 CTAGGACATG GAGCTTGCAG AGACCATTTT ATCTTTTTGA CAACTTTTTT TTTTTTTTTT
 TTTTTTTGAG ACGGAGTCTC ACTCTTGCCC AAGCTGGAGT GCAGTGGCGC GATCTTGGCT
 CACTGCAAGC TCCGCCTCCC AGGTTGATGC CATTCTCCTG CCTCAGCCTC CTGAATAGCT
 GGGACTACAG GCACCCGCCA CCATGCCCGG CTAATTTTTT GTAGTTTTAG TAGAGATGGG
 GTTTCACCGT GTTAACCAGG ATGGGCTCGA TCTCC  
