>DL;HLA:HLA18596
HLA:HLA18596 N*01:01:01:01 636 bases
 AATTAGGACC CCCTCACCTC CTTTCAGACC TGGTGCCTCC AACTATATCC TGCCTCACTC
 TGCTTTGAAA CAGGAAAGTG TTCCCCCTGG ACTCTTAGAG TAGATGTGGG TATCTGAGTT
 TCTCTTCCTA AAATCCTTTC CTTCTTAGAG CGATCAATGA GCCCTGTTGA ATGGCCTATG
 GAAGGGAAAT GAATGTTCTA AATTTCCTCT GACCCTTTTC TTCGGGACCC CCAAAGGCAT
 TCCCCACCAG CACCCACTAT GACCCCATCT CTGACTGTAA TACCACCCTG AGGTGCTGGG
 CCCTGGGCTT CCACCCTGAA GAGATCACAT TGATCTGGCA GCAGGATGGG GAGGACTATA
 CCTAGGACAT GGAGCTTGCA GAGACCATTT TATCTTTTTG ACAACTTTTT TTTTTTTTTT
 TTTTTTTGAG ACAGAGTCTC ACTCTTGCCC AAGCTGGAGT GCAGTGGCGC GATCTTGGCT
 CACTGCAAGC TCCGCCTCCC AGGTTGATGC CATTCTCCTG CCTCAGCCTC CTGAATAGCT
 GGGACTACAG GCACCCGCCA CCATGCCCGG CTAATTTTTT GTATTTTTAG TAGAGACGGG
 GTTTCACCGT GTTAACCAGG ATGGGCTCGA TCTCCT*  
>DL;HLA:HLA18599
HLA:HLA18599 N*01:01:01:02 635 bases
 AATTAGGACC CCCTCACCTC CTTTCAGACC TGGTGCCTCC AACTATATCC TGCCTCACTC
 TGCTTTGAAA CAGGAAAGTG TTCCCCCTGG ACTCTTAGAG TAGATGTGGG TATCTGAGTT
 TCTCTTCCTA AAATCCTTTC CTTCTTAGAG CGATCAATGA GCCCTGTTGA ATGGCCTATG
 GAAGGGAAAT GAATGTTCTA AATTTCCTCT GACCCTTTTC TTCGGGACCC CCAAAGGCAT
 TCCCCACCAG CACCCACTAT GACCCCATCT CTGACTGTAA TACCACCCTG AGGTGCTGGG
 CCCTGGGCTT CCACCCTGAA GAGATCACAT TGATCTGGCA GCAGGATGGG GAGGACTATA
 CCTAGGACAT GGAGCTTGCA GAGACCATTT TATCTTTTTG ACAACTTTTT TTTTTTTTTT
 TTTTTTTGAG ACAGAGTCTA CTCTTGCCCA AGCTGGAGTG CAGTGGCGCG ATCTTGGCTC
 ACTGCAACGT CCGCCTCCCA GGTTGATGCC ATTCTCCTGC CTCAGCCTCC TGAATAGCTG
 GGACTACAGG CACCCGCCAC CATGCCCGGC TAATTTTTTG TATTTTTAGT AGAGACGGGG
 TTTCACCGTG TTAACCAGGA TGGGCTCGAT CTCCT*  
>DL;HLA:HLA18597
HLA:HLA18597 N*01:01:01:03 636 bases
 AATTAGGACC CCCTCACCTC CTTTCAGACC TGGTGCCTCC AACTATATCC TGCCTCACTC
 TGCTTTGAAA CAGGAAAGTG TTCCCCCTGG ACTCTTAGAG TAGATGTGGG TATCTGAGTT
 TCTCTTCCTA AAATCCTTTC CTTCTTAGAG CGATCAATGA GCCCTGTTGA ATGGCCTATG
 GAAGGGAAAT GAATGTTCTA AATTTCCTCT GACCCTTTTC TTCGGGACCC CCAAAGGCAT
 TCCCCACCAG CACCCACTAT GACCCCATCT CTGACTGTAA TACCACCCTG AGGTGCTGGG
 CCCTGGGCTT CCACCCTGAA GAGATCACAT TGATCTGGCA GCAGGATGGG GAGGACTATA
 CCTAGGACAT GGAGCTTGCA GAGACCATTT TATCTTTTTG ACAACTTTTT TTTTTTTTTT
 TTTTTTTTGA GACAGAGTCT CACTCTTGCC CAAGCTGGAG TGCAGTGGCG CGATCTTGGC
 TCACTGCAAG CTCCGCCTCC CAGGTTGATG CCATTCTCCT GCCTCAGCCT CCTGAATAGC
 TGGGACTACA GGCACCCGCC ACCATGCCCG GCTAATTTTT TGTATTTTTA GTAGAGACGG
 GGTTTCACCG TGTTAACCAG GATGGGCTCG ATCTCC*  
>DL;HLA:HLA18598
HLA:HLA18598 N*01:01:01:04 340 bases
 GGTATCTGAG TTTCTCTTCC TAAAATCCTT TCCTTCTTAG AGCGATCAAT GAGCCCTGTT
 GAATGGCCTA TGGAAGGGAA ATGAATGTTC TAAATTTCCT CTGTCCCTTT TCTTCGGGAC
 CCCCAAAGGC ATTCCCCACC AGCACCCACT ATGACCCCAT CTCTGACTGT AATACCACCC
 TGAGGTGCTG GGCCCTGGGC TTCCACCCTG AAGAGATCAC ATTGATCTGG CAGCAGGATG
 GGGAGGACTA TACCTAGGAC ATGGAGCTTG CAGAGACCAT TTTATCTTTT TGACAACTTT
 TTTTTTTTTT TTTTTTTTTG AGACAGAGTC TCACTCTTGC * 
>DL;HLA:HLA18600
HLA:HLA18600 N*01:01:01:05 636 bases
 AATTAGGACC CCCTCACCTC CTTTCAGACC TGGTGCCTCC AACTATATCC TGCCTCACTC
 TGCTTTGAAA CAGGAAAGTG TTCCCCCTGG ACTCTTAGAG TAGATGTGGG TATCTGAGTT
 TCTCTTCCTA AAATCCTTTC CTTCTTAGAG CGATCAATGA GCCCTGTTGA ATGGCCTATG
 GAAGGGAAAT GAATGTTCTA AATTTCCTCT GACCCTTTTC TTCGGGACCC CCAAAGGCAT
 TCCCCACCAG CACCCACTAT GACCCCATCT CTGACTGTAA TACCACCCTG AGGTGCTGGG
 CCCTGGGCTT CCACCCTGAA GAGATCACAT TGATCTGGCA GCAGGATGGG GAGGACTATA
 CCTAGGACAT GGAGCTTGCA GAGACCATTT TATCTTTTTG ACAACTTTTT TTTTTTTTTT
 TTTTTTTTGA GACGGAGTCT CACTCTTGCC CAAGCTGGAG TGCAGTGGCG CGATCTTGGC
 TCACTGCAAG CTCCGCCTCC CAGGTTGATG CCATTCTCCT GCCTCAGCCT CCTGAATAGC
 TGGGACTACA GGCACCCGCC ACCATGCCCG GCTAATTTTT TGTAGTTTTA GTAGAGATGG
 GGTTTCACCG TGTTAACCAG GATGGGCTCG ATCTCC*  
