>DL;HLA:HLA18596
HLA:HLA18596 N*01:01:01:01 161 bases
 ACCCCCAAAG GCATTCCCCA CCAGCACCCA CTATGACCCC ATCTCTGACT GTAATACCAC
 CCTGAGGTGC TGGGCCCTGG GCTTCCACCC TGAAGAGATC ACATTGATCT GGCAGCAGGA
 TGGGGAGGAC TATACCTAGG ACATGGAGCT TGCAGAGACC A 
>DL;HLA:HLA18599
HLA:HLA18599 N*01:01:01:02 161 bases
 ACCCCCAAAG GCATTCCCCA CCAGCACCCA CTATGACCCC ATCTCTGACT GTAATACCAC
 CCTGAGGTGC TGGGCCCTGG GCTTCCACCC TGAAGAGATC ACATTGATCT GGCAGCAGGA
 TGGGGAGGAC TATACCTAGG ACATGGAGCT TGCAGAGACC A 
>DL;HLA:HLA18597
HLA:HLA18597 N*01:01:01:03 161 bases
 ACCCCCAAAG GCATTCCCCA CCAGCACCCA CTATGACCCC ATCTCTGACT GTAATACCAC
 CCTGAGGTGC TGGGCCCTGG GCTTCCACCC TGAAGAGATC ACATTGATCT GGCAGCAGGA
 TGGGGAGGAC TATACCTAGG ACATGGAGCT TGCAGAGACC A 
>DL;HLA:HLA18598
HLA:HLA18598 N*01:01:01:04 161 bases
 ACCCCCAAAG GCATTCCCCA CCAGCACCCA CTATGACCCC ATCTCTGACT GTAATACCAC
 CCTGAGGTGC TGGGCCCTGG GCTTCCACCC TGAAGAGATC ACATTGATCT GGCAGCAGGA
 TGGGGAGGAC TATACCTAGG ACATGGAGCT TGCAGAGACC A 
>DL;HLA:HLA18600
HLA:HLA18600 N*01:01:01:05 161 bases
 ACCCCCAAAG GCATTCCCCA CCAGCACCCA CTATGACCCC ATCTCTGACT GTAATACCAC
 CCTGAGGTGC TGGGCCCTGG GCTTCCACCC TGAAGAGATC ACATTGATCT GGCAGCAGGA
 TGGGGAGGAC TATACCTAGG ACATGGAGCT TGCAGAGACC A 
