>DL;HLA:HLA18607
HLA:HLA18607 S*01:01:01:01 875 bases
 CACCAAAGAC CAAAGCTAAC TTTGTATCTA CTATGTACCA AGTATGTCTT TACATACCGT
 GCAGTTGGTT CAGTCCTCAC ACCTGCTTTC TTCATGTTTC CTGCGCTGGG TCTGCAGTCA
 CAGTTTTGGA AACTTCTCTG GGGTCCAAGA CTAGGGGGTT CCTCTAGGAC CTCATGGCCC
 TGTCTCTTCC CTAGCCCCTC ACAGGATGAT TTCTTCCCAG AGGGCAGAGA AGGAGGTGCT
 CAGGCTGTGT GTAACTATGG GAGACAGATG TGGAGGAGCT CACCTATGCC ATAATTCCTC
 CTCTCCCACA TCTCCTGCAG GCTCTGACCG GGTCCTGTTT TTGTTCTACC CCAGGCAGTG
 ACAGTGACCA GGGCTGTGAT GTGTCTCTCA CAGCTTGTAA AGGTGGCGTC CTGGAGGGCC
 TTATGTGGAA GGGGGATGGG GTACAGGGGA CAAGACTGGA TTACGGTGAT TCTTTGGGAC
 ACTTTGAGTG TGTAGTGGGG AGTTCAGAGT GTTACGCTTT ATGGCCACTG ACCTGAATTT
 GTTCATGACT ATTGTTTTCT GTAGCCTGAG GCAGCTGTCT TGTGAGGGAC TGAGATGCAG
 GATTTCTTCA TGCCGCCCCT TTGTGACTTC AGGAGCCTCT GGTGTCTCTT TCTGCAAAGG
 CATCTGAATG TGTCTGTGTC CCTGTTAGCC TAGTGTGAGG AGGTGGAGAG ACCAGCCCTC
 CCCCATGTCT ACCATGACCC CCTTCCCCAT GCTGAATTAG CTGACTTTAC AAAAAGAAAA
 TTACCATCAA TAATGTGGAT GGGCCTCATC CGATCAGTAG AAGACTCTGA GAGCAGAAAC
 TGAGGTTTCC CAGAGAAGAA GAAATCCTGC CTCAG*  
>DL;HLA:HLA18606
HLA:HLA18606 S*01:01:01:02 875 bases
 CACCAAAGAC CAAAGCTAAC TTTGTATCTA CTATGTACCA AGTATGTCTT TACATACCGT
 GCAGTTGGTT CAGTCCTCAC ACCTGCTTTC TTCATGTTTC CTGCCCTGGG TCTGCAGTCA
 CAGTTTTGGA AACTTCTCTG GGGTCCAAGA CTAGGGGGTT CCTCTAGGAC CTCATGGCCC
 TGTCTCTTCC CTAGCCCCTC ACAGGATGAT TTCTTCCCAG AGGGCAGAGA AGGAGGTGCT
 CAGGCTGTGT GTAACTATGG GAGACGGATG TGGAGGAGCT CACCTATGCC ATAATTCCTC
 CTCTCCCACA TCTCCTGCAG GCTCTGACCG GGTCCTGTTT TTGTTCTACC CCAGGCAGTG
 ACAGTGACCA GGGCTGTGAT GTGTCTCTCA CAGCTTGTAA AGGTGGCGTC CTGGAGGGCC
 TTATGTGGAA GGGGGATGGG GTACAGGGGA CAAGACTGGA TTACGGTGAT TCTTTGGGAC
 ACTTTGAGTG TGTAGTGGGG AGTTCAGAGT GTTACGCTTT ATGGCCACTG ACCTGAATTT
 GTTCATGACT ATTGTTTTCT GTAGCCTGAG GCAGCTGTCT TGTGAGGGAC TGAGATGCAG
 GATTTCTTCA TGCCGCCCCT TTGTGACTTC AGGAGCCTCT GGTGTCTCTT TCTGCAAAGG
 CATCTGAATG TGTCTGTGTC CCTGTTAGCC TAGTGTGAGG AGGTGGAGAG ACCAGCCCTC
 CCCCATGTCT ACCATGACCC CCTTCCCCAT GCTGAATTAG CTGACTTTAC AAAAAGAAAA
 TTACCATCAA TAATGTGGAT GGGCCTCATC CGATCAGTAG AAGACTCTGA GAGCAGAAAC
 TGAGGTTTCC CAGAGAAGAA GAAATCCTGC CTCAG*  
>DL;HLA:HLA18601
HLA:HLA18601 S*01:02:01:01 875 bases
 CACCAAAGAC CAAAGCTAAC TTTGTATCTA CTATGTACCA AGTATGTCTT TACATACCGT
 GCAGTTGGTT CAGTCCTCAC ACCTGCTTTC CTCATGTTTC CTGCCCTGGG TCTGCCGTCA
 CAGTTTTGGA AACTTCTCTG GGGTCCAAGA CTAGGGGGTT CCTCTAGGAC CTCATGGCCC
 TGTCTCCTCC CTAGCCCCTC ACAGGATGAT TTCTTCCCAG AGGGCAGAGA AGGAGGTGCT
 CAGGCTGTGT GTAACTATGG GAGACGGATG TGGAGGAGCT CACCTATGCC ATAATTCCTC
 CTCTCCCACA TCTCCTGCAG GCTCTGACCA GGTCCTGTTT TTGTTCTACC CCAGGCAGTG
 ACAGTGACCA GGGCTGTGAT GTGTCTCTCA CAGCTTGTAA AGGTGGCGTC CTGGAGGGCC
 TTATGTGGAA GGGGGATGGG GTACAGGGGA CAAGACTGGA TTACGGTGAT TCTTTGGGAC
 ACTTTGAGTG TGTAGTGGGG AGTTCAGAGT GTTACGCTTT ATGGCCACTG ACCTGAATTT
 GTTCATGACT ATTGTTTTCT GTAGCCTGAG GCAGCTGTCT TGTGAGGGAC TGAGATGCAG
 TATTTCTTCA TGCCTCCCCT TTGTGACTTC AAGAGCCTCT GGTGTCTCTT TCTGCAAAGG
 CATCTGAATG TGTCTGCGTC CCTGTTAGCC TAATGTGAGA AGGTGGAGAG ACCAGCCCTC
 CCCCATGTCT ACCATGACCC CCTTCCCCAT GCTGAATTAG CTGACTTTAC AAAAAGAAAA
 TTACCATCAA TAATGTGGAT GGGCTTCACC CGATCAGTAG AAGACTCTGA GAGCAGAAAC
 TGAGGTTTCC CAGAGAAGAA GAAATCCTGC CTCAG*  
>DL;HLA:HLA18602
HLA:HLA18602 S*01:02:01:02 721 bases
 GGGGTTCCTC CTAGACCTCA TGGCCCTGTC TCCTCCCTAG CCCCTCACAG GATGATTTCT
 TCCCAGAGGG CAGAGAAGGA GGTGCTCAGG CTGTGTGTAA CTATGGGAGA CGGATGTGGA
 GGAGCTCACC TATGCCATAA TTCCTCCTCT CCCACATCTC CTGCAGGCTC TGACCAGGTC
 CTGTTTTTGT TCTACCCCAG GCAGTGACAG TGACCAGGGC TGTGATGTGT CTCTCACAGC
 TTGTAAAGGT GGCGTCCTGG AGGGCCTTAT GTGGAAGGGG GATGGGGTAC AGGGGACAAG
 ACTGGATTAC GGTGATTCTT TGGGACACTT TGAGTGTGTA GTGGGGAGTT CAGAGTGTTA
 CGCTTTATGG CCACTGACCT GAATTTGTTC ATGACTATTG TTTTCTGTAG CCTGAGGCAG
 CTGTCTTGTG AGGGACTGAG ATGCAGTATT TCTTCATGCC TCCCCTTTGT GACTTCAAGA
 GCCTCTGGTG TCTCTTTCTG CAAAGGCATC TGAATGTGTC TGCGTCCCTG TTAGCCTAAT
 GTGAGAAGGT GGAGAGACCA GCCCTCCCCC ATGTCTACCA TGACCCCCTT CCCCATGCTG
 AATTAGCTGA CTTTACAAAA AGAAAATTAC CATCAATAAT GTGGATGGGC TTCACCCGAT
 CAGTAGAAGA CTCTGAGAGC AGAAACTGAG GTTTCCCAGA GAAGAAGAAA TCCTGCCTCA
 G*     
>DL;HLA:HLA18603
HLA:HLA18603 S*01:02:01:03 875 bases
 CACCAAAGAC CAAAGCTAAC TTTGTATCTA CTATGTACCA AGTATGTCTT TACATACCGT
 GCAGTTGGTT CAGTCCTCAC ACCTGCTTTC CTCATGTTTC CTGCCCTGGG TCTGCAGTCA
 CAGTTTTGGA AACTTCTCTG GGGTCCAAGA CTAGGGGGTT CCTCTAGGAC CTCATGGCCC
 TGTCTCCTCC CTAGCCCCTC ACAGGATGAT TTCTTCCCAG AGGGCAGAGA AGGAGGTGCT
 CAGGCTGTGT GTAACTATGG GAGACGGATG TGGAGGAGCT CACCTATGCC ATAATTCCTC
 CTCTCCCACA TCTCCTGCAG GCTCTGACCA GGTCCTGTTT TTGTTCTACC CCAGGCAGTG
 ACAGTGACCA GGGCTGTGAT GTGTCTCTCA CAGCTTGTAA AGGTGGCGTC CTGGAGGGCC
 TTATGTGGAA GGGGGATGGG GTACAGGGGA CAAGACTGGA TTACGGTGAT TCTTTGGGAC
 ACTTTGAGTG TGTAGTGGGG AGTTCAGAGT GTTACGCTTT ATGGCCACTG ACCTGAATTT
 GTTCATGACT ATTGTTTTCT GTAGCCTGAG GCAGCTGTCT TGTGAGGGAC TGAGATGCAG
 TATTTCTTCA TGCCTCCCCT TTGTGACTTC AAGAGCCTCT GGTGTCTCTT TCTGCAAAGG
 CATCTGAATG TGTCTGCGTC CCTGTTAGCC TAATGTGAGA AGGTGGAGAG ACCAGCCCTC
 CCCCATGTCT ACCATGACCC CCTTCCCCAT GCTGAATTAG CTGACTTTAC AAAAAGAAAA
 TTACCATCAA TAATGTGGAT GGGCTTCACC CGATCAGTAG AAGACTCTGA GAGCAGAAAC
 TGAGGTTTCC CAGAGAAGAA GAAATCCTGC CTCAG*  
>DL;HLA:HLA18604
HLA:HLA18604 S*01:03 869 bases
 CACCAAAGAC CAAAGCTAAC TTTGTATCTA CTATGTACAA AGTATGTCTT TACATACCGT
 GCAGTTGGTT CAGTCCTCAC ACCTGCTTTC CTCATGTTTC CTGCCCTGGG TCTGCAGTCA
 CAGTTTTGGA AACTTCTCTG GGGTCCAAGA CTAGGGGGTT CCTCTAGGAC CTCATGGCCC
 TGTCTCCTCC CTAGCCCCTC ACAGGATGAT TTCTTCCCAG AGGGCAGAGA AGGAGGTGCT
 CAGGCTGTGT GTAACTATGG GAGACGGATG TGGAGGAGCT CACCTATGCC ATAATTCCTC
 CTCTCCCACA TCTCCTGCAG GCTCTGACCA GGTCCTGTTT TTGTTCTACC CCAGGCAGTG
 ACAGTGACCA GGGCTGTGAT GTGTCTCTCA CAGCTTGTAA AGGTGGCGTC CTGGAGGGCC
 TTATGTGGAA GGGGGATGGG GTACAGGGGA CAAGACTGGA TTACGGTGAT TCTTTGGGAC
 ACTTTGAGTG TGTAGTGAGG AGTTCAGAGT GTTACGCTTT ATGGCCACTG ACCTGAATTT
 GTTCATGACT ATTGTTTTCT GTAGCCTGAG GCAGCTGTCT TGTGAGGGAC TGAGATGCAG
 GATTTCTTCA CGCCTCCCCT TTGTGACTTC AAGAGCCTCT GGTGTCTCTT TCTGCAAAGG
 CATCTGAATG TGTCTGCGTC CCTGTTAGCC TAATGTGAGA AGGTGGAGAG ACCAGCCCTC
 CCCCATGTCT ACCATGACCC CCTTCCCCAT GCTGAATTAG CTGACTTTAC AAAAAGAAAA
 TTACCATCAA TAATGTGGAT GGGCTTCACC CGATCAGTAG AAGACTCTGA GAGCAGAAAC
 TGAGGTTTCC CAGAGAAGAA GAAATCCTG*   
>DL;HLA:HLA18605
HLA:HLA18605 S*01:04 869 bases
 CACCAAAGAC CAAAGCTAAC TTTGTATCTA CTATGTACAA AGTATGTCTT TACATACCGT
 GCAGTTGGTT CAGTCCTCAC ACCTGCTTTC CTCATGTTTC CTGCCCTGGG TCTGCAGTCA
 CAGTTTTGGA AACTTCTCTG GGGTCCAAGA CTAGGGGGTT CCTCTAGGAC CTCATGGCCC
 TGTCTCCTCC CTAGCCCCTC ACAGGATGAT TTCTTCCCAG AGGGCAGAGA AGGAGGTGCT
 CAGGCTGTGT GTAACTATGG GAGACGGATG TGGAGGAGCT CACCTATGCC ATAATTCCTC
 CTCTCCCACA TCTCCTGCAG GCTCTGACCA GGTCCTGTTT TTGTTCTACC CCAGGCAGTG
 ACAGTGACCA GGGCTGTGAT GTGTCTCTCA CAGCTTGTAA AGGTGGCGTC CTGGAGGGCC
 TTATGTGGAA GGGGGATGGG GTACAGGGGA CAAGACTGGA TTACGGTGAT TCTTTGGGAC
 ACTTTGAGTG TGTAGTGAGG AGTTCAGAGT GTTACGCTTT ATGGCCACTG ACCTGAATTT
 GTTCATGACT ATTGTTTTCT GTAGCCTGAG GCAGCTGTCT TGTGAGGGAC TGAGATGCAG
 GATTTCTTCA TGCCTCCCCT TTGTGACTTC AAGAGCCTCT GGTGTCTCTT TCTGCAAAGG
 CATCTGAATG TGTCTGCGTC CCTGTTAGCC TAATGTGAGA AGGTGGAGAG ACCAGCCCTC
 CCCCATGTCT ACCATGACCC CCTTCCCCAT GCTGAATTAG CTGACTTTAC AAAAAGAAAA
 TTACCATCAA TAATGTGGAT GGGCTTCACC CGATCAGTAG AAGACTCTGA GAGCAGAAAC
 TGAGGTTTCC CAGAGAAGAA GAAATCCTG*   
