>DL;HLA:HLA18607
HLA:HLA18607 S*01:01:01:01 874 bases
 CACCAAAGAC CAAAGCTAAC TTTGTATCTA CTATGTACCA AGTATGTCTT TACATACCGT
 GCAGTTGGTT CAGTCCTCAC ACCTGCTTTC TTCATGTTTC CTGCGCTGGG TCTGCAGTCA
 CAGTTTTGGA AACTTCTCTG GGGTCCAAGA CTAGGGGGTT CCTCTAGGAC CTCATGGCCC
 TGTCTCTTCC CTAGCCCCTC ACAGGATGAT TTCTTCCCAG AGGCAGAGAA GGAGGTGCTC
 AGGCTGTGTG TAACTATGGG AGACAGATGT GGAGGAGCTC ACCTATGCCA TAATTCCTCC
 TCTCCCACAT CTCCTGCAGG CTCTGACCGG GTCCTGTTTT TGTTCTACCC CAGGCAGTGA
 CAGTGACCAG GGCTGTGATG TGTCTCTCAC AGCTTGTAAA GGTGGCGTCC TGGAGGGCCT
 TATGTGGAAG GGGGATGGGG TACAGGGGAC AAGACTGGAT TACGGTGATT CTTTGGGACA
 CTTTGAGTGT GTAGTGGGGA GTTCAGAGTG TTACGCTTTA TGGCCACTGA CCTGAATTTG
 TTCATGACTA TTGTTTTCTG TAGCCTGAGG CAGCTGTCTT GTGAGGGACT GAGATGCAGG
 ATTTCTTCAT GCCGCCCCTT TGTGACTTCA GGAGCCTCTG GTGTCTCTTT CTGCAAAGGC
 ATCTGAATGT GTCTGTGTCC CTGTTAGCCT AGTGTGAGGA GGTGGAGAGA CCAGCCCTCC
 CCCATGTCTA CCATGACCCC CTTCCCCATG CTGAATTAGC TGACTTTACA AAAAGAAAAT
 TACCATCAAT AATGTGGATG GGCCTCATCC GATCAGTAGA AGACTCTGAG AGCAGAAACT
 GAGGTTTCCC AGAGAAGAAG AAATCCTGCC TCAG*  
>DL;HLA:HLA18606
HLA:HLA18606 S*01:01:01:02 874 bases
 CACCAAAGAC CAAAGCTAAC TTTGTATCTA CTATGTACCA AGTATGTCTT TACATACCGT
 GCAGTTGGTT CAGTCCTCAC ACCTGCTTTC TTCATGTTTC CTGCCCTGGG TCTGCAGTCA
 CAGTTTTGGA AACTTCTCTG GGGTCCAAGA CTAGGGGGTT CCTCTAGGAC CTCATGGCCC
 TGTCTCTTCC CTAGCCCCTC ACAGGATGAT TTCTTCCCAG AGGCAGAGAA GGAGGTGCTC
 AGGCTGTGTG TAACTATGGG AGACGGATGT GGAGGAGCTC ACCTATGCCA TAATTCCTCC
 TCTCCCACAT CTCCTGCAGG CTCTGACCGG GTCCTGTTTT TGTTCTACCC CAGGCAGTGA
 CAGTGACCAG GGCTGTGATG TGTCTCTCAC AGCTTGTAAA GGTGGCGTCC TGGAGGGCCT
 TATGTGGAAG GGGGATGGGG TACAGGGGAC AAGACTGGAT TACGGTGATT CTTTGGGACA
 CTTTGAGTGT GTAGTGGGGA GTTCAGAGTG TTACGCTTTA TGGCCACTGA CCTGAATTTG
 TTCATGACTA TTGTTTTCTG TAGCCTGAGG CAGCTGTCTT GTGAGGGACT GAGATGCAGG
 ATTTCTTCAT GCCGCCCCTT TGTGACTTCA GGAGCCTCTG GTGTCTCTTT CTGCAAAGGC
 ATCTGAATGT GTCTGTGTCC CTGTTAGCCT AGTGTGAGGA GGTGGAGAGA CCAGCCCTCC
 CCCATGTCTA CCATGACCCC CTTCCCCATG CTGAATTAGC TGACTTTACA AAAAGAAAAT
 TACCATCAAT AATGTGGATG GGCCTCATCC GATCAGTAGA AGACTCTGAG AGCAGAAACT
 GAGGTTTCCC AGAGAAGAAG AAATCCTGCC TCAG*  
>DL;HLA:HLA18601
HLA:HLA18601 S*01:02:01:01 874 bases
 CACCAAAGAC CAAAGCTAAC TTTGTATCTA CTATGTACCA AGTATGTCTT TACATACCGT
 GCAGTTGGTT CAGTCCTCAC ACCTGCTTTC CTCATGTTTC CTGCCCTGGG TCTGCCGTCA
 CAGTTTTGGA AACTTCTCTG GGGTCCAAGA CTAGGGGGTT CCTCTAGGAC CTCATGGCCC
 TGTCTCCTCC CTAGCCCCTC ACAGGATGAT TTCTTCCCAG AGGCAGAGAA GGAGGTGCTC
 AGGCTGTGTG TAACTATGGG AGACGGATGT GGAGGAGCTC ACCTATGCCA TAATTCCTCC
 TCTCCCACAT CTCCTGCAGG CTCTGACCAG GTCCTGTTTT TGTTCTACCC CAGGCAGTGA
 CAGTGACCAG GGCTGTGATG TGTCTCTCAC AGCTTGTAAA GGTGGCGTCC TGGAGGGCCT
 TATGTGGAAG GGGGATGGGG TACAGGGGAC AAGACTGGAT TACGGTGATT CTTTGGGACA
 CTTTGAGTGT GTAGTGGGGA GTTCAGAGTG TTACGCTTTA TGGCCACTGA CCTGAATTTG
 TTCATGACTA TTGTTTTCTG TAGCCTGAGG CAGCTGTCTT GTGAGGGACT GAGATGCAGT
 ATTTCTTCAT GCCTCCCCTT TGTGACTTCA AGAGCCTCTG GTGTCTCTTT CTGCAAAGGC
 ATCTGAATGT GTCTGCGTCC CTGTTAGCCT AATGTGAGAA GGTGGAGAGA CCAGCCCTCC
 CCCATGTCTA CCATGACCCC CTTCCCCATG CTGAATTAGC TGACTTTACA AAAAGAAAAT
 TACCATCAAT AATGTGGATG GGCTTCACCC GATCAGTAGA AGACTCTGAG AGCAGAAACT
 GAGGTTTCCC AGAGAAGAAG AAATCCTGCC TCAG*  
>DL;HLA:HLA18602
HLA:HLA18602 S*01:02:01:02 720 bases
 GGGGTTCCTC CTAGACCTCA TGGCCCTGTC TCCTCCCTAG CCCCTCACAG GATGATTTCT
 TCCCAGAGGC AGAGAAGGAG GTGCTCAGGC TGTGTGTAAC TATGGGAGAC GGATGTGGAG
 GAGCTCACCT ATGCCATAAT TCCTCCTCTC CCACATCTCC TGCAGGCTCT GACCAGGTCC
 TGTTTTTGTT CTACCCCAGG CAGTGACAGT GACCAGGGCT GTGATGTGTC TCTCACAGCT
 TGTAAAGGTG GCGTCCTGGA GGGCCTTATG TGGAAGGGGG ATGGGGTACA GGGGACAAGA
 CTGGATTACG GTGATTCTTT GGGACACTTT GAGTGTGTAG TGGGGAGTTC AGAGTGTTAC
 GCTTTATGGC CACTGACCTG AATTTGTTCA TGACTATTGT TTTCTGTAGC CTGAGGCAGC
 TGTCTTGTGA GGGACTGAGA TGCAGTATTT CTTCATGCCT CCCCTTTGTG ACTTCAAGAG
 CCTCTGGTGT CTCTTTCTGC AAAGGCATCT GAATGTGTCT GCGTCCCTGT TAGCCTAATG
 TGAGAAGGTG GAGAGACCAG CCCTCCCCCA TGTCTACCAT GACCCCCTTC CCCATGCTGA
 ATTAGCTGAC TTTACAAAAA GAAAATTACC ATCAATAATG TGGATGGGCT TCACCCGATC
 AGTAGAAGAC TCTGAGAGCA GAAACTGAGG TTTCCCAGAG AAGAAGAAAT CCTGCCTCAG
 *     
>DL;HLA:HLA18603
HLA:HLA18603 S*01:02:01:03 874 bases
 CACCAAAGAC CAAAGCTAAC TTTGTATCTA CTATGTACCA AGTATGTCTT TACATACCGT
 GCAGTTGGTT CAGTCCTCAC ACCTGCTTTC CTCATGTTTC CTGCCCTGGG TCTGCAGTCA
 CAGTTTTGGA AACTTCTCTG GGGTCCAAGA CTAGGGGGTT CCTCTAGGAC CTCATGGCCC
 TGTCTCCTCC CTAGCCCCTC ACAGGATGAT TTCTTCCCAG AGGCAGAGAA GGAGGTGCTC
 AGGCTGTGTG TAACTATGGG AGACGGATGT GGAGGAGCTC ACCTATGCCA TAATTCCTCC
 TCTCCCACAT CTCCTGCAGG CTCTGACCAG GTCCTGTTTT TGTTCTACCC CAGGCAGTGA
 CAGTGACCAG GGCTGTGATG TGTCTCTCAC AGCTTGTAAA GGTGGCGTCC TGGAGGGCCT
 TATGTGGAAG GGGGATGGGG TACAGGGGAC AAGACTGGAT TACGGTGATT CTTTGGGACA
 CTTTGAGTGT GTAGTGGGGA GTTCAGAGTG TTACGCTTTA TGGCCACTGA CCTGAATTTG
 TTCATGACTA TTGTTTTCTG TAGCCTGAGG CAGCTGTCTT GTGAGGGACT GAGATGCAGT
 ATTTCTTCAT GCCTCCCCTT TGTGACTTCA AGAGCCTCTG GTGTCTCTTT CTGCAAAGGC
 ATCTGAATGT GTCTGCGTCC CTGTTAGCCT AATGTGAGAA GGTGGAGAGA CCAGCCCTCC
 CCCATGTCTA CCATGACCCC CTTCCCCATG CTGAATTAGC TGACTTTACA AAAAGAAAAT
 TACCATCAAT AATGTGGATG GGCTTCACCC GATCAGTAGA AGACTCTGAG AGCAGAAACT
 GAGGTTTCCC AGAGAAGAAG AAATCCTGCC TCAG*  
>DL;HLA:HLA18604
HLA:HLA18604 S*01:03 868 bases
 CACCAAAGAC CAAAGCTAAC TTTGTATCTA CTATGTACAA AGTATGTCTT TACATACCGT
 GCAGTTGGTT CAGTCCTCAC ACCTGCTTTC CTCATGTTTC CTGCCCTGGG TCTGCAGTCA
 CAGTTTTGGA AACTTCTCTG GGGTCCAAGA CTAGGGGGTT CCTCTAGGAC CTCATGGCCC
 TGTCTCCTCC CTAGCCCCTC ACAGGATGAT TTCTTCCCAG AGGCAGAGAA GGAGGTGCTC
 AGGCTGTGTG TAACTATGGG AGACGGATGT GGAGGAGCTC ACCTATGCCA TAATTCCTCC
 TCTCCCACAT CTCCTGCAGG CTCTGACCAG GTCCTGTTTT TGTTCTACCC CAGGCAGTGA
 CAGTGACCAG GGCTGTGATG TGTCTCTCAC AGCTTGTAAA GGTGGCGTCC TGGAGGGCCT
 TATGTGGAAG GGGGATGGGG TACAGGGGAC AAGACTGGAT TACGGTGATT CTTTGGGACA
 CTTTGAGTGT GTAGTGAGGA GTTCAGAGTG TTACGCTTTA TGGCCACTGA CCTGAATTTG
 TTCATGACTA TTGTTTTCTG TAGCCTGAGG CAGCTGTCTT GTGAGGGACT GAGATGCAGG
 ATTTCTTCAC GCCTCCCCTT TGTGACTTCA AGAGCCTCTG GTGTCTCTTT CTGCAAAGGC
 ATCTGAATGT GTCTGCGTCC CTGTTAGCCT AATGTGAGAA GGTGGAGAGA CCAGCCCTCC
 CCCATGTCTA CCATGACCCC CTTCCCCATG CTGAATTAGC TGACTTTACA AAAAGAAAAT
 TACCATCAAT AATGTGGATG GGCTTCACCC GATCAGTAGA AGACTCTGAG AGCAGAAACT
 GAGGTTTCCC AGAGAAGAAG AAATCCTG*   
>DL;HLA:HLA18605
HLA:HLA18605 S*01:04 868 bases
 CACCAAAGAC CAAAGCTAAC TTTGTATCTA CTATGTACAA AGTATGTCTT TACATACCGT
 GCAGTTGGTT CAGTCCTCAC ACCTGCTTTC CTCATGTTTC CTGCCCTGGG TCTGCAGTCA
 CAGTTTTGGA AACTTCTCTG GGGTCCAAGA CTAGGGGGTT CCTCTAGGAC CTCATGGCCC
 TGTCTCCTCC CTAGCCCCTC ACAGGATGAT TTCTTCCCAG AGGCAGAGAA GGAGGTGCTC
 AGGCTGTGTG TAACTATGGG AGACGGATGT GGAGGAGCTC ACCTATGCCA TAATTCCTCC
 TCTCCCACAT CTCCTGCAGG CTCTGACCAG GTCCTGTTTT TGTTCTACCC CAGGCAGTGA
 CAGTGACCAG GGCTGTGATG TGTCTCTCAC AGCTTGTAAA GGTGGCGTCC TGGAGGGCCT
 TATGTGGAAG GGGGATGGGG TACAGGGGAC AAGACTGGAT TACGGTGATT CTTTGGGACA
 CTTTGAGTGT GTAGTGAGGA GTTCAGAGTG TTACGCTTTA TGGCCACTGA CCTGAATTTG
 TTCATGACTA TTGTTTTCTG TAGCCTGAGG CAGCTGTCTT GTGAGGGACT GAGATGCAGG
 ATTTCTTCAT GCCTCCCCTT TGTGACTTCA AGAGCCTCTG GTGTCTCTTT CTGCAAAGGC
 ATCTGAATGT GTCTGCGTCC CTGTTAGCCT AATGTGAGAA GGTGGAGAGA CCAGCCCTCC
 CCCATGTCTA CCATGACCCC CTTCCCCATG CTGAATTAGC TGACTTTACA AAAAGAAAAT
 TACCATCAAT AATGTGGATG GGCTTCACCC GATCAGTAGA AGACTCTGAG AGCAGAAACT
 GAGGTTTCCC AGAGAAGAAG AAATCCTG*   
