>DL;HLA:HLA18607
HLA:HLA18607 S*01:01:01:01 266 bases
 GCAGAGAAGG AGGTGCTCAG GCTGTGTGCA GTGACAGTGA CCAGGGCTGT GATGTGTCTC
 TCACAGCTTG TAAAGCCTGA GGCAGCTGTC TTGTGAGGGA CTGAGATGCA GGATTTCTTC
 ATGCCGCCCC TTTGTGACTT CAGGAGCCTC TGGTGTCTCT TTCTGCAAAG GCATCTGAAT
 GTGTCTGTGT CCCTGTTAGC CTAGTGTGAG GAGGTGGAGA GACCAGCCCT CCCCCATGTC
 TACCATGACC CCCTTCCCCA TGCTGA   
>DL;HLA:HLA18606
HLA:HLA18606 S*01:01:01:02 266 bases
 GCAGAGAAGG AGGTGCTCAG GCTGTGTGCA GTGACAGTGA CCAGGGCTGT GATGTGTCTC
 TCACAGCTTG TAAAGCCTGA GGCAGCTGTC TTGTGAGGGA CTGAGATGCA GGATTTCTTC
 ATGCCGCCCC TTTGTGACTT CAGGAGCCTC TGGTGTCTCT TTCTGCAAAG GCATCTGAAT
 GTGTCTGTGT CCCTGTTAGC CTAGTGTGAG GAGGTGGAGA GACCAGCCCT CCCCCATGTC
 TACCATGACC CCCTTCCCCA TGCTGA   
>DL;HLA:HLA18601
HLA:HLA18601 S*01:02:01:01 266 bases
 GCAGAGAAGG AGGTGCTCAG GCTGTGTGCA GTGACAGTGA CCAGGGCTGT GATGTGTCTC
 TCACAGCTTG TAAAGCCTGA GGCAGCTGTC TTGTGAGGGA CTGAGATGCA GTATTTCTTC
 ATGCCTCCCC TTTGTGACTT CAAGAGCCTC TGGTGTCTCT TTCTGCAAAG GCATCTGAAT
 GTGTCTGCGT CCCTGTTAGC CTAATGTGAG AAGGTGGAGA GACCAGCCCT CCCCCATGTC
 TACCATGACC CCCTTCCCCA TGCTGA   
>DL;HLA:HLA18602
HLA:HLA18602 S*01:02:01:02 266 bases
 GCAGAGAAGG AGGTGCTCAG GCTGTGTGCA GTGACAGTGA CCAGGGCTGT GATGTGTCTC
 TCACAGCTTG TAAAGCCTGA GGCAGCTGTC TTGTGAGGGA CTGAGATGCA GTATTTCTTC
 ATGCCTCCCC TTTGTGACTT CAAGAGCCTC TGGTGTCTCT TTCTGCAAAG GCATCTGAAT
 GTGTCTGCGT CCCTGTTAGC CTAATGTGAG AAGGTGGAGA GACCAGCCCT CCCCCATGTC
 TACCATGACC CCCTTCCCCA TGCTGA   
>DL;HLA:HLA18603
HLA:HLA18603 S*01:02:01:03 266 bases
 GCAGAGAAGG AGGTGCTCAG GCTGTGTGCA GTGACAGTGA CCAGGGCTGT GATGTGTCTC
 TCACAGCTTG TAAAGCCTGA GGCAGCTGTC TTGTGAGGGA CTGAGATGCA GTATTTCTTC
 ATGCCTCCCC TTTGTGACTT CAAGAGCCTC TGGTGTCTCT TTCTGCAAAG GCATCTGAAT
 GTGTCTGCGT CCCTGTTAGC CTAATGTGAG AAGGTGGAGA GACCAGCCCT CCCCCATGTC
 TACCATGACC CCCTTCCCCA TGCTGA   
>DL;HLA:HLA18604
HLA:HLA18604 S*01:03 266 bases
 GCAGAGAAGG AGGTGCTCAG GCTGTGTGCA GTGACAGTGA CCAGGGCTGT GATGTGTCTC
 TCACAGCTTG TAAAGCCTGA GGCAGCTGTC TTGTGAGGGA CTGAGATGCA GGATTTCTTC
 ACGCCTCCCC TTTGTGACTT CAAGAGCCTC TGGTGTCTCT TTCTGCAAAG GCATCTGAAT
 GTGTCTGCGT CCCTGTTAGC CTAATGTGAG AAGGTGGAGA GACCAGCCCT CCCCCATGTC
 TACCATGACC CCCTTCCCCA TGCTGA   
>DL;HLA:HLA18605
HLA:HLA18605 S*01:04 266 bases
 GCAGAGAAGG AGGTGCTCAG GCTGTGTGCA GTGACAGTGA CCAGGGCTGT GATGTGTCTC
 TCACAGCTTG TAAAGCCTGA GGCAGCTGTC TTGTGAGGGA CTGAGATGCA GGATTTCTTC
 ATGCCTCCCC TTTGTGACTT CAAGAGCCTC TGGTGTCTCT TTCTGCAAAG GCATCTGAAT
 GTGTCTGCGT CCCTGTTAGC CTAATGTGAG AAGGTGGAGA GACCAGCCCT CCCCCATGTC
 TACCATGACC CCCTTCCCCA TGCTGA   
