>DL;HLA:HLA18607
HLA:HLA18607 S*01:01:01:01 268 bases
 GGCAGAGAAG GAGGTGCTCA GGCTGTGTGC AGTGACAGTG ACCAGGGCTG TGATGTGTCT
 CTCACAGCTT GTAAAGGCCT GAGGCAGCTG TCTTGTGAGG GACTGAGATG CAGGATTTCT
 TCATGCCGCC CCTTTGTGAC TTCAGGAGCC TCTGGTGTCT CTTTCTGCAA AGGCATCTGA
 ATGTGTCTGT GTCCCTGTTA GCCTAGTGTG AGGAGGTGGA GAGACCAGCC CTCCCCCATG
 TCTACCATGA CCCCCTTCCC CATGCTGA*   
>DL;HLA:HLA18606
HLA:HLA18606 S*01:01:01:02 268 bases
 GGCAGAGAAG GAGGTGCTCA GGCTGTGTGC AGTGACAGTG ACCAGGGCTG TGATGTGTCT
 CTCACAGCTT GTAAAGGCCT GAGGCAGCTG TCTTGTGAGG GACTGAGATG CAGGATTTCT
 TCATGCCGCC CCTTTGTGAC TTCAGGAGCC TCTGGTGTCT CTTTCTGCAA AGGCATCTGA
 ATGTGTCTGT GTCCCTGTTA GCCTAGTGTG AGGAGGTGGA GAGACCAGCC CTCCCCCATG
 TCTACCATGA CCCCCTTCCC CATGCTGA*   
>DL;HLA:HLA18601
HLA:HLA18601 S*01:02:01:01 268 bases
 GGCAGAGAAG GAGGTGCTCA GGCTGTGTGC AGTGACAGTG ACCAGGGCTG TGATGTGTCT
 CTCACAGCTT GTAAAGGCCT GAGGCAGCTG TCTTGTGAGG GACTGAGATG CAGTATTTCT
 TCATGCCTCC CCTTTGTGAC TTCAAGAGCC TCTGGTGTCT CTTTCTGCAA AGGCATCTGA
 ATGTGTCTGC GTCCCTGTTA GCCTAATGTG AGAAGGTGGA GAGACCAGCC CTCCCCCATG
 TCTACCATGA CCCCCTTCCC CATGCTGA*   
>DL;HLA:HLA18602
HLA:HLA18602 S*01:02:01:02 268 bases
 GGCAGAGAAG GAGGTGCTCA GGCTGTGTGC AGTGACAGTG ACCAGGGCTG TGATGTGTCT
 CTCACAGCTT GTAAAGGCCT GAGGCAGCTG TCTTGTGAGG GACTGAGATG CAGTATTTCT
 TCATGCCTCC CCTTTGTGAC TTCAAGAGCC TCTGGTGTCT CTTTCTGCAA AGGCATCTGA
 ATGTGTCTGC GTCCCTGTTA GCCTAATGTG AGAAGGTGGA GAGACCAGCC CTCCCCCATG
 TCTACCATGA CCCCCTTCCC CATGCTGA*   
>DL;HLA:HLA18603
HLA:HLA18603 S*01:02:01:03 268 bases
 GGCAGAGAAG GAGGTGCTCA GGCTGTGTGC AGTGACAGTG ACCAGGGCTG TGATGTGTCT
 CTCACAGCTT GTAAAGGCCT GAGGCAGCTG TCTTGTGAGG GACTGAGATG CAGTATTTCT
 TCATGCCTCC CCTTTGTGAC TTCAAGAGCC TCTGGTGTCT CTTTCTGCAA AGGCATCTGA
 ATGTGTCTGC GTCCCTGTTA GCCTAATGTG AGAAGGTGGA GAGACCAGCC CTCCCCCATG
 TCTACCATGA CCCCCTTCCC CATGCTGA*   
>DL;HLA:HLA18604
HLA:HLA18604 S*01:03 268 bases
 GGCAGAGAAG GAGGTGCTCA GGCTGTGTGC AGTGACAGTG ACCAGGGCTG TGATGTGTCT
 CTCACAGCTT GTAAAGGCCT GAGGCAGCTG TCTTGTGAGG GACTGAGATG CAGGATTTCT
 TCACGCCTCC CCTTTGTGAC TTCAAGAGCC TCTGGTGTCT CTTTCTGCAA AGGCATCTGA
 ATGTGTCTGC GTCCCTGTTA GCCTAATGTG AGAAGGTGGA GAGACCAGCC CTCCCCCATG
 TCTACCATGA CCCCCTTCCC CATGCTGA*   
>DL;HLA:HLA18605
HLA:HLA18605 S*01:04 268 bases
 GGCAGAGAAG GAGGTGCTCA GGCTGTGTGC AGTGACAGTG ACCAGGGCTG TGATGTGTCT
 CTCACAGCTT GTAAAGGCCT GAGGCAGCTG TCTTGTGAGG GACTGAGATG CAGGATTTCT
 TCATGCCTCC CCTTTGTGAC TTCAAGAGCC TCTGGTGTCT CTTTCTGCAA AGGCATCTGA
 ATGTGTCTGC GTCCCTGTTA GCCTAATGTG AGAAGGTGGA GAGACCAGCC CTCCCCCATG
 TCTACCATGA CCCCCTTCCC CATGCTGA*   
