>DL;HLA:HLA16376
HLA:HLA16376 T*01:01:01:01 459 bases
 AATCCCAGAA TACATGTGTG ATCCACTACC CCATCTCGGA CCATGAGGCC GCCCTGAGGT
 GCTGGGTCCC GGGCTTCTAC CATGTGGAAA TCACAGTGAC CCAACTGTGG GATGGGGAGG
 ACCAAATTTA GGACGCAGAG CTTGTGGGGA CCAGACCTGC AGGGTATAGA ACCTTCCAGA
 AGTGGGCAGC TGTGATGCTG TCTTCTAGAG ACAAGTAGAG ATACACATGC CATGTGCAGC
 AGGAGGCACT GCCAGAGCCC CTCACACTGA GATGGGGGCC ATCTTCCCAG CCCACATTCC
 TCATCATGGG CATCGTTACC GTCCTGGTTG TTCTAGGTGC TGTGGTCACT GCTGTGATGT
 GGAAGAATAA GACCCCAGAT GGAAAAGGAG TCAGCTATGC TCAGGCTTCA AACAGGAACA
 GTACCCAGGG CTCTGATGTG TCTCTCAAGT CTTGTAAAA  
>DL;HLA:HLA16377
HLA:HLA16377 T*01:01:01:02 459 bases
 AATCCCAGAA TACATGTGTG ATCCACTACC CCATCTCGGA CCATGAGGCC GCCCTGAGGT
 GCTGGGTCCC GGGCTTCTAC CATGTGGAAA TCACAGTGAC CCAACTGTGG GATGGGGAGG
 ACCAAATTTA GGACGCAGAG CTTGTGGGGA CCAGACCTGC AGGGTATAGA ACCTTCCAGA
 AGTGGGCAGC TGTGATGCTG TCTTCTAGAG ACAAGTAGAG ATACACATGC CATGTGCAGC
 AGGAGGCACT GCCAGAGCCC CTCACACTGA GATGGGGGCC ATCTTCCCAG CCCACATTCC
 TCATCATGGG CATCGTTACC GTCCTGGTTG TTCTAGGTGC TGTGGTCACT GCTGTGATGT
 GGAAGAATAA GACCCCAGAT GGAAAAGGAG TCAGCTATGC TCAGGCTTCA AACAGGAACA
 GTACCCAGGG CTCTGATGTG TCTCTCAAGT CTTGTAAAA  
>DL;HLA:HLA16382
HLA:HLA16382 T*01:01:01:03 459 bases
 AATCCCAGAA TACATGTGTG ATCCACTACC CCATCTCGGA CCATGAGGCC GCCCTGAGGT
 GCTGGGTCCC GGGCTTCTAC CATGTGGAAA TCACAGTGAC CCAACTGTGG GATGGGGAGG
 ACCAAATTTA GGACGCAGAG CTTGTGGGGA CCAGACCTGC AGGGTATAGA ACCTTCCAGA
 AGTGGGCAGC TGTGATGCTG TCTTCTAGAG ACAAGTAGAG ATACACATGC CATGTGCAGC
 AGGAGGCACT GCCAGAGCCC CTCACACTGA GATGGGGGCC ATCTTCCCAG CCCACATTCC
 TCATCATGGG CATCGTTACC GTCCTGGTTG TTCTAGGTGC TGTGGTCACT GCTGTGATGT
 GGAAGAATAA GACCCCAGAT GGAAAAGGAG TCAGCTATGC TCAGGCTTCA AACAGGAACA
 GTACCCAGGG CTCTGATGTG TCTCTCAAGT CTTGTAAAA  
>DL;HLA:HLA16375
HLA:HLA16375 T*01:01:01:04 459 bases
 AATCCCAGAA TACATGTGTG ATCCACTACC CCATCTCGGA CCATGAGGCC GCCCTGAGGT
 GCTGGGTCCC GGGCTTCTAC CATGTGGAAA TCACAGTGAC CCAACTGTGG GATGGGGAGG
 ACCAAATTTA GGACGCAGAG CTTGTGGGGA CCAGACCTGC AGGGTATAGA ACCTTCCAGA
 AGTGGGCAGC TGTGATGCTG TCTTCTAGAG ACAAGTAGAG ATACACATGC CATGTGCAGC
 AGGAGGCACT GCCAGAGCTC CTCACACTGA GATGGGGGCC ATCTTCCCAG CCCACATTCC
 TCATCATGGG CATCGTTACC GTCCTGGTTG TTCTAGGTGC TGTGGTCACT GCTGTGATGT
 GGAAGAATAA GACCCCAGAT GGAAAAGGAG TCAGCTATGC TCAGGCTTCA AACAGGAACA
 GTACCCAGGG CTCTGATGTG TCTCTCAAGT CTTGTAAAA  
>DL;HLA:HLA16378
HLA:HLA16378 T*01:01:01:05 459 bases
 AATCCCAGAA TACATGTGTG ATCCACTACC CCATCTCGGA CCATGAGGCC GCCCTGAGGT
 GCTGGGTCCT GGGCTTCTAC CATGTGGAAA TCACAGTGAC CCAACTGTGG GATGGGGAGG
 ACCAAATTTA GGACGCAGAG CTTGTGGGGA CCAGACCTGC AGGGTATAGA ACCTTCCAGA
 AGTGGGCAGC TGTGATGCTG TCTTCTAGAG ACAAGTAGAG ATACACATGC CATGTGCAGC
 AGGAGGCACT GCCAGAGCCC CTCACACTGA GATGGGGGCC ATCTTCCCAG CCCACATTCC
 TCATCATGGG CATCGTTACC GTCCTGGTTG TTCTAGGTGC TGTGGTCACT GCTGTGATGT
 GGAAGAATAA GACCCCAGAT GGAAAAGGAG TCAGCTATGC TCAGGCTTCA AACAGGAACA
 GTACCCAGGG CTCTGATGTG TCTCTCAAGT CTTGTAAAA  
>DL;HLA:HLA16380
HLA:HLA16380 T*02:01:01:01 459 bases
 AATCCCAGAA TGCATGTGTG ATCCACTACC CCATCTCAGA CCATGAGGCC GCCCTGAGGT
 GCTGGGTCCC GGGCTTCTAC CATGTGGAAA TCACAGTGAC CCAACTGTGG GATGGGGAGG
 ACCAAATTTA GGACGCAGAG CTTGTGGGGA CCAGACCTGC AGGGTATAGA ACCTTCCAGA
 AGTGGGCAGC TGTGGTGCTG TCTTCTAGAG ACAAGTAGAG ATACACATGC CATGTGCAGC
 AGGAGGCACT GCCAGAGCCC CTCACACTGA GATGGGGGCC ATCTTCCCAG CCCACATTCC
 TCATCATGGG CATCGTTACC GTCCTGGTTG TTCTAGGTGC TGTGGTCACT GCTGTGATGT
 GGAAGAATAA GACCCCAGAT GGAAAAGGAG TCAGCTATGC TCAGGCTTCA AACAGGAACA
 GTACCCAGGG CTCTGATGTG TCTCTCAAGT CTTGTAAAA  
>DL;HLA:HLA16379
HLA:HLA16379 T*02:01:01:02 459 bases
 AATCCCAGAA TGCATGTGTG ATCCACTACC CCATCTCGGA CCATGAGGCC GCCCTGAGGT
 GCTGGGTCCC GGGCTTCTAC CATGTGGAAA TCACAGTGAC CCAACTGTGG GATGGGGAGG
 ACCAAATTTA GGACGCAGAG CTTGTGGGGA CCAGACCTGC AGGGTATAGA ACCTTCCAGA
 AGTGGGCAGC TGTGGTGCTG TCTTCTAGAG ACAAGTAGAG ATCCACATGC CATGTGCAGC
 AGGAGGCACT GCCAGAGCCC CTCACACTGA GATGGGGGCC ATCTTCCCAG CCCACATTCC
 TCATCATGGG CATCGTTACC GTCCTGGTTG TTCTAGGTGC TGTGGTCACT GCTGTGATGT
 GGAAGAATAA GACCCCAGAT GGAAAAGGAG TCAGCTATGC TCAGGCTTCA AACAGGAACA
 GTACCCAGGG CTCTGATGTG TCTCTCAAGT CTTGTAAAA  
>DL;HLA:HLA16381
HLA:HLA16381 T*03:01:01:01 459 bases
 AATCCCAGAA TACATGTGGG ATCCACTACC CCATCTCGGA CCATGAGGCC ACCCTGAGGT
 GCTGGGTCCC GGGCTTCTAC CATGTGGAAA TCACAGTGAC CCAACTGTGG GATGGGGAGG
 ACCAAATTTA GGACACAGAG CTTGTGGGGA CCAGACCTGC AGGGTATAGA ACCTTCCAGA
 AGTGGGCAGC TGTGGTGCTG TCTTCTAGAG ACAAGTAGAG ATACACATGC CATGTGCAGC
 AGGAGGCACT GCCAGAGCCC CTCACACTGA GATGGGGGCC ATCTTCCCAG CCCACATTCC
 CCATCGTGGG CATTGTTACT GTCCTGGTTG TTCTAGGTGC TGTGGTCACT GCTGTGATGT
 GGAAGAATAA GACCCCAGAT GGAAAAGGAG TCAGCTATGC TCAGGCTTCA AACAGGAACA
 GTACCCAGGG CTCTGATGTG TCTCTCAAGT CTTGTAAAA  
>DL;HLA:HLA38950
HLA:HLA38950 T*03:01:01:02 459 bases
 AATCCCAGAA TACATGTGGG ATCCACTACC CCATCTCGGA CCATGAGGCC ACCCTGAGGT
 GCTGGGTCCC GGGCTTCTAC CATGTGGAAA TCACAGTGAC CCAACTGTGG GATGGGGAGG
 ACCAAATTTA GGACACAGAG CTTGTGGGGA CCAGACCTGC AGGGTATAGA ACCTTCCAGA
 AGTGGGCAGC TGTGGTGCTG TCTTCTAGAG ACAAGTAGAG ATACACATGC CATGTGCAGC
 AGGAGGCACT GCCAGAGCCC CTCACACTGA GATGGGGGCC ATCTTCCCAG CCCACATTCC
 CCATCGTGGG CATTGTTACT GTCCTGGTTG TTCTAGGTGC TGTGGTCACT GCTGTGATGT
 GGAAGAATAA GACCCCAGAT GGAAAAGGAG TCAGCTATGC TCAGGCTTCA AACAGGAACA
 GTACCCAGGG CTCTGATGTG TCTCTCAAGT CTTGTAAAA  
