>P1;HLA:HLA16376
HLA:HLA16376 T*01:01:01:01 5 bases
 MMMMM*     
>P1;HLA:HLA16377
HLA:HLA16377 T*01:01:01:02 6 bases
 NPRIHV*     
>P1;HLA:HLA16382
HLA:HLA16382 T*01:01:01:03 6 bases
 NPRIHV*     
>P1;HLA:HLA16375
HLA:HLA16375 T*01:01:01:04 6 bases
 NPRIHV*     
>P1;HLA:HLA16378
HLA:HLA16378 T*01:01:01:05 6 bases
 NPRIHV*     
>P1;HLA:HLA16380
HLA:HLA16380 T*02:01:01:01 6 bases
 NPRMHV*     
>P1;HLA:HLA16379
HLA:HLA16379 T*02:01:01:02 6 bases
 NPRMHV*     
>P1;HLA:HLA16381
HLA:HLA16381 T*03:01 18 bases
 NPRIHVGSTT PSRTMRPP*    
>P1;HLA:HLA00953
HLA:HLA00953 TAP1*01:01:01:01 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLITLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVDEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA06627
HLA:HLA06627 TAP1*01:01:01:02 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLITLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVDEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA06628
HLA:HLA06628 TAP1*01:01:01:03 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLITLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVDEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA06629
HLA:HLA06629 TAP1*01:01:01:04 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLITLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVDEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA06631
HLA:HLA06631 TAP1*01:01:01:05 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLITLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVDEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA00954
HLA:HLA00954 TAP1*01:02N 228 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG RWPFHSLRAA SLTGFYKMAQ PIPSLETX* 
>P1;HLA:HLA00955
HLA:HLA00955 TAP1*02:01:01 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLVTLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVGEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA00956
HLA:HLA00956 TAP1*02:01:02 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLVTLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVGEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA00957
HLA:HLA00957 TAP1*03:01 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLVTLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVDEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA00958
HLA:HLA00958 TAP1*04:01 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLVTLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQALEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVGEAG SQLSGGQQQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA01890
HLA:HLA01890 TAP1*05:01 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL PHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLVTLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEV LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDILV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVGEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA06630
HLA:HLA06630 TAP1*06:01 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATG GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLITLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVDEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA00959
HLA:HLA00959 TAP2*01:01:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA06625
HLA:HLA06625 TAP2*01:01:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA06636
HLA:HLA06636 TAP2*01:01:03:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA06637
HLA:HLA06637 TAP2*01:01:03:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA06640
HLA:HLA06640 TAP2*01:01:03:03 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA00960
HLA:HLA00960 TAP2*01:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNITYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA00961
HLA:HLA00961 TAP2*01:03 622 bases
 LLLPLCLATP LTVSLRALVA GASRAPPARV ASAPWSWLLV GYGAAGLSWS LWAVLSPPGA
 QEKEQDQVNN KVLMWRLLKL SRPDLPLLVA AFFFLVLAVL GETLIPHYSG RVIDILGGDF
 DPHAFASAIF FMCLFSFGSS LSAGCRGGCF TYTMSRINLR IREQLFSSLL RQDLGFFQET
 KTGELNSRLS SDTTLMSNWL PLNANVLLRS LVKVVGLYGF MLSISPRLTL LSLLHMPFTI
 AAEKVYNTRH QEVLREIQDA VARAGQVVRE AVGGLQTVRS FGAEEHEVCR YKEALEQCRQ
 LYWRRDLERA LYLLVRRVLH LGVQMLMLSC GLQQMQDGEL TQGSLLSFMI YQESVGSYVQ
 TLVYIYGDML SNVGAAEKVF SYMDRQPNLP SPGTLAPTTL QGVVKFQDVS FAYPNRPDRP
 VLKGLTFTLR PGEVTALVGP NGSGKSTVAA LLQNLYQPTG GQVLLDEKPI SQYEHCYLHS
 QVVSVGQEPV LFSGSVRNNI AYGLQSCEDD KVMAAAQAAH ADDFIQEMEH GIYTDVGEKG
 SQLAAGQKQR LAIARALVRD PRVLILDEAT SALDVQCEQA LQDWNSCGDR TVLVIAHRLQ
 TVQRAHQILV LQEGKLQKLA QL*   
>P1;HLA:HLA06641
HLA:HLA06641 TAP2*01:04 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNITYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA00962
HLA:HLA00962 TAP2*02:01:01 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX* 
>P1;HLA:HLA06635
HLA:HLA06635 TAP2*02:01:02:01 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX* 
>P1;HLA:HLA06638
HLA:HLA06638 TAP2*02:01:02:02 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX* 
>P1;HLA:HLA06639
HLA:HLA06639 TAP2*02:01:02:03 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX* 
