>P1;HLA:HLA00953
HLA:HLA00953 TAP1*01:01 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLITLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVDEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA00954
HLA:HLA00954 TAP1*01:02N 228 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG RWPFHSLRAA SLTGFYKMAQ PIPSLETX* 
>P1;HLA:HLA00955
HLA:HLA00955 TAP1*02:01:01 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLVTLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVGEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA00956
HLA:HLA00956 TAP1*02:01:02 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLVTLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVGEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA00957
HLA:HLA00957 TAP1*03:01 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLVTLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVDEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA00958
HLA:HLA00958 TAP1*04:01 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL LHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLVTLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEA LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQALEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDVLV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVGEAG SQLSGGQQQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
>P1;HLA:HLA01890
HLA:HLA01890 TAP1*05:01 748 bases
 MASSRCPAPR GCRCLPGASL AWLGTVLLLL ADWVLLRTAL PRIFSLLVPT ALPLLRVWAV
 GLSRWAVLWL GACGVLRATV GSKSENAGAQ GWLAALKPLA AALGLALPGL ALFRELISWG
 APGSADSTRL PHWGSHPTAF VVSYAAALPA AALWHKLGSL WVPGGQGGSG NPVRRLLGCL
 GSETRRLSLF LVLVVLSSLG EMAIPFFTGR LTDWILQDGS ADTFTRNLTL MSILTIASAV
 LEFVGDGIYN NTMGHVHSHL QGEVFGAVLR QETEFFQQNQ TGNIMSRVTE DTSTLSDSLS
 ENLSLFLWYL VRGLCLLGIM LWGSVSLTMV TLVTLPLLFL LPKKVGKWYQ LLEVQVRESL
 AKSSQVAIEV LSAMPTVRSF ANEEGEAQKF REKLQEIKTL NQKEAVAYAV NSWTTSISGM
 LLKVGILYIG GQLVTSGAVS SGNLVTFVLY QMQFTQAVEV LLSIYPRVQK AVGSSEKIFE
 YLDRTPRCPP SGLLTPLHLE GLVQFQDVSF AYPNRPDILV LQGLTFTLRP GEVTALVGPN
 GSGKSTVAAL LQNLYQPTGG QLLLDGKPLP QYEHRYLHRQ VAAVGQEPQV FGRSLQENIA
 YGLTQKPTME EITAAAVKSG AHSFISGLPQ GYDTEVGEAG SQLSGGQRQA VALARALIRK
 PCVLILDDAT SALDANSQLQ VEQLLYESPE RYSRSVLLIT QHLSLVEQAD HILFLEGGAI
 REGGTHQQLM EKKGCYWAMV QAPADAPE*   
