>P1;HLA:HLA00959
HLA:HLA00959 TAP2*01:01:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA06625
HLA:HLA06625 TAP2*01:01:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA06636
HLA:HLA06636 TAP2*01:01:03:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA06637
HLA:HLA06637 TAP2*01:01:03:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA06640
HLA:HLA06640 TAP2*01:01:03:03 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA00960
HLA:HLA00960 TAP2*01:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNITYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA00961
HLA:HLA00961 TAP2*01:03 622 bases
 LLLPLCLATP LTVSLRALVA GASRAPPARV ASAPWSWLLV GYGAAGLSWS LWAVLSPPGA
 QEKEQDQVNN KVLMWRLLKL SRPDLPLLVA AFFFLVLAVL GETLIPHYSG RVIDILGGDF
 DPHAFASAIF FMCLFSFGSS LSAGCRGGCF TYTMSRINLR IREQLFSSLL RQDLGFFQET
 KTGELNSRLS SDTTLMSNWL PLNANVLLRS LVKVVGLYGF MLSISPRLTL LSLLHMPFTI
 AAEKVYNTRH QEVLREIQDA VARAGQVVRE AVGGLQTVRS FGAEEHEVCR YKEALEQCRQ
 LYWRRDLERA LYLLVRRVLH LGVQMLMLSC GLQQMQDGEL TQGSLLSFMI YQESVGSYVQ
 TLVYIYGDML SNVGAAEKVF SYMDRQPNLP SPGTLAPTTL QGVVKFQDVS FAYPNRPDRP
 VLKGLTFTLR PGEVTALVGP NGSGKSTVAA LLQNLYQPTG GQVLLDEKPI SQYEHCYLHS
 QVVSVGQEPV LFSGSVRNNI AYGLQSCEDD KVMAAAQAAH ADDFIQEMEH GIYTDVGEKG
 SQLAAGQKQR LAIARALVRD PRVLILDEAT SALDVQCEQA LQDWNSCGDR TVLVIAHRLQ
 TVQRAHQILV LQEGKLQKLA QL*   
>P1;HLA:HLA06641
HLA:HLA06641 TAP2*01:04 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNITYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL*   
>P1;HLA:HLA00962
HLA:HLA00962 TAP2*02:01:01 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX* 
>P1;HLA:HLA06635
HLA:HLA06635 TAP2*02:01:02:01 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX* 
>P1;HLA:HLA06638
HLA:HLA06638 TAP2*02:01:02:02 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX* 
>P1;HLA:HLA06639
HLA:HLA06639 TAP2*02:01:02:03 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX* 
