>P1;HLA:HLA00959
HLA:HLA00959 TAP2*01:01:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA06625
HLA:HLA06625 TAP2*01:01:02:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38400
HLA:HLA38400 TAP2*01:01:02:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA06636
HLA:HLA06636 TAP2*01:01:03:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA06637
HLA:HLA06637 TAP2*01:01:03:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA06640
HLA:HLA06640 TAP2*01:01:03:03 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37936
HLA:HLA37936 TAP2*01:01:03:04 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37935
HLA:HLA37935 TAP2*01:01:03:05 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38020
HLA:HLA38020 TAP2*01:01:03:06 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38038
HLA:HLA38038 TAP2*01:01:03:07 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38018
HLA:HLA38018 TAP2*01:01:03:08 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37951
HLA:HLA37951 TAP2*01:01:03:09 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37953
HLA:HLA37953 TAP2*01:01:03:10 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38050
HLA:HLA38050 TAP2*01:01:03:11 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38017
HLA:HLA38017 TAP2*01:01:03:12 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38284
HLA:HLA38284 TAP2*01:01:03:13 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38236
HLA:HLA38236 TAP2*01:01:03:14 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38220
HLA:HLA38220 TAP2*01:01:03:15 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38456
HLA:HLA38456 TAP2*01:01:03:16 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38488
HLA:HLA38488 TAP2*01:01:03:17 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38490
HLA:HLA38490 TAP2*01:01:03:18 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38283
HLA:HLA38283 TAP2*01:01:03:19 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38374
HLA:HLA38374 TAP2*01:01:03:20 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38703
HLA:HLA38703 TAP2*01:01:03:21 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38072
HLA:HLA38072 TAP2*01:01:04 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37952
HLA:HLA37952 TAP2*01:01:05:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38012
HLA:HLA38012 TAP2*01:01:05:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38016
HLA:HLA38016 TAP2*01:01:05:03 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37997
HLA:HLA37997 TAP2*01:01:05:04 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37962
HLA:HLA37962 TAP2*01:01:05:05 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38262
HLA:HLA38262 TAP2*01:01:05:06 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38192
HLA:HLA38192 TAP2*01:01:05:07 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38140
HLA:HLA38140 TAP2*01:01:05:08 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38487
HLA:HLA38487 TAP2*01:01:05:09 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38320
HLA:HLA38320 TAP2*01:01:05:10 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38307
HLA:HLA38307 TAP2*01:01:05:11 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38432
HLA:HLA38432 TAP2*01:01:05:12 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38023
HLA:HLA38023 TAP2*01:01:06 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38011
HLA:HLA38011 TAP2*01:01:07:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38022
HLA:HLA38022 TAP2*01:01:07:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38052
HLA:HLA38052 TAP2*01:01:07:03 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38037
HLA:HLA38037 TAP2*01:01:07:04 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38045
HLA:HLA38045 TAP2*01:01:07:05 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38190
HLA:HLA38190 TAP2*01:01:07:06 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38259
HLA:HLA38259 TAP2*01:01:07:07 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38111
HLA:HLA38111 TAP2*01:01:07:08 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38158
HLA:HLA38158 TAP2*01:01:07:09 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38256
HLA:HLA38256 TAP2*01:01:07:10 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38390
HLA:HLA38390 TAP2*01:01:07:11 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38651
HLA:HLA38651 TAP2*01:01:07:12 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38391
HLA:HLA38391 TAP2*01:01:08 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA00960
HLA:HLA00960 TAP2*01:02:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNITYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38255
HLA:HLA38255 TAP2*01:02:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNITYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA00961
HLA:HLA00961 TAP2*01:03:01 622 bases
 LLLPLCLATP LTVSLRALVA GASRAPPARV ASAPWSWLLV GYGAAGLSWS LWAVLSPPGA
 QEKEQDQVNN KVLMWRLLKL SRPDLPLLVA AFFFLVLAVL GETLIPHYSG RVIDILGGDF
 DPHAFASAIF FMCLFSFGSS LSAGCRGGCF TYTMSRINLR IREQLFSSLL RQDLGFFQET
 KTGELNSRLS SDTTLMSNWL PLNANVLLRS LVKVVGLYGF MLSISPRLTL LSLLHMPFTI
 AAEKVYNTRH QEVLREIQDA VARAGQVVRE AVGGLQTVRS FGAEEHEVCR YKEALEQCRQ
 LYWRRDLERA LYLLVRRVLH LGVQMLMLSC GLQQMQDGEL TQGSLLSFMI YQESVGSYVQ
 TLVYIYGDML SNVGAAEKVF SYMDRQPNLP SPGTLAPTTL QGVVKFQDVS FAYPNRPDRP
 VLKGLTFTLR PGEVTALVGP NGSGKSTVAA LLQNLYQPTG GQVLLDEKPI SQYEHCYLHS
 QVVSVGQEPV LFSGSVRNNI AYGLQSCEDD KVMAAAQAAH ADDFIQEMEH GIYTDVGEKG
 SQLAAGQKQR LAIARALVRD PRVLILDEAT SALDVQCEQA LQDWNSCGDR TVLVIAHRLQ
 TVQRAHQILV LQEGKLQKLA QL   
>P1;HLA:HLA37998
HLA:HLA37998 TAP2*01:03:02:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS CGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38024
HLA:HLA38024 TAP2*01:03:02:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS CGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37947
HLA:HLA37947 TAP2*01:03:02:03 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS CGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37979
HLA:HLA37979 TAP2*01:03:02:04 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS CGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37946
HLA:HLA37946 TAP2*01:03:02:05 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS CGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38592
HLA:HLA38592 TAP2*01:03:02:06 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS CGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38527
HLA:HLA38527 TAP2*01:03:02:07 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS CGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38580
HLA:HLA38580 TAP2*01:03:02:08 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS CGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38661
HLA:HLA38661 TAP2*01:03:03 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS CGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38568
HLA:HLA38568 TAP2*01:03:04 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS CGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA06641
HLA:HLA06641 TAP2*01:04:01:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNITYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38019
HLA:HLA38019 TAP2*01:04:01:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNITYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37937
HLA:HLA37937 TAP2*01:04:01:03 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNITYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38281
HLA:HLA38281 TAP2*01:04:01:04 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNITYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37989
HLA:HLA37989 TAP2*01:05:01:01 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38043
HLA:HLA38043 TAP2*01:05:01:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38039
HLA:HLA38039 TAP2*01:05:01:03 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38049
HLA:HLA38049 TAP2*01:05:01:04 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38010
HLA:HLA38010 TAP2*01:05:01:05 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA37963
HLA:HLA37963 TAP2*01:05:01:06 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38211
HLA:HLA38211 TAP2*01:05:01:07 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38219
HLA:HLA38219 TAP2*01:05:01:08 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38202
HLA:HLA38202 TAP2*01:05:01:09 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38193
HLA:HLA38193 TAP2*01:05:01:10 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38234
HLA:HLA38234 TAP2*01:05:01:11 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38212
HLA:HLA38212 TAP2*01:05:01:12 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38164
HLA:HLA38164 TAP2*01:05:01:13 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38423
HLA:HLA38423 TAP2*01:05:01:14 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38459
HLA:HLA38459 TAP2*01:05:02 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38464
HLA:HLA38464 TAP2*01:06 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLMR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38139
HLA:HLA38139 TAP2*01:07 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNITYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS CGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA38516
HLA:HLA38516 TAP2*01:08 686 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLSANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQTVQRAH QILVLQEGKL QKLAQL   
>P1;HLA:HLA00962
HLA:HLA00962 TAP2*02:01:01 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA06635
HLA:HLA06635 TAP2*02:01:02:01 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA06638
HLA:HLA06638 TAP2*02:01:02:02 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA06639
HLA:HLA06639 TAP2*02:01:02:03 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA37964
HLA:HLA37964 TAP2*02:01:02:04 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38335
HLA:HLA38335 TAP2*02:01:02:05 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38315
HLA:HLA38315 TAP2*02:01:02:06 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38431
HLA:HLA38431 TAP2*02:01:02:07 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38026
HLA:HLA38026 TAP2*02:01:03:01 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA37975
HLA:HLA37975 TAP2*02:01:03:02 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38044
HLA:HLA38044 TAP2*02:01:03:03 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38082
HLA:HLA38082 TAP2*02:01:03:04 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38399
HLA:HLA38399 TAP2*02:01:03:05 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38306
HLA:HLA38306 TAP2*02:01:03:06 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38455
HLA:HLA38455 TAP2*02:01:03:07 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38075
HLA:HLA38075 TAP2*02:01:04 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38025
HLA:HLA38025 TAP2*02:02 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTHHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38029
HLA:HLA38029 TAP2*02:03 704 bases
 MRLPDLRPWT SLLLADAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38159
HLA:HLA38159 TAP2*02:04 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLVR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAVG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
>P1;HLA:HLA38463
HLA:HLA38463 TAP2*02:05 704 bases
 MRLPDLRPWT SLLLVDAALL WLLQGPLGTL LPQGLPGLWL EGTLRLGGLW GLLKLRGLLG
 FVGTLLLPLC LATPLTVSLR ALVAGASRAP PARVASAPWS WLLVGYGAAG LSWSLWAVLS
 PPGAQEKEQD QVNNKVLMWR LLKLSRPDLP LLVAAFFFLV LAVLGETLIP HYSGRVIDIL
 GGDFDPHAFA SAIFFMCLFS FGSSLSAGCR GGCFTYTMSR INLRIREQLF SSLLRQDLGF
 FQETKTGELN SRLSSDTTLM SNWLPLNANV LLRSLVKVVG LYGFMLSISP RLTLLSLLHM
 PFTIAAEKVY NTRHQEVLRE IQDAVARAGQ VVREAVGGLQ TVRSFGAEEH EVCRYKEALE
 QCRQLYWRRD LERALYLLIR RVLHLGVQML MLSCGLQQMQ DGELTQGSLL SFMIYQESVG
 SYVQTLVYIY GDMLSNVGAA EKVFSYMDRQ PNLPSPGTLA PTTLQGVVKF QDVSFAYPNR
 PDRPVLKGLT FTLRPGEVTA LVGPNGSGKS TVAALLQNLY QPTGGQVLLD EKPISQYEHC
 YLHSQVVSVG QEPVLFSGSV RNNIAYGLQS CEDDKVMAAA QAAHADDFIQ EMEHGIYTDV
 GEKGSQLAAG QKQRLAIARA LVRDPRVLIL DEATSALDVQ CEQALQDWNS RGDRTVLVIA
 HRLQAVQRAH QILVLQEGKL QKLAQLQEGQ DLYSRLVQQR LMDX 
