>DL;HLA:HLA18591
HLA:HLA18591 U*01:01:01:01 546 bases
 AATCCTGTCC TGGTTATCTC CCCATTCTCT GTAAAAACGA TTCTCTGTAA AAAGATTACA
 TCGCCCTAAA CGAGGACCTG AGCTCTTGGA CCGCGGCGGC CATGGCGGCT CAGATTACCC
 AGCGCAAGTG GGAGGCGGCC CATGAGGCGG AGCAGCAGAG AGCCTACCTG GAGGGCACGT
 GCGTGGAGTG GCTCCGCAGA TACCTGGAGA ACGGGAAGGA GACGCTGCAG CGCACTGGTA
 CCAGGGGCCA CGGGGCGCCT CCCTGATCGC CTGTAGATCT CCCAGGCTGG CCTCCCACAA
 GGAGAGGAGA CAGATGGGAC CAACACTAGA ATATCACCCT CCCTCTGGTC CTGAGGGAGA
 AGAATCCTCC TGGGTTTCCA GATCCTGTAC CAGAGAGTGA CTCTGAGGTT CCACCCTGCT
 CTCTGACATA ATTAAGGGAT AAAATCTCTG AGGGAATGAC GGGAAGACGA TCCCTCATTT
 AGTGATCCCA AGTCACTAAA TTTGGGAGTA GTTTGTTACA CAGCAATGGA TAACTAATGA
 AGCCCT     
>DL;HLA:HLA18592
HLA:HLA18592 U*01:01:01:02 587 bases
 AATCCTGTCC TGGTTATCTC CCCATTCTCT GTAAAAACGA TTCTCTGTAA AAAGATTACA
 TCGCCCTAAA CGAGGACCTG AGCTCTTGGA CCGCGGCGGC CATGGCGGCT CAGATTACCC
 AGCGCAAGTG GGAGGCGGCC CATGAGGCGG AGCAGCAGAG AGCCTACCTG GAGGGCACGT
 GCGTGGAGTG GCTCCGCAGA TACCTGGAGA ACGGGAAGGA GACGCTGCAG CGCACTGGTA
 CCAGGGGCCA CGGGGCGCCT CCCTGATCGC CTGTAGATCT CCCAGGCTGG CCTCCCACAA
 GGAGAGGAGA CAGATGGGAC CAACACTAGA ATATCACCCT CCCTCTGGTC CTGAGGGAGA
 AGAATCCTCC TGGGTTTCCA GATCCTGTAC CAGAGAGTGA CTCTGAGGTT CCACCCTGCT
 CTCTGACACA ATTAAGGGAT AAAATCTCTG AGGCAATGAC GGGAAGACGC AATTAAGGGA
 TAAAATCTCT GAGGGAATGA CGGGAAGAAG ATCCCTCATT TAGTGATCCC AAGTCACTAA
 ATTTGGGGGT AGTTTGTTAC ACAGCAATGG ATAACTAATG AAGCCCT 
>DL;HLA:HLA18593
HLA:HLA18593 U*01:02 586 bases
 AATCCTGTCC TGGTTATCTC CCCATTCTCT GTAAAAACGA TTCTCTGTAA AAAGATTACA
 TCGCCCTAAA CGAGGACCTG AGCTCTTGGA CCGCGGCGGC CATGGCGGCT CAGATTACCC
 AGCGCAAGTG GGAGGCGGCC CATGAGGCGG AGCAGCAGAG AGCCTACCTA GAGGGCACGT
 GCGAGGAGTG GCTCCGCAGA TACCTGGAGA ACAGGAAGGA GACGCTGCAG CGCACTGTAC
 CAGGGGCCAC GGGGCGCCTC CCTGATCGCC TGTAGATCTC GCAGGCTGGC CTCCCACAAG
 GAGAGGAGAC AGATGGGACC AACACTAGAA TATCACCCTC CCTCTGGTCC TGAGGGAGAA
 GAATCCTCCT GGGTTTCCAG ATCCTGTACC AGAGAGTGAC TCTGAGGTTC CACCCTGCTC
 TCTGACACAA TTAAGGGATA AAATCTCTGA GGCAATGACG GGAAGACGCA ATTAAGGGAT
 AAAATCTCTG AGGGAATGAC GGGAAGACGA TCCCTCATTT AGTGATCCCA AGTCACTAAA
 TTTGGGGGTA GTTTGTTACA CAGCAATGGA TAACTAATGA AGCCCT 
>DL;HLA:HLA18594
HLA:HLA18594 U*01:03 732 bases
 AATCCTGTCC TGGTTATCTC CCCATTCTCT GTAAAAAGGA TTCTCTGTAA AAAGATTACA
 TCGCCCTAAA GGAGGACCTG AGCTCTTGGA CCGCGGCGGC CATGGCGGCT CAGATTACCC
 AGCGCAAGTG GGAGGCGGCC CATGAGGCGG AGCAGCAGAG AGCCTACCTG GAGGGCACGT
 GCGTGGAGTG GCTCCGCAGA TACCTGGAGA ACAGGAAGGA GATGCTGCAG CGCACTGGTA
 CCAGGGGCCA CGGGGCGCCT CCCTGATCGC CTGTAGATCT CCCGGGCTGG CCTCCCACAA
 GGAGGGGAGA CAGATGGGAC CAACACTAGA ATATCACCCT CCCTCTGGTC CTGAGGGAGA
 AGAATCCTCC TGGGTTTCCA GATCCTGTAC CAGAGAGTGA CTCTGAGGTT CCACCCTGCT
 CTCTGACACA ATTAAGGGAT AAAATCTCTG AGGCAATGAC GGGAAGACGC AATTAAGGGA
 TAAAATCTCT GAGGGAATGA CTGGAAGACG ATCCCTCATT TAGTGATCCC AAGTCACTAA
 ATTTGGGGGT AGTTTGTTAC ACAGCAATGG ATAACTAATG AAGCCCTCTT ACATTTCCAT
 TATTCTCTAG AGGTTAACTA CATCTGTTTT ATTTTCTCCT ATTTTGATAA TATTAGCCAC
 ACATAGGTTT CTAGTTTCTC AACACCTATT CTTTTCTTTA TTTTAGTTTC TTTTCTCCTT
 TGTTCCATCC TT    
>DL;HLA:HLA18595
HLA:HLA18595 U*01:04 730 bases
 AATCCTGTCC TGGTTATCTC CCCATTCTCT GTAAAAAGGA TTCTCTGTAA AAAGATTACA
 TCGCCCTAAA CCAGGACCTG AGCTCTTGGA CTGCGGCGGC CATGGCGGCT CAGATTACCC
 AGCGCAAGTG GGAGGCGGCC CATGAGGCGG AGCAGCAGAC AGCCTACCTG GAGGGCAGGT
 GCGTGGAGTG GCTCCGCAGA TACCTGGAGA ACAGGAAGGA GACACTGCAG CACACCTGTA
 CCAGGGACCA CGGGCGCCTC CCTGATCGCC TGTAATCTCC CGGGCTGGCC TCCCACAAGG
 ATGGGAGACA GATGGGACCA ACACTAGAAT ATCACCCTCC CTCTGGTCCT GAGGGAGAAG
 AATCCTCCTC AGTTTCCAGA TCCTGTACCA GAGAGTGACT CTGAGGTTCC ACACTGCTCT
 CTGACACAAT TAAGGGATAA AATCTCTGAG GCAATGACGG GAAGACGCAA TTAAGGGATA
 AAATCTCTGA GGGAATGACG GGAACACGAT CCCTCATTTA GTGATCCCAA GTCACTAAAT
 TTGGGAGTAG TTTGTTACAC AGCAATGGAT AACTAATGAA GCCCTCTTAC ATTTCCATTA
 TTCTCTAGAG GTTAACTACA TCTGTTTTAT TTTCTCCTAT TTTGATAATA TTAGCCACAC
 ATAGGTTTCT AGTTTCTCAA CACCTATTCT TTTCTTTATT TTAGTTTCTT TTCTCCTTTG
 TTCCATCCTT     
>DL;HLA:HLA38928
HLA:HLA38928 U*01:05 730 bases
 AATCCTGTCC TGGTTATCTC CCCATTCTCT GTAAAAAGGA TTCTCTGTAA AAAGATTACA
 TCGCCCTAAA CGAGGACCTG AGCTCTTGGA CCGCGGCGGC CATGGCGGCT CAGATTACCC
 AGCGCAAGTG GGAGGCGGCC CATGAGGCGG AGCAGCAGAC AGCCTACCTG GAGGGCAGGT
 GCGTGGAGTG GCTCCGCAGA TACCTGGAGA ACAGGAAGGA GACGCTGCAG CACACCTGTA
 CCAGGGACCA CGGGCGCCTC CCTGATCGCC TGTAATCTCC CGGGCTGGCC TCCCACAAGG
 ATGGGAGACA GATGGGACCA ACACTAGAAT ATCACCCTCC TTCTGGTCCT GAGGGAGAAG
 AATCCTCCTG AGTTTCCAGA TCCTGTACCA GAGAGTGACT CTGAGGTTCC ACCCTGCTCT
 CTGACACAAT TAAGGGATAA AATCTCTGAG GCAATGACGG GAAGATGCAA TTAAGGGATA
 AAATCTCTGA GGGAATGACG GGAACACGAT CCCTCATTTA GTGATCCCAA GTCACTAAAT
 TTGGGAGTAG TTTGTTACAC AGCAATGGAT AACTAATGAA GCCCTCTTAC ATTTCCATTA
 TTCTCTAGAG GTTAACTACA TCTGTTTTAT TTTCTCCTAT TTTGATAATA TTAGCCACAC
 AGAGGTTTCT AGTTTCTCAA CACCTATTCT TTTCTTTATT TTAGTTTCTT TTCTCCTTTG
 TTCCATCCTT     
>DL;HLA:HLA38929
HLA:HLA38929 U*01:06 732 bases
 AATCCTGTCC TGGTTATCTC CCCATTCTCT GTAAAAACGA TTCTCTGTAA AAAGATTACA
 TCGCCCTAAA CGAGGACCTG AGCTCTTGGA CCGCGGCGGC CATGGCGGCT CAGATTACCC
 AGCGCAAGTG GGAGGCGGCC CATGAGGCGG AGCAGCAGAC AGCCTACCTG GAGGGCACGT
 GCGTGGAGAG GCTCCGCAGA TACCTGGAGA ACGGGAAGGA GACACTGCAG CGCACTGGTA
 CCAGGAGCCA CGGGGCGCCT CCCTGATCGC CTGTAGATCT CCCGGGCTGG CCTCCCACAA
 GGAGAGGAGA CAGATGGGAC CAACACTAGA ATATCACCCT CCCTCTGGTC CTGAGGGAGA
 AGAATCCTCC TGGGTTTCCA GATCCTGTAC CAGAGAGTGA CTCTGAGGTT CCACACTGCT
 CTCTGACACA ATTAAGGGAT AAAATCTCTG AGGCAATGAC GGGAAGACTC AATTAAGGGA
 TAAAATCTCT GAGGGAATGA CTGGAAGGTG ATCCCTCATT TAGTGATCCC AAGTCACTAA
 ATTTGGGGGT AGTTTGTTAC ACAGCAATGG ATAACTAATG AAGCCCTCTT ACATTTCCAT
 TATTCTCTAG AGGTTAACTA CATTTGTTTT ATTTTCTCCT ATTTTGATAA TATTAGCCAC
 ACATAGGTTT CTAGTTTCTC AACACCTATT CTTTTCTTTA TTTTAGTTTC TTTTCTCCTT
 TGTTCCATCC TT    
