>DL;HLA:HLA18591
HLA:HLA18591 U*01:01:01:01 196 bases
 AAGATTACAT CGCCCTAAAC GAGGACCTGA GCTCTTGGAC CGCGGCGGCC ATGGCGGCTC
 AGATTACCCA GCGCAAGTGG GAGGCGGCCC ATGAGGCGGA GCAGCAGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC
 GCACTGGTAC CAGGGG    
>DL;HLA:HLA18592
HLA:HLA18592 U*01:01:01:02 196 bases
 AAGATTACAT CGCCCTAAAC GAGGACCTGA GCTCTTGGAC CGCGGCGGCC ATGGCGGCTC
 AGATTACCCA GCGCAAGTGG GAGGCGGCCC ATGAGGCGGA GCAGCAGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCGCAGAT ACCTGGAGAA CGGGAAGGAG ACGCTGCAGC
 GCACTGGTAC CAGGGG    
>DL;HLA:HLA18593
HLA:HLA18593 U*01:02 195 bases
 AAGATTACAT CGCCCTAAAC GAGGACCTGA GCTCTTGGAC CGCGGCGGCC ATGGCGGCTC
 AGATTACCCA GCGCAAGTGG GAGGCGGCCC ATGAGGCGGA GCAGCAGAGA GCCTACCTAG
 AGGGCACGTG CGAGGAGTGG CTCCGCAGAT ACCTGGAGAA CAGGAAGGAG ACGCTGCAGC
 GCACTGTACC AGGGG    
>DL;HLA:HLA18594
HLA:HLA18594 U*01:03 196 bases
 AAGATTACAT CGCCCTAAAG GAGGACCTGA GCTCTTGGAC CGCGGCGGCC ATGGCGGCTC
 AGATTACCCA GCGCAAGTGG GAGGCGGCCC ATGAGGCGGA GCAGCAGAGA GCCTACCTGG
 AGGGCACGTG CGTGGAGTGG CTCCGCAGAT ACCTGGAGAA CAGGAAGGAG ATGCTGCAGC
 GCACTGGTAC CAGGGG    
>DL;HLA:HLA18595
HLA:HLA18595 U*01:04 196 bases
 AAGATTACAT CGCCCTAAAC CAGGACCTGA GCTCTTGGAC TGCGGCGGCC ATGGCGGCTC
 AGATTACCCA GCGCAAGTGG GAGGCGGCCC ATGAGGCGGA GCAGCAGACA GCCTACCTGG
 AGGGCAGGTG CGTGGAGTGG CTCCGCAGAT ACCTGGAGAA CAGGAAGGAG ACACTGCAGC
 ACACCTGTAC CAGGGA    
