>DL;HLA:HLA02801
HLA:HLA02801 V*01:01:01:01 538 bases
 ATGGTGTCAT GGCGCCCCGA ACCCTGCTTC TGCTGCTCTC GGGGGCCCTG GTCCTGACCC
 AGACCTGGGC AGGCTTCCAC TCCTTGAGGT ATTTCCACAC CACCATGTCC CGGCCCGGCC
 GCGCGGATCC CCGCTTCCTC TCCGTGGGCG ACGTGGACGA CACGCAGTGC GTGCGGCTCG
 ACAGCGACGC CACGAGTCCC AGGATGGAGC CGCGGGCGCC GTGGATGGAG CAGGAGGGGC
 CGGAATATTG GGAAGAGGAG ACAGGGACCG CCAAGGCCAA AGCACAGTTT TACCGAGTGA
 ACCTGCGGAC CCTGAGCGGC TACTACAACC AGAGTGAGGC CTGGTCTCAC ACCCATCTAG
 AGGATGTCTG TCTGCGACGT GGGGTCGGAC GGGCGCCTAC TCCGCGGGTA TCACCAGCTT
 GCTTACGATG GCAAGGATTA CATCGTCCTG AACGAGGACC TGTGCTCCTT GACAGCCGCA
 GACACGGCGG CTCAGATCAC CCAGCTCAAG TGGGAGGCGG CCCGGGGGGC GGAGGTTC
>DL;HLA:HLA02802
HLA:HLA02802 V*01:01:01:02 517 bases
 ATGGTGTCAT GGCGCCCCGA ACCCTGCTTC TGCTGCTCTC GGGGGCCCTG GTCCTGACCC
 AGACCTGGGC AGGCTTCCAC TCCTTGAGGT ATTTCCACAC CACCATGTCC CGGCCCGGCC
 GCGCGGATCC CCGCTTCCTC TCCGTGGGCG ACGTGGACGA CACGCAGTGC GTGCGGCTCG
 ACAGCGACGC CACGAGTCCC AGGATGGAGC CGGAGGGGCC GGAATATTGG GAAGAGGAGA
 CAGGGACCGC CAAGGCCAAA GCACAGTTTT ACCGAGTGAA CCTGCGGACC CTGAGCGGCT
 ACTACAACCA GAGTGAGGCC TGGTCTCACA CCCATCTAGA GGATGTCTGT CTGCGACGTG
 GGGTCGGACG GGCGCCTACT CCGCGGGTAT CACCAGCTTG CTTACGATGG CAAGGATTCC
 ATCGTCCTGA ACGAGGACCT GTGCTCCTTG ACAGCCGCAG ACACGGCGGC TCAGATCACC
 CAGCTCAAGT GGGAGGCGGC CCGGGGGGCG GAGGTTC  
>DL;HLA:HLA02803
HLA:HLA02803 V*01:01:01:03 517 bases
 ATGGTGTCAT GGCGCCCCGA ACCCTGCTTC TGCTGCTCTC GGGGGCCCTG GTCCTGACCC
 AGACCTGGGC AGGCTTCCAC TCCTTGAGGT ATTTCCACAC CACCATGTCC CGGCCCGGCC
 GCGCGGATCC CCGCTTCCTC TCCGTGGGCG ACGTGGACGA CACGCAGTGC GTGCGGCTCG
 ACAGCGACGC CACGAGTCCC AGGATGGAGC CGGAGGGGCC GGAATATTGG GAAGAGGAGA
 CAGGGACCGC CAAGGCCAAA GCACAGTTTT ACCGAGTGAA CCTGCGGACC CTGAGCGGCT
 ACTACAACCA GAGTGAGGCC TGGTCTCACA CCCATCTAGA GGATGTCTGT CTGCGACGTG
 GGGTCGGACG GGCGCCTACT CCGCGGGTAT CACCAGCTTG CTTACGATGG CAAGGATTCC
 ATCGTCCTGA ACGAGGACCT GTGCTCCTTG ACAGCCGCAG ACACGGCGGC TCAGATCACC
 CAGCTCAAGT GGGAGGCGGC CCGGGGGGCG GAGGTTC  
