>DL;HLA:HLA16364
HLA:HLA16364 W*01:01:01:01 936 bases
 GGTCTCACAC CCTTCAATGG GTACACAGCT GCGACGTGGA CTCGGACTGC AGTCTCCTCA
 GTGGGTATGA ACATACCCTA TCACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCTTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAG GCAGAGCTGC
 TCAAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGAGGCT GCAGTGCCCA GAACCCCAAA GACTCACATG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCTCT GGGCTTCTAC CCTGTGGAGA TCACACTGAC
 CCAGTAGTGG GATGGACAGG ACCAAATGTA GGATGCAGAG GTTGTGGAGA CCACACCTGC
 AGGGTACAGA ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG TCTTCTGGAG AGGAGCAGAG
 ATACACATGC CATGTGCAGC ACGATGGGCT GCCAGAGCCC CTCACCCTGA GATGGCTGTC
 TTCCCAGCCC ACCATCCCCA TCATGGGCAT CGTTACTGTC CTGGTTGTTC TTGGTGCTGT
 TTTCACCAGA GCTGTGGTCA CTGCTGTGAT GTGAAGAATA AGAGCCCAGA TGGAAAAGGA
 GGCAGCTATG CTCAGGCTTC ATACAGGGAC AGTACCCAGG GCTCTGATGT GTCTCTCAAG
 GCTTGTAAAA ACTGCCTTGT GAGGGACTGA GATGCAAGAT TTGTTCATGC CTCCCCTTTG
 TGACTTCAAG GGCCTCTGTC TTCTCTTTCT GCCAAGGTGT CTGAATGTGT CTACATCCCT
 GGTATCATGT GAGAAGTGGG GAGACCAGCC CACCCTCATG TCCACCATGA CCCCTGATAT
 TGTTTGGATC TGTGTCTCCA CCCAAATCTC ATGTTC  
>DL;HLA:HLA16366
HLA:HLA16366 W*01:01:01:02 936 bases
 GGTCTCACAC CCTTCAATGG GTACACAGCT GCGACGTGGA CTCGGACTGC AGTCTCCTCA
 GTGGGTATGA ACATACCCTA TCACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCTTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAG GCAGAGCTGC
 TCAAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGAGGCT GCAGTGCCCA GAACCCCAAA GACTCACATG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCTCT GGGCTTCTAC CCTGTGGAGA TCACACTGAC
 CCAGTAGTGG GATGGACAGG ACCAAATGTA GGATGCAGAG GTTGTGGAGA CCACACCTGC
 AGGGTACAGA ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG TCTTCTGGAG AGGAGCAGAG
 ATACACATGC CATGTGCAGC ACGATGGGCT GCCAGAGCCC CTCACCCTGA GATGGCTGTC
 TTCCCAGCCC ACCATCCCCA TCATGGGCAT CGTTACTGTC CTGGTTGTTC TTGGTGCTGT
 TTTCACCAGA GCTGTGGTCA CTGCTGTGAT GTGAAGAATA AGAGCCCAGA TGGAAAAGGA
 GGCAGCTATG CTCAGGCTTC ATACAGGGAC AGTACCCAGG GCTCTGATGT GTCTCTCAAG
 GCTTGTAAAA ACTGCCTTGT GAGGGACTGA GATGCAAGAT TTGTTCATGC CTCCCCTTTG
 TGACTTCAAG GGCCTCTGTC TTCTCTTTCT GCCAAGGTGT CTGAATGTGT CTACATCCCT
 GGTATCATGT GAGAAGTGGG GAGACCAGCC CACCCTCATG TCCACCATGA CCCCTGATAT
 TGTTTGGATC TGTGTCTCCA CCCAAATCTC ATGTTC  
>DL;HLA:HLA16369
HLA:HLA16369 W*01:01:01:03 936 bases
 GGTCTCACAC CCTTCAATGG GTACACAGCT GCGACGTGGA CTCGGACTGC AGTCTCCTCA
 GTGGGTATGA ACATACCCTA TCACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCTTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAG GCAGAGCTGC
 TCAAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGAGGCT GCAGTGCCCA GAACCCCAAA GACTCACATG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCTCT GGGCTTCTAC CCTGTGGAGA TCACACTGAC
 CCAGTAGTGG GATGGACAGG ACCAAATGTA GGATGCAGAG GTTGTGGAGA CCACACCTGC
 AGGGTACAGA ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG TCTTCTGGAG AGGAGCAGAG
 ATACACATGC CATGTGCAGC ACGATGGGCT GCCAGAGCCC CTCACCCTGA GATGGCTGTC
 TTCCCAGCCC ACCATCCCCA TCATGGGCAT CGTTACTGTC CTGGTTGTTC TTGGTGCTGT
 TTTCACCAGA GCTGTGGTCA CTGCTGTGAT GTGAAGAATA AGAGCCCAGA TGGAAAAGGA
 GGCAGCTATG CTCAGGCTTC ATACAGGGAC AGATCCCAGG GCTCTGATGT GTCTCTCAAG
 GCTTGTAAAA ACTGCCTTGT GAGGGACTGA GATGCAAGAT TTGTTCATGC CTCCCCTTTG
 TGACTTCAAG GGCCTCTGTC TTCTCTTTCT GCCAAGGTGT CTGAATGTGT CTACATCCCT
 GGTATCATGT GAGAAGTGGG GAGACCAGCC CACCCTCATG TCCACCATGA CCCCTGATAT
 TGTTTGGATC TGTGTCTCCA CCCAAATCTC ATGTTC  
>DL;HLA:HLA16368
HLA:HLA16368 W*01:01:01:04 936 bases
 GGTCTCACAC CCTTCAATGG GTACACAGCT GCGACGTGGA CTCGGACTGC AGTCTCCTCA
 GTGGGTATGA ACATACCCTA TCACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCTTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAG GCAGAGCTGC
 TCAAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGAGGCT GCAGTGCCCA GAACCCCAAA GACTCACATG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCTCT GGGCTTCTAC CCTGTGGAGA TCACACTGAC
 CCAGTAGTGG GATGGACAGG ACCAAATGTA GGATGCAGAG GTTGTGGAGA CCACACCTGC
 AGGGTACAGA ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG TCTTCTGGAG AGGAGCAGAG
 ATACACATGC CATGTGCAGC ACGATGGGCT GCCAGAGCCC CTCACCCTGA GATGGCTGTC
 TTCCCAGCCC ACCATCCCCA TCATGGGCAT CGTTACTGTC CTGGTTGTTC TTGGTGCTGT
 TTTCACCAGA GCTGTGGTCA CTGCTGTGAT GTGAAGAATA AGAGCCCAGA TGGAAAAGGA
 GGCAGCTATG CTCAGGCTTC ATACAGGGAC AGTACCCAGG GCTCTGATGT GTCTCTCAAG
 GCTTGTAAAA ACTGCCTTGT GAGGGACTGA GATGCAAGAT TTGTTCATGC CTCCCCTTTG
 TGACTTCAAG GGCCTCTGTC TTCTCTTTCT GCCAAGGTGT CTGAATGTGT CTACATCCCT
 GGTATCATGT GAGAAGTGGG GAGACCAGCC CACCCTCATG TCCACCATGA CCCCTGATAT
 TGTTTGGATC TGTGTCTCCA CCCAAATCTC ATGTTC  
>DL;HLA:HLA16367
HLA:HLA16367 W*01:01:01:05 936 bases
 GGTCTCACAC CCTTCAATGG GTACACAGCT GCGACGTGGA CTCGGACTGC AGTCTCCTCA
 GTGGGTATGA ACATACCCTA TCACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCTTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAG GCAGAGCTGC
 TCAAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGAGGCT GCAGTGCCCA GAACCCCAAA GACTCACATG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCTCT GGGCTTCTAC CCTGTGGAGA TCACACTGAC
 CCAGTAGTGG GATGGACAGG ACCAAATGTA GGATGCAGAG GTTGTGGAGA CCACACCTGC
 AGGGTACAGA ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG TCTTCTGGAG AGGAGCAGAG
 ATACACATGC CATGTGCAGC ACGATGGGCT GCCAGAGCCC CTCACCCTGA GATGGCTGTC
 TTCCCAGCCC ACCAGCCCCA TCATGGGCAT CGTTACTGTC CTGGTTGTTC TTGGTGCTGT
 TTTCACCAGA GCTGTGGTCA CTGCTGTGAT GTGAAGAATA AGAGCCCAGA TGGAAAAGGA
 GGCAGCTATG CTAAGGCTTC ATACAGGGAC AGTACCCAGG GCTCTGATGT GTCTCTCAAG
 GCTTGTAAAA ACTGCCTTGT GAGGGACTGA GATGCAAGAT TTGTTCATGC CTCCCCTTTG
 TGACTTCAAG GGCCTCTGTC TTCTCTTTCT GCCAAGGTGT CTGAATGTGT CTACATCCCT
 GGTATCATGT GAGAAGTGGG GAGACCAGCC CACCCTCATG TCCACCATCA CCCCTGATAT
 TGTTTGGATC TGTGTCTCCA CCCAAATCTC ATGTTC  
>DL;HLA:HLA16371
HLA:HLA16371 W*01:01:01:06 936 bases
 GGTCTCACAC CCTTCAATGG GTACACAGCT GCGACGTGGA CTCGGACTGC AGTCTCCTCA
 GTGGGTATGA ACATACCCTA TCACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCTTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAG GCAGAGCTGC
 TCAAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGAGGCT GCAGTGCCCA GAACCCCAAA GACTCACATG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCATGAGGT GCTGGGCTCT GGGCTTCTAC CCTGTGGAGA TCACACTGAC
 CCAGTAGTGG GATGGACAGG ACCAAATGTA GGATGCAGAG GTTGTGGAGA CCACACCTGC
 AGGGTACAGA ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG TCTTCTGGAG AGGAGCAGAG
 ATACACATGC CATGTGCAGC ACGATGGGCT GCCAGAGCCC CTCACCCTGA GATGGCTGTC
 TTCCCAGCCC ACCATCCCCA TCATGGGCAT CGTTACTGTC CTGGTTGTTC TTGGTGCTGT
 TTTCACCAGA GCTGTGGTCA CTGCTGTGAT GTGAAGAATA AGAGCCCAGA TGGAAAAGGA
 GGCAGCTATG CTCAGGCTTC ATACAGGGAC AGTACCCAGG GCTCTGATGT GTCTCTCAAG
 GCTTGTAAAA ACTGCCTTGT GAGGGACTGA GATGCAAGAT TTGTTCATGC CTCCCCTTTG
 TGACTTCAAG GGCCTCTGTC TTCTCTTTCT GCCAAGGTGT CTGAATGTGT CTACATCCCT
 GGTATCATGT GAGAAGTGGG GAGACCAGCC CACCCTCATG TCCACCATGA CCCCTGATAT
 TGTTTGGATC TGTGTCTCCA CCCAAATCTC ATGTTC  
>DL;HLA:HLA38919
HLA:HLA38919 W*01:01:01:07 936 bases
 GGTCTCACAC CCTTCAATGG GTACACAGCT GCGACGTGGA CTCGGACTGC AGTCTCCTCA
 GTGGGTATGA ACATACCCTA TCACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCTTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAG GCAGAGCTGC
 TCAAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGAGGCT GCAGTGCCCA GAACCCCAAA GACTCACATG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCTCT GGGCTTCTAC CCTGTGGAGA TCACACTGAC
 CCAGTAGTGG GATGGACAGG ACCAAATGTA GGATGCAGAG GTTGTGGAGA CCACACCTGC
 AGGGTACAGA ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG TCTTCTGGAG AGGAGCAGAG
 ATACACATGC CATGTGCAGC ACGATGGGCT GCCAGAGCCC CTCACCCTGA GATGGCTGTC
 TTCCCAGCCC ACCATCCCCA TCATGGGCAT CGTTACTGTC CTGGTTGTTC TTGGTGCTGT
 TTTCACCAGA GCTGTGGTCA CTGCTGTGAT GTGAAGAATA AGAGCCCAGA TGGAAAAGGA
 GGCAGCTATG CTCAGGCTTC ATACAGGGAC AGTACCCAGG GCTCTGATGT GTCTCTCAAG
 GCTTGTAAAA ACTGCCTTGT GAGGGACTGA GATGCAAGAT TTGTTCATGC CTCCCCTTTG
 TGACTTCAAG GGCCTCTGTC TTCTCTTTCT GCCAAGGTGT CTGAATGTGT CTACATCCCT
 GGTATCATGT GAGAAGTGGG GAGACCAGCC CACCCTCATG TCCACCATGA CCCCTGATAT
 TGTTTGGATC TGTGTCTCCA CCCAAATCTC ATGTTC  
>DL;HLA:HLA16372
HLA:HLA16372 W*02:01 938 bases
 GGTCTCACAC CCTCCAATGG GTACACAGCT GCGACCTGGA CTCGGACTGC AGCCTCCTCA
 GTGGGTATGA ACATACCCTA TGACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCCTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAT GCAGAGCTGC
 TCGAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGACGCT GCACTGCCCA GAACCCCAAA AGACTCACAT GACCCACCAC CCCATCTCTG
 ACCATGAGGC CACCCTGAGG TGCTGGGCTC TGGGCTTCTA CCCTGTGGAG ATCACACTGA
 CCCAGTAGTG GGATGGATAG GACCAAATGT AGGATGCAGA GGTTGTGGAG ACCACACCTG
 CAGGGTACAG AACCTTCCAG AAGTGGGCAG CTGTGGTGGT GTCTTCTGGA GAGGAGCAGA
 GATACACATG CCATGTGCAG CACGATGGGC TGCCAGAGCT CCTCACCCTG AGATGGCTGT
 CTTCCCAGCC CACCATCCCC ATCATGGGCA TCGTTACTGT CCTGGTTGTT CTTGGTGCTG
 TTTTCACCAG AGCTGTGGTC ACTGCTGTGA TGTGGAAGAG TAAGAGCCCA GATGGAAAAG
 GAGTCAGCTA TGCTCAGGCT TCATACAGGG ACAGTACCCA GGGCTCTGAT GTGTCTCTCA
 AGGCTTGTAA AAACTGCCTT GTGAGGGACT GAGATGCAAG ATTTGTTCAT GTCTCCCCTT
 TGTGACTTCA AGGGCCTCTG TCTTCTCTTT CTGCCAAGGC GTCTGAATGT GTCTACATCC
 CTGGTATCAT GTGAGAAGTG GGGAGACCAG CCCACCTTCA TGTCCACCAT GACCCCTGAT
 ATTGTTTGGA TCTGTGTCCC CACCCAAATC TCATGTTC  
>DL;HLA:HLA16365
HLA:HLA16365 W*03:01:01:01 923 bases
 GGTCTCACAC CCTCCAGTGG GTACACAGCT GCGACGTGGA CTCGGACTGC AGTCTCCTCA
 GTGGGTATGA ACATACCCTA TCACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCTTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAG GCAGAGCTGC
 TCAAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGAGGCT GCAGTGCCCA GAACCCCAAA AGACTCACAT GACCCACCAC CCCATCTCTG
 ACCATGAGGC CACCCTGAGG TGCTGGGCTC TGGGCTTCTA CCCTGTGGAG ATCACACTGA
 CCCAGTAGTG GGATGGACAG GACCAAATGT AGGATGCAGA GGTTGTGGAG ACCACACCTG
 CAGGGTACAG AACCTTCCAG AAGTGGGCAG CTGTGGTGGT GTCTTCTGGA GAGGAGCAGA
 GATACACATG CCATGTGCAG CACGATGGGC TGCCAGAGCC CCTCACCCTG AGATGGCTGT
 CTTCCCAGCC CACCATCCCC ATCATGGGCA TCGTTACTGT CCTGGTTGTT CTTGGTGCTG
 TTTTCACCAG AGCTGTGGTC ACTGCTGTGA TGTGGAAGAA TAAGAGCCCA GATGGAAAAG
 GAGGCAGCTA TGCTCAGGCT TCATACAGCT CTGATGTGTC TCTCAAGGCT TGTAAAAACT
 GCCTTGTGAG GGACTGAGAT GCAAGATTTG TTCATGCCTC CCCTTTGTGA CTTCAAGGGC
 CTCTGTCTTC TCTTTCTGCC AAGGCGTCTG AATGTGTCTA CATCCCTGGT ATCATGTGAG
 AAGTGGGGAG ACCAGCCCAC CCTCATGTCC ACCATGACCC CTGATATTGT TTGGATCTGT
 GTCTCCACCC AAATCTCATG TTC   
>DL;HLA:HLA16374
HLA:HLA16374 W*03:01:01:02 923 bases
 GGTCTCACAC CCTCCAGTGG GTACACAGCT GCGACGTGGA CTCGGACTGC AGTCTCCTCA
 GTGGGTATGA ACATACCCTA TCACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCTTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAG GCAGAGCTGC
 TCAAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGAGGCT GCAGTGCCCA GAACCCCAAA AGACTCACAT GACCCACCAC CCCATCTCTG
 ACCATGAGGC CACCCTGAGG TGCTGGGCTC TGGGCTTCTA CCCTGTGGAG ATCACACTGA
 CCCAGTAGTG GGATGGACAG GACCAAATGT AGGATGCAGA GGTTGTGGAG ACCACACCTG
 CAGGGTACAG AACCTTCCAG AAGTGGGCAG CTGTGGTGGT GTCTTCTGGA GAGGAGCAGA
 GATACACATG CCATGTGCAG CACGATGGGC TGCCAGAGCC CCTCACCCTG AGATGGCTGT
 CTTCCCAGCC CACCATCCCC ATCATGGGCA TCGTTACTGT CCTGGTTGTT CTTGGTGCTG
 TTTTCACCAG AGCTGTGGTC ACTGCTGTGA TGTGGAAGAA TAAGAGCCCA GATGGAAAAG
 GAGGCAGCTA TGCTCAGGCT TCATACAGCT CTGATGTGTC TCTCAAGGCT TGTAAAAACT
 GCCTTGTGAG GGACTGAGAT GCAAGATTTG TTCATGCCTC CCCTTTGTGA CTTCAAGGGC
 CTCTGTCTTC TCTTTCTGCC AAGGCGTCTG AATGTGTCTA CATCCCTGGT ATCATGTGAG
 AAGTGGGGAG ACCAGCCCAC CCTCATGTCC ACCATGACCC CTGATATTGT TTGGATCTGT
 GTCTCCACCC AAATCTCATG TTC   
>DL;HLA:HLA16373
HLA:HLA16373 W*04:01 938 bases
 GGTCTCACAC CCTCCAATGG GTACACAGCT GCGACCTGGA CTCGGACTGC AGCCTCCTCA
 GTGGGTATGA ACATACCCTA TGACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCCTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAT GCAGAGCTGC
 TCGAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGAGGCT GCAGTGCCCA GAACCCCAAA AGACTCACAT GACCCACCAC CCCATCTCTG
 ACCATGAGGC CACCCTGAGG TGCTGGGCTC TGGGCTTCTA CCCTGTGGAG ATCACACTGA
 CCCAGTAGTG GGATGGATAG GACCAAATGT AGGATGCAGA GGTTGTGGAG ACCACACCTG
 CAGGGTACAG AACCTTCCAG AAGTGGGCAG CTGTGGTGGT GTCTTCTGGA GAGGAGCAGA
 GATACACATG CCATGTGCAG CACGATGGGC TGCCAGAGCT CCTCACCCTG AGATGGCTGT
 CTTCCCAGCC CACCATCCCC ATCATGGGCA TCGTTACTGT CCTGGTTGTT CTTGGTGCTG
 TTTTCACCAG AGCTGTGGTC ACTGCTGTGA TGTGGAAGAG TAAGAGCCCA GATGGAAAAG
 GAGTCAGCTA TGCTCAGGCT TCATACAGGG ACAGTACCCA GGGCTCTGAT GTGTCTCTCA
 AGGCTTGTAA AAACTGCCTT GTGAGGGACT GAGATGCAAG ATTTGTTCAT GCCTCCCCTT
 TGTGACTTCA AGGGCCTCTG TCTTCTCTTT CTGCCAAGGC GTCTGAATGT GTCTACATCC
 CTGGTATCAT GTGAGAAGTG GGGAGACCAG CCCACCTTCA TGTCCACCAT GACCCCTGAT
 ATTGTTTGGA TCTGTGTCCC CACCCAAATC TCATGTTC  
>DL;HLA:HLA16370
HLA:HLA16370 W*05:01 936 bases
 GGTCTCACAC CCTCCAGTGG GTACACAGCT GCGACGTGGA CTCGGACTGC AGTCTCCTCA
 GTGGGTATGA ACATACCCTA TCACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCTTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAG GCAGAGCTGC
 TCAAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGAGGCT GCAGTGCCCA GAACCCCAAA GACTCACATG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCATGAGGT GCTGGGCTCT GGGCTTCTAC CCTGTGGAGA TCACACTGAC
 CCAGTAGTGG GATGGACAGG ACCAAATGTA GGATGCAGAG GTTGTGGAGA CCACACCTGC
 AGGGTACAGA ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG TCTTCTGGAG AGGAGCAGAG
 ATACACATGC CATGTGCAGC ACGATGGGCT GCCAGAGCCC CTCACCCTGA GATGGCTGTC
 TTCCCAGCCC ACCATCCCCA TCATGGGCAT CGTTACTGTC CTGGTTGTTC TTGGTGCTGT
 TTTCACCAGA GCTGTGGTCA CTGCTGTGAT GTGAAGAATA AGAGCCCAGA TGGAAAAGGA
 GGCAGCTATG CTCAGGCTTC ATACAGGGAC AGTACCCAGG GCTCTGATGT GTCTCTCAAG
 GCTTGTAAAA ACTGCCTTGT GAGGGACTGA GATGCAAGAT TTGTTCATGC CTCCCCTTTG
 TGACTTCAAG GGCCTCTGTC TTCTCTTTCT GCCAAGGTGT CTGAATGTGT CTACATCCCT
 GGTATCATGT GAGAAGTGGG GAGACCAGCC CACCCTCATG TCCACCATGA CCCCTGATAT
 TGTTTGGATC TGTGTCTCCA CCCAAATCTC ATGTTC  
>DL;HLA:HLA38948
HLA:HLA38948 W*05:02 936 bases
 GGTCTCACAC CCTCCAGTGG GTACACAGCT GCGACGTGGA CTCGGACTGC AGCCTCCTCA
 GTGGGTACGA ACATACCCTA TCACGGCGCC AGTTACCTCG TCCGAAACCA GGAACTGCGC
 TCTTGGACTG CAGCGGACAA GGCGGCTCAG ATGCCCTGGC GGAGGAACAG GCAGAGCTGC
 TCAAAACCTA CCTGCAGGGA AGGTGGGCGG AGTGGCTCAG CAAAGTCCTT AAGAATGGGA
 AGGAGAGGCT GCAGTGCCCA GAACCCCAAA GACTCACATG ACCCACCACC CCATCTCTGA
 CCATGAGGCC ACCCTGAGGT GCTGGGCTCT GGGCTTCTAC CCTGTGGAGA TCACACTGAC
 CCAGTAGTGG GATGGACAGG ACCAAATGTA GGATGCAGAG GTTGTGGAGA CCACACCTGC
 AGGGTACAGA ACCTTCCAGA AGTGGGCAGC TGTGGTGGTG TCTTCTGGAG AGGAGCAGAG
 ATACACATGC CATGTGCAGC ACGATGGGCT GCCAGAGCCC CTCACCCTGA GATGGCTGTC
 TTCCCAGCCC ACCATCCCCA TCATGGGCAT CGTTACTGTC CTGGTTGTTC TTGGTGCTGT
 TTTCACCAGA GCTGTGGTCA CTGCTGTGAT GTGAAGAATA AGAGCCCAGA TGGAAAAGGA
 GGCAGCTATG CTCAGGCTTC ATACAGGGAC AGTACCCAGG GCTCTGATGT GTCTCTCAAG
 GCTTGTAAAA ACTGCCTTGT GAGGGACTGA GATGCAAGAT TTGTTCATGC CTCCCCTTTG
 TGACTTCAAG GGCCTCTGTC TTCTCTTTCT GCCAAGGTGT CTGAATGTGT CTACATCCCT
 GGTATCATGT GAGAAGTGGG GAGACCAGCC CACCCTCATG TCCACCATGA CCCCTGATAT
 TGTTTGGATC TGTGTCTCCA CCCAAATCTC ATGTTC  
