>DL;HLA:HLA13320
HLA:HLA13320 Y*01:01 1098 bases
 ATGGCGGTCG TGGCGCCCCG AACCCTCCTC CTGCTACTCT CGGGGGCCCT GGCCCTGACC
 CAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCTCCA CATCCGTGTC CCGGCCCGGC
 AGTGGAGAGC CCCGCTTCAT CGCAGTGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACG CCGCGAGCCA GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGAG
 CCGGAGTATT GGGACCGGCA GACACAGATC TCCAAGACCA ACGCACAGAT TGACCTAGAG
 AGCCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGTTCTCA CACCATCCAG
 AGGATGTCTG GCTGCGACGT GGGGTCGGAC GGGCGCTTCC TCCGCGGGTA CCGGCAGGAC
 GCCTACGACG GCAAGGATTA CATCGCCCTG AACGAGGACC TGCGCTCTTG GACCGCGGCG
 GACATGGCGG CTCAGATCAC CCAGCGCAAG TGGGAGGCGG CCCGTCAGGC GGAGCAGTTG
 AGAGCCTACC TGGAGGGCGA GTGCATGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCACGGA CGCCCCCAAG ACGCATATGA CTCACCACGC TGTCTCTGAC
 AATGAGGCCA CCCTGAGGTG CTGAGCCCTG AGCTTCTACC CTGCGGAGAT CACACTGACC
 TGGCAGCGGG ATGGGGAGGA CCAGACCCAG GACACGGAGC TCGTGGAGAC CAGGCCTGCA
 GGGGATGGAA TCTTCCAGAA GTGGGCGGCT GTGGTGGTGC CTTCTGGAGA GGAGCAGAGA
 TACACCTGCC ATGTGCAGCA TGAGGGTCTG CCCAAGCCCC TCACCCTGAG ATGGGAGCCG
 TCTTCCCATC CCACCATCCC CATCGTGGGC ATCCTTGCTG GCCTGGTTCT CTTTGGAGCT
 GTGATCGCTG GAGCTGTGGT CGCTGCTGTG ATGTGGAGGA GGAAGAGCTC AGATAGAAAA
 GGAGGGAGCT ACTCTCAGGC TGCAAGCAGT GACATTGCCC AGGGCTCTGA TGTGTCTCTC
 ACAGCTTGTA AAGTGTGA    
>DL;HLA:HLA13322
HLA:HLA13322 Y*02:01 824 bases
 ATGGCGGTCG TGGCGCCCCG AACCCTCCTC CTGCTACTCT CGGGGGCCCT GGCCCTGACC
 CAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCTCCA CATCCGTGTC CCGGCCCGGC
 AGTGGAGAGC CCCGCTTCAT CGCAGTGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACG CCGCGAGCCA GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGAG
 CCGGAGTATT GGGACCGGCA GACAGAGATC TCCAAGACCA ACGCACAGAT TGACCTAGAG
 AGCCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG ACGACCCCCC CCCAAGACAC
 ATATGACCCA CCACCCCATC TCTGACCATG AGGCCACCCT GAGGTGCTGG GCCCTGAGCT
 TCTACCCTGC GGAGATCACA CTGACCTGGC AGCGGGATGG GGAGGACCAG ACCCAGGACA
 CGGAGCTCGT GGAGACCAGG CCTGCAGGGG ATGGAACCTT CCAGAAGTGG GCGTCTGTGG
 TGGTGCCTTC TGGACAGGAG CAGAGATACA CCTGCCATGT GCAGCATGAG GGTCTGCCCA
 AGCCCCTCAC CCTGAGATGG GAGCCGTCTT CCCAGCCCAC CATCCCCATC GTGGGCATCC
 TTGCTGGCCT GGTTCTCTTT GGAGCTGTGA TCGCTGGAGC TGTGGTCGCT GCTGTGATGT
 GGAGGAGGAA GAGCTCAGAT AGAAAAGGAG GGAGCTACTC TCAGGCTGCA AGCAGTGACA
 GTGCCCAGGG CTCTGATGTG TCTCTCACAG CTTGTAAAGT GTGA 
>DL;HLA:HLA13321
HLA:HLA13321 Y*03:01 1100 bases
 ATGGCGGTCG TGGCGCCCCG AACCCTCCTC CTGCTACTCT CGGGGGCCCT GGCCCTGACC
 CAGACCTGGG CGGGCTCCCA CTCCATGAGG TATTTCTCCA CATCCGTGTC CCGGCCCGGC
 AGTGGAGAGC CCCGCTTCAT CGCAGTGGGC TACGTGGACG ACACGCAGTT CGTGCGGTTC
 GACAGCGACG CCGCGAGCCA GAGGATGGAG CCGCGGGCGC CGTGGATGGA GCAGGAGGAG
 CCGGAGTATT GGGACCGGCA GACACAGATC TCCAAGACCA ACGCACAGAT TGACCTAGAG
 AGCCTGCGGA TCGCGCTCCG CTACTACAAC CAGAGCGAGG CCGGTTCTCA CACCATCCAG
 AGGATGTCTG GCTGCGACGT GGGGTCGGAC GGGCGCTTCC TCCGCGGGTA CCGGCAGGAC
 GCCTACGACG GCAAGGATTA CATCGCCCTG AACGAGGACC TGCGCTCTTG GACCGCGGCG
 GACATGGCGG CTCAGATCAC CCAGCGCAAG TGGGAGGCGG CCCGTCAGGC GGAGCAGTTG
 AGAGCCTACC TGGAGGGCGA GTGCATGGAG TGGCTCCGCA GATACCTGGA GAACGGGAAG
 GAGACGCTGC AGCGCACGGA CCCCCCCCCA AGACACATAT GACCCACCAC CCCATCTCTG
 ACCATGAGGC CACCCTGAGG TGCTGGGCCC TGAGCTTCTA CCCTGCGGAG ATCACACTGA
 CCTGGCAGCG GGATGGGGAG GACCAGACCC AGGACACGGA GCTCGTGGAG ACCAGGCCTG
 CAGGGGATGG AACCTTCCAG AAGTGGGCGT CTGTGGTGGT GCCTTCTGGA CAGGAGCAGA
 GATACACCTG CCATGTGCAG CATGAGGGTC TGCCCAAGCC CCTCACCCTG AGATGGGAGC
 CGTCTTCCCA GCCCACCATC CCCATCGTGG GCATCCTTGC TGGCCTGGTT CTCTTTGGAG
 CTGTGATCGC TGGAGCTGTG GTCGCTGCTG TGATGTGGAG GAGGAAGAGC TCAGATAGAA
 AAGGAGGGAG CTACTCTCAG GCTGCAAGCA GTGACAGTGC CCAGGGCTCT GATGTGTCTC
 TCACAGCTTG TAAAGTGTGA    
